Repository rapid7/metasploit-framework, pull requests merged in 2018-03, with the labels that each got.

#9639 if multi/handler is disabled, exit
  modules/exploits/multi/handler.rb
Labels: bug, module

#9647 lock protobuf version
  Gemfile
  Gemfile.lock
Labels: library, rn-no-release-notes

#9596 update NTP drdos lib to use correct method on bindata objects
  lib/rex/proto/ntp/modes.rb
Labels: bug, module

#9661 Correct metasploit heart banner filename
  data/logos/metasploit-heart-red-bold.txt
Labels: easy

#9658 Fixed Typos
  modules/exploits/windows/smb/ms17_010_eternalblue.rb
Labels: easy

#9669 fix SSL certificate provider
  lib/msf/core/cert_provider.rb
Labels: android, library

#9644 Add Memcached amplification scanner
  documentation/modules/auxiliary/scanner/memcached/memcached_amp.md
  modules/auxiliary/scanner/memcached/memcached_amp.rb
Labels: module

#9671 Fix #9650, missed code from TelnetEnable refactor
  modules/exploits/linux/telnet/netgear_telnetenable.rb
Labels: bug, module

#9665 add missing payload tests
  modules/payloads/stagers/windows/x64/reverse_tcp_rc4.rb
  spec/modules/payloads_spec.rb
Labels: rn-no-release-notes, test module, tests

#9614 Juniper post enum module
  documentation/modules/post/juniper/gather/enum_juniper.md
  lib/metasploit/framework/login_scanner/ssh.rb
  lib/msf/core/auxiliary/juniper.rb
  lib/msf/core/auxiliary/mixins.rb
  lib/msf/core/module/platform.rb
  lib/msf/core/payload/uuid.rb
  modules/auxiliary/scanner/ssh/ssh_login.rb
  modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb
  modules/post/juniper/gather/enum_juniper.rb
Labels: docs, library, module

#9672 Fix docker build
  .dockerignore
Labels: bug

#9606 Add some tests for cmd_exec
  test/modules/post/test/cmd_exec.rb
Labels: payload, rn-no-release-notes, test module, tests

#7654 varnish file read
  documentation/modules/auxiliary/scanner/varnish/varnish_cli_file_read.md
  modules/auxiliary/scanner/varnish/varnish_cli_file_read.rb
Labels: delayed, docs, module

#9705 Updating rubocop rules
  .rubocop.yml
Labels: enhancement, msftidy

#9710 update test for CPE abstraction
  test/modules/exploits/windows/smb/ms17_010_eternalblue.json
Labels: tests

#9713 updated juniper docs
  documentation/modules/post/juniper/gather/enum_juniper.md
Labels: docs

#8422 Typo3 News Module Sql Injection exploit
  documentation/modules/auxiliary/admin/http/typo3_news_module_sqli.md
  modules/auxiliary/admin/http/typo3_news_module_sqli.rb
Labels: feature, module

#9529 Add module for HP iLO CVE-2017-12542 authentication bypass
  documentation/modules/auxiliary/admin/hp/hp_ilo_create_admin_account.md
  modules/auxiliary/admin/hp/hp_ilo_create_admin_account.rb
Labels: docs, module

#9723 Require dependencies conditionally in msfvenom
  msfvenom
Labels: bug, msfvenom

#9744 Add synchronization around public module metadata cache methods
  lib/msf/core/modules/metadata/cache.rb
  lib/msf/core/modules/metadata/store.rb
Labels: bug, library, msf5, rn-no-release-notes

#9586 fix #9112, improve android screenshot error message on failure
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/ui.rb
Labels: android, bug, enhancement

#9765 fix -b as only options when calling msfvenom
  msfvenom
Labels: bug, msfvenom

#9423 Add powershell payload to jenkins_xstream_deserialize module
  modules/exploits/multi/http/jenkins_xstream_deserialize.rb
Labels: enhancement, module

#9708 Add a reload_lib command
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: feature, library, msfconsole

#9636 Improve post module persistence_exe
  modules/post/windows/manage/persistence_exe.rb
Labels: enhancement, module

#9768 Use a better error in scriptable sessions
  lib/msf/base/sessions/scriptable.rb
Labels: bug, library, newbie-friendly

#9773 updates to Gemfile.lock for current master
  Gemfile.lock
Labels: msf5, ruby-compat

#9670 Gitstack v2.3.10 RCE
  documentation/modules/exploit/windows/http/gitstack_rce.md
  modules/exploits/windows/http/gitstack_rce.rb
Labels: docs, module

#9775 Update ms17_010_{psexec,command} module docs
  documentation/modules/auxiliary/admin/smb/ms17_010_command.md
  documentation/modules/exploit/windows/smb/ms17_010_psexec.md
Labels: docs, feature

#9684 Adding ManageEngine Application Manager RCE
  documentation/modules/exploit/windows/http/manageengine_appmanager_exec.md
  modules/exploits/windows/http/manageengine_appmanager_exec.rb
Labels: docs, module

#9760 etcd scanner
  documentation/modules/auxiliary/scanner/etcd/open_key_scanner.md
  modules/auxiliary/scanner/etcd/open_key_scanner.rb
Labels: docs, module

#9782 Return CheckCode::Safe for unsupported x64 systems
  modules/exploits/windows/local/ms_ndproxy.rb
Labels: bug, module
