Repository rapid7/metasploit-framework, pull requests merged in 2018-08, with the labels that each got.

#10411 Fix rspec due to missing __attribute__
  spec/lib/metasploit/framework/obfuscation/crandomizer/code_factory/fake_function_collection_spec.rb
Labels: msf5, tests

#10409 Implement dropper target in axis_srv_parhand_rce
  modules/exploits/linux/http/axis_srv_parhand_rce.rb
Labels: feature, module

#10405 Remove uploaded files from application
  modules/exploits/multi/http/cmsms_upload_rename_rce.rb
Labels: bug, module

#10358 dicoogle directory traversal
  documentation/modules/auxiliary/scanner/http/dicoogle_traversal.md
  modules/auxiliary/scanner/http/dicoogle_traversal.rb
Labels: docs, module

#10419 2016
  lib/msf/core/post/windows/priv.rb
Labels: bug, library, newbie-friendly

#10417 Update check method of Hadoop exploit
  modules/exploits/linux/http/hadoop_unauth_exec.rb
Labels: enhancement, module, newbie-friendly

#10421 Fix use -h to call cmd_use_help
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: bug, easy, library, msfconsole, newbie-friendly

#10423 Prevent adding the same command to history
  lib/rex/ui/text/input/readline.rb
Labels: enhancement, library, msfconsole

#10424 fix history issues as stated in #10423
  lib/rex/ui/text/shell.rb
Labels: bug, enhancement, library, msfconsole

#10436 Add weblogic_deserialize module CVE-2018-2628
  documentation/modules/exploit/windows/misc/weblogic_deserialize.md
  modules/exploits/windows/misc/weblogic_deserialize.rb
Labels: docs, module

#10440 Fix issue #8887, when injecting into an existing .apk file on windows
  lib/msf/core/payload/apk.rb
Labels: android, bug, msfvenom

#10420 cgit < 1.2.1 Directory Traversal
  documentation/modules/auxiliary/scanner/http/cgit_traversal.md
  modules/auxiliary/scanner/http/cgit_traversal.rb
Labels: module, needs-docs

#10454 Update cgit doc
  documentation/modules/auxiliary/scanner/http/cgit_traversal.md
Labels: docs

#10457 Create elasticsearch indices_enum documentation
  documentation/modules/auxiliary/scanner/elasticsearch/indices_enum.md
Labels: docs

#10394 Fixes in aws_ec2_instance_metadata module
  modules/post/multi/gather/aws_ec2_instance_metadata.rb
Labels: bug

#10463 msfdb - add default workspace via MSF web service
  msfdb
Labels: bug, msf5

#10464 Prompt to use module when given plain module name
  lib/msf/ui/console/driver.rb
  lib/rex/ui/text/shell.rb
Labels: enhancement, feature, library, msfconsole

#10469 Fix lurking bugs in the shell's prompt_yesno
  lib/rex/ui/text/shell.rb
Labels: bug, msfconsole, newbie-friendly, rn-no-release-notes

#10472 Move and update marked_redos module doc
  documentation/modules/auxiliary/dos/http/marked_redos.md
Labels: bug, docs, rn-no-release-notes

#10476 add automation test for smb_ms17_010 scanner module
  test/modules/auxiliary/scanner/smb/smb_ms17_010_pass.json
Labels: tests

#10488 msfdb - Improve usage help
  msfdb
Labels: database, msf5

#10493 update help for show and search
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: enhancement, msfconsole

#10492 show help when no argument is provided to `show`
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: enhancement, msfconsole

#10491 fix match error in ppc simple nop generator
  modules/nops/ppc/simple.rb
Labels: bug, payload

#10479 Add CVE-2018-15473 to ssh_enumusers
  modules/auxiliary/scanner/ssh/ssh_enumusers.rb
Labels: feature, module

#10471 Import target DefaultOptions into the datastore
  lib/msf/core/exploit.rb
  lib/msf/core/module/target.rb
  lib/msf/ui/console/command_dispatcher/core.rb
  modules/exploits/linux/http/hp_van_sdn_cmd_inject.rb
Labels: enhancement, feature, library

#10498 Add module doc for ssh_enumusers
  documentation/modules/auxiliary/scanner/ssh/ssh_enumusers.md
  modules/auxiliary/scanner/ssh/ssh_enumusers.rb
Labels: bug, docs, module

#10510 Add full disclosure for CVE-2018-15473
  modules/auxiliary/scanner/ssh/ssh_enumusers.rb
Labels: docs, module

#10517 Update CloudMe Sync Module Documentation
  documentation/modules/exploit/windows/misc/cloudme_sync.md
Labels: docs

#10466 Create documentation for PostgreSQL version scanner
  documentation/modules/auxiliary/scanner/postgres/postgres_version.md
Labels: docs

#10467 Create documentation for PostgreSQL hash dumper
  documentation/modules/auxiliary/scanner/postgres/postgres_hashdump.md
Labels: docs

#10523 Update Foxit Reader PoC Link
  modules/exploits/windows/fileformat/foxit_reader_uaf.rb
Labels: docs, module, rn-no-release-notes

#10527 Fix msftdiy EDB link check
  modules/exploits/multi/http/phpmyadmin_null_termination_exec.rb
  modules/exploits/windows/fileformat/shaper_pdf_bof.rb
  tools/dev/msftidy.rb
Labels: easy, msftidy, newbie-friendly

#10531 avoid inserting a float into instruction generation randomly in sparc nops generator
  modules/nops/sparc/random.rb
Labels: bug, module

#10519 Add msfvenom -l archs like -l platforms
  msfvenom
Labels: feature, msfvenom, newbie-friendly

#10537 Add audio output to the Windows meterpreter
  Gemfile.lock
  metasploit-framework.gemspec
Labels: meterpreter

#10538 Uncomment PSH target in struts2_rest_xstream
  modules/exploits/multi/http/struts2_rest_xstream.rb
Labels: bug, feature, module

#10541 Correct claymore_dos.py's CVE reference
  modules/auxiliary/dos/tcp/claymore_dos.py
Labels: bug, module

#10543 Add Windows ARCH_CMD target and refactor again
  modules/exploits/multi/http/struts2_rest_xstream.rb
Labels: feature, module

#10542 Add CVE reference to office_ms17_11882 exploit
  modules/exploits/windows/fileformat/office_ms17_11882.rb
Labels: bug, module

#10549 Remove trailing space from CVE identifier
  modules/exploits/windows/browser/asus_net4switch_ipswcom.rb
Labels: bug, newbie-friendly, rn-enhancement, rn-no-release-notes

#10545 Update doc, fix generated strings
  documentation/modules/exploit/windows/fileformat/foxit_reader_uaf.md
  modules/exploits/windows/fileformat/foxit_reader_uaf.rb
Labels: bug, docs, module

#10566 Fix missing normalize_uri in struts2_rest_xstream
  modules/exploits/multi/http/struts2_rest_xstream.rb
Labels: bug, module, rn-no-release-notes

#10568 Update weblogic module docs
  documentation/modules/exploit/multi/misc/weblogic_deserialize.md
Labels: docs, rn-no-release-notes

#10567 Update label for the kiwi extention to match latest ver
  lib/rex/post/meterpreter/ui/console/command_dispatcher/kiwi.rb
Labels: enhancement, meterpreter

#10571 Bump metasploit payloads to 1.3.47
  Gemfile.lock
  metasploit-framework.gemspec
Labels: rn-no-release-notes
