Repository rapid7/metasploit-framework, pull requests merged in 2018-11, with the labels that each got.

#10899 Preserve old thread exception reporting behavior
  lib/msf/core/thread_manager.rb
Labels: bug, library

#10900 Turn off thread exception reporting only if it's an available method
  lib/msf/core/thread_manager.rb
Labels: bug, library

#10873 Add applicable notes to my exploit modules
  modules/exploits/linux/http/empire_skywalker.rb
  modules/exploits/multi/ftp/pureftpd_bash_env_exec.rb
  modules/exploits/multi/http/jenkins_script_console.rb
  modules/exploits/multi/http/netwin_surgeftp_exec.rb
  modules/exploits/multi/http/phpmailer_arg_injection.rb
  modules/exploits/multi/ssh/sshexec.rb
  modules/exploits/unix/http/lifesize_room.rb
  modules/exploits/windows/fileformat/blazedvd_plf.rb
  modules/exploits/windows/fileformat/cve_2017_8464_lnk_rce.rb
  modules/exploits/windows/fileformat/ms14_017_rtf.rb
  modules/exploits/windows/local/cve_2017_8464_lnk_lpe.rb
  modules/exploits/windows/local/mqac_write.rb
  modules/exploits/windows/local/ms11_080_afdjoinleaf.rb
  modules/exploits/windows/local/ms13_081_track_popup_menu.rb
  modules/exploits/windows/local/ms14_058_track_popup_menu.rb
  modules/exploits/windows/local/ms15_051_client_copy_image.rb
  modules/exploits/windows/local/razer_zwopenprocess.rb
  modules/exploits/windows/misc/fb_cnct_group.rb
  modules/exploits/windows/misc/hta_server.rb
  modules/exploits/windows/misc/lianja_db_net.rb
Labels: easy, module

#10834 messagebox payload for x64
  modules/payloads/singles/windows/x64/messagebox.rb
Labels: payload

#10910 Use `writable?` method for local modules
  modules/exploits/linux/local/af_packet_chocobo_root_priv_esc.rb
  modules/exploits/linux/local/af_packet_packet_set_ring_priv_esc.rb
  modules/exploits/linux/local/bpf_priv_esc.rb
  modules/exploits/linux/local/bpf_sign_extension_priv_esc.rb
  modules/exploits/linux/local/glibc_realpath_priv_esc.rb
  modules/exploits/linux/local/libuser_roothelper_priv_esc.rb
  modules/exploits/linux/local/rc_local_persistence.rb
  modules/exploits/linux/local/rds_priv_esc.rb
  modules/exploits/linux/local/recvmmsg_priv_esc.rb
  modules/exploits/linux/local/sock_sendpage.rb
  modules/exploits/linux/local/ufo_privilege_escalation.rb
  modules/exploits/osx/local/dyld_print_to_file_root.rb
  modules/exploits/osx/local/rootpipe.rb
  modules/exploits/osx/local/rootpipe_entitlements.rb
  modules/exploits/osx/local/rsh_libmalloc.rb
  modules/exploits/osx/local/setuid_tunnelblick.rb
  modules/exploits/osx/local/setuid_viscosity.rb
  modules/exploits/osx/local/tpwn.rb
  modules/exploits/osx/local/vmware_bash_function_root.rb
  modules/post/multi/recon/sudo_commands.rb
Labels: easy

#10888 Fix Net::SSH::CommandStream session open failure
  documentation/modules/auxiliary/scanner/ssh/libssh_auth_bypass.md
  lib/net/ssh/command_stream.rb
  modules/auxiliary/scanner/ssh/libssh_auth_bypass.rb
Labels: bug, library

#10792 Add support for ms17_010_eternalblue ProcessName option
  modules/exploits/windows/smb/ms17_010_eternalblue.rb
Labels: enhancement, module

#10794 Add support for ms17_010_eternalblue_win8 ProcessName option
  modules/exploits/windows/smb/ms17_010_eternalblue_win8.py
Labels: enhancement, module

#10874 Remove the size restriction from payload_inject
  modules/exploits/windows/local/payload_inject.rb
Labels: easy, module

#10924 Rename `hash` to `generate_process_hash`
  modules/exploits/windows/smb/ms17_010_eternalblue.rb
Labels: bug, module

#10917 Update sshexec to allow unix cmd for testing and other targets not supported
  modules/exploits/multi/ssh/sshexec.rb
Labels: enhancement, module

#10895 Update vmware_http_login
  modules/auxiliary/scanner/vmware/vmware_http_login.rb
Labels: bug, easy, module, newbie-friendly

#10927 Add CentOS and Alpine Linux detection to Linux system lib
  lib/msf/core/post/linux/system.rb
Labels: bug, easy, enhancement, library

#10945 Ensure `sessions --up` shows only services which are up
  lib/msf/ui/console/command_dispatcher/db.rb
Labels: bug, database

#10951 Prepend python path
  lib/msf/core/modules/external/bridge.rb
Labels: bug, external modules

#10971 Fix extraneous whitespace in check output
  lib/msf/ui/console/module_command_dispatcher.rb
Labels: bug, library, msfconsole

#10972 Rework session_compatible? check in post mixin, excluding ARCH_CMD modules
  lib/msf/core/post_mixin.rb
Labels: bug, library

#10992 fix `loadpath test/modules`
  test/modules/auxiliary/test/space_check.rb
Labels: tests

#10984 res.code
  modules/auxiliary/dos/http/ms15_034_ulonglongadd.rb
Labels: bug, easy, module

#10352 Added check and response for CVE-2017-12149 in jboss_vulnscan.rb
  modules/auxiliary/scanner/http/jboss_vulnscan.rb
Labels: enhancement, module

#10998 Unregister aliases when a datastore option is unregistered
  lib/msf/core/data_store.rb
Labels: bug, library

#10996 Fix ms15-034 module
  modules/auxiliary/scanner/http/ms15_034_http_sys_memory_dump.rb
Labels: bug, easy, module, newbie-friendly

#11000 Fix/import exceptions message
  lib/metasploit/framework/data_service/proxy/db_import_data_proxy.rb
Labels: library, msf5, newbie-friendly, rn-no-release-notes

#10872 #6100 : --pad-nops option for msfvenom
  lib/msf/core/payload_generator.rb
  msfvenom
Labels: enhancement, msfvenom

#10802 Update msfvenom format CLI parameter to be case insensitive
  lib/msf/base/simple/buffer.rb
  lib/msf/core/payload_generator.rb
  msfvenom
Labels: enhancement, msfvenom

#11001 Properly error out when attempting to format ELFs
  lib/msf/core/payload_generator.rb
Labels: library, msfvenom

#10997 Remove harmful default command to execute
  modules/payloads/singles/php/exec.rb
Labels: enhancement, payload

#10981 start printjob docs and bug fixes
  documentation/modules/auxiliary/server/capture/printjob_capture.md
  modules/auxiliary/server/capture/printjob_capture.rb
Labels: bug, delayed, docs

#10990 Move existing Metasploit Web Service app and servlets to more appropriate location in source tree
  LICENSE
  lib/msf/core/db_manager/http/authentication.rb
  lib/msf/core/web_services/authentication.rb
  lib/msf/core/web_services/authentication/strategies.rb
  lib/msf/core/web_services/authentication/strategies/admin_api_token.rb
  lib/msf/core/web_services/authentication/strategies/api_token.rb
  lib/msf/core/web_services/authentication/strategies/user_password.rb
  lib/msf/core/web_services/db_manager_proxy.rb
  lib/msf/core/web_services/http_db_manager_service.rb
  lib/msf/core/web_services/job_processor.rb
  lib/msf/core/web_services/json_rpc_app.rb
  lib/msf/core/web_services/metasploit_api_app.rb
  lib/msf/core/web_services/public/favicon-16x16.png
  lib/msf/core/web_services/public/favicon-32x32.png
  lib/msf/core/web_services/public/favicon.ico
  lib/msf/core/web_services/public/msf-ws.css
  lib/msf/core/web_services/public/oauth2-redirect.html
  lib/msf/core/web_services/public/swagger-ui.css
  lib/msf/core/web_services/public/swagger-ui.css.map
  lib/msf/core/web_services/servlet/api_docs_servlet.rb
  lib/msf/core/web_services/servlet/auth_servlet.rb
  lib/msf/core/web_services/servlet/credential_servlet.rb
  lib/msf/core/web_services/servlet/db_export_servlet.rb
  lib/msf/core/web_services/servlet/event_servlet.rb
  lib/msf/core/web_services/servlet/exploit_servlet.rb
  lib/msf/core/web_services/servlet/host_servlet.rb
  lib/msf/core/web_services/servlet/login_servlet.rb
  lib/msf/core/web_services/servlet/loot_servlet.rb
  lib/msf/core/web_services/servlet/msf_servlet.rb
  lib/msf/core/web_services/servlet/nmap_servlet.rb
  lib/msf/core/web_services/servlet/note_servlet.rb
  lib/msf/core/web_services/servlet/service_servlet.rb
  lib/msf/core/web_services/servlet/session_event_servlet.rb
  lib/msf/core/web_services/servlet/session_servlet.rb
  lib/msf/core/web_services/servlet/user_servlet.rb
  lib/msf/core/web_services/servlet/vuln_attempt_servlet.rb
  lib/msf/core/web_services/servlet/vuln_servlet.rb
  lib/msf/core/web_services/servlet/web_servlet.rb
  lib/msf/core/web_services/servlet/workspace_servlet.rb
  lib/msf/core/web_services/servlet_helper.rb
  lib/msf/core/web_services/views/api_docs.erb
  lib/msf/core/web_services/views/auth/account.erb
  lib/msf/core/web_services/views/auth/login.erb
  msfdb
  msfdb_ws
Labels: msf5

#11006 Explain "junk" in buffer for morris_fingerd_bof
  modules/exploits/bsd/finger/morris_fingerd_bof.rb
Labels: bug, module, rn-no-release-notes

#11011 iis_shortname fixes
  modules/auxiliary/scanner/http/iis_shortname_scanner.rb
Labels: enhancement, module

#11020 Update php reverse_tcp instructions
  documentation/modules/payload/php/meterpreter/reverse_tcp.md
Labels: docs, easy, newbie-friendly

#11027 remove secondary check that prevents aliases from functioning
  lib/msf/core/data_store.rb
Labels: bug

#11017 Fix userns_enabled? check for unprivileged_userns_clone
  lib/msf/core/post/linux/kernel.rb
Labels: bug, library

#10509 Add source meta command for shell session
  lib/msf/base/sessions/command_shell.rb
Labels: feature, module

#10987 php imap_open RCE
  documentation/modules/exploit/linux/http/php_imap_open_rce.md
  modules/exploits/linux/http/php_imap_open_rce.rb
Labels: docs, module

#11032 Add check for SMAP
  documentation/modules/exploit/linux/local/af_packet_chocobo_root_priv_esc.md
  modules/exploits/linux/local/af_packet_chocobo_root_priv_esc.rb
Labels: bug, easy, module

#10716 Create PureVPN Credential Collector Post Explotation Module
  modules/post/windows/gather/credentials/purevpn_cred_collector.rb
Labels: docs, module

#11035 improve fingerprinting for Cisco ASA VPN scanner
  modules/auxiliary/scanner/http/cisco_ssl_vpn.rb
Labels: bug, module

#11042 Spaces at EOL fixes
  modules/auxiliary/scanner/misc/ibm_mq_login.rb
  modules/exploits/windows/browser/getgodm_http_response_bof.rb
Labels: easy, newbie-friendly
