Repository rapid7/metasploit-framework, pull requests merged in 2018-10, with the labels that each got.

#10726 Fix downgraded gem dependencies recog and ruby-macho
  Gemfile.lock
Labels: rn-no-release-notes

#10728 Fix outdated metadata
  modules/auxiliary/admin/http/wp_easycart_privilege_escalation.rb
  modules/auxiliary/admin/http/wp_wplms_privilege_escalation.rb
  modules/auxiliary/dos/http/wordpress_long_password_dos.rb
  modules/auxiliary/gather/wp_all_in_one_migration_export.rb
  modules/auxiliary/gather/wp_ultimate_csv_importer_user_extract.rb
  modules/exploits/multi/http/wp_ninja_forms_unauthenticated_file_upload.rb
  modules/exploits/unix/webapp/maarch_letterbox_file_upload.rb
  modules/exploits/unix/webapp/wp_admin_shell_upload.rb
  modules/exploits/unix/webapp/wp_easycart_unrestricted_file_upload.rb
  modules/exploits/unix/webapp/wp_holding_pattern_file_upload.rb
  modules/exploits/unix/webapp/wp_photo_gallery_unrestricted_file_upload.rb
  modules/exploits/unix/webapp/wp_symposium_shell_upload.rb
Labels: bug, docs, module, rn-no-release-notes

#10727 Fix loading external modules without notes
  lib/msf/core/modules/external/shim.rb
Labels: bug, external modules, msf5

#10725 fix post/android/gather/subinfo.rb path
  modules/post/android/gather/sub_info.rb
Labels: android, bug

#10704 Navigate CMS Unauthenticated Remote Code Execution
  documentation/modules/exploit/multi/http/navigate_cms_rce.md
  modules/exploits/multi/http/navigate_cms_rce.rb
Labels: docs, module

#10739 Remove unneeded UserServlet from JSON-RPC App
  lib/msf/core/web_services/json_rpc_app.rb
Labels: automation, easy, msf5, rn-no-release-notes

#10712 Make exploit/linux/http/axis_srv_parhand_rce more stable
  modules/exploits/linux/http/axis_srv_parhand_rce.rb
Labels: bug, enhancement, module

#10750 Fix formatting and convert a missed AKA reference
  modules/auxiliary/scanner/http/apache_mod_cgi_bash_env.rb
  modules/exploits/linux/http/axis_srv_parhand_rce.rb
  modules/exploits/linux/http/hp_van_sdn_cmd_inject.rb
  modules/exploits/multi/fileformat/ghostscript_failed_restore.rb
  modules/exploits/unix/fileformat/imagemagick_delegate.rb
  modules/exploits/unix/webapp/drupal_drupalgeddon2.rb
  modules/exploits/windows/smb/ms17_010_eternalblue_win8.py
Labels: bug, module

#10746 Fix RPC module.payloads method performance
  lib/msf/core/rpc/v10/rpc_module.rb
Labels: enhancement, msf5, rn-no-release-notes

#10745 Update lastore_daemon_dbus_priv_esc tested versions
  documentation/modules/exploit/linux/local/lastore_daemon_dbus_priv_esc.md
  modules/exploits/linux/local/lastore_daemon_dbus_priv_esc.rb
Labels: docs, easy, newbie-friendly

#10743 reduce docker image size
  Dockerfile
Labels: easy, enhancement, newbie-friendly

#10729 Namespace modules using full name instead of hex
  lib/msf/core/modules/loader/base.rb
  spec/lib/msf/core/modules/loader/base_spec.rb
Labels: enhancement, library, msf5

#10753 Improve check_snake_case_filename check in msftidy
  tools/dev/msftidy.rb
Labels: enhancement, msftidy

#10754 Improve check_snake_case_filename regex in msftidy (redux)
  tools/dev/msftidy.rb
Labels: bug, msftidy

#10751 Fix issue that not interact with session when exploit with single-host rhosts.
  lib/msf/ui/console/command_dispatcher/exploit.rb
Labels: bug, library, msf5, msfconsole

#10755 Bump fallback pager in log command to tail -n 50
  lib/msf/ui/console/command_dispatcher/developer.rb
Labels: bug, enhancement, library, msfconsole

#10744 Add AUDIO_EFFECTS to distinguish from others
  lib/msf/core/constants.rb
Labels: enhancement, library, msf5

#10775 Delta zdi ref
  modules/exploits/windows/scada/delta_ia_commgr_bof.rb
Labels: docs, module

#10776 Address @bcoles' review in #10672
  modules/exploits/windows/scada/delta_ia_commgr_bof.rb
Labels: bug, module

#10762 Change "4" to "5" in missile command banner
  data/logos/missile-command.txt
Labels: easy, msf5, newbie-friendly, rn-no-release-notes

#10770 webcam_stream full path to console
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/webcam.rb
Labels: enhancement, payload

#10781 Rpc shell read fix
  lib/msf/core/rpc/v10/rpc_session.rb
Labels: bug, library

#10784 Add 'evasion' to search help
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: easy, enhancement, msf5, newbie-friendly, rn-no-release-notes

#10786 Fix #10785, incorrect implementation of "show evasion" command
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: bug, library, msf5, rn-no-release-notes

#10787 Remove unknown author mapping in author.rb
  lib/msf/core/author.rb
Labels: bug, library

#10789 Description update / typo fix
  modules/auxiliary/admin/scada/moxa_credentials_recovery.rb
Labels: docs, easy, rn-no-release-notes

#10668 Add Solaris RSH Stack Clash Privilege Escalation module
  documentation/modules/exploit/solaris/local/rsh_stack_clash_priv_esc.md
  modules/exploits/solaris/local/rsh_stack_clash_priv_esc.rb
Labels: docs, module

#10797 add sip options_tcp docs
  documentation/modules/auxiliary/scanner/sip/options_tcp.md
Labels: docs, easy, rn-no-release-notes

#10793 improve windows_defender_js_hta
  data/exploits/evasion_shellcode.js
  data/exploits/hta_evasion.hta
  modules/evasion/windows/windows_defender_js_hta.rb
Labels: enhancement, module

#10816 add bg command to meterpreter
  lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb
Labels: easy, enhancement, rn-enhancement

#10824 Add PTY option to Net::SSH::CommandStream
  lib/net/ssh/command_stream.rb
Labels: enhancement, library

#10833 Update Net::SSH::CommandStream exception handling
  lib/net/ssh/command_stream.rb
Labels: bug, enhancement, library

#10826 Update ruby version
  .ruby-version
  .travis.yml
  Dockerfile
Labels: rn-no-release-notes, ruby-compat

#10832 Added module TARGETURI support.
  modules/auxiliary/admin/http/tomcat_utf8_traversal.rb
Labels: enhancement, module

#10819 ssh_login* now populates the os_name field
  modules/auxiliary/scanner/ssh/ssh_login.rb
  modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb
Labels: delayed, enhancement

#10837 Move exploit/qnx/qconn_exec to exploit/qnx/qconn/qconn_exec
  modules/exploits/qnx/qconn/qconn_exec.rb
  modules/exploits/unix/misc/qnx_qconn_exec.rb
Labels: bug, module

#10845 fix small typo
  modules/auxiliary/scanner/http/glassfish_traversal.rb
Labels: bug, docs, easy, module

#10450 [GSoC] Implementation of CTRL+Z in reverse shell session
  123
Labels: feature, payload

#10856 bump payloads gem
  Gemfile.lock
  metasploit-framework.gemspec
  modules/payloads/singles/php/meterpreter_reverse_tcp.rb
Labels: enhancement, payload, rn-no-release-notes

#10851 add ndkstager to data/exploits
  data/exploits/CVE-2012-6636/armeabi/libndkstager.so
  data/exploits/CVE-2012-6636/mips/libndkstager.so
  data/exploits/CVE-2012-6636/x86/libndkstager.so
  lib/msf/core/exploit/android.rb
Labels: payload, rn-no-release-notes

#10857 ensure os_flavor can be supplied for non Windows OS
  lib/msf/core/db_manager/host.rb
Labels: database, enhancement

#10866 Enhance the module libssh_auth_bypass
  modules/auxiliary/scanner/ssh/libssh_auth_bypass.rb
Labels: enhancement, module

#10858 bypassuac_eventvwr optimizations - reduce created processes and artifacts
  modules/exploits/windows/local/bypassuac_eventvwr.rb
Labels: enhancement, module
