Repository rapid7/metasploit-framework, pull requests merged in 2018-09, with the labels that each got.

#10550 Add prompt to persist data service connection in msfdb
  msfdb
Labels: database, msf5

#10591 Fix target DisableNops not being passed to payload
  lib/msf/core/exploit.rb
  lib/msf/core/module/target.rb
Labels: bug, library

#10604 Add CVE reference to ghostscript_failed_restore.rb
  modules/exploits/multi/fileformat/ghostscript_failed_restore.rb
Labels: bug, module, newbie-friendly

#10612 fix xml ctypes in store_loot
  modules/auxiliary/scanner/smb/smb_enum_gpp.rb
  modules/post/multi/gather/jenkins_gather.rb
  modules/post/windows/gather/credentials/gpp.rb
Labels: bug, easy, newbie-friendly

#10611 fix pathing in mremoteng
  modules/post/windows/gather/credentials/mremote.rb
Labels: bug

#10593 Refactor SSH mixins and update modules
  lib/msf/core/exploit/mixins.rb
  lib/msf/core/exploit/ssh.rb
  lib/msf/core/exploit/ssh/auth_methods.rb
  modules/auxiliary/scanner/ssh/fortinet_backdoor.rb
  modules/auxiliary/scanner/ssh/ssh_enumusers.rb
Labels: bug, feature, library, module

#10617 Fix crash when using sessions -x
  lib/msf/base/serializer/readable_text.rb
Labels: bug, library

#10621 add gcc path for solaris lib
  lib/msf/core/post/solaris/system.rb
Labels: library

#10589 Added auxiliary/fileformat/multidrop support for Word XML documents
  modules/auxiliary/fileformat/multidrop.rb
Labels: module

#10619 Add warning for mimikatz and kiwi if OS versions are wrong
  lib/rex/post/meterpreter/ui/console/command_dispatcher/kiwi.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/mimikatz.rb
Labels: enhancement, library

#10631 Update warning message when loading mimikatz on new OSes
  lib/rex/post/meterpreter/ui/console/command_dispatcher/mimikatz.rb
Labels: bug, library

#10560 ms17_010_eternalblue: use SMBDomain value when provided instead of ignoring it
  modules/exploits/windows/smb/ms17_010_eternalblue.rb
Labels: enhancement, module

#10633 Fix Msf::Post::Solaris::System pidof method
  lib/msf/core/post/solaris/system.rb
Labels: easy, library

#10639 Remember to assign `self.prompt` in shell.rb
  lib/rex/ui/text/shell.rb
Labels: bug, library, msfconsole

#10389 Add PTY option for Meterpreter shell command
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/sys.rb
Labels: enhancement, meterpreter

#10645 Add writable? method to Msf::Post::File - Fix #10644
  lib/msf/core/post/file.rb
Labels: enhancement, library

#10662 Travis fix
  .travis.yml
Labels: bug, rn-no-release-notes, tests

#10660 deregister_options RHOSTS
  modules/auxiliary/gather/http_pdf_authors.rb
  modules/auxiliary/gather/searchengine_subdomains_collector.rb
Labels: bug, module, msf5, rn-no-release-notes

#10627 Add SMB2 support to smb_enumshares
  modules/auxiliary/scanner/smb/smb_enumshares.rb
Labels: enhancement, module

#10666 Fix crash issue when auto complete the session option.
  lib/msf/ui/console/command_dispatcher/core.rb
Labels: bug, library

#10652 Add iOS Safari Webkit Blur Denial of Service
  modules/auxiliary/dos/apple_ios/webkit_backdrop_filter_blur.rb
Labels: ios, module, needs-docs

#10673 Move SQLi module to auxiliary/gather
  documentation/modules/auxiliary/gather/dolibarr_list_creds_sqli.md
  modules/auxiliary/gather/dolibarr_list_creds_sqli.rb
Labels: bug, docs, module

#10670 Add Pimcore SQLi Auxiliary Module
  documentation/modules/auxiliary/gather/pimcore_creds_sqli.md
  modules/auxiliary/gather/pimcore_creds_sqli.rb
Labels: docs, module

#10677 Rename Pimcore and Dolibarr SQLi modules
  modules/auxiliary/gather/dolibarr_creds_sqli.rb
  modules/auxiliary/gather/pimcore_creds_sqli.rb
Labels: bug, module, rn-no-release-notes

#10681 Update Payload cached sizes
  modules/payloads/singles/apple_ios/aarch64/meterpreter_reverse_http.rb
  modules/payloads/singles/apple_ios/aarch64/meterpreter_reverse_https.rb
  modules/payloads/singles/apple_ios/aarch64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/aarch64/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/aarch64/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/aarch64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/armbe/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/armbe/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/armbe/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/armle/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/armle/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/armle/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/mips64/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/mips64/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/mips64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/mipsbe/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/mipsbe/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/mipsbe/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/mipsle/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/mipsle/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/mipsle/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/ppc/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/ppc/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/ppc/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/ppc64le/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/ppc64le/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/ppc64le/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/ppce500v2/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/ppce500v2/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/ppce500v2/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/x64/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/x64/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/x64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/x86/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/x86/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/x86/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/zarch/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/zarch/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/zarch/meterpreter_reverse_tcp.rb
  modules/payloads/singles/osx/x64/meterpreter_reverse_http.rb
  modules/payloads/singles/osx/x64/meterpreter_reverse_https.rb
  modules/payloads/singles/osx/x64/meterpreter_reverse_tcp.rb
Labels: bug, payload

#10680 Add LEAK_COUNT option to Heartbleed
  modules/auxiliary/scanner/ssl/openssl_heartbleed.rb
Labels: enhancement, module

#10628 srsexec Solaris Post module
  documentation/modules/post/solaris/escalate/srsexec_readline.md
  modules/post/solaris/escalate/srsexec_readline.rb
Labels: docs, module

#10683 Prefer to_s in Heartbleed for cleaner code
  modules/auxiliary/scanner/ssl/openssl_heartbleed.rb
Labels: bug, module

#10685 Fix NameError in cmd_shell due to renamed variable
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/sys.rb
Labels: bug, library, msfconsole

#10684 Remove stray quote from raise in writable? method
  lib/msf/core/post/file.rb
Labels: bug, library

#10687 Add pry command to Meterpreter
  lib/msf/ui/console/command_dispatcher/developer.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb
Labels: feature, library, meterpreter

#10663 Add Solaris 'EXTREMEPARR' dtappgather Privilege Escalation module
  documentation/modules/exploit/solaris/local/extremeparr_dtappgather_priv_esc.md
  modules/exploits/solaris/local/extremeparr_dtappgather_priv_esc.rb
Labels: docs, hotness, module

#10428 updated windows mysql udf files and documentation
  data/exploits/mysql/lib_mysqludf_sys_32.dll
  data/exploits/mysql/lib_mysqludf_sys_64.dll
  documentation/modules/exploit/multi/mysql/mysql_udf_payload.md
Labels: bug, docs

#10696 Add autofilter_ports and autofilter_services to cache
  lib/msf/core/modules/metadata/obj.rb
Labels: enhancement, msf5

#10706 Update metasploit-payloads to 1.3.51
  Gemfile.lock
  metasploit-framework.gemspec
Labels: enhancement, rn-no-release-notes

#10705 Enhance reload_lib to reload changed files
  lib/msf/ui/console/command_dispatcher/developer.rb
Labels: enhancement, library, msfconsole

#10713 Add ed25519 gem to bundle for ssh_login_pubkey
  Gemfile.lock
  metasploit-framework.gemspec
Labels: bug
