Repository rapid7/metasploit-framework, pull requests merged in 2018-04, with the labels that each got.

#9738 msfconsole: Improve handling of CTRL-C interrupts and command-line parameters
  lib/metasploit/framework/parsed_options/base.rb
  lib/metasploit/framework/parsed_options/console.rb
  msfconsole
Labels: msfconsole

#9802 Update documentation for get_user_spns.py
  documentation/modules/auxiliary/gather/get_user_spns.md
Labels: docs

#9803 Fix no-uac msi creation
  lib/msf/util/exe.rb
Labels: bug, payload

#9787 Fix adding IPv6 routes with subnets or cidr masks
  lib/msf/ui/console/command_dispatcher/core.rb
Labels: bug, payload

#9749 Formatted reg binary type to hex when displaying query results.
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/sys.rb
Labels: enhancement, payload

#9742 Update QNX qconn command execution exploit module
  documentation/modules/exploit/unix/misc/qnx_qconn_exec.md
  modules/exploits/unix/misc/qnx_qconn_exec.rb
Labels: docs, enhancement, module

#9828 Fix #9827 - reverse HTTPS listeners
  lib/msf/core/payload/transport_config.rb
Labels: bug, payload

#9834 bump payloads, add Python UDP channel support
  Gemfile.lock
  metasploit-framework.gemspec
  modules/payloads/singles/python/meterpreter_bind_tcp.rb
  modules/payloads/singles/python/meterpreter_reverse_http.rb
  modules/payloads/singles/python/meterpreter_reverse_https.rb
  modules/payloads/singles/python/meterpreter_reverse_tcp.rb
Labels: enhancement, payload

#9839 Update rex-text to 0.2.17
  Gemfile.lock
  LICENSE_GEMS
Labels: feature, library

#9845 Remove temp file after cmd execution
  modules/post/windows/manage/run_as.rb
Labels: bug, module

#9848 Fix unsupported check_simple method for modules
  lib/msf/ui/console/module_command_dispatcher.rb
Labels: bug, library, newbie-friendly

#9864 Print generated CmdStager with inspect, not join
  lib/msf/core/exploit/cmdstager.rb
Labels: bug, library, rn-no-release-notes

#9863 Fix DBManager::Service each_service method use of services method
  lib/msf/core/db_manager/service.rb
Labels: bug, msf5

#9865 Update stdapi/fs help output to match searching/masking parameters
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb
Labels: easy

#9871 show help when no arguments are provided to `search`
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: bug, feature, library, msfconsole

#9872 Conform to JSONRPC 2.0 spec in external modules
  lib/msf/core/modules/external/message.rb
  lib/msf/core/modules/external/python/metasploit/module.py
  lib/msf/core/modules/external/ruby/metasploit.rb
Labels: bug, external modules, library, rn-no-release-notes

#9862 Post-exploitation module for meterpreter (Windows) to send wireless probe requests
  modules/post/windows/wlan/wlan_probe_request.rb
Labels: module, needs-docs

#9892 Fix target encoder not being passed to payload
  lib/msf/core/exploit.rb
  lib/msf/core/module/target.rb
Labels: bug, library

#9899 Pass NOP generator to exploit_simple
  lib/msf/base/simple/exploit.rb
Labels: android, bug, creds

#9902 Fix Crash On Startup When No DB Configured
  lib/msf/ui/console/driver.rb
Labels: bug, msf5

#9858 rescue errors in cmd_route method
  lib/msf/ui/console/command_dispatcher/core.rb
Labels: bug, msfconsole

#9628 Add GitStack v2.3.10 Unauth REST API Aux Module
  documentation/modules/auxiliary/admin/http/gitstack_rest.md
  modules/auxiliary/admin/http/gitstack_rest.rb
Labels: docs, module

#9912 Fix type validation in the notes add operation
  lib/msf/ui/console/command_dispatcher/db.rb
Labels: bug, easy, msf5

#9851 Fix #9850 preventing psexec against non-powershell targets
  lib/msf/util/exe.rb
Labels: bug

#9925 Fix Missing :workspace Attribute On db_import Command
  lib/metasploit/framework/data_service/proxy/data_proxy_auto_loader.rb
  lib/metasploit/framework/data_service/proxy/db_import_data_proxy.rb
  lib/metasploit/framework/data_service/stubs/db_export_service.rb
  lib/metasploit/framework/data_service/stubs/db_import_service.rb
  lib/msf/core/db_manager/import.rb
Labels: bug, easy, msf5

#9886 Fix Bug When Importing XML File
  lib/msf/core/db_manager/import/metasploit_framework/xml.rb
Labels: bug

#9924 Improve printing in ETERNALBLUE's verify_arch
  modules/exploits/windows/smb/ms17_010_eternalblue.rb
Labels: bug, module, newbie-friendly

#9900 Added base64 encoder for Ruby
  modules/encoders/ruby/base64.rb
Labels: enhancement, library, payload

#9931 Fix #9876, minor updates to Drupalgeddon 2
  modules/exploits/unix/webapp/drupal_drupalgeddon2.rb
Labels: bug, module, rn-no-release-notes

#9934 Revert NoteDataService to raise RuntimeError
  lib/metasploit/framework/data_service/stubs/note_data_service.rb
Labels: easy, msf5, rn-no-release-notes

#9936 Narrow rescue scope to StandardError
  lib/metasploit/framework/data_service/proxy/credential_data_proxy.rb
  lib/metasploit/framework/data_service/proxy/db_export_data_proxy.rb
  lib/metasploit/framework/data_service/proxy/event_data_proxy.rb
  lib/metasploit/framework/data_service/proxy/exploit_data_proxy.rb
  lib/metasploit/framework/data_service/proxy/host_data_proxy.rb
  lib/metasploit/framework/data_service/proxy/loot_data_proxy.rb
  lib/metasploit/framework/data_service/proxy/nmap_data_proxy.rb
  lib/metasploit/framework/data_service/proxy/note_data_proxy.rb
  lib/metasploit/framework/data_service/proxy/service_data_proxy.rb
  lib/metasploit/framework/data_service/proxy/session_data_proxy.rb
  lib/metasploit/framework/data_service/proxy/session_event_data_proxy.rb
  lib/metasploit/framework/data_service/proxy/vuln_attempt_data_proxy.rb
  lib/metasploit/framework/data_service/proxy/vuln_data_proxy.rb
  lib/metasploit/framework/data_service/proxy/web_data_proxy.rb
  lib/metasploit/framework/data_service/proxy/workspace_data_proxy.rb
  lib/metasploit/framework/data_service/remote/http/response_data_helper.rb
  lib/metasploit/framework/login_scanner/bavision_cameras.rb
  lib/msf/core/db_manager/http/job_processor.rb
  lib/msf/core/db_manager/http/servlet/credential_servlet.rb
  lib/msf/core/db_manager/http/servlet/db_export_servlet.rb
  lib/msf/core/db_manager/http/servlet/host_servlet.rb
  lib/msf/core/db_manager/http/servlet/loot_servlet.rb
  lib/msf/core/db_manager/http/servlet/note_servlet.rb
  lib/msf/core/db_manager/http/servlet/service_servlet.rb
  lib/msf/core/db_manager/http/servlet/session_event_servlet.rb
  lib/msf/core/db_manager/http/servlet/session_servlet.rb
  lib/msf/core/db_manager/http/servlet/vuln_attempt_servlet.rb
  lib/msf/core/db_manager/http/servlet/vuln_servlet.rb
  lib/msf/core/db_manager/http/servlet/workspace_servlet.rb
  lib/msf/core/db_manager/http/servlet_helper.rb
  lib/msf/ui/console/command_dispatcher/db.rb
Labels: easy, msf5

#9943 move super call in merge! so that it returns the proper value
  lib/msf/core/data_store.rb
Labels: bug, library

#9951 Update linux/gather/enum_protections
  modules/post/linux/gather/enum_protections.rb
Labels: easy, enhancement, module

#9954 Add search command CSV output option
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: easy, enhancement
