Repository rapid7/metasploit-framework, pull requests merged in 2018-07, with the labels that each got.

#9896 Java JMX Package Name Randomization
  modules/exploits/multi/misc/java_jmx_server.rb
Labels: enhancement, module

#10217 bind_named_pipe fixed for simpleclient versions param
  lib/msf/core/handler/bind_named_pipe.rb
  lib/msf/core/payload/windows/bind_named_pipe.rb
  lib/msf/core/payload/windows/x64/bind_named_pipe.rb
Labels: bug, payload

#10242 avoid using SMBv2 on Windows XP Native Upload targets
  modules/exploits/windows/smb/psexec.rb
Labels: bug, module

#10250 Increase read depth for smb pipes
  lib/rex/proto/smb/simpleclient/open_file.rb
Labels: bug, rubysmb

#10251 Add more verbose printing to bind handlers
  lib/msf/core/handler/bind_named_pipe.rb
  lib/msf/core/handler/bind_tcp.rb
  lib/msf/core/handler/bind_udp.rb
Labels: delayed, feature, library

#10263 fix undefined method capitalize error for array
  modules/post/multi/gather/jenkins_gather.rb
Labels: bug, rn-no-release-notes

#10241 don't call print_error from rex context, use elog instead
  lib/rex/proto/dcerpc/svcctl/packet.rb
Labels: bug

#10108 Add exploit for QRadar, CVE-2018-1418
  modules/exploits/linux/http/ibm_qradar_unauth_rce.rb
Labels: module, needs-docs

#10280 Return CheckCode::Unsupported in ETERNALBLUE
  modules/exploits/windows/smb/ms17_010_eternalblue.rb
Labels: bug, module, newbie-friendly

#10268 Make sure module_reference is able to continue loading rb modules
  tools/modules/module_reference.rb
Labels: bug, newbie-friendly

#10286 Add Auxiliary module to enumerate the Docker Server Version
  modules/auxiliary/scanner/http/docker_enum.rb
Labels: feature, module

#10298 Add missed ARCH_CMD to top-level Arch array
  modules/exploits/linux/http/hp_van_sdn_cmd_inject.rb
Labels: bug, module

#10278 Remove double eval for Gitlist Argument Injection exploit module #10262
  modules/exploits/multi/http/gitlist_arg_injection.rb
Labels: bug, module

#10296 A few aux module docs
  documentation/modules/auxiliary/scanner/imap/imap_version.md
  documentation/modules/auxiliary/scanner/pop3/pop3_version.md
  documentation/modules/auxiliary/scanner/rsync/modules_list.md
  documentation/modules/auxiliary/scanner/smtp/smtp_version.md
Labels: docs

#10302 Move module documentation to documentation directory
  documentation/modules/exploit/windows/http/manageengine_adshacluster_rce.md
  modules/post/windows/gather/ntds_grabber.md
Labels: docs

#10304 Add "log" console command to display framework.log
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: feature, msfconsole

#10273 [clean up] iis_webdav_scstoragepathfromurl
  modules/exploits/windows/iis/iis_webdav_scstoragepathfromurl.rb
Labels: enhancement, module, rn-no-release-notes

#10315 Add support for HTTP POST and Basic Auth to psnuffle
  data/exploits/psnuffle/url.rb
Labels: module

#10317 Check if IPRANGE was supplied - Fix #10316
  modules/auxiliary/gather/enum_dns.rb
Labels: bug, newbie-friendly

#10309 show error if server.pid == pid
  lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb
Labels: bug, library, meterpreter

#10340 Fix fake_function_collection_spec
  spec/lib/metasploit/framework/obfuscation/crandomizer/code_factory/fake_function_collection_spec.rb
Labels: rn-no-release-notes, tests

#10334 Add grep -C to msfconsole and fix prompt rewriting
  lib/msf/ui/console/command_dispatcher/core.rb
Labels: bug, feature, msfconsole, newbie-friendly

#10328 Print connection errors and fix RPORT in Python ETERNALBLUE
  modules/exploits/windows/smb/ms17_010_eternalblue_win8.py
Labels: bug, external modules

#10346 Update cmsms_upload_rename_rce check and docs
  documentation/modules/exploit/multi/http/cmsms_upload_rename_rce.md
  modules/exploits/multi/http/cmsms_upload_rename_rce.rb
Labels: enhancement, module, rn-no-release-notes

#10364 Specify address family in shell_reverse_tcp_ipv6
  modules/payloads/singles/linux/x86/shell_reverse_tcp_ipv6.rb
Labels: bug, payload

#10345 Refactor grep command to use optparse
  lib/msf/ui/console/command_dispatcher/core.rb
  lib/rex/ui/text/dispatcher_shell.rb
Labels: enhancement, msfconsole

#10369 Fix rspec for fake_function_collection_spec.rb
  spec/lib/metasploit/framework/obfuscation/crandomizer/code_factory/fake_function_collection_spec.rb
Labels: tests

#10370 Fix #10357, minor change to service info
  modules/auxiliary/scanner/couchdb/couchdb_enum.rb
Labels: bug, module

#10300 Add root exploit for Axis network cameras
  modules/exploits/linux/http/axis_srv_parhand_rce.rb
Labels: feature, module, needs-docs

#10375 Modify options for smb_login
  modules/auxiliary/scanner/smb/smb_login.rb
Labels: bug, module

#10303 Fix issue that the check would swallow exceptions
  lib/msf/core/exploit/http/client.rb
Labels: bug, library

#10319 Update ms15_034_http_sys_memory_dump.rb with VHOST
  modules/auxiliary/scanner/http/ms15_034_http_sys_memory_dump.rb
Labels: enhancement, module

#10247 Add Wordpress Arbitrary File Deletion module
  documentation/modules/auxiliary/scanner/http/wp_arbitrary_file_deletion.md
  modules/auxiliary/scanner/http/wp_arbitrary_file_deletion.rb
Labels: docs, module

#10397 Added line in psexec_psh to support SMB2
  modules/exploits/windows/smb/psexec_psh.rb
Labels: easy, enhancement, newbie-friendly

#10398 remove unused juniper options
  modules/post/juniper/gather/enum_juniper.rb
Labels: bug, module

#10384 Fix upload_exec for absolute paths
  modules/post/multi/manage/upload_exec.rb
Labels: bug, module

#10403 Show IP and Port in joomla page scanner output
  modules/auxiliary/scanner/http/joomla_pages.rb
Labels: enhancement, module
