Repository rapid7/metasploit-framework, pull requests merged in 2019-06, with the labels that each got.

#11906 fix osx 10.7 hash IDing, and JTR ids
  modules/post/osx/gather/hashdump.rb
Labels: a2k19, osx

#11902 add missing cmd/unix/reverse_bash_udp test
  spec/modules/payloads_spec.rb
Labels: rn-no-release-notes, tests

#11913 remove Ruby 2.3.8 from Metasploit test matrix
  .travis.yml
Labels: a2k19, ruby-compat, tests

#11933 Add default VID and cmd/unix support to post/multi/manage/play_youtube
  modules/post/multi/manage/play_youtube.rb
Labels: a2k19, enhancement, module

#11936 Move frontpage_credential_dump.md to correct directory
  documentation/modules/auxiliary/scanner/http/frontpage_credential_dump.md
Labels: docs, easy

#11918 replace trivial usage of expand_path with getenv
  lib/msf/base/sessions/meterpreter.rb
  lib/rex/post/meterpreter/extensions/stdapi/webcam/webcam.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/kiwi.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/sys.rb
  modules/exploits/windows/local/cve_2017_8464_lnk_lpe.rb
  modules/exploits/windows/local/persistence_service.rb
  modules/exploits/windows/local/ps_persist.rb
  modules/post/windows/gather/credentials/tortoisesvn.rb
  modules/post/windows/manage/persistence_exe.rb
  modules/post/windows/manage/powershell/build_net_code.rb
  scripts/meterpreter/metsvc.rb
  scripts/meterpreter/persistence.rb
  test/modules/post/test/meterpreter.rb
Labels: a2k19, library, payload

#11937 if there is no content, don't include content length
  lib/rex/proto/http/packet.rb
Labels: a2k19, library

#11940 Add some files to the test that are not likely to be open
  test/modules/post/test/file.rb
Labels: bug, easy, test module

#11798 Added Extended passive mode to the core ftp module.
  lib/msf/core/exploit/ftp.rb
Labels: enhancement, module

#11951 Add meterpreter > screenshare command for real time desktop monitoring
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/stream.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/ui.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/webcam.rb
Labels: meterpreter

#11970 Correct IBM Websphere Application Server Network Deployment RCE module CVE reference
  modules/exploits/windows/ibm/ibm_was_dmgr_java_deserialization_rce.rb
Labels: easy, module, rn-no-release-notes

#11963 Remove jobs options from kill help
  lib/msf/ui/console/command_dispatcher/jobs.rb
Labels: a2k19, bug, easy, library, msfconsole

#11974 Concatenate path and name in Meterpreter pgrep -lf
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/sys.rb
Labels: bug, library, meterpreter

#11958 abrt_raceabrt_priv_esc: Fix abrt package version check
  modules/exploits/linux/local/abrt_raceabrt_priv_esc.rb
Labels: bug, module

#11965 Add a `secure` command to renegotiate TLV encryption
  lib/rex/post/meterpreter/client_core.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb
Labels: a2k19, enhancement, meterpreter

#11966 Stop error rendering in multi/meterpreter handler
  lib/msf/core/handler/reverse_http.rb
Labels: enhancement

#11979 add missing bind_tcp_rc4 payload tests
  spec/modules/payloads_spec.rb
Labels: bug, tests

#11932 Bluekeep (CVE-2019-0708): add TLS, document blobs, refactor
  modules/auxiliary/scanner/rdp/cve_2019_0708_bluekeep.rb
Labels: delayed, enhancement, module

#11904 fix the meterpreter > screenshot command to only upload the dll on Windows
  lib/rex/post/meterpreter/extensions/stdapi/ui.rb
Labels: a2k19

#11960 Add Privilege Escalation Module for Cisco Prime Infrastructure's runrshell Executable
  documentation/modules/exploit/linux/local/cpi_runrshell_priv_esc.md
  modules/exploits/linux/local/cpi_runrshell_priv_esc.rb
Labels: docs, module

#11996 Add a ZDI reference for CVE-2019-5420 Rails exploit
  modules/exploits/multi/http/rails_double_tap.rb
Labels: easy, rn-no-release-notes

#12008 struts2_content_type_ognl: Don't care about response code
  modules/exploits/multi/http/struts2_content_type_ognl.rb
Labels: bug, easy

#12015 Remove misleading comment from dcerpc_getarch
  lib/msf/core/exploit/dcerpc.rb
Labels: bug, easy, library, rn-no-release-notes

#12018 Add Pen Test Partners reference to Cisco RV130 exploit
  modules/exploits/linux/http/cisco_rv130_rmi_rce.rb
Labels: docs, enhancement, module

#12017 Minor fix for xdebug_unauth_exec
  modules/exploits/unix/http/xdebug_unauth_exec.rb
Labels: bug, module

#12019 Update bypassuac_sluihijack: Fix typo
  modules/exploits/windows/local/bypassuac_sluihijack.rb
Labels: bug, easy, module

#12022 Deregister PASSWORD_SPRAY option for LoginScanner modules
  modules/auxiliary/scanner/acpp/login.rb
  modules/auxiliary/scanner/afp/afp_login.rb
  modules/auxiliary/scanner/db2/db2_auth.rb
  modules/auxiliary/scanner/ftp/ftp_login.rb
  modules/auxiliary/scanner/http/advantech_webaccess_login.rb
  modules/auxiliary/scanner/http/appletv_login.rb
  modules/auxiliary/scanner/http/axis_login.rb
  modules/auxiliary/scanner/http/bavision_cam_login.rb
  modules/auxiliary/scanner/http/buffalo_login.rb
  modules/auxiliary/scanner/http/caidao_bruteforce_login.rb
  modules/auxiliary/scanner/http/chef_webui_login.rb
  modules/auxiliary/scanner/http/cisco_firepower_login.rb
  modules/auxiliary/scanner/http/directadmin_login.rb
  modules/auxiliary/scanner/http/gitlab_login.rb
  modules/auxiliary/scanner/http/glassfish_login.rb
  modules/auxiliary/scanner/http/hp_sys_mgmt_login.rb
  modules/auxiliary/scanner/http/http_login.rb
  modules/auxiliary/scanner/http/ipboard_login.rb
  modules/auxiliary/scanner/http/jenkins_login.rb
  modules/auxiliary/scanner/http/manageengine_desktop_central_login.rb
  modules/auxiliary/scanner/http/mybook_live_login.rb
  modules/auxiliary/scanner/http/octopusdeploy_login.rb
  modules/auxiliary/scanner/http/phpmyadmin_login.rb
  modules/auxiliary/scanner/http/symantec_web_gateway_login.rb
  modules/auxiliary/scanner/http/tomcat_mgr_login.rb
  modules/auxiliary/scanner/http/wordpress_multicall_creds.rb
  modules/auxiliary/scanner/http/wordpress_xmlrpc_login.rb
  modules/auxiliary/scanner/http/zabbix_login.rb
  modules/auxiliary/scanner/mqtt/connect.rb
  modules/auxiliary/scanner/mssql/mssql_login.rb
  modules/auxiliary/scanner/mysql/mysql_login.rb
  modules/auxiliary/scanner/nessus/nessus_rest_login.rb
  modules/auxiliary/scanner/pop3/pop3_login.rb
  modules/auxiliary/scanner/postgres/postgres_login.rb
  modules/auxiliary/scanner/redis/redis_login.rb
  modules/auxiliary/scanner/smb/smb_login.rb
  modules/auxiliary/scanner/snmp/snmp_login.rb
  modules/auxiliary/scanner/ssh/karaf_login.rb
  modules/auxiliary/scanner/ssh/ssh_login.rb
  modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb
  modules/auxiliary/scanner/telnet/brocade_enable_login.rb
  modules/auxiliary/scanner/telnet/telnet_login.rb
  modules/auxiliary/scanner/varnish/varnish_cli_login.rb
  modules/auxiliary/scanner/vmware/vmauthd_login.rb
  modules/auxiliary/scanner/vnc/vnc_login.rb
  modules/auxiliary/scanner/winrm/winrm_login.rb
Labels: bug, library, module

#12025 Fix sshexec hanging on exec! and blocking close
  modules/exploits/multi/ssh/sshexec.rb
Labels: bug, module

#12014 Fix get_resource nil bug in HttpServer#get_uri
  lib/msf/core/exploit/http/server.rb
Labels: bug, easy, library

#12029 Fix creds error
  lib/msf/ui/console/command_dispatcher/creds.rb
Labels: bug, confirmed, creds

#12023 Add the ability to display previous search results
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: enhancement, library, msf5, msfconsole

#11976 fix #11975, fix meterpreter shell command on android
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/sys.rb
Labels: android, bug, meterpreter, payload

#11923 Fix issue where Linux x64 shell_find_port did not set the sockaddr_len value
  modules/payloads/singles/linux/x64/shell_find_port.rb
Labels: bug, payload
