Repository rapid7/metasploit-framework, pull requests merged in 2019-02, with the labels that each got.

#11310 Don't use system() to ZIP files in auxiliary/client/smtp/emailer
  modules/auxiliary/client/smtp/emailer.rb
Labels: bug, module

#11309 Normalize newlines in CommandShell#run_single
  lib/msf/base/sessions/command_shell.rb
Labels: bug, library

#11350 undefined method `to_linux_armle_elf_dll' for Msf::Util::EXE:Class
  lib/msf/util/exe.rb
Labels: bug, library, msfvenom

#11347 add version check to Safari RCE exploit
  modules/exploits/osx/browser/safari_proxy_object_type_confusion.rb
Labels: module, osx

#11304 Add CVE-2018-1000999 to MailCleaner module
  modules/exploits/linux/http/mailcleaner_exec.rb
Labels: docs, feature, module, rn-no-release-notes

#11362 restrict sqlite3 gem for windows
  Gemfile
  Gemfile.lock
Labels: rn-no-release-notes

#11363 lock sqlite3 to compatible minor not just major
  Gemfile
Labels: rn-no-release-notes

#11072 Add nuuo_nvrmini_upgrade_rce.rb
  modules/exploits/multi/http/nuuo_nvrmini_upgrade_rce.rb
Labels: module, needs-docs

#11361 Add URL scheme and Base64.encode64 checks to msftidy
  tools/dev/msftidy.rb
Labels: easy, msftidy, newbie-friendly

#11342 Modify Post read_file to check if file is readable
  lib/msf/core/post/file.rb
Labels: enhancement, library

#11371 Add auxiliary/scanner/http/rips_traversal docs
  documentation/modules/auxiliary/scanner/http/rips_traversal.md
Labels: docs, easy, newbie-friendly

#11345 Add Solaris pfexec Upgrade Shell module
  documentation/modules/post/solaris/escalate/pfexec.md
  modules/post/solaris/escalate/pfexec.rb
Labels: docs, module

#11239 Add check for writable and nosuid WritableDir
  modules/exploits/linux/local/docker_daemon_privilege_escalation.rb
Labels: enhancement, module, newbie-friendly

#11220 new PCOM module to send admin commands
  documentation/modules/auxiliary/dos/scada/pcom.md
  modules/auxiliary/dos/scada/pcom.rb
Labels: docs, module

#11394 Add auxiliary/scanner/http/options doc
  documentation/modules/auxiliary/scanner/http/options.md
Labels: docs

#11398 python 3 compatibility
  data/exploits/CVE-2015-1130/exploit.py
Labels: enhancement

#11384 Adding auxiliary/scanner/http/dir_listing documentation
  documentation/modules/auxiliary/scanner/http/dir_listing.md
Labels: docs

#11401 fix #11395, use db.hosts.each
  lib/msf/ui/console/command_dispatcher/core.rb
Labels: bug, msf5

#11408 spelling fixes in docs
  documentation/modules/auxiliary/analyze/apply_pot.md
  documentation/modules/auxiliary/scanner/http/dir_listing.md
Labels: docs

#11411 Meterpreter scripts do not display help info.
  lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb
Labels: bug

#11416 Deprecate get_env script
  lib/msf/base/sessions/scriptable.rb
Labels: easy, newbie-friendly

#11424 Changed print_status to print_good on line 87
  modules/auxiliary/scanner/http/title.rb
Labels: easy, enhancement, module, rn-no-release-notes

#11434 Fix #11433 creds command bug
  lib/msf/ui/console/command_dispatcher/creds.rb
Labels: bug, creds

#11439 Added Telnet Modules Docs
  documentation/modules/auxiliary/scanner/telnet/telnet_login.md
  documentation/modules/auxiliary/scanner/telnet/telnet_version.md
Labels: docs

#11430 Deregister RHOSTS instead of RHOST
  modules/auxiliary/scanner/jenkins/jenkins_udp_broadcast_enum.rb
Labels: bug, easy, module

#11393 Implement deregistering an option by alias
  lib/msf/core/data_store.rb
  lib/msf/core/module/options.rb
Labels: bug, library, module

#11404 Add manageengine_deviceexpert_user_creds docs
  documentation/modules/auxiliary/scanner/http/manageengine_deviceexpert_user_creds.md
Labels: docs, easy, newbie-friendly

#11392 don't create a new socket every time the command prompt is displayed
  lib/rex/ui/text/shell.rb
Labels: bug, library, msfconsole

#11444 change default database web service port to 5443
  msfdb
Labels: database, enhancement

#11451 update module authors to consume JSON cache
  tools/modules/module_author.rb
Labels: bug

#11462 Add Reliability REPEATABLE_SESSION to Wemo exploit
  modules/exploits/linux/upnp/belkin_wemo_upnp_exec.rb
Labels: bug, easy, module

#11460 Changing print_line to print_good
  modules/auxiliary/scanner/http/iis_shortname_scanner.rb
Labels: module

#11463 Add NOCVE and reason to Wemo exploit
  modules/exploits/linux/upnp/belkin_wemo_upnp_exec.rb
Labels: easy, enhancement, module

#11465 Fix author names in a couple modules
  modules/auxiliary/scanner/printer/canon_iradv_pwd_extract.rb
  modules/exploits/linux/misc/jenkins_java_deserialize.rb
Labels: bug, easy, module

#11446 SideEffects Stability Reliability check
  tools/dev/msftidy.rb
Labels: msftidy

#11486 Fix several bugs running non-scanner aux modules
  lib/msf/ui/console/command_dispatcher/auxiliary.rb
Labels: bug, module

#11467 Add CMDSTAGER::TEMP with WritableDir fallback
  lib/msf/core/exploit/cmdstager.rb
Labels: enhancement, library

#11485 Add VHOST support to full_uri
  lib/msf/core/exploit/http/client.rb
Labels: easy, enhancement, library

#11447 Updated Docs
  documentation/modules/auxiliary/scanner/http/http_put.md
  documentation/modules/auxiliary/scanner/http/scraper.md
Labels: docs

#11493 Further improve / fix RHOSTS support for aux modules
  lib/msf/ui/console/command_dispatcher/auxiliary.rb
Labels: bug, msfconsole

#11497 add file: support for RHOSTS option on exploit modules
  lib/msf/ui/console/command_dispatcher/exploit.rb
Labels: bug, msf5

#11445 Enhanced winrm_cmd module
  modules/auxiliary/scanner/winrm/winrm_cmd.rb
Labels: enhancement, module
