Repository rapid7/metasploit-framework, pull requests merged in 2019-05, with the labels that each got.

#11786 Fix DB RPC issues
  lib/msf/core/rpc/v10/rpc_db.rb
Labels: bug, database

#11804 loadpath command generates bad plural for 'auxiliarys'
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: bug, msfconsole, newbie-friendly

#11803 check for platform-specific env. variables in post-API tests
  test/modules/post/test/get_env.rb
Labels: bug, test module

#11821 throw exception on actual payload size violation, not formatted output size
  lib/msf/core/payload_generator.rb
Labels: bug, msfvenom, payload

#11820 Display NOCVE reason cleanly in info command output
  lib/msf/base/serializer/readable_text.rb
Labels: enhancement, library

#11802 CVE-2019-11231 exploit: GetSimple CMS Unauth RCE
  modules/exploits/multi/http/getsimplecms_unauth_code_exec.rb
Labels: module, needs-docs

#11842 Regression fix: Disabling wrap_double_quotes
  modules/exploits/windows/browser/ms14_064_ole_code_execution.rb
Labels: bug, module

#11374 Add metasm format of code for Super small Shell Bind TCP Random Port
  modules/payloads/singles/linux/x86/shell_bind_tcp_super_small_random_port.rb
Labels: payload

#11834 Fix ams_hndlrsvc
  documentation/modules/exploit/windows/antivirus/ams_hndlrsvc.md
  modules/exploits/windows/antivirus/ams_hndlrsvc.rb
Labels: bug

#11859 Indent ternary statement in struts2_rest_xstream
  modules/exploits/multi/http/struts2_rest_xstream.rb
Labels: bug, easy, module, rn-no-release-notes

#11833 moodle_cmd_exec nil check
  modules/exploits/multi/http/moodle_cmd_exec.rb
Labels: bug, easy

#11808 Add FreeBSD rtld execl() Privilege Escalation module
  documentation/modules/exploit/freebsd/local/rtld_execl_priv_esc.md
  modules/exploits/freebsd/local/rtld_execl_priv_esc.rb
Labels: docs, module

#11805 Add BSD targets to exploit/multi/ssh/sshexec module
  modules/exploits/multi/ssh/sshexec.rb
Labels: easy, enhancement, module

#11661 Add http login scanner for Onion Omega2 devices
  documentation/modules/auxiliary/scanner/http/onion_omega2_login.md
  modules/auxiliary/scanner/http/onion_omega2_login.py
Labels: docs, external modules

#11847 Bugfix for post/multi/gather/jenkins_gather
  modules/post/multi/gather/jenkins_gather.rb
Labels: bug, module

#11868 Fix disclosure date for WebDAV module
  modules/exploits/windows/iis/iis_webdav_upload_asp.rb
Labels: bug, docs, easy, module

#11877 restore analyze on framework object
  lib/msf/core/framework.rb
Labels: bug, library, msf5

#11879 Add multi-host tab completion to analyze command and fix range truncation bug
  lib/msf/ui/console/command_dispatcher/db.rb
  lib/msf/ui/console/command_dispatcher/db/analyze.rb
Labels: bug, enhancement, library

#11880 Update show command to zero-index
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: bug, library, msf5, msfconsole

#11794 Postgres 8.2+ update to postgres_payload.rb module
  modules/exploits/linux/postgres/postgres_payload.rb
Labels: bug, module

#11811 exploit/linux/local/bpf_sign_extension_priv_esc: add tested system
  documentation/modules/exploit/linux/local/bpf_sign_extension_priv_esc.md
Labels: docs

#11869 CVE-2019-0708 "BlueKeep" auxiliary scanner module
  modules/auxiliary/scanner/rdp/cve_2019_0708_bluekeep.rb
Labels: feature, hotness, module

#11883 CVE-2019-0708 docs change to .md extension instead of .rb
  documentation/modules/auxiliary/scanner/rdp/cve_2019_0708_bluekeep.md
Labels: docs, module, rn-no-release-notes

#11885 Update linux/armle/shell_bind_tcp.rb
  modules/payloads/singles/linux/armle/shell_bind_tcp.rb
Labels: bug, payload

#11888 Update autoroute.md
  documentation/modules/post/multi/manage/autoroute.md
Labels: docs

#11797 Added to code to remove payload once run.
  modules/payloads/singles/cmd/mainframe/apf_privesc_jcl.rb
Labels: payload

#11898 move require for pdf-reader
  modules/auxiliary/gather/http_pdf_authors.rb
Labels: module, ruby-compat

#11865 expand utility for allegro_rompager_auth_bypass
  modules/auxiliary/admin/http/allegro_rompager_auth_bypass.rb
Labels: enhancement, module

#11900 Prefer initial slash in normalize_uri for jenkins_metaprogramming and future modules
  modules/exploits/multi/http/jenkins_metaprogramming.rb
Labels: bug, module, rn-no-release-notes

#11887 Fix multi meterpreter_reverse_http handler to not care so much about the workspace.
  lib/msf/core/handler/reverse_http.rb
  lib/msf/core/payload/uuid/options.rb
Labels: msf5

#11838 Add meterpreter keyboard and mouse input
  lib/rex/post/meterpreter/extensions/stdapi/tlv.rb
  lib/rex/post/meterpreter/extensions/stdapi/ui.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/ui.rb
Labels: meterpreter

#11892 Fix parse IPv6 address in reverse_http
  lib/msf/core/handler/reverse_http.rb
Labels: bug, library

#11912 Bigdecimal boot
  config/boot.rb
  lib/msf/core.rb
Labels: a2k19, easy, msfconsole

#11911 fix java/android cmd_exec and shell_command_token
  Gemfile.lock
  metasploit-framework.gemspec
Labels: a2k19, bug, payload

#11915 Bubble Validation Error which is caught
  lib/metasploit/framework/data_service/proxy/core.rb
Labels: a2k19, rn-no-release-notes
