Repository rapid7/metasploit-framework, pull requests merged in 2019-08, with the labels that each got.

#11653 Apache Tika CVE-2018-1335 RCE
  documentation/modules/exploit/windows/http/apache_tika_jp2_jscript.md
  modules/exploits/windows/http/apache_tika_jp2_jscript.rb
Labels: docs, module

#12155 Fix printed CVE number
  modules/auxiliary/scanner/http/intel_amt_digest_bypass.rb
Labels: bug, module

#12152 Rescue EOFError in cve_2019_0708_bluekeep get_once
  modules/auxiliary/scanner/rdp/cve_2019_0708_bluekeep.rb
Labels: bug, easy, module

#12170 BlueKeep: Add DoS exploit
  modules/auxiliary/scanner/rdp/cve_2019_0708_bluekeep.rb
Labels: enhancement, module

#12175 Fix #12156, NoMethodError in hadoop exploit.
  modules/exploits/linux/http/hadoop_unauth_exec.rb
Labels: bug, module

#12161 Store opasswd password history
  modules/post/linux/gather/hashdump.rb
Labels: enhancement, module

#12188 Fix typo, full_name -> fullname
  tools/modules/module_author.rb
Labels: bug

#12199 Fix nil RangeWalker length for invalid range in exploit RHOSTS
  lib/msf/ui/console/command_dispatcher/exploit.rb
Labels: bug, library, msf5, msfconsole

#12202 Add needs_cleanup to the post module class so filedropper does not
  lib/msf/core/post.rb
Labels: bug, library

#12203 Disable a couple of modules for autoexploitation
  modules/exploits/windows/dcerpc/ms03_026_dcom.rb
  modules/exploits/windows/smb/netidentity_xtierrpcpipe.rb
Labels: enhancement, module

#12214 RDP lib: accept TLS 1.0
  lib/msf/core/exploit/rdp.rb
Labels: enhancement, library

#12181 juniper config parser tests
  lib/msf/core/auxiliary/juniper.rb
  spec/lib/msf/core/auxiliary/juniper_spec.rb
Labels: library, tests

#12168 Use correct case for SSL option
  lib/msf/core/exploit/http/client.rb
Labels: bug, library

#12218 explicitly require factory_bot, see #12181
  spec/spec_helper.rb
Labels: rn-no-release-notes, tests

#12221 Fix RPC console.create database active check
  lib/msf/ui/web/console.rb
Labels: bug, msf5

#12064 Add Exim 4.87 - 4.91 deliver_message() Local Privilege Escalation Module (CVE 2019-10149)
  documentation/modules/exploit/linux/local/exim4_deliver_message_priv_esc.md
  modules/exploits/linux/local/exim4_deliver_message_priv_esc.rb
Labels: docs, module

#12252 Add dwelch to mailmap
  .mailmap
Labels: docs

#12253 Backport #12223, module deprecation by alias
  lib/msf/core/auxiliary.rb
  lib/msf/core/exploit.rb
  lib/msf/core/module.rb
  lib/msf/core/module/alert.rb
  lib/msf/core/module/deprecated.rb
  lib/msf/core/module/full_name.rb
  lib/msf/core/module/ui.rb
  lib/msf/core/module_manager.rb
  lib/msf/core/module_manager/loading.rb
  lib/msf/core/modules/loader/base.rb
  lib/msf/core/modules/metadata/cache.rb
  lib/msf/core/modules/metadata/maps.rb
  lib/msf/core/modules/metadata/obj.rb
  lib/msf/core/post_mixin.rb
  modules/exploits/linux/http/ubiquiti_airos_file_upload.rb
  modules/exploits/unix/misc/qnx_qconn_exec.rb
  modules/exploits/unix/polycom_hdx_auth_bypass.rb
  spec/lib/msf/core/module_spec.rb
Labels: bug

#12254 Correct realname calls in the cache to fullname
  lib/msf/core/modules/metadata/maps.rb
Labels: bug
