Repository rapid7/metasploit-framework, pull requests merged in 2019-07, with the labels that each got.

#12042 Add lokiuox to bypassuac_silentcleanup authors
  modules/exploits/windows/local/bypassuac_silentcleanup.rb
Labels: bug, module, rn-no-release-notes

#12036 Fix OpenVAS import issue caused by missing wspace key
  lib/msf/core/db_manager/import/open_vas.rb
  spec/support/shared/examples/msf/db_manager/import/open_vas.rb
Labels: bug, database

#12044 Fix SNMP enumeration module network interface processing
  modules/auxiliary/scanner/snmp/snmp_enum.rb
Labels: bug, module

#12045 revert rex-socket back to 0.1.17 for now
  Gemfile.lock
  metasploit-framework.gemspec
Labels: bug, payload

#12072 Fix cmd_psh_payload requiring an arch string
  modules/exploits/multi/fileformat/ghostscript_failed_restore.rb
  modules/exploits/multi/http/struts2_rest_xstream.rb
  modules/exploits/windows/local/ms16_032_secondary_logon_handle_privesc.rb
Labels: bug, easy, module

#12074 Fix missing split in cmd_psh_payload fixes
  modules/exploits/multi/http/struts2_rest_xstream.rb
Labels: bug, module

#12079 No effing idea
  modules/exploits/apple_ios/browser/webkit_createthis.rb
Labels: docs, easy, feature

#12080 Gracefully handle passthrough commands
  lib/msf/ui/console/driver.rb
Labels: bug, easy, msfconsole

#12085 Fix is_payload_compatible? for nil payloads
  lib/msf/core/exploit.rb
Labels: bug, easy, library

#12041 Add Xymon useradm Command Execution module
  documentation/modules/exploit/unix/webapp/xymon_useradm_cmd_exec.md
  modules/exploits/unix/webapp/xymon_useradm_cmd_exec.rb
Labels: docs, module

#12031 Add shutdown method to Exploit::Remote::Tcp
  lib/msf/core/exploit/tcp.rb
Labels: enhancement, library

#12087 Restore unknown_command passthrough to the shell
  lib/msf/ui/console/driver.rb
Labels: bug, library, msfconsole

#12086 Minor fix for aux joomla_registration_privesc
  modules/auxiliary/admin/http/joomla_registration_privesc.rb
Labels: enhancement, module

#12011 Add module for cve-2018-8453
  data/exploits/CVE-2018-8453/CVE-2018-8453.exe
  documentation/modules/exploit/windows/local/cve_2018_8453_win32k_priv_esc.md
  external/source/exploits/CVE-2018-8453/CVE-2018-8453.sln
  external/source/exploits/CVE-2018-8453/CVE-2018-8453/CVE-2018-8453.cpp
  external/source/exploits/CVE-2018-8453/CVE-2018-8453/CVE-2018-8453.vcxproj
  external/source/exploits/CVE-2018-8453/CVE-2018-8453/ReadMe.txt
  external/source/exploits/CVE-2018-8453/CVE-2018-8453/stdafx.cpp
  external/source/exploits/CVE-2018-8453/CVE-2018-8453/stdafx.h
  external/source/exploits/CVE-2018-8453/CVE-2018-8453/targetver.h
  modules/exploits/windows/local/cve_2018_8453_win32k_priv_esc.rb
Labels: docs, module

#12111 nmod fix for non-scanner aux RHOSTS
  lib/msf/ui/console/command_dispatcher/auxiliary.rb
Labels: bug, library, msf5

#12108 Prefer Rex::Text.dehex over Rex::Text.hex_to_raw in msfvenom
  msfvenom
Labels: enhancement, msfvenom

#12033 Metasploit context-keyed payload encoder based on hostname (linux, intel, 64 bit)
  modules/encoders/x64/xor_context.rb
Labels: feature

#12121 Bump rex-text gem to 0.2.22 for XOR enhancements
  Gemfile.lock
  LICENSE_GEMS
Labels: enhancement, library, rn-no-release-notes

#11205 Add support for Linux and pubprn.vbs to multi/script/web_delivery
  modules/exploits/multi/script/web_delivery.rb
Labels: enhancement, module

#12124 Add HttpRawHeaders (file) advanced option to HttpClient
  lib/msf/core/exploit/http/client.rb
Labels: enhancement, library

#12132 Catch EOFError - Fix #12061
  modules/auxiliary/admin/emc/alphastor_devicemanager_exec.rb
Labels: bug, easy, rn-no-release-notes

#12131 Cast to_s - Fix #11725
  lib/msf/base/sessions/command_shell.rb
Labels: bug, easy

#12148 Lock bcrypt gem until armhf support is restored.
  Gemfile.lock
  metasploit-framework.gemspec
Labels: library, ruby-compat

#12150 Accidentally removed include that is sort of imperative....
  lib/msf/core/payload/windows/x64/reverse_tcp.rb
Labels: bug, easy, meterpreter, newbie-friendly, payload
