Repository rapid7/metasploit-framework, pull requests merged in 2019-01, with the labels that each got.

#11154 Enhance the command auto-complete in aux.
  lib/msf/ui/console/command_dispatcher/auxiliary.rb
Labels: easy, enhancement

#11194 set bundler version for travis for now
  .travis.yml
Labels: rn-no-release-notes, ruby-compat

#11195 update travis to use latest rubygems
  .travis.yml
Labels: rn-no-release-notes, ruby-compat

#11187 Fix LoginServlet to meet API standards and documented functionality
  lib/msf/core/web_services/servlet/login_servlet.rb
Labels: bug, msf5

#11199 update joomla wordlists
  data/wordlists/joomla.txt
Labels: easy, enhancement

#11106 DoS Exploitation of Allen-Bradley legacy protocol (PCCC)
  documentation/modules/auxiliary/dos/scada/allen_bradley_pccc.md
  modules/auxiliary/dos/scada/allen_bradley_pccc.rb
Labels: docs, module

#11211 Update db_connect Connection Persistence Logic
  lib/msf/ui/console/command_dispatcher/db.rb
Labels: bug, database, msf5

#11226 typo fixes in cisco_firepower_useradd.md
  documentation/modules/exploit/linux/http/cisco_firepower_useradd.md
Labels: bug, docs, easy

#11225 Dont log every request when using HTTP data service
  lib/metasploit/framework/data_service/remote/http/core.rb
Labels: msf5

#11223 ueb priv esc suggestion
  modules/exploits/linux/http/ueb_api_rce.rb
Labels: easy

#11232 Update msfdb to get the MSF config root directory rather than use a fixed value
  msfdb
Labels: msf5

#11217 auxiliary/fileformat/badpdf: fix syntax and logic error in options handling
  modules/auxiliary/fileformat/badpdf.rb
Labels: bug, module

#11233 Update MSF v5 banner on account of the MSF5 release
  data/logos/metasploit-v5.txt
Labels: easy, msf5

#11255 Assign CVE-2018-11770 to exploits/linux/http/spark_unauth_rce
  modules/exploits/linux/http/spark_unauth_rce.rb
Labels: easy, module

#11245 Update documentation for post/multi/gather/chrome_cookies
  documentation/modules/post/multi/gather/chrome_cookies.md
  modules/post/multi/gather/chrome_cookies.rb
Labels: docs

#11242 Use 'to_s.strip' for Msf::Post::File.pwd output
  lib/msf/core/post/file.rb
Labels: bug, easy, library

#11269 Update java_deserialization_spec to rescue the right exception
  spec/lib/msf/util/java_deserialization_spec.rb
Labels: easy, rn-no-release-notes, tests

#11277 Fix failing remote data service spec tests for Msf::DBManager::Cred
  spec/support/shared/examples/msf/db_manager/cred.rb
Labels: bug, msf5

#11284 Pass down workspace too report_web_site
  plugins/wmap.rb
Labels: bug

#11287 Attribution
  modules/exploits/linux/local/blueman_set_dhcp_handler_dbus_priv_esc.rb
Labels: easy, module

#11272 Prefer Tempfile over Rex::Quickfile for info -d
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: bug, library, msfconsole

#11297 typo fixed
  modules/auxiliary/dos/scada/allen_bradley_pccc.rb
Labels: easy, newbie-friendly

#11268 set AndroidWakelock=true by default
  lib/msf/core/payload/android/payload_options.rb
Labels: android

#11275 Fix typo of "architectures" in pivot command help
  lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb
Labels: bug, easy, library

#11271 Implement resource scripting for command shells
  lib/msf/base/sessions/command_shell.rb
  lib/msf/base/sessions/meterpreter.rb
Labels: bug, enhancement, library

#11303 Add Msf::Post::Linux::Kernel.cpu_flags
  lib/msf/core/post/linux/kernel.rb
Labels: library

#11299 Simplified UX + enhancements for msfdb
  msfdb
Labels: enhancement, msf5
