Repository rapid7/metasploit-framework, pull requests merged in 2019-10, with the labels that each got.

#12377 Fix stack_adjustment nil bug and refactor method
  lib/msf/core/exploit.rb
Labels: bug, library

#12385 Remove invalid email addresses
  lib/msf/core/exploit/tincd.rb
  modules/exploits/multi/vpn/tincd_bof.rb
Labels: easy, newbie-friendly

#12368 Smb docs
  documentation/modules/auxiliary/server/capture/smb.md
Labels: docs

#12388 Add Required Signature Detection To smb_version
  lib/rex/proto/smb/client.rb
  modules/auxiliary/scanner/smb/smb_version.rb
Labels: enhancement

#12392 Spelling correction in iis_shortname_scanner.rb
  modules/auxiliary/scanner/http/iis_shortname_scanner.rb
Labels: easy, newbie-friendly

#12393 Spelling correction in udp_sweep.rb
  modules/auxiliary/scanner/discovery/udp_sweep.rb
Labels: easy, newbie-friendly

#12395 Corrected spelling in bison_ftp_traversal.rb
  modules/auxiliary/scanner/ftp/bison_ftp_traversal.rb
Labels: easy, newbie-friendly

#12394 Corrected spelling in db2_auth.rb
  modules/auxiliary/scanner/db2/db2_auth.rb
Labels: easy, newbie-friendly

#12398 Add documentation for auxiliary/scanner/ssh/ssh_version module
  documentation/modules/auxiliary/scanner/ssh/ssh_version.md
Labels: docs

#12407 begining to fix spelling errors
  modules/auxiliary/admin/http/rails_devise_pass_reset.rb
  modules/exploits/linux/local/hp_smhstart.rb
  modules/exploits/windows/smb/ms09_050_smb2_negotiate_func_index.rb
  modules/post/windows/gather/forensics/recovery_files.rb
Labels: easy

#12406 adress a spelling problem
  documentation/modules/exploit/linux/http/alienvault_exec.md
  modules/auxiliary/admin/oracle/ora_ntlm_stealer.rb
  modules/auxiliary/scanner/printer/canon_iradv_pwd_extract.rb
  modules/exploits/multi/http/mutiny_subnetmask_exec.rb
Labels: easy

#12408 fix spelling received
  documentation/modules/auxiliary/client/iec104/iec104.md
  documentation/modules/exploit/linux/misc/ueb9_bpserverd.md
  lib/msf/core/exploit/http/wordpress/posts.rb
  lib/msf/core/exploit/winrm.rb
  modules/auxiliary/client/iec104/iec104.rb
  modules/exploits/linux/misc/ueb9_bpserverd.rb
  modules/exploits/multi/misc/erlang_cookie_rce.rb
  modules/exploits/windows/local/ms16_014_wmi_recv_notif.rb
  modules/exploits/windows/misc/gh0st.rb
  modules/exploits/windows/misc/plugx.rb
Labels: easy

#12421 adjust for more limited require
  lib/msf/ui/console/command_dispatcher/creds.rb
Labels: msf5, rn-no-release-notes

#12404 to_s - Fix #12345
  lib/msf/base/sessions/command_shell.rb
Labels: bug, easy, newbie-friendly

#12426 Remove duplicate module in the wrong place
  modules/post/windows/manage/payload_inject.rb
Labels: module, potato

#12430 Add new Untitled Goose Game inspired logo
  data/logos/honk.txt
Labels: easy, feature, hotness

#12434 Fix misnamed BlueKeep exploit documentation
  documentation/modules/exploit/windows/rdp/cve_2019_0708_bluekeep_rce.md
Labels: bug, docs, easy

#12432 handle extra data on rdp_recv with length check
  lib/msf/core/exploit/rdp.rb
Labels: bug, library

#12401 Get rid of RSpec implicit block expectation syntax
  Gemfile
  Gemfile.lock
  spec/lib/msf/core/payload_generator_spec.rb
  spec/models/mdm/workspace_spec.rb
Labels: tests

#12435 Add documentation for wordpress_xmlrpc_login aux scanner
  documentation/modules/auxiliary/scanner/http/wordpress_xmlrpc_login.md
Labels: docs

#12436 Add documentation for auxiliary/scanner/http/wordpress_scanner
  documentation/modules/auxiliary/scanner/http/wordpress_scanner.md
Labels: docs

#12443 Fix Python reverse_http & reverse_https
  lib/msf/core/payload/python/reverse_http.rb
  modules/payloads/singles/python/meterpreter_reverse_http.rb
  modules/payloads/singles/python/meterpreter_reverse_https.rb
  modules/payloads/stagers/python/reverse_http.rb
  modules/payloads/stagers/python/reverse_https.rb
Labels: bug

#12444 Update CONTRIBUTING.md to clarify where questions shouldn't go
  CONTRIBUTING.md
Labels: bug, docs

#12418 Add documentation for auxiliary/scanner/redis/redis_server module
  documentation/modules/auxiliary/scanner/redis/redis_server.md
Labels: docs

#12366 fix nil check in atutor module
  modules/exploits/multi/http/atutor_sqli.rb
Labels: bug

#12416 tftpbrute docs
  documentation/modules/auxiliary/scanner/tftp/tftpbrute.md
Labels: docs, easy

#12455 Add generate_random_c method to randomized compiler
  lib/metasploit/framework/compiler/windows.rb
  tools/exploit/random_compile_c.rb
Labels: enhancement, library

#12454 Add documentation for auxiliary/scanner/redis/file_upload module
  documentation/modules/auxiliary/scanner/redis/file_upload.md
Labels: docs, easy

#12450 heartbleed docs
  documentation/modules/auxiliary/scanner/ssl/openssl_heartbleed.md
Labels: docs, easy

#12483 futex updates
  documentation/modules/exploit/android/local/futex_requeue.md
  modules/exploits/android/local/futex_requeue.rb
Labels: android, delayed, docs, enhancement

#12456 Add documentation for auxiliary/scanner/http/title module
  documentation/modules/auxiliary/scanner/http/title.md
Labels: docs

#12482 Fix the default meterpreter prompt
  lib/rex/ui/text/shell.rb
Labels: bug, library

#12467 Bug Fix: nops `generate` '-s' option ignored
  lib/msf/ui/console/command_dispatcher/nop.rb
Labels: bug, payload

#12491 Update .mailmap
  .mailmap
Labels: bug, enhancement

#12500 Use CheckCode.message - Fix #12499
  modules/auxiliary/scanner/http/elasticsearch_traversal.rb
  modules/post/multi/recon/local_exploit_suggester.rb
Labels: bug, module
