Repository rapid7/metasploit-framework, pull requests merged in 2020-02, with the labels that each got.

#12911 Revert "Fix style" in beetel_netconfig_ini_bof
  modules/exploits/windows/fileformat/beetel_netconfig_ini_bof.rb
Labels: bug, module, rn-no-release-notes

#12909 show search help when args and module_search_results are empty
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: enhancement

#12904 cleans up contributor guide
  CONTRIBUTING.md
Labels: docs, easy, rn-no-release-notes

#12894 Add Windscribe WindscribeService Named Pipe Privilege Escalation
  documentation/modules/exploit/windows/local/windscribe_windscribeservice_priv_esc.md
  modules/exploits/windows/local/windscribe_windscribeservice_priv_esc.rb
Labels: docs, module

#12917 chmod +x tools/dev/msftidy_docs.rb
  tools/dev/msftidy_docs.rb
Labels: bug, docs

#12927 Fix getsockname usage in the SOCKS5 server
  lib/rex/post/meterpreter/channels/socket_abstraction.rb
  lib/rex/proto/proxy/socks5/server_client.rb
Labels: bug, library

#12830 cleanup windows/gather/enum_patches
  modules/post/windows/gather/enum_patches.rb
Labels: enhancement, module

#12892 add default username to my/mssql login
  modules/auxiliary/scanner/mssql/mssql_login.rb
  modules/auxiliary/scanner/mysql/mysql_login.rb
Labels: bug

#12932 Add generate -v to optionally show payload stage
  lib/msf/base/simple/payload.rb
  lib/msf/ui/console/command_dispatcher/payload.rb
Labels: bug, enhancement, library, msfconsole

#12950 remove a scratchpad line I saved while testing blog link fixes
  modules/exploits/windows/browser/ie_cbutton_uaf.rb
Labels: docs, module, rn-no-release-notes

#12938 Add check for CPU vulnerability status to post/linux/gather/enum_system
  modules/post/linux/gather/enum_system.rb
Labels: easy, enhancement, module

#12958 Fix broken module documentation link
  lib/msf/util/document_generator/normalizer.rb
Labels: docs, easy

#12942 Add Diamorphine Rootkit Signal Privilege Escalation module
  documentation/modules/exploit/linux/local/diamorphine_rootkit_signal_priv_esc.md
  modules/exploits/linux/local/diamorphine_rootkit_signal_priv_esc.rb
Labels: docs, module

#12946 Allows `set PAYLOAD` parameters to begin with `/`, `payload/`, & `/payload/`
  lib/msf/ui/console/command_dispatcher/core.rb
Labels: easy, enhancement, library, msfconsole, rn-enhancement

#12961 Vendor the stdlib `expect` for Windows sockets
  LICENSE
  lib/expect.rb
Labels: bug, library

#12862 Add Apache James 2.3.2 Arbitrary File Write Exploit Module
  documentation/modules/exploit/linux/smtp/apache_james_exec.md
  modules/exploits/linux/smtp/apache_james_exec.rb
Labels: docs, module

#12966 Fix DisablePayloadHandler warning once and for all
  documentation/modules/exploit/windows/local/persistence_image_exec_options.md
  lib/msf/core/exploit/exe.rb
  lib/msf/ui/console/command_dispatcher/common.rb
Labels: bug, easy, library

#12945 fix #12579, fix the cmd/windows/reverse_powershell payload
  modules/payloads/singles/cmd/windows/reverse_powershell.rb
Labels: cmd_exec is broken again

#12921 Updating regex in ms16_075_reflection_juicy exploit windows version check
  documentation/modules/exploit/windows/local/ms16_075_reflection_juicy.md
  modules/exploits/windows/local/ms16_075_reflection_juicy.rb
Labels: bug, module

#12849 Add documentation for auxiliary/scanner/oracle/oracle_login
  documentation/modules/auxiliary/scanner/oracle/oracle_login.md
Labels: docs

#12002 Feature/reverse ssh
  lib/msf/base/sessions/ssh_command_shell.rb
  lib/msf/core/handler/reverse_ssh.rb
  lib/rex/proto/ssh.rb
  lib/rex/proto/ssh/connection.rb
  lib/rex/proto/ssh/hrr_rb_ssh.rb
  lib/rex/proto/ssh/server.rb
  metasploit-framework.gemspec
  modules/auxiliary/gather/external_ip.rb
  modules/payloads/singles/cmd/unix/bind_r.rb
  modules/payloads/singles/cmd/unix/reverse_bash_telnet_ssl.rb
  modules/payloads/singles/cmd/unix/reverse_perl_ssl.rb
  modules/payloads/singles/cmd/unix/reverse_php_ssl.rb
  modules/payloads/singles/cmd/unix/reverse_python_ssl.rb
  modules/payloads/singles/cmd/unix/reverse_r.rb
  modules/payloads/singles/cmd/unix/reverse_ruby_ssl.rb
  modules/payloads/singles/cmd/unix/reverse_ssh.rb
  modules/payloads/singles/cmd/unix/reverse_ssl_double_telnet.rb
  modules/payloads/singles/python/shell_reverse_tcp_ssl.rb
  modules/payloads/singles/r/shell_bind_tcp.rb
  modules/payloads/singles/r/shell_reverse_tcp.rb
  modules/payloads/singles/ruby/shell_reverse_tcp_ssl.rb
  modules/post/windows/manage/download_exec.rb
  modules/post/windows/manage/exec_powershell.rb
  modules/post/windows/manage/powershell/exec_powershell.rb
Labels: a2k19

#12968 Fix aux modules check command on mac
  lib/msf/core/auxiliary/scanner.rb
Labels: bug

#12955 Update logic for ForceExploit in my modules
  modules/auxiliary/admin/wemo/crockpot.rb
  modules/exploits/linux/http/hp_van_sdn_cmd_inject.rb
  modules/exploits/linux/http/webmin_backdoor.rb
  modules/exploits/linux/upnp/belkin_wemo_upnp_exec.rb
  modules/exploits/multi/http/jenkins_metaprogramming.rb
  modules/exploits/unix/webapp/drupal_drupalgeddon2.rb
  modules/exploits/unix/webapp/drupal_restws_unserialize.rb
Labels: bug, enhancement, module

#12972 Remove the --help-formats option
  external/zsh/_msfvenom
Labels: bug, easy, msfvenom

#12973 Update Gemfile.lock
  Gemfile.lock
Labels: bug

#12970 Revert "Land #12945, fix the cmd/windows/reverse_powershell payload"
  modules/payloads/singles/cmd/windows/reverse_powershell.rb
Labels: bug, payload

#12976 Add additional logging for unknown postgres authtypes
  lib/msf/core/exploit/postgres.rb
  lib/postgres/postgres-pr/connection.rb
  lib/postgres/postgres-pr/message.rb
Labels: enhancement, module

#12951 Update module doc template
  documentation/modules/module_doc_template.md
Labels: docs

#12914 Updating GPG keys needed for install binaries. Fixes #12913.
  Vagrantfile
Labels: msfconsole

#12465 Add CVE-2019-2215 Android Binder Use-After-Free module
  data/exploits/CVE-2019-2215/exploit
  external/source/exploits/CVE-2019-2215/Android.mk
  external/source/exploits/CVE-2019-2215/Makefile
  external/source/exploits/CVE-2019-2215/README.md
  external/source/exploits/CVE-2019-2215/poc.c
  modules/exploits/android/local/binder_uaf.rb
Labels: android, module, needs-docs

#12964 Adds RPC call for total modules running, ready, and with results
  lib/msf/core/rpc/v10/rpc_module.rb
Labels: enhancement

#12953 Fix json-rpc module.check calls
  lib/msf/base/simple/auxiliary.rb
  lib/msf/core/rpc/v10/rpc_module.rb
  spec/api/json_rpc_spec.rb
Labels: bug

#12916 Colorize HttpTrace output, add an option to show headers only, and refactor send_request_cgi
  lib/msf/core/exploit/http/client.rb
  lib/rex/proto/http/client_request.rb
  lib/rex/proto/http/packet.rb
Labels: enhancement, library

#12971 Begin module refactors to use new AutoCheck mixin
  lib/msf/core/exploit/auto_check.rb
  lib/msf/core/exploit/check_module.rb
Labels: bug, enhancement, module

#12419 New feature for rpc client - Delete credentials from a specific workspace
  lib/msf/core/rpc/v10/rpc_db.rb
Labels: database, enhancement, library

#12994 Remove executable flags from exploit files
  modules/exploits/linux/local/omniresolve_suid_priv_esc.rb
  modules/exploits/osx/browser/adobe_flash_delete_range_tl_op.rb
  modules/exploits/unix/webapp/wp_plainview_activity_monitor_rce.rb
  modules/exploits/windows/misc/ais_esel_server_rce.rb
Labels: code quality, rn-no-release-notes

#12952 Add additional pry dependencies
  Gemfile
  Gemfile.lock
Labels: enhancement

#12992 Fix for a simple typo.
  modules/auxiliary/dos/smb/smb_loris.rb
Labels: easy, enhancement, newbie-friendly

#12960 Ms 5061 add ttl job results
  lib/msf/base/simple/auxiliary.rb
  lib/msf/base/simple/exploit.rb
  lib/msf/base/simple/framework.rb
  lib/msf/base/simple/job_state_tracker.rb
  lib/msf/core/rpc/v10/rpc_base.rb
  lib/msf/core/rpc/v10/rpc_module.rb
  lib/msf/core/rpc/v10/service.rb
  spec/lib/msf/base/simple/framework_spec.rb
  spec/lib/msf/base/simple/job_state_tracker_spec.rb
Labels: enhancement

#12995 Pipe Auditor - add support to SMBv2
  lib/msf/core/exploit/smb/client/pipe_auditor.rb
  modules/auxiliary/scanner/smb/pipe_auditor.rb
Labels: enhancement, module

#12997 Fix msftidy warnings
  modules/exploits/linux/http/zenoss_showdaemonxmlconfig_exec.rb
  modules/exploits/windows/browser/teechart_pro.rb
  modules/exploits/windows/fileformat/vlc_modplug_s3m.rb
  modules/exploits/windows/http/novell_imanager_upload.rb
Labels: code quality, rn-no-release-notes

#12865 Add arguments support to reflective_dll_inject
  modules/post/windows/manage/reflective_dll_inject.rb
Labels: enhancement, module

#12907 update userlist to ubuntu 18.04 lamp & Others
  data/wordlists/unix_users.txt
Labels: easy, enhancement

#13001 Fix OpenSMTPD CVE-2020-7247 module and doc
  documentation/modules/exploit/unix/smtp/opensmtpd_mail_from_rce.md
  modules/exploits/unix/smtp/opensmtpd_mail_from_rce.rb
Labels: bug, docs, module, rn-no-release-notes

#13002 Reorder Expect mixin's send_expect parameters
  lib/msf/core/exploit/expect.rb
  modules/exploits/unix/smtp/opensmtpd_mail_from_rce.rb
Labels: bug, library, module, rn-no-release-notes

#13005 Integrate pry-byebug
  Gemfile
  Gemfile.lock
Labels: enhancement

#13006 Use AutoCheck mixin in OpenSMTPD CVE-2020-7247
  documentation/modules/exploit/unix/smtp/opensmtpd_mail_from_rce.md
  modules/exploits/unix/smtp/opensmtpd_mail_from_rce.rb
  modules/exploits/unix/webapp/wp_infinitewp_auth_bypass.rb
Labels: bug, docs, enhancement, module

#13000 add cmd/unix/reverse_ssh test stub
  spec/modules/payloads_spec.rb
Labels: easy, tests
