Repository rapid7/metasploit-framework, pull requests merged in 2020-09, with the labels that each got.

#14062 Add a SECURITY.md file
  SECURITY.md
Labels: docs, suggestion-docs

#13919 [GSoC] Ev2 - Easier actions interaction system for modules implemented
  lib/msf/ui/console/command_dispatcher/auxiliary.rb
Labels: enhancement, library

#14068 Update smb_enum_gpp to use RubySMB
  documentation/modules/auxiliary/scanner/smb/smb_enum_gpp.md
  lib/msf/core/exploit/smb/client.rb
  lib/rex/proto/smb/simpleclient.rb
  modules/auxiliary/scanner/smb/smb_enum_gpp.rb
Labels: enhancement, module

#14050 Fixing zip import errors
  lib/msf/core/db_manager/import/metasploit_framework/zip.rb
Labels: bug, library

#14081 Move SECURITY.md from root folder to the .github folder
  .github/SECURITY.md
Labels: code quality, docs

#14084 Add url reference to peplink_bauth_sqli
  modules/auxiliary/gather/peplink_bauth_sqli.rb
Labels: module, rn-no-release-notes

#14075 Add support for ZIP file generation in zip_slip exploit
  modules/exploits/multi/fileformat/zip_slip.rb
Labels: enhancement, module

#13978 Add proxy authentication support to the Python Meterpreter
  lib/msf/core/payload/python/meterpreter_loader.rb
  lib/msf/core/payload/python/reverse_http.rb
  modules/payloads/stages/python/meterpreter.rb
Labels: bug, meterpreter, payload

#14056 Set exempt labels
  .github/workflows/schedule-stale.yml
Labels: automation

#14090 Add example of `info 3` to the search results
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: docs, easy

#13836 Add Modbus banner grabbing module
  documentation/modules/auxiliary/scanner/scada/modbus_banner_grabbing.md
  modules/auxiliary/scanner/scada/modbus_banner_grabbing.rb
Labels: docs, module

#14112 Increase operations per run
  .github/workflows/schedule-stale.yml
Labels: enhancement, rn-no-release-notes

#14096 Fix a payload cache size generation issue and bump the gem
  Gemfile.lock
  lib/msf/util/payload_cached_size.rb
  metasploit-framework.gemspec
  modules/payloads/singles/php/meterpreter_reverse_tcp.rb
  modules/payloads/singles/python/meterpreter_bind_tcp.rb
  modules/payloads/singles/python/meterpreter_reverse_http.rb
  modules/payloads/singles/python/meterpreter_reverse_https.rb
  modules/payloads/singles/python/meterpreter_reverse_tcp.rb
Labels: bug, library

#14099 Fix user path on newer Windows
  modules/post/windows/gather/enum_powershell_env.rb
Labels: bug, easy, module

#12983 Dnsadmin ServerLevelPluginDLL Feature Abuse Privilege Escalation
  documentation/modules/exploit/windows/local/dnsadmin_serverlevelplugindll.md
  modules/exploits/windows/local/dnsadmin_serverlevelplugindll.rb
Labels: docs, module

#14111 Remove sizes hash and calculation of payload sizes on boot
  lib/msf/core/payload_set.rb
Labels: enhancement, rn-enhancement

#13942 Add module for CVE-2020-9934
  documentation/modules/post/osx/escalate/tccbypass.md
  modules/post/osx/escalate/tccbypass.rb
Labels: osx

#13571 add Session notified to DingTalk Bot
  plugins/session_notifier.rb
Labels: enhancement, plugin

#14138 Fix nexus_repo_manager_el_injection.md scenario
  documentation/modules/exploit/linux/http/nexus_repo_manager_el_injection.md
Labels: bug, docs, easy

#14125 Add warning for screen effect to tccbypass
  modules/post/osx/escalate/tccbypass.rb
Labels: bug, easy, osx

#14120 Group multi-column search conditions
  lib/msf/util/db_manager.rb
Labels: bug, database

#14074 Add Mida Solutions eFramework ajaxreq.php Command Injection
  documentation/modules/exploit/linux/http/mida_solutions_eframework_ajaxreq_rce.md
  modules/exploits/linux/http/mida_solutions_eframework_ajaxreq_rce.rb
Labels: docs, module

#14139 Add cookie management to HttpClient and improve standards compliance
  lib/msf/core/exploit/http/client.rb
  lib/rex/proto/http/client.rb
  lib/rex/proto/http/response.rb
Labels: code quality, enhancement, library

#14126 Add Microsoft Exchange Server DLP Policy RCE (CVE-2020-16875)
  documentation/modules/exploit/windows/http/exchange_ecp_dlp_policy.md
  modules/exploits/windows/http/exchange_ecp_dlp_policy.rb
Labels: feature, module

#14146 simple typo fix in comment (in the YARD)
  lib/msf/core/rpc/v10/rpc_session.rb
Labels: easy, library, rn-no-release-notes

#14145 Fix issue with web service when storing a file to the loot
  lib/metasploit/framework/data_service/proxy/loot_data_proxy.rb
Labels: bug, database

#14143 Replaces erroneous calls to get_service
  lib/metasploit/framework/data_service/remote/http/remote_service_data_service.rb
  lib/metasploit/framework/data_service/stubs/service_data_service.rb
  lib/msf/core/db_manager/exploit_attempt.rb
  lib/msf/core/db_manager/note.rb
  lib/msf/core/db_manager/service.rb
  lib/msf/core/exploit.rb
  lib/msf/core/exploit/http/client.rb
  lib/msf/core/web_services/servlet/service_servlet.rb
  lib/rex/parser/appscan_nokogiri.rb
  spec/support/shared/examples/msf/db_manager/service.rb
Labels: bug, database

#14117 Hyper-V VM Enumeration Module
  documentation/modules/post/windows/gather/enum_hyperv_vms.md
  modules/post/windows/gather/enum_hyperv_vms.rb
Labels: docs, module

#14135 Add module for TP-Link Cameras Command Injection (CVE-2020-12109)
  documentation/modules/exploit/linux/http/tp_link_ncxxx_bonjour_command_injection.md
  modules/exploits/linux/http/tp_link_ncxxx_bonjour_command_injection.rb
Labels: docs, module

#14123 Add VyOS restricted-shell Escape and Privilege Escalation
  documentation/modules/exploit/linux/ssh/vyos_restricted_shell_privesc.md
  modules/exploits/linux/ssh/vyos_restricted_shell_privesc.rb
Labels: docs, module

#14025 [Module] Artica Proxy Auth Bypass + RCE
  documentation/modules/exploit/linux/http/artica_proxy_auth_bypass_service_cmds_peform_command_injection.md
  modules/exploits/linux/http/artica_proxy_auth_bypass_service_cmds_peform_command_injection.rb
Labels: docs, module

#14122 Add exploit for CVE-2017-1000353
  data/exploits/CVE-2017-1000353/Payload.java
  documentation/modules/exploit/linux/http/jenkins_cli_deserialization.md
  modules/exploits/linux/http/jenkins_cli_deserialization.rb
Labels: docs, module

#14118 Origin/gather securecrt password
  documentation/modules/post/windows/gather/credentials/securecrt.md
  modules/post/windows/gather/credentials/securecrt.rb
Labels: docs, module

#14176 Show correct rank for show exploits command
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: bug, rn-fix

#14153 Always display `SRVHOST` and `SRVPORT` options when `CMDSTAGER::FLAVOR` is set to `auto`
  lib/msf/core/exploit/cmdstager.rb
Labels: bug

#14172 Add DisableExec Option to persistence_exe.rb
  modules/post/windows/manage/persistence_exe.rb
Labels: easy, enhancement, module

#14175 Add MaraCMS 7.5 Arbitrary File Upload Module and Docs (CVE-2020-25042)
  documentation/modules/exploit/multi/http/maracms_upload_exec.md
  modules/exploits/multi/http/maracms_upload_exec.rb
Labels: docs, module

#14161 initial vyos implementation
  documentation/modules/auxiliary/admin/networking/vyos_config.md
  documentation/modules/post/networking/gather/enum_vyos.md
  lib/msf/core/auxiliary/vyos.rb
  modules/auxiliary/admin/networking/vyos_config.rb
  modules/post/networking/gather/enum_vyos.rb
  spec/lib/msf/core/auxiliary/vyos_spec.rb
Labels: docs, module

#14178 Update Gemfile.local.example to Showcase the Path Option
  Gemfile.local.example
Labels: docs, easy

#14030 New GetSystem Technique: Named Pipe Impersonation (RPCSS Variant)
  Gemfile.lock
  lib/rex/post/meterpreter/extensions/priv/priv.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/priv/elevate.rb
  metasploit-framework.gemspec
Labels: feature, meterpreter

#14183 Attach msf-ws.log to debug -e & debug -l
  lib/msf/ui/debug.rb
  spec/file_fixtures/debug/error_logs/basic/msf-ws.log
  spec/file_fixtures/debug/error_logs/empty/msf-ws.log
  spec/file_fixtures/debug/error_logs/long/msf-ws.log
  spec/file_fixtures/debug/framework_logs/empty/msf-ws.log
  spec/file_fixtures/debug/framework_logs/equal/msf-ws.log
  spec/file_fixtures/debug/framework_logs/long/msf-ws.log
  spec/file_fixtures/debug/framework_logs/short/msf-ws.log
  spec/lib/msf/debug_spec.rb
Labels: enhancement

#14177 Reserve space for the encoder when generating payloads
  lib/msf/core/encoded_payload.rb
Labels: bug, library, payload

#14187 Added CVE-2020-3433 module
  documentation/modules/exploit/windows/local/anyconnect_lpe.md
  documentation/modules/exploit/windows/local/anyconnect_path_traversal_lpe.md
  modules/exploits/windows/local/anyconnect_lpe.rb
Labels: enhancement, module

#13995 Windows Secrets Dump module
  documentation/modules/auxiliary/gather/windows_secrets_dump.md
  lib/metasploit/framework/hashes/identify.rb
  lib/metasploit/framework/password_crackers/cracker.rb
  lib/metasploit/framework/password_crackers/hashcat/formatter.rb
  lib/msf/core/post/windows/priv.rb
  lib/msf/util/windows_registry_parser.rb
  modules/auxiliary/analyze/crack_windows.rb
  modules/auxiliary/gather/windows_secrets_dump.rb
  spec/lib/metasploit/framework/hashes/identify_spec.rb
  spec/lib/msf/core/post/windows/priv_spec.rb
Labels: feature, module

#14199 Fix gather securecrt password bug
  documentation/modules/post/windows/gather/credentials/securecrt.md
  modules/post/windows/gather/credentials/securecrt.rb
Labels: bug

#14200 Fix port parsing error when importing openvas
  lib/rex/parser/openvas_nokogiri.rb
Labels: bug, rn-fix

#14203 Fix report_note ActiveRecord::StatementInvalid PG::InvalidTextRepresentation exception
  lib/msf/core/db_manager/note.rb
Labels: bug, database, library
