Repository rapid7/metasploit-framework, pull requests merged in 2020-06, with the labels that each got.

#13512 Add vbulletin_getindexablecontent SQLi to RCE exploit and auxillary gather module
  documentation/modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.md
  documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md
  modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.rb
  modules/exploits/multi/http/vbulletin_getindexablecontent.rb
Labels: docs, module

#13553 PR to fix two modules for CVE-2020-12720 not properly handling vBulletin table prefixes
  modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.rb
  modules/exploits/multi/http/vbulletin_getindexablecontent.rb
Labels: bug, module

#13552 Add WebLogic exploit for CVE-2020-2883
  data/exploits/CVE-2020-2883/Weblogic_2883.java
  documentation/modules/exploit/multi/misc/weblogic_deserialize_badattr_extcomp.md
  modules/exploits/multi/misc/weblogic_deserialize_badattr_extcomp.rb
Labels: docs, module

#13540 Change OptString of RPORT to OptPort
  lib/msf/core/exploit/oracle.rb
  lib/msf/core/exploit/smb/client/psexec_ms17_010.rb
  modules/auxiliary/admin/aws/aws_launch_instances.rb
  modules/auxiliary/admin/smb/ms17_010_command.rb
  modules/auxiliary/admin/smb/psexec_command.rb
  modules/auxiliary/client/smtp/emailer.rb
  modules/auxiliary/scanner/smb/psexec_loggedin_users.rb
  modules/auxiliary/scanner/smb/smb_enum_gpp.rb
  modules/auxiliary/server/jsse_skiptls_mitm_proxy.rb
  modules/auxiliary/server/openssl_altchainsforgery_mitm_proxy.rb
  modules/auxiliary/vsploit/pii/email_pii.rb
  modules/post/multi/escalate/aws_create_iam_user.rb
Labels: enhancement, rn-no-release-notes

#13448 Fix following redirects from send_request_cgi!
  lib/msf/core/exploit/http/client.rb
Labels: bug

#13558 Restrict the ruby_smb gem version until v2.0 has been tested more
  Gemfile.lock
  metasploit-framework.gemspec
Labels: library, rubysmb

#13384 Add Cisco UCS Director auth bypass, directory traversal(s), and Cloupia script RCE (CVE-2020-3243 / ZDI-20-540)
  documentation/modules/exploit/linux/http/cisco_ucs_cloupia_script_rce.md
  modules/exploits/linux/http/cisco_ucs_cloupia_script_rce.rb
Labels: docs, feature, module

#13306 enum_xchat updates and upgrades
  documentation/modules/post/multi/gather/enum_hexchat.md
  modules/post/linux/gather/enum_xchat.rb
  modules/post/multi/gather/enum_hexchat.rb
Labels: docs, easy, enhancement

#13442 Fix winrm_login module
  lib/metasploit/framework/login_scanner/http.rb
  lib/metasploit/framework/login_scanner/winrm.rb
Labels: bug

#13572 Updates activerecord version check for deprecated_constants
  lib/pg/deprecated_constants.rb
Labels: bug, easy, rn-no-release-notes

#13562 iis_internal_ip docs and vprint_status
  documentation/modules/auxiliary/scanner/http/iis_internal_ip.md
  modules/auxiliary/scanner/http/iis_internal_ip.rb
Labels: docs, enhancement

#13468 Fix memcached extractor issue 12884
  modules/auxiliary/gather/memcached_extractor.rb
Labels: bug

#13579 more iis internal ip info
  modules/auxiliary/scanner/http/iis_internal_ip.rb
Labels: easy

#13566 Show automatically selected payload in module options and refactor default payload selection
  lib/msf/core/evasion.rb
  lib/msf/ui/console/command_dispatcher/evasion.rb
  lib/msf/ui/console/command_dispatcher/exploit.rb
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: enhancement, library, msf5, msfconsole

#13576 Deprecate the psexec_psh module
  lib/msf/core/module/deprecated.rb
  modules/exploits/windows/smb/psexec_psh.rb
Labels: module

#13583 Require msf/core/post/windows/filesystem in lib/msf/core/post/windows.rb
  lib/msf/core/post/windows.rb
Labels: bug, easy, library, mixin madness

#13537 Add new module linuxki_rce - CVE-2020-7209
  documentation/modules/exploit/linux/http/linuxki_rce.md
  modules/exploits/linux/http/linuxki_rce.rb
Labels: docs, module

#13374 Fix Events rest api Encoding
  documentation/modules/payload/windows/meterpreter/reverse_tcp.md
  lib/msf/core/framework.rb
  lib/msf/util/document_generator.rb
  modules/exploits/linux/http/nagios_xi_magpie_debug.rb
Labels: bug, confirmed, rn-no-release-notes

#13599 rollback yanked gem
  Gemfile.lock
Labels: rn-no-release-notes

#13444 GOG Galaxy Client Privilege Escalation Module
  documentation/modules/exploit/windows/local/gog_galaxyclientservice_privesc.md
  modules/exploits/windows/local/gog_galaxyclientservice_privesc.rb
Labels: docs, module

#13303 Add CVE-2020-9015 Arista TACACS+ SSH Shell Escape
  documentation/modules/exploit/unix/ssh/arista_tacplus_shell.md
  modules/exploits/unix/ssh/arista_tacplus_shell.rb
Labels: docs, module

#13170 Added exploit for CVE-2017-17106
  documentation/modules/exploit/unix/http/zivif_ipcheck_exec.rb
  modules/exploits/unix/http/zivif_ipcheck_exec.rb
Labels: docs, module, rn-modules

#13432 Add TLV encryption support to Python Meterpreter
  lib/msf/core/payload/python.rb
  lib/msf/core/payload/python/bind_tcp.rb
  lib/msf/core/payload/python/meterpreter_loader.rb
  lib/msf/core/payload/python/reverse_http.rb
  lib/msf/core/payload/python/reverse_tcp.rb
  lib/msf/core/payload/python/reverse_tcp_ssl.rb
Labels: enhancement, library, meterpreter, msf6

#13628 postgres_payload: fix deadlink
  modules/exploits/windows/postgres/postgres_payload.rb
Labels: easy

#13529 Remove the old Mimikatz extension
  documentation/modules/payload/windows/meterpreter/reverse_tcp.md
  lib/rex/post/meterpreter/extensions/kiwi/kiwi.rb
  lib/rex/post/meterpreter/extensions/mimikatz/mimikatz.rb
  lib/rex/post/meterpreter/extensions/mimikatz/tlv.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/kiwi.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/mimikatz.rb
  modules/post/windows/gather/credentials/sso.rb
Labels: library, meterpreter, msf6

#13727 fix author in pihole module
  modules/exploits/unix/http/pihole_dhcp_mac_exec.rb
Labels: easy

#13734 check shodan API key
  modules/auxiliary/gather/shodan_honeyscore.rb
  modules/auxiliary/gather/shodan_search.rb
Labels: enhancement

#13607 Cayin xPost and CMS exploits
  documentation/modules/exploit/linux/http/cayin_cms_ntp.md
  documentation/modules/exploit/windows/http/cayin_xpost_sql_rce.md
  modules/exploits/linux/http/cayin_cms_ntp.rb
  modules/exploits/windows/http/cayin_xpost_sql_rce.rb
Labels: docs, module

#13605 Base64 enc payload to bypass escaping quotes etc.
  modules/exploits/multi/http/ibm_openadmin_tool_soap_welcomeserver_exec.rb
Labels: bug

#12277 add. exploit module for agent tesla panel rce
  documentation/modules/exploit/multi/http/agent_tesla_panel_rce.md
  modules/exploits/multi/http/agent_tesla_panel_rce.rb
Labels: docs, module

#13721 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_suggestion.md
  .github/ISSUE_TEMPLATE/module_suggestion.md
  .github/ISSUE_TEMPLATE/question.md
Labels: feature, rn-no-release-notes

#13600 Check that ctx[1] has a datastore attribute
  lib/msf/ui/console/command_dispatcher/jobs.rb
Labels: bug

#13645 Add Trend Micro WebSecurity Remote Code Execution
  documentation/modules/exploit/linux/http/trendmicro_websecurity_exec.md
  modules/exploits/linux/http/trendmicro_websecurity_exec.rb
Labels: docs, module

#13748 off to false
  modules/auxiliary/scanner/ssh/ssh_login.rb
  modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb
Labels: easy, rn-no-release-notes

#13726 Update PR Template to request Demos for difficult to test Modules
  .github/PULL_REQUEST_TEMPLATE.md
Labels: docs, easy

#13757 Add consistent error logging for module loading and handle nil backtraces
  lib/msf/core/modules/loader/base.rb
  lib/rex/logging/log_dispatcher.rb
Labels: bug

#13755 Exclude multi from automatic PAYLOAD selection
  lib/msf/core/evasion.rb
  lib/msf/core/exploit.rb
  lib/msf/ui/console/command_dispatcher/exploit.rb
  lib/msf/ui/console/command_dispatcher/modules.rb
  modules/exploits/multi/handler.rb
Labels: bug, enhancement, library, msf5

#13417 SMBv3 integration with Framework
  lib/msf/core/exploit/smb/client.rb
  lib/msf/core/exploit/smb/client/psexec.rb
  lib/msf/core/exploit/smb/client/psexec_ms17_010.rb
  lib/msf/core/handler/bind_named_pipe.rb
  lib/rex/proto/dcerpc/client.rb
  lib/rex/proto/smb/simpleclient.rb
  lib/rex/proto/smb/simpleclient/open_file.rb
  lib/rex/proto/smb/simpleclient/open_pipe.rb
  metasploit-framework.gemspec
  modules/auxiliary/admin/db2/db2rcmd.rb
  modules/auxiliary/admin/smb/check_dir_file.rb
  modules/auxiliary/admin/smb/delete_file.rb
  modules/auxiliary/admin/smb/download_file.rb
  modules/auxiliary/admin/smb/list_directory.rb
  modules/auxiliary/admin/smb/ms17_010_command.rb
  modules/auxiliary/admin/smb/samba_symlink_traversal.rb
  modules/auxiliary/admin/smb/upload_file.rb
  modules/auxiliary/dos/samba/read_nttrans_ea_list.rb
  modules/auxiliary/dos/windows/smb/ms06_035_mailslot.rb
  modules/auxiliary/dos/windows/smb/ms06_063_trans.rb
  modules/auxiliary/dos/windows/smb/ms09_001_write.rb
  modules/auxiliary/dos/windows/smb/ms10_054_queryfs_pool_overflow.rb
  modules/auxiliary/fuzzers/smb/smb_create_pipe_corrupt.rb
  modules/auxiliary/fuzzers/smb/smb_ntlm1_login_corrupt.rb
  modules/auxiliary/fuzzers/smb/smb_tree_connect_corrupt.rb
  modules/auxiliary/gather/windows_deployment_services_shares.rb
  modules/auxiliary/scanner/smb/pipe_auditor.rb
  modules/auxiliary/scanner/smb/smb_enum_gpp.rb
  modules/auxiliary/scanner/smb/smb_enumshares.rb
  modules/auxiliary/scanner/smb/smb_ms17_010.rb
  modules/auxiliary/scanner/smb/smb_version.rb
  modules/auxiliary/server/http_ntlmrelay.rb
  modules/exploits/freebsd/samba/trans2open.rb
  modules/exploits/linux/samba/chain_reply.rb
  modules/exploits/linux/samba/is_known_pipename.rb
  modules/exploits/linux/samba/lsa_transnames_heap.rb
  modules/exploits/linux/samba/setinfopolicy_heap.rb
  modules/exploits/linux/samba/trans2open.rb
  modules/exploits/multi/samba/nttrans.rb
  modules/exploits/multi/samba/usermap_script.rb
  modules/exploits/osx/samba/trans2open.rb
  modules/exploits/solaris/samba/trans2open.rb
  modules/exploits/windows/smb/ipass_pipe_exec.rb
  modules/exploits/windows/smb/ms04_007_killbill.rb
  modules/exploits/windows/smb/ms04_011_lsass.rb
  modules/exploits/windows/smb/ms06_025_rras.rb
  modules/exploits/windows/smb/ms06_040_netapi.rb
  modules/exploits/windows/smb/ms06_070_wkssvc.rb
  modules/exploits/windows/smb/ms07_029_msdns_zonename.rb
  modules/exploits/windows/smb/ms08_067_netapi.rb
  modules/exploits/windows/smb/ms10_061_spoolss.rb
  modules/exploits/windows/smb/ms17_010_eternalblue.rb
  modules/exploits/windows/smb/ms17_010_psexec.rb
  modules/exploits/windows/smb/netidentity_xtierrpcpipe.rb
  modules/exploits/windows/smb/psexec.rb
  modules/exploits/windows/smb/psexec_psh.rb
  modules/exploits/windows/smb/smb_doublepulsar_rce.rb
  modules/exploits/windows/smb/timbuktu_plughntcommand_bof.rb
  modules/exploits/windows/smb/webexec.rb
Labels: enhancement, msf6, rubysmb

#13739 Add Cisco AnyConnect Priv Esc through Path Traversal module
  documentation/modules/exploit/windows/local/anyconnect_path_traversal_lpe.md
  modules/exploits/windows/local/anyconnect_path_traversal_lpe.rb
Labels: docs, module

#13601 Add custom service name support to msfvenom's exe-service generator
  external/zsh/_msfvenom
  lib/msf/core/payload_generator.rb
  lib/msf/util/exe.rb
  msfvenom
Labels: enhancement, library, msfvenom

#13780 Remove debug print from lib/msf/core/session/interactive.rb
  lib/msf/core/session/interactive.rb
Labels: code quality, easy, library

#13521 Add module and docs for Bolt CMS 3.6.*-3.7.0 authenticated RCE (cmdstager WIP)
  documentation/modules/exploit/unix/webapp/bolt_authenticated_rce.md
  modules/exploits/unix/webapp/bolt_authenticated_rce.rb
Labels: feature, module

#13430 Command that can be used to generate information useful when debugging user errors
  lib/msf/ui.rb
  lib/msf/ui/console/command_dispatcher/core.rb
  lib/msf/ui/console/driver.rb
  lib/msf/ui/debug.rb
  lib/rex/ui/text/shell.rb
  spec/file_fixtures/debug/config_files/db.ini
  spec/file_fixtures/debug/config_files/empty.ini
  spec/file_fixtures/debug/error_logs/basic/framework.log
  spec/file_fixtures/debug/error_logs/empty/framework.log
  spec/file_fixtures/debug/error_logs/long/framework.log
  spec/file_fixtures/debug/framework_logs/empty/framework.log
  spec/file_fixtures/debug/framework_logs/equal/framework.log
  spec/file_fixtures/debug/framework_logs/long/framework.log
  spec/file_fixtures/debug/framework_logs/short/framework.log
  spec/file_fixtures/debug/installs/omnibus/version.yml
  spec/lib/msf/debug_spec.rb
Labels: enhancement, feature

#13725 Fix atutor_filemanager_traversal.rb credentials checks and clean up code
  modules/exploits/linux/http/atutor_filemanager_traversal.rb
Labels: enhancement, module
