Repository rapid7/metasploit-framework, pull requests merged in 2020-07, with the labels that each got.

#13793 Fix typo in debug command
  lib/msf/ui/debug.rb
  spec/file_fixtures/debug/config_files/module.ini
  spec/lib/msf/debug_spec.rb
Labels: bug, rn-no-release-notes

#13764 Update SMB Version Scanning
  documentation/modules/auxiliary/scanner/smb/smb_version.md
  lib/msf/core/module/deprecated.rb
  modules/auxiliary/scanner/smb/smb1.rb
  modules/auxiliary/scanner/smb/smb2.rb
  modules/auxiliary/scanner/smb/smb_version.rb
  modules/exploits/windows/smb/psexec_psh.rb
Labels: enhancement, module, msf6

#13795 Add note about using a module after searching
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: enhancement

#13787 Update AutoCheck to use prepend instead of include, add ForceExploit option
  lib/msf/core/exploit/auto_check.rb
  modules/exploits/linux/http/cisco_ucs_cloupia_script_rce.rb
  modules/exploits/linux/http/netsweeper_webadmin_unixlogin.rb
  modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
  modules/exploits/linux/local/diamorphine_rootkit_signal_priv_esc.rb
  modules/exploits/multi/http/agent_tesla_panel_rce.rb
  modules/exploits/multi/http/atutor_upload_traversal.rb
  modules/exploits/multi/http/liferay_java_unmarshalling.rb
  modules/exploits/multi/http/vbulletin_getindexablecontent.rb
  modules/exploits/multi/misc/weblogic_deserialize_badattr_extcomp.rb
  modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
  modules/exploits/unix/local/opensmtpd_oob_read_lpe.rb
  modules/exploits/unix/smtp/opensmtpd_mail_from_rce.rb
  modules/exploits/unix/webapp/bolt_authenticated_rce.rb
  modules/exploits/unix/webapp/thinkphp_rce.rb
  modules/exploits/unix/webapp/wp_infinitewp_auth_bypass.rb
  modules/exploits/windows/http/desktopcentral_deserialization.rb
  modules/exploits/windows/http/plesk_mylittleadmin_viewstate.rb
  modules/exploits/windows/http/sharepoint_workflows_xoml.rb
  modules/exploits/windows/http/tomcat_cgi_cmdlineargs.rb
  modules/exploits/windows/local/cve_2020_0787_bits_arbitrary_file_move.rb
  modules/exploits/windows/local/cve_2020_0796_smbghost.rb
  modules/exploits/windows/local/ntusermndragover.rb
  spec/lib/msf/core/exploit/remote/auto_check.rb
Labels: enhancement

#13733 Add an exploit for CVE-2020-13160 (RCE in AnyDesk GUI)
  documentation/modules/exploit/linux/misc/cve_2020_13160_anydesk.md
  modules/exploits/linux/misc/cve_2020_13160_anydesk.rb
Labels: docs, module

#13768 Netgear r6700 lan rce
  documentation/modules/auxiliary/admin/http/netgear_r6700_pass_reset.md
  modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
Labels: docs, module

#13801 Point to paylodas v2.0.8
  Gemfile.lock
  metasploit-framework.gemspec
Labels: msf6, payload

#13789 Add openSIS Unauthenticated PHP Code Execution
  documentation/modules/exploit/unix/webapp/opensis_chain_exec.md
  modules/exploits/unix/webapp/opensis_chain_exec.rb
Labels: docs, module

#13806 Make cmd/unix target types consistent to :unix_cmd
  modules/exploits/linux/http/cisco_ucs_cloupia_script_rce.rb
  modules/exploits/linux/http/citrix_dir_traversal_rce.rb
  modules/exploits/linux/misc/saltstack_salt_unauth_rce.rb
Labels: code quality, easy, module, rn-no-release-notes

#13820 Remove rspec test focus, and ensure all tests run
  spec/lib/msf/core/modules/loader/base_spec.rb
  spec/rubocop/cop/layout/module_description_indentation_spec.rb
  spec/spec_helper.rb
  spec/support/shared/examples/msf/db_manager/migration.rb
Labels: bug

#13807 Add F5 BIG-IP TMUI Directory Traversal and File Upload RCE (CVE-2020-5902)
  documentation/modules/exploit/linux/http/f5_bigip_tmui_rce.md
  modules/exploits/linux/http/f5_bigip_tmui_rce.rb
Labels: feature, module

#13829 Credit Mikhail Klyuchnikov for CVE-2019-19781
  modules/auxiliary/scanner/http/citrix_dir_traversal.rb
  modules/exploits/linux/http/citrix_dir_traversal_rce.rb
Labels: bug, easy, module, rn-no-release-notes

#13783 Support AES-128-CBC as an additional option for TLV encryption
  Gemfile.lock
  lib/msf/base/serializer/readable_text.rb
  lib/rex/post/meterpreter/packet.rb
  metasploit-framework.gemspec
Labels: bug, meterpreter, msf6

#13832 Polymorphic x86/x64 Block API
  data/shellcode/block_api.x64.graphml
  data/shellcode/block_api.x86.graphml
  external/source/shellcode/windows/x64/src/block/block_api.asm
  external/source/shellcode/windows/x86/src/block/block_api.asm
  lib/msf/core/payload/windows/block_api.rb
  lib/msf/core/payload/windows/x64/block_api.rb
  lib/msf/util/exe.rb
  lib/rex/parser/graphml.rb
  lib/rex/payloads/shuffle.rb
  modules/payloads/singles/windows/pingback_bind_tcp.rb
  modules/payloads/singles/windows/pingback_reverse_tcp.rb
  modules/payloads/stagers/windows/bind_ipv6_tcp.rb
  modules/payloads/stagers/windows/bind_ipv6_tcp_uuid.rb
  modules/payloads/stagers/windows/bind_named_pipe.rb
  modules/payloads/stagers/windows/bind_tcp.rb
  modules/payloads/stagers/windows/bind_tcp_rc4.rb
  modules/payloads/stagers/windows/bind_tcp_uuid.rb
  modules/payloads/stagers/windows/reverse_http.rb
  modules/payloads/stagers/windows/reverse_https.rb
  modules/payloads/stagers/windows/reverse_named_pipe.rb
  modules/payloads/stagers/windows/reverse_tcp.rb
  modules/payloads/stagers/windows/reverse_tcp_dns.rb
  modules/payloads/stagers/windows/reverse_tcp_rc4.rb
  modules/payloads/stagers/windows/reverse_tcp_rc4_dns.rb
  modules/payloads/stagers/windows/reverse_tcp_uuid.rb
  modules/payloads/stagers/windows/reverse_udp.rb
  modules/payloads/stagers/windows/reverse_winhttp.rb
  modules/payloads/stagers/windows/reverse_winhttps.rb
Labels: enhancement, library, msf6, payload

#13812 Add a command target to the main PSexec module
  documentation/modules/exploit/windows/smb/psexec.md
  lib/msf/core/exploit/smb/client/psexec.rb
  modules/auxiliary/admin/smb/ms17_010_command.rb
  modules/auxiliary/admin/smb/psexec_command.rb
  modules/exploits/windows/smb/psexec.rb
Labels: enhancement, module, msf6

#13626 post/windows/gather/checkvm: cleanup, increase efficiency, fix style
  modules/post/windows/gather/checkvm.rb
Labels: enhancement, module

#13596 [GSoC] SQLi library with support to MySQL (and MariaDB)
  lib/msf/core/exploit/mixins.rb
  lib/msf/core/exploit/sqli.rb
  lib/msf/core/exploit/sqli/common.rb
  lib/msf/core/exploit/sqli/mysqli.rb
  lib/msf/core/exploit/sqli/mysqli/boolean_based_blind.rb
  lib/msf/core/exploit/sqli/mysqli/common.rb
  lib/msf/core/exploit/sqli/mysqli/time_based_blind.rb
  modules/auxiliary/sqli/openemr/openemr_sqli_dump.rb
  modules/exploits/linux/http/eyesofnetwork_autodiscovery_rce.rb
Labels: feature

#13730 Add Pandora FMS Events Remote Code Execution (CVE-2020-13851) module and docs
  documentation/modules/exploit/linux/http/pandora_fms_events_exec.md
  modules/exploits/linux/http/pandora_fms_events_exec.rb
Labels: docs, module

#13271 aux/server/capture/smtp now captures auth!
  documentation/modules/auxiliary/server/capture/smtp.md
  lib/metasploit/framework/hashes/identify.rb
  lib/metasploit/framework/password_crackers/cracker.rb
  lib/metasploit/framework/password_crackers/hashcat/formatter.rb
  modules/auxiliary/server/capture/smtp.rb
  spec/lib/metasploit/framework/hashes/identify_spec.rb
Labels: docs, enhancement, library, rn-enhancement

#13841 Add Msf::Post::Unix.is_root? method
  lib/msf/core/post/unix.rb
  modules/exploits/freebsd/local/intel_sysret_priv_esc.rb
  modules/exploits/freebsd/local/rtld_execl_priv_esc.rb
  modules/exploits/openbsd/local/dynamic_loader_chpass_privesc.rb
Labels: easy, library

#13759 Add optional baseline for http response time in scanner/http/owa_login
  modules/auxiliary/scanner/http/owa_login.rb
Labels: enhancement

#13848 Cdata backdoor wordlist
  data/wordlists/telnet_cdata_ftth_backdoor_userpass.txt
Labels: easy, enhancement

#13830 Add QEMU/KVM target for CVE-2019-0708
  modules/exploits/windows/rdp/cve_2019_0708_bluekeep_rce.rb
Labels: enhancement, module

#13872 Add needs issue template bot responses
  .github/label-actions.yml
Labels: automation, rn-no-release-notes

#13874 Fix false positive with shodan search module
  modules/auxiliary/gather/shodan_search.rb
Labels: bug

#13873 check if a module has a check method first
  lib/msf/base/simple/auxiliary.rb
  lib/msf/base/simple/exploit.rb
  lib/msf/core/rpc/json/dispatcher.rb
Labels: enhancement, library

#13859 Remove fail_with from check method
  modules/exploits/linux/local/exim4_deliver_message_priv_esc.rb
Labels: bug, easy

#13822 Update rubocop version
  Gemfile
  Gemfile.lock
  lib/rubocop/cop/layout/module_description_indentation.rb
  lib/rubocop/cop/layout/module_hash_on_new_line.rb
  spec/spec_helper.rb
Labels: rn-no-release-notes, ruby-compat

#13868 Added Dump hashes to auxiliary/gather/vmware_vcenter_vmdir_ldap
  documentation/modules/auxiliary/admin/ldap/vmware_vcenter_vmdir_auth_bypass.md
  documentation/modules/auxiliary/gather/vmware_vcenter_vmdir_ldap.md
  lib/metasploit/framework/hashes/identify.rb
  lib/metasploit/framework/password_crackers/cracker.rb
  lib/metasploit/framework/password_crackers/hashcat/formatter.rb
  lib/metasploit/framework/password_crackers/jtr/formatter.rb
  modules/auxiliary/admin/ldap/vmware_vcenter_vmdir_auth_bypass.rb
  modules/auxiliary/gather/vmware_vcenter_vmdir_ldap.rb
Labels: docs, enhancement, module

#13853 Use Msf::Exploit::Remote::AutoCheck and Msf::Post::Linux::Compile
  modules/exploits/linux/local/bpf_sign_extension_priv_esc.rb
Labels: enhancement, module

#13885 Add LDAPS support and update VMware vCenter Server vmdir (CVE-2020-3952) modules
  documentation/modules/auxiliary/admin/ldap/vmware_vcenter_vmdir_auth_bypass.md
  documentation/modules/auxiliary/gather/vmware_vcenter_vmdir_ldap.md
  lib/msf/core/exploit/ldap.rb
  modules/auxiliary/admin/ldap/vmware_vcenter_vmdir_auth_bypass.rb
  modules/auxiliary/gather/vmware_vcenter_vmdir_ldap.rb
Labels: docs, enhancement, library, module

#13886 Fixed shell script creation with passwords with special characters
  modules/post/multi/manage/sudo.rb
Labels: bug, module

#13884 Remove Msf::Post::Linux::Priv.download_cmd method
  lib/msf/core/post/linux/priv.rb
Labels: bug, easy

#13883 hwbridge: fix syntax error introduced in aeed81de291260c12934d3afe1425a3852875a01
  lib/rex/post/hwbridge/ui/console/command_dispatcher/custom_methods.rb
Labels: bug

#13852 Module for SAP "RECON" CVE-2020-6287 that adds an admin user
  documentation/modules/auxiliary/admin/sap/cve_2020_6287_ws_add_user.md
  modules/auxiliary/admin/sap/cve_2020_6287_ws_add_user.rb
Labels: feature, hotness, module

#13861 Use AutoCheck mixin and prefer cc over gcc
  modules/exploits/freebsd/local/intel_sysret_priv_esc.rb
Labels: module

#13898 fix #13779, fix error on invalid geolocation api key
  lib/rex/google/geolocation.rb
Labels: bug, rn-fix

#13899 Clean up the temperary script with the clear text password in it from sudo module
  modules/post/multi/manage/sudo.rb
Labels: bug

#13895 Improvements for SAP "RECON" CVE-2020-6287 auxiliary module
  documentation/modules/auxiliary/admin/sap/cve_2020_6287_ws_add_user.md
  modules/auxiliary/admin/sap/cve_2020_6287_ws_add_user.rb
Labels: enhancement, module

#13914 move config_changes on plex module
  modules/exploits/windows/http/plex_unpickle_dict_rce.rb
Labels: easy, module

#13896 Add checks to msftidy_docs and update the template for them
  data/markdown_doc/default_template.erb
  documentation/modules/module_doc_template.md
  lib/msf/core/constants.rb
  lib/msf/util/document_generator.rb
  lib/msf/util/document_generator/normalizer.rb
  spec/lib/msf/util/document_generator/normalizer_spec.rb
  tools/dev/msftidy_docs.rb
Labels: code quality, docs, msftidy

#13837 Add FreeBSD ip6_setpktopt Use-After-Free Privilege Escalation module
  data/exploits/CVE-2020-7457/exploit.c
  documentation/modules/exploit/freebsd/local/ip6_setpktopt_uaf_priv_esc.md
  modules/exploits/freebsd/local/ip6_setpktopt_uaf_priv_esc.rb
Labels: docs, module

#13920 Add the exploit for CVE-2020-1147
  documentation/modules/exploit/windows/http/sharepoint_data_deserialization.md
  modules/exploits/windows/http/sharepoint_data_deserialization.rb
Labels: docs, module

#13921 make default prompt always display running major #
  lib/msf/ui/console/driver.rb
Labels: easy, library

#13900 Add Packet::Header#include? to check for the presence of headers in a case-insensitive manner
  lib/rex/proto/http/packet/header.rb
Labels: bug, library

#13922 Add an optional delay when executing PSExec commands
  modules/exploits/windows/smb/psexec.rb
Labels: enhancement, module, msf6
