Repository rapid7/metasploit-framework, pull requests merged in 2020-04, with the labels that each got.

#13148 Reduce Unknown commands handling from 1 second to 0.5 seconds
  lib/msf/core/payload/android.rb
Labels: easy, enhancement

#13164 Add documentation for http_hsts.md
  documentation/modules/auxiliary/scanner/http/http_hsts.md
Labels: docs

#13155 Enable CPU & Memory profilers to work with Individual Code Blocks
  lib/metasploit/framework/profiler.rb
Labels: enhancement

#12096 Add DNN Cookie Deserialization RCE Exploit
  documentation/modules/exploit/windows/http/dnn_cookie_deserialization_rce.md
  modules/exploits/windows/http/dnn_cookie_deserialization_rce.rb
Labels: delayed, docs, module, needs-testing

#12759 Apache Solr Remote Code Execution via Velocity Template
  documentation/modules/exploit/multi/http/solr_velocity_rce.md
  modules/exploits/multi/http/solr_velocity_rce.rb
Labels: docs, module

#13123 VMWare Fusion OSX priv esc CVE-2020-3950
  documentation/modules/exploit/osx/local/vmware_fusion_lpe.md
  modules/exploits/osx/local/vmware_fusion_lpe.rb
Labels: docs, module, osx

#13184 Correct version in vmware_fusion_lpe module doc
  documentation/modules/exploit/osx/local/vmware_fusion_lpe.md
Labels: bug, docs

#13067 Playsms pre auth rce
  documentation/modules/exploit/unix/webapp/playsms_pre_auth_rce.md
  modules/exploits/unix/webapp/playsms_pre_auth_rce.rb
Labels: docs, module

#13188 new tidy_docs checks
  tools/dev/msftidy_docs.rb
Labels: easy, enhancement

#13211 Add my own GitHub handle and work email to .mailmap
  .mailmap
Labels: easy, enhancement

#13212 grab bag of meterpreter bug fixes
  Gemfile.lock
  metasploit-framework.gemspec
Labels: bug, payload

#13179 fix unmarshal docs
  documentation/modules/post/windows/escalate/unmarshal_cmd_exec.md
Labels: docs, easy

#13220 Fix broken ubiquiti spec
  lib/msf/core/auxiliary/ubiquiti.rb
Labels: bug

#13216 Add automated comments to no docs label with github app
  .github/label-actions.yml
  .github/label-commenter-config.yml
  .github/workflows/label-commenter.yml
Labels: automation, docs, enhancement, rn-no-release-notes

#13205 ms-5185 Add validation for rpc module selection
  lib/msf/core/rpc/v10/rpc_module.rb
Labels: enhancement

#13240 Add ThinkPHP Multiple PHP Injection RCEs
  documentation/modules/exploit/unix/webapp/thinkphp_rce.md
  modules/exploits/unix/webapp/thinkphp_rce.rb
Labels: feature, module

#13242 Explain CVEs and "fix" CMDSTAGER::FLAVOR in ThinkPHP exploit
  modules/exploits/unix/webapp/thinkphp_rce.rb
Labels: bug, module

#13094 Adding Vesta Control Panel Remote Code Execution 0day
  documentation/modules/exploit/linux/http/vestacp_exec.md
  modules/exploits/linux/http/vestacp_exec.rb
Labels: docs, easy, module

#13140 Adds payload completion and fixes format completion
  external/zsh/_msfvenom
Labels: enhancement, msfvenom

#13215 limesurvey dir traversals
  documentation/modules/auxiliary/scanner/http/limesurvey_zip_traversals.md
  modules/auxiliary/scanner/http/limesurvey_zip_traversals.rb
Labels: docs, module

#13249 Cleanup and Description fixes for VestaCP Exploit
  modules/exploits/linux/http/vestacp_exec.rb
Labels: enhancement, module

#13213 Add Liferay Portal Java Unmarshalling RCE (CVE-2020-7961) and remote classloading mixin
  documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
  lib/msf/core/exploit/java.rb
  lib/msf/core/exploit/java/http/classloader.rb
  modules/exploits/multi/http/liferay_java_unmarshalling.rb
Labels: feature, module

#13223 Add additional automated label actions
  .github/label-actions.yml
Labels: automation, delayed, rn-no-release-notes, usability

#13250 YAML warnings are very unnecessary, they can only do harm
  lib/msf/ui/console/driver.rb
Labels: database, enhancement

#13208 Archer a7 c7 lan
  documentation/modules/exploit/linux/misc/tplink_archer_a7_c7_lan_rce.md
  modules/exploits/linux/misc/tplink_archer_a7_c7_lan_rce.rb
Labels: docs, module

#13256 bump ruby versions
  .ruby-version
  .travis.yml
  Dockerfile
Labels: ruby-compat

#13195 Add Nexus Repository Manager Java EL Injection RCE (CVE-2020-10199)
  documentation/modules/exploit/linux/http/nexus_repo_manager_el_injection.md
  modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
Labels: docs, feature, module

#13193 Updates to Trusted Service Path (now Unquoted Service path)
  documentation/modules/exploit/windows/local/unquoted_service_path.md
  modules/exploits/windows/local/trusted_service_path.rb
  modules/exploits/windows/local/unquoted_service_path.rb
Labels: docs, enhancement

#13266 Fix CVE-2020-7350 (command execution in libnotify)
  plugins/libnotify.rb
Labels: bug, plugin

#13268 Add additional productivity tips
  lib/msf/ui/tip.rb
Labels: msfconsole, usability

#13259 Backport fixes to various modules committed between Nexus and Liferay PRs
  documentation/modules/exploit/bsd/finger/morris_fingerd_bof.md
  documentation/modules/exploit/linux/http/nexus_repo_manager_el_injection.md
  documentation/modules/exploit/unix/local/emacs_movemail.md
  documentation/modules/exploit/unix/local/opensmtpd_oob_read_lpe.md
  documentation/modules/exploit/unix/smtp/morris_sendmail_debug.md
  documentation/modules/exploit/unix/smtp/opensmtpd_mail_from_rce.md
  documentation/modules/exploit/unix/webapp/thinkphp_rce.md
  documentation/modules/exploit/unix/webapp/wp_infinitewp_auth_bypass.md
  documentation/modules/exploit/windows/http/desktopcentral_deserialization.md
  lib/msf/core/exploit/auto_check.rb
  lib/msf/core/exploit/cmdstager/http.rb
  lib/msf/core/exploit/expect.rb
  lib/msf/core/exploit/mixins.rb
  modules/exploits/linux/http/axis_srv_parhand_rce.rb
  modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
  modules/exploits/linux/upnp/belkin_wemo_upnp_exec.rb
  modules/exploits/multi/http/jenkins_metaprogramming.rb
  modules/exploits/unix/local/opensmtpd_oob_read_lpe.rb
  modules/exploits/unix/smtp/morris_sendmail_debug.rb
  modules/exploits/unix/smtp/opensmtpd_mail_from_rce.rb
  modules/exploits/unix/webapp/thinkphp_rce.rb
  modules/exploits/unix/webapp/wp_infinitewp_auth_bypass.rb
  modules/exploits/unix/webapp/wp_phpmailer_host_header.rb
  modules/exploits/windows/http/desktopcentral_deserialization.rb
Labels: bug, docs, library, module

#13261 Rubocop recently landed modules
  .rubocop.yml
  modules/auxiliary/scanner/http/limesurvey_zip_traversals.rb
  modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
  modules/exploits/linux/http/pandora_ping_cmd_exec.rb
  modules/exploits/linux/http/vestacp_exec.rb
  modules/exploits/linux/misc/tplink_archer_a7_c7_lan_rce.rb
  modules/exploits/multi/http/liferay_java_unmarshalling.rb
  modules/exploits/osx/local/vmware_fusion_lpe.rb
  modules/exploits/unix/smtp/opensmtpd_mail_from_rce.rb
  modules/exploits/unix/webapp/thinkphp_rce.rb
  modules/exploits/windows/local/cve_2020_0796_smbghost.rb
  modules/exploits/windows/telnet/goodtech_telnet.rb
  modules/post/windows/gather/credentials/teamviewer_passwords.rb
  modules/post/windows/manage/execute_dotnet_assembly.rb
Labels: automation, code quality, delayed, rn-no-release-notes

#13267 Rename tip command to tips
  lib/msf/ui/console/command_dispatcher/core.rb
  lib/msf/ui/tip.rb
Labels: easy, msfconsole, usability

#13274 Fix RuboCop's mistakes in recently landed modules
  modules/exploits/multi/http/liferay_java_unmarshalling.rb
  modules/exploits/unix/webapp/thinkphp_rce.rb
Labels: bug, module, rn-no-release-notes

#13299 Update my module documentation to the new standard
  documentation/modules/exploit/bsd/finger/morris_fingerd_bof.md
  documentation/modules/exploit/linux/http/nexus_repo_manager_el_injection.md
  documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
  documentation/modules/exploit/unix/local/emacs_movemail.md
  documentation/modules/exploit/unix/local/opensmtpd_oob_read_lpe.md
  documentation/modules/exploit/unix/smtp/morris_sendmail_debug.md
  documentation/modules/exploit/unix/smtp/opensmtpd_mail_from_rce.md
  documentation/modules/exploit/unix/webapp/thinkphp_rce.md
  documentation/modules/exploit/unix/webapp/wp_infinitewp_auth_bypass.md
  documentation/modules/exploit/windows/http/desktopcentral_deserialization.md
  lib/msf/core/exploit/check_module.rb
  modules/exploits/linux/http/citrix_dir_traversal_rce.rb
  modules/exploits/linux/http/pulse_secure_cmd_exec.rb
  modules/exploits/windows/rdp/cve_2019_0708_bluekeep_rce.rb
  modules/exploits/windows/smb/ms17_010_eternalblue.rb
  modules/exploits/windows/smb/ms17_010_psexec.rb
Labels: bug, docs, library, module, rn-no-release-notes

#13298 Fix ExitOnSession usage in to_handler
  lib/msf/ui/console/command_dispatcher/evasion.rb
  lib/msf/ui/console/command_dispatcher/payload.rb
Labels: bug, easy, library

#13263 Added Python stager format without a space
  lib/msf/core/payload/python.rb
  modules/payloads/singles/python/meterpreter_bind_tcp.rb
  modules/payloads/singles/python/meterpreter_reverse_http.rb
  modules/payloads/singles/python/meterpreter_reverse_https.rb
  modules/payloads/singles/python/meterpreter_reverse_tcp.rb
  modules/payloads/stagers/python/bind_tcp.rb
  modules/payloads/stagers/python/bind_tcp_uuid.rb
  modules/payloads/stagers/python/reverse_http.rb
  modules/payloads/stagers/python/reverse_https.rb
  modules/payloads/stagers/python/reverse_tcp.rb
  modules/payloads/stagers/python/reverse_tcp_ssl.rb
  modules/payloads/stagers/python/reverse_tcp_uuid.rb
Labels: enhancement, library

#13308 Update post-RuboCop style in my recent modules
  documentation/modules/exploit/linux/http/nexus_repo_manager_el_injection.md
  documentation/modules/exploit/multi/http/liferay_java_unmarshalling.md
  modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
  modules/exploits/multi/http/liferay_java_unmarshalling.rb
  modules/exploits/unix/smtp/opensmtpd_mail_from_rce.rb
  modules/exploits/unix/webapp/thinkphp_rce.rb
Labels: bug, docs, module, rn-no-release-notes

#13311 ZDI Public Numbers can be 4 digits, ZDI-19-1045
  tools/dev/msftidy.rb
Labels: easy, msftidy

#11967 Add screenshare post module for mouse and keyboard input
  documentation/modules/post/multi/manage/screensaver.md
  documentation/modules/post/multi/manage/screenshare.md
  modules/post/multi/manage/screenshare.rb
Labels: module, needs-docs

#13253 Add VMware vCenter Server vmdir Information Disclosure and Authentication Bypass (CVE-2020-3952)
  Gemfile.lock
  documentation/modules/auxiliary/admin/ldap/vmware_vcenter_vmdir_auth_bypass.md
  documentation/modules/auxiliary/gather/vmware_vcenter_vmdir_ldap.md
  lib/msf/core/exploit/ldap.rb
  lib/msf/core/exploit/mixins.rb
  metasploit-framework.gemspec
  modules/auxiliary/admin/ldap/vmware_vcenter_vmdir_auth_bypass.rb
  modules/auxiliary/gather/vmware_vcenter_vmdir_ldap.rb
Labels: docs, feature, module

#13314 Fix "Land #13311, ZDI reference update to msftidy"
  tools/dev/msftidy.rb
Labels: bug, msftidy, rn-no-release-notes

#13315 flip gatherpoof
  modules/auxiliary/scanner/ssh/ssh_login.rb
  modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb
Labels: enhancement, module

#13319 f5 mgmt module docs
  documentation/modules/auxiliary/scanner/http/f5_mgmt_scanner.md
  documentation/modules/module_doc_template.md
  modules/auxiliary/scanner/http/f5_mgmt_scanner.rb
Labels: docs, easy

#13260 First swipe at CVE-2019-15752
  documentation/modules/exploit/windows/local/docker_credential_wincred.md
  modules/exploits/windows/local/docker_credential_wincred.rb
Labels: easy, module

#13328 Add in missing plural tense to f5_mgmt_scanner.md
  documentation/modules/auxiliary/scanner/http/f5_mgmt_scanner.md
Labels: docs

#13100 Add MeterpreterDebugLevel option and a fix for the osx stager
  data/meterpreter/x64_osx_stage
  external/source/shellcode/osx/stager/main.c
  modules/payloads/stagers/osx/x64/reverse_tcp.rb
Labels: enhancement, payload

#13257 .NET Deserialization Library Improvements
  lib/msf/util/dot_net_deserialization.rb
  lib/msf/util/dot_net_deserialization/assemblies.rb
  lib/msf/util/dot_net_deserialization/enums.rb
  lib/msf/util/dot_net_deserialization/formatters.rb
  lib/msf/util/dot_net_deserialization/formatters/binary_formatter.rb
  lib/msf/util/dot_net_deserialization/formatters/los_formatter.rb
  lib/msf/util/dot_net_deserialization/formatters/soap_formatter.rb
  lib/msf/util/dot_net_deserialization/gadget_chains.rb
  lib/msf/util/dot_net_deserialization/gadget_chains/text_formatting_run_properties.rb
  lib/msf/util/dot_net_deserialization/gadget_chains/type_confuse_delegate.rb
  lib/msf/util/dot_net_deserialization/gadget_chains/windows_identity.rb
  lib/msf/util/dot_net_deserialization/types.rb
  lib/msf/util/dot_net_deserialization/types/general.rb
  lib/msf/util/dot_net_deserialization/types/primitives.rb
  lib/msf/util/dot_net_deserialization/types/record_values.rb
  modules/exploits/windows/http/dnn_cookie_deserialization_rce.rb
  modules/exploits/windows/http/exchange_ecp_viewstate.rb
  modules/exploits/windows/http/ssrs_navcorrector_viewstate.rb
  spec/lib/msf/util/dot_net_deserialization_spec.rb
Labels: enhancement, library, module

#13347 Remove safe navigation rubocop rule
  .rubocop.yml
Labels: code quality

#13340 Fix broken link to broken PKS for key verification
  tools/dev/import-dev-keys.sh
Labels: bug, easy

#13348 Randomize target directory in desktopcentral_deserialization and apply RuboCop for great justice
  documentation/modules/exploit/windows/http/desktopcentral_deserialization.md
  modules/exploits/windows/http/desktopcentral_deserialization.rb
Labels: bug, docs, enhancement, module, rn-no-release-notes

#13350 Remove directory traversal prefix altogether in desktopcentral_deserialization
  modules/exploits/windows/http/desktopcentral_deserialization.rb
Labels: bug, enhancement, module, rn-no-release-notes

#13321 ssh_login windows 10/2019 friendly, and 'submit unknown' banner.
  lib/metasploit/framework/login_scanner/ssh.rb
  modules/auxiliary/scanner/ssh/ssh_login.rb
  modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb
Labels: bug, library, module

#13280 Add additional label actions
  .github/label-actions.yml
Labels: automation, docs, rn-no-release-notes

#13316 Adds tag functionality for hosts
  lib/metasploit/framework/data_service/proxy/host_data_proxy.rb
  lib/metasploit/framework/data_service/remote/http/remote_host_data_service.rb
  lib/metasploit/framework/data_service/stubs/host_data_service.rb
  lib/msf/core/db_manager/host.rb
  lib/msf/core/web_services/servlet/host_servlet.rb
  lib/msf/ui/console/command_dispatcher/db.rb
Labels: bug, database

#13281 Add checks to 'screenshot' command to fix issue #13182
  lib/rex/post/meterpreter/extensions/stdapi/ui.rb
Labels: bug, library

#13360 Turn off Ruby deprecation warnings for all users
  msfconsole
Labels: usability

#13361 Add guard clause to ruby warning supression
  msfconsole
Labels: bug, rn-no-release-notes

#13363 Fix uri escape in rex request for reverse http/https meterpreter shells
  lib/rex/proto/http/request.rb
Labels: usability
