Repository rapid7/metasploit-framework, pull requests merged in 2020-05, with the labels that each got.

#13371 Use stageless payload with HTTP command stager in ThinkPHP exploit
  documentation/modules/exploit/unix/webapp/thinkphp_rce.md
  modules/exploits/unix/webapp/thinkphp_rce.rb
Labels: bug, docs, module, rn-no-release-notes

#13325 Fix #13318, Expand Environment Variables In Meterpreter's ls Command
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb
Labels: easy, enhancement, library, meterpreter, usability

#13376 add test for reverse_tcp_uuid stager with osx
  spec/modules/payloads_spec.rb
Labels: easy, tests

#13327 Add Veeam ONE Agent .NET deserialization exploit (CVE-2020-10915 / ZDI-20-546) and new Windows HTTP command stager
  Gemfile.lock
  LICENSE_GEMS
  documentation/modules/exploit/windows/misc/veeam_one_agent_deserialization.md
  lib/msf/core/exploit/cmdstager.rb
  modules/exploits/windows/misc/veeam_one_agent_deserialization.rb
Labels: docs, feature, library, module

#13373 Improves "No DB Connected" error message
  lib/msf/ui/console/command_dispatcher/db.rb
Labels: easy, rn-no-release-notes

#13375 Fix for issue #13372, buffer register option in unicode encoders
  modules/encoders/x86/unicode_mixed.rb
  modules/encoders/x86/unicode_upper.rb
Labels: bug, confirmed, payload

#13380 Fix typo and RuboCop errors in lib/msf/core/encoder/alphanum.rb
  lib/msf/core/encoder/alphanum.rb
  modules/encoders/x86/unicode_mixed.rb
  modules/encoders/x86/unicode_upper.rb
Labels: code quality, library, module

#13313 Warn the user that changing the SSL option's value may require changing RPORT
  lib/msf/ui/console/command_dispatcher/core.rb
Labels: enhancement, library, usability

#13353 Trixbox CE v2.8.0.4 endpoint_devicemap.php Authenticated Remote Command Execution
  documentation/modules/exploit/unix/webapp/trixbox_ce_endpoint_devicemap_rce.md
  modules/exploits/unix/webapp/trixbox_ce_endpoint_devicemap_rce.rb
Labels: module

#13396 silence warnings for all users
  msfconsole
  msfvenom
Labels: usability

#13364 Add a .NET deserialization tool
  lib/msf/base/simple/buffer.rb
  lib/msf/util/dot_net_deserialization/formatters/soap_formatter.rb
  spec/lib/msf/util/dot_net_deserialization_spec.rb
  tools/payloads/ysoserial/dot_net.rb
Labels: feature

#13304 Add SSH exploit for IBM Data Risk Manager (CVE-2020-4429)
  documentation/modules/exploit/linux/ssh/ibm_drm_a3user.md
  modules/exploits/linux/ssh/ibm_drm_a3user.rb
Labels: docs, module, needs-testing-environment

#13301 Add exploit for IBM DRM arbitrary file download (CVE-2020-4427, CVE-2020-4429)
  documentation/modules/auxiliary/admin/http/ibm_drm_download.md
  modules/auxiliary/admin/http/ibm_drm_download.rb
Labels: docs, module, needs-testing-environment

#13300 Add exploit for IBM DRM RCE (CVE-2020-4427, CVE-2020-4428, CVE-2020-4429)
  documentation/modules/exploit/linux/http/ibm_drm_rce.md
  modules/exploits/linux/http/ibm_drm_rce.rb
Labels: docs, module, needs-testing-environment

#13399 Fix fail with call in vmware fusion lpe
  modules/exploits/osx/local/vmware_fusion_lpe.rb
Labels: bug, rn-no-release-notes

#13392 Fix ruby 2.7 rex http client warnings
  lib/rex/proto/http/client.rb
Labels: bug, rn-no-release-notes

#13388 Updates for SAP ICM paths
  data/wordlists/sap_icm_paths.txt
Labels: enhancement, module

#13367 Surface developer provided exception messages to users
  lib/msf/base/simple/evasion.rb
  lib/msf/base/simple/exploit.rb
  lib/msf/core/auxiliary/drdos.rb
  lib/msf/core/evasion_driver.rb
  lib/msf/core/exceptions.rb
  lib/msf/core/exploit/brute.rb
  lib/msf/core/exploit_driver.rb
  lib/msf/core/option_container.rb
Labels: rn-enhancement, usability

#13386 fix #10181, add error when an android stageless payload is used with -x
  lib/msf/core/payload_generator.rb
Labels: enhancement, rn-no-release-notes

#13406 Fix multiple DNS enumeration related bugs
  lib/net/dns/packet.rb
  lib/rex/proto/dns/resolver.rb
  modules/auxiliary/gather/enum_dns.rb
Labels: bug, library

#13413 Add auxiliary/admin/http/ibm_drm_download action
  modules/auxiliary/admin/http/ibm_drm_download.rb
Labels: bug, module

#13416 Add an RDLL Visual Studio project template
  external/source/rdll_template/README.md
  external/source/rdll_template/Reflective DLL.zip
  external/source/rdll_template/dllmain.c
  external/source/rdll_template/rdll_template.sln
  external/source/rdll_template/rdll_template.vcxproj
Labels: feature

#13358 Fix packet ordering check
  lib/rex/post/meterpreter/packet_dispatcher.rb
Labels: bug, library, meterpreter, priority

#12234 add. new gather module cloud_lookup
  documentation/modules/auxiliary/gather/cloud_lookup.md
  lib/msf/core/exploit/dns.rb
  lib/msf/core/exploit/dns/enumeration.rb
  modules/auxiliary/gather/cloud_lookup.rb
  modules/auxiliary/gather/enum_dns.rb
Labels: docs, module

#13426 Refactor Msf::Exploit::CmdStager::HTTP
  lib/msf/core/exploit/cmdstager.rb
  lib/msf/core/exploit/cmdstager/http.rb
Labels: code quality, library, rn-no-release-notes

#13423 IBM advisory link fixes
  documentation/modules/exploit/multi/misc/ibm_tm1_unauth_rce.md
  modules/exploits/linux/http/ibm_qradar_unauth_rce.rb
  modules/exploits/multi/misc/ibm_tm1_unauth_rce.rb
Labels: docs, rn-no-release-notes

#13433 Update msf json rpc framework path to be relative
  msf-json-rpc.ru
Labels: bug, database

#13422 Update CVE-2019-13272 exploit C code to prefer auto targeting
  data/exploits/CVE-2019-13272/exploit
  data/exploits/CVE-2019-13272/poc.c
Labels: enhancement, module

#13429 Add Netsweeper WebAdmin unixlogin.php pre-auth RCE
  documentation/modules/exploit/linux/http/netsweeper_webadmin_unixlogin.md
  modules/exploits/linux/http/netsweeper_webadmin_unixlogin.rb
Labels: docs, feature, module

#13404 fakedns: specificy in help the wildcard character
  modules/auxiliary/server/fakedns.rb
Labels: easy, newbie-friendly, rn-no-release-notes

#13370 Add Druva inSync inSyncCPHwnet64.exe RPC Type 5 Privilege Escalation
  documentation/modules/exploit/windows/local/druva_insync_insynccphwnet64_rcp_type_5_priv_esc.md
  modules/exploits/windows/local/druva_insync_insynccphwnet64_rcp_type_5_priv_esc.rb
Labels: docs, module

#13402 Add Post::Windows::Services.service_exists? method
  lib/msf/core/post/windows/services.rb
  modules/exploits/windows/local/ikeext_service.rb
  modules/exploits/windows/local/plantronics_hub_spokesupdateservice_privesc.rb
  modules/exploits/windows/local/webexec.rb
  modules/exploits/windows/local/windscribe_windscribeservice_priv_esc.rb
Labels: easy, enhancement, library

#13441 delete komand plugin
  plugins/komand.rb
Labels: plugin

#13405 Use OptAddressLocal for SRVHOST to specify by interface name instead of IP
  lib/msf/core/exploit/socket_server.rb
Labels: enhancement, library, usability

#13436 Fix regression in psexec mixing filename and encoder
  lib/msf/core/exploit/smb/client/psexec.rb
  modules/exploits/windows/smb/ms17_010_psexec.rb
  modules/exploits/windows/smb/psexec.rb
Labels: bug, library

#13456 distinct_tftp_traversal: increase delay between upload requests
  documentation/modules/exploit/windows/tftp/distinct_tftp_traversal.md
  modules/exploits/windows/tftp/distinct_tftp_traversal.rb
Labels: module

#13464 update ruby-prof version due to broken compile
  Gemfile.lock
Labels: bug, rn-no-release-notes

#13415 Avoid auto-encoding payloads free of badchars
  lib/msf/core/encoded_payload.rb
  lib/msf/core/payload_generator.rb
  spec/lib/msf/core/encoded_payload_spec.rb
  spec/lib/msf/core/payload_generator_spec.rb
Labels: bug, enhancement, library, payload

#13445 Pi-Hole <= 4.4 root RCE CVE-2020-11108
  documentation/modules/exploit/unix/http/pihole_blocklist_exec.md
  modules/exploits/unix/http/pihole_blocklist_exec.rb
Labels: docs, module

#13465 Prioritise incomplete packets in the dispatch loop
  lib/rex/post/meterpreter/packet_dispatcher.rb
Labels: bug, hotness, library, meterpreter, priority

#13492 Fix punctuation typo in exploit/windows/http/exchange_ecp_viewstate documentation
  documentation/modules/exploit/windows/http/exchange_ecp_viewstate.md
  modules/exploits/windows/http/exchange_ecp_viewstate.rb
Labels: bug, docs, module

#13262 add python native stager
  lib/msf/util/exe.rb
Labels: module, msfvenom, payload

#13493 Fix miscellaneous things in ThinkPHP and ManageEngine exploits
  modules/exploits/unix/webapp/thinkphp_rce.rb
  modules/exploits/windows/http/desktopcentral_deserialization.rb
Labels: bug, module, rn-no-release-notes

#13463 Add WebLogic Exploit for CVE-2020-2555
  data/exploits/CVE-2020-2555/Weblogic_2555.java
  documentation/modules/exploit/multi/misc/weblogic_deserialize_badattrval.md
  modules/exploits/multi/misc/weblogic_deserialize_badattrval.rb
Labels: docs, module, needs-linting

#13499 fix Java cmd_exec stderr output
  Gemfile.lock
  metasploit-framework.gemspec
Labels: payload

#13485 Update eyesofnetwork_autodiscovery_rce with CVE-2020-9465 (extends use to 5.1 & 5.2) and add meterpreter support
  documentation/modules/exploit/linux/http/eyesofnetwork_autodiscovery_rce.md
  modules/exploits/linux/http/eyesofnetwork_autodiscovery_rce.rb
Labels: docs, enhancement, module

#13498 CVE-2017-9554 Synology Username Enumerator
  documentation/modules/auxiliary/scanner/http/synology_forget_passwd_user_enum.md
  modules/auxiliary/scanner/http/synology_forget_passwd_user_enum.rb
Labels: docs, module

#13487 CVE-2017-15889 Synology DSM < 5.2-5967-5 authenticated root exploit
  documentation/modules/exploit/linux/http/synology_dsm_smart_exec_auth.md
  modules/exploits/linux/http/synology_dsm_smart_exec_auth.rb
Labels: docs, module

#13494 Add Plesk/myLittleAdmin ViewState .NET deserialization pre-auth RCE (CVE-2020-13166), plus babby ViewState mixin
  documentation/modules/exploit/windows/http/plesk_mylittleadmin_viewstate.md
  lib/msf/core/exploit/mixins.rb
  lib/msf/core/exploit/viewstate.rb
  modules/exploits/linux/http/netsweeper_webadmin_unixlogin.rb
  modules/exploits/windows/http/plesk_mylittleadmin_viewstate.rb
Labels: docs, feature, library, module

#13503 Add BASE_DN and ROOT_KEY options to VMware vCenter vmdir and SaltStack Salt modules
  documentation/modules/auxiliary/admin/ldap/vmware_vcenter_vmdir_auth_bypass.md
  documentation/modules/auxiliary/gather/vmware_vcenter_vmdir_ldap.md
  documentation/modules/exploit/linux/misc/saltstack_salt_unauth_rce.md
  modules/auxiliary/admin/ldap/vmware_vcenter_vmdir_auth_bypass.rb
  modules/auxiliary/gather/vmware_vcenter_vmdir_ldap.rb
  modules/exploits/linux/misc/saltstack_salt_unauth_rce.rb
Labels: enhancement, module

#13455 Pi-Hole < 3.3 whitelist RCE
  documentation/modules/exploit/unix/http/pihole_whitelist_exec.md
  modules/exploits/unix/http/pihole_whitelist_exec.rb
Labels: docs, module

#13508 Update authors in Netsweeper and myLittleAdmin modules
  modules/exploits/linux/http/netsweeper_webadmin_unixlogin.rb
  modules/exploits/windows/http/plesk_mylittleadmin_viewstate.rb
Labels: bug, module, rn-no-release-notes

#13460 pop3 capture docs
  documentation/modules/auxiliary/server/capture/pop3.md
Labels: docs

#13500 Ignore unloadable modules in search-after-use
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: bug, msfconsole

#13511 Update TinyIdentD 2.2 Stack Buffer Overflow module
  documentation/modules/exploit/windows/misc/tiny_identd_overflow.md
  modules/exploits/windows/misc/tiny_identd_overflow.rb
Labels: docs, easy, enhancement, module

#13526 Correct the author and add a reference to CVE-2020-8617
  modules/auxiliary/dos/dns/bind_tsig_badtime.rb
Labels: bug, easy, module

#13488 Fix memory leak in ms01_026_dbldecode
  modules/exploits/windows/iis/ms01_026_dbldecode.rb
Labels: bug, rn-no-release-notes

#13530 exim_gethostbyname_bof docs
  documentation/modules/exploit/linux/smtp/exim_gethostbyname_bof.md
Labels: docs

#13531 ghost doc fixes
  documentation/modules/exploit/linux/smtp/exim_gethostbyname_bof.md
Labels: docs

#13470 Pi-Hole < 4.3.3 dhcp static address RCE
  documentation/modules/exploit/unix/http/pihole_dhcp_mac_exec.md
  lib/msf/core/exploit.rb
  modules/exploits/unix/http/pihole_dhcp_mac_exec.rb
Labels: docs, module, rn-modules

#13522 Suggest valid options in Msf::OptAddressRange (RHOSTS) tab completion
  lib/msf/ui/console/command_dispatcher/core.rb
Labels: bug, easy, msfconsole

#13514 Add irb as a runtime dependency
  metasploit-framework.gemspec
Labels: bug

#13538 Add Cisco CML and VIRL-PE advisory to Salt modules
  documentation/modules/auxiliary/gather/saltstack_salt_root_key.md
  documentation/modules/exploit/linux/misc/saltstack_salt_unauth_rce.md
  modules/auxiliary/gather/saltstack_salt_root_key.rb
  modules/exploits/linux/misc/saltstack_salt_unauth_rce.rb
Labels: docs, easy, module
