Repository rapid7/metasploit-framework, pull requests merged in 2020-01, with the labels that each got.

#12785 fix telnet login with a / in it being parsed as a regex
  lib/msf/core/auxiliary/login.rb
Labels: bug, library

#12788 update rds docs
  documentation/modules/exploit/linux/local/rds_rds_page_copy_user_priv_esc.md
Labels: docs

#12779 Adding PrependSetuid support for ARMLE Targets
  lib/msf/core/payload/linux.rb
Labels: enhancement

#12806 Need to `force` on bunlde when using `clean`.
  Dockerfile
Labels: bug

#12792 Check for nil response due to connection failure
  modules/exploits/windows/http/efs_fmws_userid_bof.rb
Labels: bug, easy, module

#12811 enhancement print payload generate raw
  lib/msf/ui/console/command_dispatcher/payload.rb
Labels: enhancement, payload

#12797 Add mouse-move keepalives for >30 second BlueKeep grooming, verbose progress...
  lib/msf/core/exploit/rdp.rb
  modules/exploits/windows/rdp/cve_2019_0708_bluekeep_rce.rb
Labels: enhancement, module

#12819 Fix #12813, Twitter handle correction
  modules/auxiliary/scanner/http/citrix_dir_traversal.rb
Labels: bug, module, rn-no-release-notes

#12821 Move unix/webapp/webmin_backdoor to linux/http
  documentation/modules/exploit/linux/http/webmin_backdoor.md
  modules/exploits/linux/http/webmin_backdoor.rb
Labels: bug, module

#12827 document additional PoC authors
  modules/exploits/linux/http/citrix_dir_traversal_rce.rb
Labels: docs, module, msf5

#12828 Check for whitespace in [global] directive for Citrix
  modules/auxiliary/scanner/http/citrix_dir_traversal.rb
Labels: bug, module

#12808 Add description udp listening information
  lib/msf/core/handler/reverse_udp.rb
Labels: enhancement

#12823 fix bind_lua
  modules/payloads/singles/cmd/unix/bind_lua.rb
  modules/payloads/singles/cmd/windows/bind_lua.rb
Labels: bug, payload

#12795 Add lwp-request CmdStager
  lib/msf/core/exploit/cmdstager.rb
Labels: enhancement, feature

#12757 Randomize Msf::Post::File _write_file_unix_shell test_str
  lib/msf/core/post/file.rb
Labels: easy, library

#12758 Add Msf::Post::File.attributes method
  lib/msf/core/post/file.rb
  modules/exploits/linux/local/abrt_raceabrt_priv_esc.rb
  modules/exploits/linux/local/libuser_roothelper_priv_esc.rb
Labels: easy, library

#12776 add PROTOCOL option for sunrpc_portmapper
  modules/auxiliary/scanner/misc/sunrpc_portmapper.rb
Labels: enhancement

#12846 Use new immutable? method in modules
  modules/exploits/linux/local/abrt_raceabrt_priv_esc.rb
  modules/exploits/linux/local/libuser_roothelper_priv_esc.rb
Labels: bug, enhancement, module

#12845 Check SSL in exploit/linux/http/webmin_backdoor
  modules/exploits/linux/http/webmin_backdoor.rb
Labels: bug, easy, enhancement, module

#12856 tighten whitespace in cracker lib
  lib/metasploit/framework/password_crackers/cracker.rb
Labels: bug, library

#12857 Update LICENSE and COPYING
  COPYING
  LICENSE
Labels: bug

#12751 Add Reliable Datagram Sockets (RDS) rds_atomic_free_op NULL pointer dereference Privilege Escalation
  data/exploits/CVE-2018-5333/cve-2018-5333.c
  data/exploits/CVE-2018-5333/cve-2018-5333.out
  documentation/modules/exploit/linux/local/rds_atomic_free_op_null_pointer_deref_priv_esc.md
  modules/exploits/linux/local/rds_atomic_free_op_null_pointer_deref_priv_esc.rb
Labels: docs, module

#12873 Add flags to send custom cookies
  lib/msf/core/payload/windows/reverse_http.rb
  lib/msf/core/payload/windows/x64/reverse_http.rb
Labels: bug

#12874 handle Ranges with rand_text while in debug mode
  lib/msf/core/exploit.rb
Labels: enhancement, library

#12877 Prefer exploit.rb's rand_text wrapper in doublepulsar_rce
  modules/exploits/windows/smb/doublepulsar_rce.rb
Labels: bug, easy, module, rn-no-release-notes

#12859 Update AF_PACKET chocobo_root Privilege Escalation module
  data/exploits/CVE-2016-8655/chocobo_root
  data/exploits/CVE-2016-8655/chocobo_root.c
  documentation/modules/exploit/linux/local/af_packet_chocobo_root_priv_esc.md
  modules/exploits/linux/local/af_packet_chocobo_root_priv_esc.rb
Labels: enhancement, module

#12733 Added Array Handling
  lib/rex/proto/http/client_request.rb
Labels: enhancement, library

#12882 Update set command help for PAYLOAD by index
  lib/msf/ui/console/command_dispatcher/core.rb
Labels: bug, easy, library, msf5, msfconsole

#12871 Update removal commands for osx/local/persistence
  modules/exploits/osx/local/persistence.rb
Labels: bug

#12883 Add listm and clearm commands to manage the module stack
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: feature, library, msfconsole

#12885 Reference URL is broken
  modules/post/windows/gather/netlm_downgrade.rb
Labels: easy

#12706 Add documentation for auxiliary/scanner/http/apache_userdir_enum
  documentation/modules/auxiliary/scanner/http/apache_userdir_enum.md
Labels: docs

#12878 msftidy_docs
  documentation/modules/exploit/multi/postgres/postgres_copy_from_program_cmd_exec.md
  documentation/modules/exploit/windows/fileformat/office_excel_slk.md
  documentation/modules/exploit/windows/http/disk_pulse_enterprise_get.md
  documentation/modules/exploit/windows/http/geutebrueck_gcore_x64_rce_bo.md
  documentation/modules/exploit/windows/http/hp_imc_java_deserialize.md
  documentation/modules/exploit/windows/http/manageengine_connectionid_write.md
  documentation/modules/exploit/windows/http/octopusdeploy_deploy.md
  documentation/modules/exploit/windows/ibm/ibm_was_dmgr_java_deserialization_rce.md
  documentation/modules/exploit/windows/iis/iis_webdav_upload_asp.md
  documentation/modules/exploit/windows/local/bypassuac_fodhelper.md
  documentation/modules/exploit/windows/local/bypassuac_silentcleanup.md
  documentation/modules/exploit/windows/local/bypassuac_sluihijack.md
  documentation/modules/exploit/windows/local/bypassuac_windows_store_reg.md
  documentation/modules/exploit/windows/local/ms16_075_reflection.md
  documentation/modules/exploit/windows/local/ms16_reflection.md
  documentation/modules/exploit/windows/local/panda_psevents.md
  documentation/modules/exploit/windows/misc/ahsay_backup_fileupload.md
  documentation/modules/exploit/windows/misc/ais_esel_server_rce.md
  documentation/modules/exploit/windows/misc/gh0st.md
  documentation/modules/exploit/windows/misc/hp_loadrunner_magentproc_cmdexec.md
  documentation/modules/exploit/windows/misc/plugx.md
  documentation/modules/exploit/windows/smb/group_policy_startup.md
  documentation/modules/exploit/windows/winrm/winrm_script_exec.md
  tools/dev/msftidy_docs.rb
Labels: docs, feature
