Repository rapid7/metasploit-framework, pull requests merged in 2020-03, with the labels that each got.

#13012 Fix error handling when a plugin load fails
  lib/msf/core/rpc/v10/rpc_plugin.rb
  lib/msf/ui/console/command_dispatcher/core.rb
Labels: bug, plugin, usability

#12998 Allows use of type:aux in search
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: enhancement, library

#13015 Enable usage of usernames in cred collections
  lib/msf/core/auxiliary/auth_brute.rb
  modules/auxiliary/scanner/smb/smb_login.rb
Labels: bug, enhancement, library

#13018 Add module notes to my recent modules
  modules/exploits/unix/smtp/opensmtpd_mail_from_rce.rb
  modules/exploits/unix/webapp/wp_infinitewp_auth_bypass.rb
Labels: bug, module, rn-no-release-notes

#12929 Optionally store enumerated SMB usernames in DB
  modules/auxiliary/scanner/smb/smb_enumusers.rb
Labels: enhancement, module

#13014 Add an exploit for Exchange ECP ViewState deserialization (CVE-2020-0688)
  documentation/modules/exploit/windows/http/exchange_ecp_viewstate.md
  lib/msf/util.rb
  lib/msf/util/dot_net_deserialization.rb
  modules/exploits/windows/http/exchange_ecp_viewstate.rb
  spec/lib/msf/util/dot_net_deserialization_spec.rb
Labels: docs, module

#12989 Moves file path logic into command_dispatcher/common
  lib/msf/ui/console/command_dispatcher/common.rb
  lib/msf/ui/console/command_dispatcher/core.rb
  lib/msf/ui/console/command_dispatcher/modules.rb
  spec/lib/msf/ui/console/command_dispatcher/common_spec.rb
Labels: enhancement, library

#12980 Prevents HTML being returned by RPC
  lib/msf/core/rpc.rb
  lib/msf/core/rpc/json/error.rb
  lib/msf/core/web_services/json_rpc_app.rb
  lib/msf/core/web_services/json_rpc_exception_handling.rb
  spec/api/json_rpc_spec.rb
Labels: enhancement, usability

#13008 Google Chrome 80 JSCreate side-effect type confusion exploit
  documentation/modules/exploit/multi/browser/chrome_jscreate_sideeffect.md
  modules/exploits/multi/browser/chrome_jscreate_sideeffect.rb
Labels: module

#13003 Add OpenSMTPD CVE-2020-8794 LPE exploit
  documentation/modules/exploit/unix/local/opensmtpd_oob_read_lpe.md
  documentation/modules/exploit/unix/smtp/opensmtpd_mail_from_rce.md
  modules/exploits/unix/local/opensmtpd_oob_read_lpe.rb
  modules/exploits/unix/smtp/opensmtpd_mail_from_rce.rb
  modules/exploits/unix/webapp/wp_infinitewp_auth_bypass.rb
Labels: feature, module

#12863 Add PHP-FPM Underflow RCE module
  documentation/modules/exploit/multi/http/php_fpm_rce.md
  modules/exploits/multi/http/php_fpm_rce.rb
Labels: docs, module

#12984 Process updates to socket parameters when opening channels
  Gemfile.lock
  lib/msf/ui/console/command_dispatcher/core.rb
  lib/rex/post/meterpreter/channel.rb
  lib/rex/post/meterpreter/channels/pool.rb
  lib/rex/post/meterpreter/channels/pools/file.rb
  lib/rex/post/meterpreter/channels/pools/stream_pool.rb
  lib/rex/post/meterpreter/channels/socket_abstraction.rb
  lib/rex/post/meterpreter/extensions/stdapi/net/socket.rb
  lib/rex/post/meterpreter/extensions/stdapi/net/socket_subsystem/tcp_client_channel.rb
  lib/rex/post/meterpreter/extensions/stdapi/net/socket_subsystem/tcp_server_channel.rb
  lib/rex/post/meterpreter/extensions/stdapi/net/socket_subsystem/udp_channel.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/net.rb
  lib/rex/services/local_relay.rb
  metasploit-framework.gemspec
  modules/payloads/singles/apple_ios/aarch64/meterpreter_reverse_http.rb
  modules/payloads/singles/apple_ios/aarch64/meterpreter_reverse_https.rb
  modules/payloads/singles/apple_ios/aarch64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/apple_ios/armle/meterpreter_reverse_http.rb
  modules/payloads/singles/apple_ios/armle/meterpreter_reverse_https.rb
  modules/payloads/singles/apple_ios/armle/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/aarch64/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/aarch64/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/aarch64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/armbe/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/armbe/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/armbe/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/armle/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/armle/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/armle/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/mips64/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/mips64/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/mips64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/mipsbe/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/mipsbe/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/mipsbe/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/mipsle/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/mipsle/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/mipsle/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/ppc/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/ppc/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/ppc/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/ppc64le/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/ppc64le/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/ppc64le/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/ppce500v2/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/ppce500v2/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/ppce500v2/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/x64/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/x64/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/x64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/x86/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/x86/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/x86/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/zarch/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/zarch/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/zarch/meterpreter_reverse_tcp.rb
  modules/payloads/singles/osx/x64/meterpreter_reverse_http.rb
  modules/payloads/singles/osx/x64/meterpreter_reverse_https.rb
  modules/payloads/singles/osx/x64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/windows/encrypted_shell_reverse_tcp.rb
Labels: bug, library, meterpreter

#12985 fix the cmd/windows/reverse_powershell payload
  modules/payloads/singles/cmd/windows/reverse_powershell.rb
Labels: bug, payload

#12944 Fix bug in owa_login if AUTH_TIME is set to false
  modules/auxiliary/scanner/http/owa_login.rb
Labels: bug

#12574 Add CVE-2019-5825, Chrome 73 1-day Array.map --no-sandbox exploit
  documentation/modules/exploit/multi/browser/chrome_array_map.md
  modules/exploits/multi/browser/chrome_array_map.rb
Labels: module

#12384 CVE-2018-17463, Google Chrome < 70 Object.create exploit
  documentation/modules/exploit/multi/browser/chrome_object_create.md
  modules/exploits/multi/browser/chrome_object_create.rb
Labels: module

#13029 Filter payloads by platform and arch for msfvenom
  lib/msf/core/module/platform_list.rb
  msfvenom
Labels: bug, easy, msfvenom

#13038 Fix PHP-FPM RCE module issue when calling check and exploit multiple times
  modules/exploits/multi/http/php_fpm_rce.rb
Labels: bug, module

#13042 Use VHOST instead of RHOST
  modules/exploits/windows/http/exchange_ecp_viewstate.rb
Labels: enhancement, module

#13004 Add module and docs for Nagios XI < 5.6.6 authenticated RCE (CVE-2019-15949)
  documentation/modules/exploit/linux/http/nagios_xi_authenticated_rce.md
  modules/exploits/linux/http/nagios_xi_authenticated_rce.rb
Labels: docs, module

#13050 bump metasploit-payloads properly for #12927
  Gemfile.lock
  metasploit-framework.gemspec
Labels: bug, payload

#12975 Add phpstudy backdoor exploit module
  documentation/modules/exploit/multi/http/phpstudy_backdoor_rce.md
  modules/exploits/multi/http/phpstudy_backdoor_rce.rb
Labels: delayed, docs, module

#13041 Cut unknown command handling time in half
  lib/msf/ui/console/driver.rb
Labels: enhancement, library

#13052 Add hex-noslashes to Rex::Proto::Http::Client
  lib/rex/proto/http/client.rb
Labels: bug, easy, library

#13037 Add useful tips when starting up metasploit
  lib/msf/ui.rb
  lib/msf/ui/console/command_dispatcher/core.rb
  lib/msf/ui/tip.rb
Labels: library, msfconsole, usability

#13040 Add an exploit for SQL Server Reporting Services ViewState deserialization (CVE-2020-0618)
  documentation/modules/exploit/windows/http/ssrs_navcorrector_viewstate.md
  lib/msf/core/exploit/http/client.rb
  modules/exploits/windows/http/exchange_ecp_viewstate.rb
  modules/exploits/windows/http/ssrs_navcorrector_viewstate.rb
Labels: docs, module

#13064 quick fix for rapid7/metasploit-framework#13060 (meterpreter > shell)
  lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb
Labels: bug

#13035 fix #7366, ignore the ssl cert verification on PHP web_delivery
  modules/exploits/multi/script/web_delivery.rb
Labels: bug

#13054 Fix #13053 - post/windows/manage/migrate & PPID_NAME
  lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb
  modules/post/windows/manage/migrate.rb
Labels: bug, module

#13069 Fix args when directly opening a channel
  lib/rex/post/meterpreter/extensions/extapi/ntds/ntds.rb
  lib/rex/post/meterpreter/extensions/networkpug/networkpug.rb
  lib/rex/post/meterpreter/extensions/powershell/powershell.rb
  lib/rex/post/meterpreter/extensions/stdapi/mic/mic.rb
  lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb
  lib/rex/post/meterpreter/extensions/winpmem/winpmem.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/audio_output.rb
Labels: bug, easy, library

#13062 Remove preceding whitespace from module name
  modules/exploits/windows/iis/iis_webdav_scstoragepathfromurl.rb
Labels: rn-no-release-notes

#13057 Add profiling tools
  Gemfile
  Gemfile.lock
  lib/metasploit/framework/profiler.rb
  msfconsole
  msfvenom
Labels: enhancement

#13063 Add PSH-AmsiBypassURI option to allow persistent web_delivery
  modules/exploits/multi/script/web_delivery.rb
Labels: enhancement

#13071 Add ManageEngine Desktop Central exploit (CVE-2020-10189)
  data/ysoserial_payloads.json
  documentation/modules/exploit/windows/http/desktopcentral_deserialization.md
  lib/msf/util/java_deserialization.rb
  modules/exploits/windows/http/desktopcentral_deserialization.rb
Labels: docs, feature, module

#13079 Fix find_ysoserial_offsets.rb and incorrect serialVersionUID patching
  lib/msf/util/java_deserialization.rb
  modules/exploits/windows/http/desktopcentral_deserialization.rb
  tools/payloads/ysoserial/find_ysoserial_offsets.rb
Labels: bug, enhancement

#13066 Add module rConfig 3.9 RCE
  documentation/modules/exploit/linux/http/rconfig_ajaxarchivefiles_rce.md
  modules/exploits/linux/http/rconfig_ajaxarchivefiles_rce.rb
Labels: docs, module

#12901 Centreon 19.10.5 Authenticated RCE
  documentation/modules/exploit/linux/http/centreon_pollers_auth_rce.md
  modules/exploits/linux/http/centreon_pollers_auth_rce.rb
Labels: docs, module

#12851 add exploit module tautulli_shutdown_exec [ CVE-2019-19833 ]
  documentation/modules/auxiliary/dos/http/tautulli_shutdown_exec.md
  modules/auxiliary/dos/http/tautulli_shutdown_exec.rb
Labels: docs, module, newbie-friendly

#13070 Cisco DCNM Upload 2019 Correction
  modules/exploits/multi/http/cisco_dcnm_upload_2019.rb
Labels: bug, needs-testing

#13039 Colorizes search text matches and module ranks
  Gemfile.lock
  lib/msf/ui/console/command_dispatcher/modules.rb
  lib/msf/ui/console/table_print/highlight_substring_styler.rb
  lib/msf/ui/console/table_print/rank_formatter.rb
  lib/msf/ui/console/table_print/rank_styler.rb
  spec/lib/msf/ui/console/table_print/highlight_substring_styler_spec.rb
  spec/lib/msf/ui/console/table_print/rank_formatter_spec.rb
  spec/lib/msf/ui/console/table_print/rank_styler_spec.rb
Labels: delayed, enhancement, library, msfconsole

#13118 Changing from Remote to Local
  modules/exploits/example_linux_priv_esc.rb
Labels: docs, easy

#13131 bump Metasploit Vagrant devenv to the latest LTS version
  Vagrantfile
Labels: msfconsole

#13124 enhance info tip
  lib/msf/ui/tip.rb
Labels: easy, enhancement, library

#13133 doc cleanup
  documentation/modules/auxiliary/admin/smb/webexec_command.md
  documentation/modules/auxiliary/dos/http/flexense_http_server_dos.md
  documentation/modules/auxiliary/dos/http/marked_redos.md
  documentation/modules/auxiliary/dos/http/ua_parser_js_redos.md
  documentation/modules/auxiliary/dos/smb/smb_loris.md
  documentation/modules/auxiliary/scanner/misc/ibm_mq_channel_brute.md
  documentation/modules/auxiliary/scanner/misc/ibm_mq_enum.md
  documentation/modules/auxiliary/scanner/misc/ibm_mq_login.md
  documentation/modules/exploit/linux/http/apache_couchdb_cmd_exec.md
  documentation/modules/exploit/linux/http/goahead_ldpreload.md
  documentation/modules/exploit/linux/http/hadoop_unauth_exec.md
  documentation/modules/exploit/linux/http/microfocus_secure_messaging_gateway.md
  documentation/modules/exploit/linux/local/juju_run_agent_priv_esc.md
  documentation/modules/exploit/linux/local/network_manager_vpnc_username_priv_esc.md
  documentation/modules/exploit/linux/redis/redis_unauth_exec.md
  documentation/modules/exploit/multi/http/clipbucket_fileupload_exec.md
  documentation/modules/exploit/multi/http/freenas_exec_raw.md
  documentation/modules/exploit/multi/http/glassfish_deployer.md
  documentation/modules/exploit/multi/http/jenkins_script_console.md
  documentation/modules/exploit/multi/http/magento_unserialize.md
  documentation/modules/exploit/multi/http/trendmicro_threat_discovery_admin_sys_time_cmdi.md
  documentation/modules/exploit/unix/webapp/ajenti_auth_username_cmd_injection.md
  documentation/modules/exploit/unix/webapp/wp_mobile_detector_upload_execute.md
  documentation/modules/exploit/windows/fileformat/nitro_reader_jsapi.rb
  documentation/modules/exploit/windows/http/exchange_ecp_viewstate.md
  documentation/modules/exploit/windows/http/ssrs_navcorrector_viewstate.md
  documentation/modules/post/osx/gather/apfs_encrypted_volume_passwd.md
  documentation/modules/post/osx/gather/vnc_password_osx.md
  modules/exploits/multi/http/freenas_exec_raw.rb
  modules/exploits/multi/http/magento_unserialize.rb
  modules/exploits/multi/http/trendmicro_threat_discovery_admin_sys_time_cmdi.rb
  modules/exploits/windows/fileformat/nitro_reader_jsapi.rb
  tools/dev/msftidy_docs.rb
Labels: docs

#13059 Limit Option Sizes When Appropriate
  lib/msf/core/exceptions.rb
  lib/msf/core/handler/reverse_http.rb
  lib/msf/core/opt.rb
  lib/msf/core/opt_base.rb
  lib/msf/core/opt_string.rb
  lib/msf/core/payload.rb
  lib/rex/payloads/meterpreter/config.rb
  modules/payloads/singles/windows/messagebox.rb
Labels: bug, library

#13030 New Windows post module: install_python
  documentation/modules/post/windows/manage/install_python.md
  modules/post/windows/manage/install_python.rb
Labels: docs, module

#13122 Add Exploit Module For CVE-2020-0646 (SharePoint Workflows XOML RCE)
  documentation/modules/exploit/windows/http/sharepoint_workflows_xoml.md
  modules/exploits/windows/http/sharepoint_workflows_xoml.rb
Labels: docs, module

#13130 Transport and pivot fixes for Meterpreter
  Gemfile.lock
  metasploit-framework.gemspec
  modules/payloads/singles/linux/aarch64/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/aarch64/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/aarch64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/mipsbe/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/mipsbe/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/mipsbe/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/mipsle/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/mipsle/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/mipsle/meterpreter_reverse_tcp.rb
Labels: bug, payload

#13143 Fix has_check? conflict in exploit/linux/redis/redis_unauth_exec
  lib/msf/base/simple/exploit.rb
  modules/exploits/linux/redis/redis_unauth_exec.rb
Labels: bug, mixin madness

#13141 Add cmd/unix/reverse_tclsh
  modules/payloads/singles/cmd/unix/reverse_tclsh.rb
  spec/modules/payloads_spec.rb
Labels: payload

#13159 Created documentation for apache_mod_cgi_bash_env.rb
  documentation/modules/auxiliary/scanner/http/apache_mod_cgi_bash_env.md
Labels: docs

#13085 Rename module redis_unauth_exec
  documentation/modules/exploit/linux/redis/redis_replication_cmd_exec.md
  modules/exploits/linux/redis/redis_replication_cmd_exec.rb
Labels: bug, easy, module, rn-no-release-notes

#13105 make pattern_* and makeiplist tools faster
  tools/exploit/nasm_shell.rb
  tools/exploit/pattern_create.rb
  tools/exploit/pattern_offset.rb
  tools/recon/makeiplist.rb
Labels: bug, usability

#13093 Adding alias of ftp_connect
  lib/msf/core/exploit/ftp.rb
Labels: bug, library, mixin madness

#13132 remove spaces at EOL
  lib/metasploit/framework/afp/client.rb
  lib/metasploit/framework/compiler/windows.rb
  lib/metasploit/framework/credential.rb
  lib/metasploit/framework/login_scanner/directadmin.rb
  lib/metasploit/framework/login_scanner/glassfish.rb
  lib/metasploit/framework/login_scanner/manageengine_desktop_central.rb
  lib/metasploit/framework/login_scanner/phpmyadmin.rb
  lib/metasploit/framework/password_crackers/cracker.rb
  lib/msf/core/auxiliary/brocade.rb
  lib/msf/core/auxiliary/crand.rb
  lib/msf/core/auxiliary/juniper.rb
  lib/msf/core/db_manager/ip_address.rb
  lib/msf/core/db_manager/workspace.rb
  lib/msf/core/exploit/dns/client.rb
  lib/msf/core/exploit/dns/common.rb
  lib/msf/core/exploit/exe.rb
  lib/msf/core/exploit/java/rmi/util.rb
  lib/msf/core/exploit/socket_server.rb
  lib/msf/core/module/alert.rb
  lib/msf/core/payload/php/bind_tcp.rb
  lib/msf/core/payload/php/reverse_tcp.rb
  lib/msf/core/payload/php/send_uuid.rb
  lib/msf/core/payload/transport_config.rb
  lib/msf/core/payload/windows/bind_named_pipe.rb
  lib/msf/core/payload/windows/powershell.rb
  lib/msf/core/payload/windows/reverse_named_pipe.rb
  lib/msf/core/payload/windows/reverse_tcp.rb
  lib/msf/core/payload/windows/x64/bind_named_pipe.rb
  lib/msf/core/payload/windows/x64/bind_tcp.rb
  lib/msf/core/payload/windows/x64/block_api.rb
  lib/msf/core/payload/windows/x64/reverse_named_pipe.rb
  lib/msf/core/payload/windows/x64/reverse_tcp.rb
  lib/msf/core/post/linux/kernel.rb
  lib/msf/core/post/windows/dotnet.rb
  lib/msf/core/rpc/v10/rpc_db.rb
  lib/msf/core/session/interactive.rb
  lib/rex/google/geolocation.rb
  lib/rex/parser/acunetix_nokogiri.rb
  lib/rex/parser/fs/ntfs.rb
  lib/rex/parser/unattend.rb
  lib/rex/post/meterpreter/client.rb
  lib/rex/post/meterpreter/extensions/stdapi/tlv.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb
  lib/rex/proto/dcerpc/wdscp/packet.rb
  lib/rex/proto/dns.rb
  lib/rex/proto/dns/resolver.rb
  lib/rex/proto/dns/server.rb
  lib/rex/proto/smb/client.rb
Labels: code quality

#13176 remove inappropriate python files from issue_finder
  tools/docs/issue_finder.py
Labels: bug, docs

#13172 Bump the metasploit_payloads-mettle gem to 0.5.21
  Gemfile.lock
  LICENSE_GEMS
  metasploit-framework.gemspec
  modules/payloads/singles/apple_ios/aarch64/meterpreter_reverse_http.rb
  modules/payloads/singles/apple_ios/aarch64/meterpreter_reverse_https.rb
  modules/payloads/singles/apple_ios/aarch64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/apple_ios/armle/meterpreter_reverse_http.rb
  modules/payloads/singles/apple_ios/armle/meterpreter_reverse_https.rb
  modules/payloads/singles/apple_ios/armle/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/aarch64/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/aarch64/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/aarch64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/armbe/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/armbe/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/armbe/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/armle/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/armle/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/armle/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/mips64/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/mips64/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/mips64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/mipsbe/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/mipsbe/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/mipsbe/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/mipsle/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/mipsle/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/mipsle/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/ppc/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/ppc/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/ppc/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/ppc64le/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/ppc64le/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/ppc64le/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/ppce500v2/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/ppce500v2/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/ppce500v2/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/x64/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/x64/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/x64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/x86/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/x86/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/x86/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/zarch/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/zarch/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/zarch/meterpreter_reverse_tcp.rb
  modules/payloads/singles/osx/x64/meterpreter_reverse_http.rb
  modules/payloads/singles/osx/x64/meterpreter_reverse_https.rb
  modules/payloads/singles/osx/x64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/windows/encrypted_shell_reverse_tcp.rb
  modules/payloads/singles/windows/x64/encrypted_shell_reverse_tcp.rb
  modules/payloads/stagers/windows/encrypted_reverse_tcp.rb
  modules/payloads/stagers/windows/x64/encrypted_reverse_tcp.rb
Labels: bug

#12818 Adding Cable Haunt WebSocket DoS Module
  documentation/modules/auxiliary/dos/http/cable_haunt_websocket_dos.md
  documentation/modules/auxiliary/gather/chrome_debugger.md
  modules/auxiliary/dos/http/cable_haunt_websocket_dos.rb
  modules/auxiliary/gather/chrome_debugger.rb
Labels: docs, module
