Repository rapid7/metasploit-framework, pull requests merged in 2020-08, with the labels that each got.

#13903 Allow OpenVAS import to import vulns without references.
  lib/rex/parser/openvas_nokogiri.rb
Labels: enhancement

#13517 Add Documalis Free PDF Editor and Scanner Windows file format exploit
  documentation/modules/exploit/windows/fileformat/documalis_pdf_editor_and_scanner.md
  modules/exploits/windows/fileformat/documalis_pdf_editor_and_scanner.rb
Labels: docs, module

#13194 bloodhound cleanup
  data/post/SharpHound.exe
  data/post/powershell/SharpHound.ps1
  documentation/modules/post/windows/gather/bloodhound.md
  modules/post/windows/gather/bloodhound.rb
Labels: enhancement, module

#13936 Fix up ExploitError Module Inside exceptions.rb to Properly Propagate Errors to Users
  lib/msf/core/exceptions.rb
Labels: bug, library

#13904 Added Module: priviledged docker container escape
  documentation/modules/exploit/linux/local/docker_priviledged_container_escape.md
  modules/exploits/linux/local/docker_privileged_container_escape.rb
Labels: docs, module

#13939 Fix up lib/postgres/postgre-pr/message.rb's self.read function to Avoid nil Errors After Calling stream.read_exactly_n_bytes
  lib/postgres/postgres-pr/message.rb
Labels: bug, library

#13191 check_external_scripts.rb add more files to check
  data/jtr/dumb16.conf
  data/jtr/dumb32.conf
  data/jtr/dynamic_flat_sse_formats.conf
  data/jtr/john.conf
  data/post/SharpHound.exe
  data/post/powershell/SharpHound.ps1
  documentation/modules/exploit/multi/mysql/mysql_udf_payload.md
  tools/dev/check_external_scripts.rb
Labels: enhancement

#13897 Fix dangling reference issue in cve_2020_0688_service_tracing.rb and filesystem.rb
  lib/msf/core/post/windows/filesystem.rb
  modules/exploits/windows/local/cve_2020_0668_service_tracing.rb
Labels: bug, library, module

#13844 Add Linux Container Enumeration Module
  documentation/modules/post/linux/gather/enum_containers.md
  modules/post/linux/gather/enum_containers.rb
Labels: docs, module

#13940 Edit baldr_upload_exec.rb and Its Documentation For Compliance and To Remove Typos
  documentation/modules/exploit/multi/http/baldr_upload_exec.md
  modules/exploits/multi/http/baldr_upload_exec.rb
Labels: docs, module, rn-no-release-notes

#13945 Updates for PsExec documentation
  documentation/modules/exploit/windows/smb/psexec.md
Labels: docs, easy, module

#13949 Fix update mode in DBManager::Note#report_note
  lib/msf/core/db_manager/note.rb
Labels: bug, database

#13953 Skip CNAME records in DNS SRV parsing - Fix #13952
  lib/msf/core/exploit/dns/enumeration.rb
Labels: bug, library

#13860 Mikrotik processing
  documentation/modules/auxiliary/admin/networking/mikrotik_config.md
  documentation/modules/post/networking/gather/enum_mikrotik.md
  lib/metasploit/framework/login_scanner/ssh.rb
  lib/msf/core/auxiliary/juniper.rb
  lib/msf/core/auxiliary/mikrotik.rb
  lib/msf/core/auxiliary/mixins.rb
  lib/msf/core/module/platform.rb
  lib/msf/core/payload/uuid.rb
  modules/auxiliary/admin/networking/mikrotik_config.rb
  modules/post/networking/gather/enum_mikrotik.rb
  spec/lib/msf/core/auxiliary/juniper_spec.rb
  spec/lib/msf/core/auxiliary/mikrotik_spec.rb
Labels: docs, library, module, tests

#13957 allow dns server on different port
  modules/auxiliary/admin/dns/dyn_dns_update.rb
Labels: enhancement, module

#13877 Add a stale bot for dealing with stale issues
  .github/workflows/schedule-stale.yml
Labels: enhancement

#13975 Fixes for bug #13956
  lib/msf/core/exploit/dns/enumeration.rb
  modules/auxiliary/gather/enum_dns.rb
Labels: bug, library, module

#13238 Changed 'exit' to 'return' in bind_named_pipe handler
  lib/msf/core/handler/bind_named_pipe.rb
Labels: bug, library

#13965 Networking Scripts w/o DB (#13962)
  documentation/modules/auxiliary/admin/networking/brocade_config.md
  documentation/modules/auxiliary/admin/networking/juniper_config.md
  lib/msf/core/auxiliary/brocade.rb
  lib/msf/core/auxiliary/cisco.rb
  lib/msf/core/auxiliary/juniper.rb
  lib/msf/core/auxiliary/mikrotik.rb
  lib/msf/core/auxiliary/ubiquiti.rb
Labels: bug

#13988 Ignore tests when reloading files
  lib/msf/ui/console/command_dispatcher/developer.rb
Labels: enhancement

#13969 Fix Scanner stall for modules of non equal per host duration
  lib/msf/core/auxiliary/scanner.rb
Labels: enhancement, library

#13846 Nmap vulners script import
  lib/msf/core/db_manager/vuln.rb
  lib/rex/parser/nmap_nokogiri.rb
Labels: enhancement, feature

#13999 Backport miscellaneous fixes to my modules
  documentation/modules/exploit/windows/http/desktopcentral_deserialization.md
  documentation/modules/exploit/windows/http/plesk_mylittleadmin_viewstate.md
  documentation/modules/exploit/windows/misc/veeam_one_agent_deserialization.md
  modules/auxiliary/gather/nis_bootparamd_domain.rb
  modules/exploits/linux/http/cisco_ucs_cloupia_script_rce.rb
  modules/exploits/linux/http/f5_bigip_tmui_rce.rb
  modules/exploits/linux/http/netsweeper_webadmin_unixlogin.rb
  modules/exploits/linux/http/nexus_repo_manager_el_injection.rb
  modules/exploits/multi/http/liferay_java_unmarshalling.rb
  modules/exploits/unix/local/opensmtpd_oob_read_lpe.rb
  modules/exploits/unix/smtp/opensmtpd_mail_from_rce.rb
  modules/exploits/unix/webapp/thinkphp_rce.rb
  modules/exploits/unix/webapp/wp_infinitewp_auth_bypass.rb
  modules/exploits/windows/http/desktopcentral_deserialization.rb
  modules/exploits/windows/http/plesk_mylittleadmin_viewstate.rb
  modules/exploits/windows/misc/veeam_one_agent_deserialization.rb
Labels: bug, docs, module, rn-no-release-notes

#13911 Add module for an iPhone 4 iOS 7.1.2
  data/exploits/CVE-2016-4669/loader
  data/exploits/CVE-2016-4669/macho
  documentation/modules/exploit/apple_ios/browser/safari_jit.md
  external/source/exploits/CVE-2016-4669/Makefile
  external/source/exploits/CVE-2016-4669/__task.h
  external/source/exploits/CVE-2016-4669/loader.c
  external/source/exploits/CVE-2016-4669/macho.h
  external/source/exploits/CVE-2016-4669/macho.m
  external/source/exploits/CVE-2016-4669/macho_to_bin.py
  external/source/exploits/CVE-2016-4669/offsets.h
  external/source/exploits/CVE-2016-4669/shell.h
  external/source/exploits/CVE-2016-4669/shell.m
  external/source/exploits/CVE-2016-4669/task.c
  external/source/exploits/CVE-2016-4669/utils.h
  external/source/exploits/CVE-2016-4669/utils.m
  modules/exploits/apple_ios/browser/safari_jit.rb
Labels: module

#13968 [GSoC] Add a method for SQL injections where query output is not needed, and read_from_file support for MySQLi
  lib/msf/core/exploit/sqli/common.rb
  lib/msf/core/exploit/sqli/mysqli/common.rb
Labels: library, rn-no-release-notes

#13951 Update payload_generator.rb to properly check if payload_module is nil
  lib/msf/core/payload_generator.rb
Labels: bug, library

#14002 Fix payloads not being encoded in exploits when BadChars contains whitespace
  lib/msf/core/encoded_payload.rb
Labels: bug, library

#14003 Use WritableDir in execute_cmdstager for exploit/linux/http/f5_bigip_tmui_rce
  modules/exploits/linux/http/f5_bigip_tmui_rce.rb
Labels: bug, enhancement, module, rn-no-release-notes

#14000 Add Apache OFBiz XML-RPC Java deserialization (CVE-2020-9496)
  documentation/modules/exploit/linux/http/apache_ofbiz_deserialiation.md
  modules/exploits/linux/http/apache_ofbiz_deserialiation.rb
Labels: docs, feature, module

#13986 Add CVE-2020-16205 exploit for Geutebruck G-CAM
  documentation/modules/exploit/linux/http/geutebruck_testaction_exec.md
  modules/exploits/linux/http/geutebruck_testaction_exec.rb
Labels: docs, module

#14012 Remove no-op Nokogiri::XML pretty printing in exploit/linux/http/apache_ofbiz_deserialiation
  modules/exploits/linux/http/apache_ofbiz_deserialiation.rb
Labels: bug, easy, module, rn-no-release-notes

#14006 Update path in osx_enum to fix keychain download
  modules/post/osx/gather/enum_osx.rb
Labels: bug, module

#14007 Msf::Post::File.file_local_write: Use Rex::FileUtils.clean_path(local_file_name)
  lib/msf/core/post/file.rb
Labels: bug, library

#13989 TeamViewer URI SMB exploit (CVE-2020-13699)
  documentation/modules/auxiliary/server/teamviewer_uri_smb_redirect.md
  modules/auxiliary/server/teamviewer_uri_smb_redirect.rb
Labels: docs, module

#13974 Winrm login workaround
  lib/metasploit/framework/login_scanner/http.rb
  lib/metasploit/framework/login_scanner/winrm.rb
Labels: bug, library

#13961 Adds rhost url support behind a feature flag
  lib/msf/core/data_store.rb
  lib/msf/core/exploit/http/client.rb
  lib/msf/core/feature_manager.rb
  lib/msf/core/opt.rb
  lib/msf/core/opt_http_rhost_url.rb
  lib/msf/core/opt_raw.rb
  lib/msf/core/option_container.rb
  spec/lib/metasploit/framework/aws/client_spec.rb
  spec/lib/msf/core/exploit/http/jboss/base_spec.rb
  spec/lib/msf/core/exploit/http/jboss/bean_shell_scripts_spec.rb
  spec/lib/msf/core/exploit/http/jboss/bean_shell_spec.rb
  spec/lib/msf/core/exploit/http/jboss/deployment_file_repository_scripts_spec.rb
  spec/lib/msf/core/exploit/http/jboss/deployment_file_repository_spec.rb
  spec/lib/msf/core/exploit/http/joomla/base_spec.rb
  spec/lib/msf/core/exploit/http/joomla/version_spec.rb
  spec/lib/msf/core/exploit/http/wordpress/base_spec.rb
  spec/lib/msf/core/exploit/http/wordpress/login_spec.rb
  spec/lib/msf/core/exploit/http/wordpress/version_spec.rb
  spec/lib/msf/core/opt_http_rhost_url_spec.rb
  spec/tools/md5_lookup_spec.rb
  spec/tools/virustotal_spec.rb
Labels: delayed, enhancement, feature

#14016 post/osx/gather/enum_osx: Fix typos
  modules/post/osx/gather/enum_osx.rb
Labels: bug, module

#13913 [GSoC] Specs for the SQLi library
  spec/lib/msf/core/exploit/sqli/mysqli/mysqli_common_spec.rb
  spec/lib/msf/core/exploit/sqli/mysqli/mysqli_time_based_spec.rb
  spec/support/shared/examples/msf/core/exploit/sqli/sqli_common_spec.rb
  spec/support/shared/examples/msf/core/exploit/sqli/sqli_time_based_spec.rb
Labels: GSoC, library, tests

#14039 freebsd/local/rtld_execl_priv_esc: Use AutoCheck mixin and prefer cc over gcc
  modules/exploits/freebsd/local/rtld_execl_priv_esc.rb
Labels: enhancement, module

#14041 Fix features help command
  lib/msf/ui/console/command_dispatcher/core.rb
Labels: bug, rn-no-release-notes

#14045 Reload module after toggling features
  lib/msf/ui/console/command_dispatcher/core.rb
Labels: rn-enhancement

#14034 telpho10_credential_dump: Prevent traversal in untar
  modules/auxiliary/admin/http/telpho10_credential_dump.rb
Labels: bug, module

#14043 Fix jupyter-login when scanning non-Jupyter hosts
  modules/auxiliary/scanner/http/jupyter_login.rb
Labels: bug, easy, module

#14048 Allow scanner modules to skip hosts on fail_with
  lib/msf/core/auxiliary.rb
  lib/msf/core/auxiliary/scanner.rb
  modules/auxiliary/scanner/http/jupyter_login.rb
Labels: bug, library

#13906 Add generic LDAP hashdump module
  documentation/modules/auxiliary/gather/ldap_hashdump.md
  lib/metasploit/framework/hashes/identify.rb
  lib/metasploit/framework/password_crackers/cracker.rb
  lib/metasploit/framework/password_crackers/hashcat/formatter.rb
  lib/metasploit/framework/password_crackers/jtr/formatter.rb
  lib/msf/core/exploit/ldap.rb
  modules/auxiliary/gather/ldap_hashdump.rb
  modules/auxiliary/gather/vmware_vcenter_vmdir_ldap.rb
Labels: docs, feature, module, needs-linting

#14021 Use and semantics when searching for text
  lib/msf/core/modules/metadata/search.rb
  lib/msf/ui/console/command_dispatcher/modules.rb
  spec/lib/msf/core/modules/metadata/search_spec.rb
Labels: bug, enhancement, library, tests

#14040 Use CheckModule auxiliary/scanner/misc/java_rmi_server in exploit/multi/misc/java_rmi_server
  modules/auxiliary/scanner/misc/java_rmi_server.rb
  modules/exploits/multi/misc/java_rmi_server.rb
Labels: easy, enhancement, module

#14061 Reduce msfvenom run time by only loading relevant modules
  msfvenom
Labels: bug, enhancement, needs-pull-request-template

#14064 fixed module html references for info -d command
  lib/msf/util/document_generator/normalizer.rb
Labels: bug, docs, library

#14066 report `CheckCode` for `check` failure
  modules/auxiliary/gather/peplink_bauth_sqli.rb
Labels: bug, easy, rn-no-release-notes

#14065 switch to lazy loading faker
  lib/msf/core/cert_provider.rb
Labels: enhancement

#14072 Python3 / bash checks and improvements when using 'shell'
  lib/msf/base/sessions/command_shell.rb
  lib/msf/core/payload/python.rb
Labels: enhancement, library
