Repository rapid7/metasploit-framework, pull requests merged in 2020-10, with the labels that each got.

#14204 Update the module docs for CVE-2020-1472 (Zerologon)
  documentation/modules/auxiliary/admin/dcerpc/cve_2020_1472_zerologon.md
  modules/auxiliary/admin/dcerpc/cve_2020_1472_zerologon.rb
Labels: docs, easy, module

#14212 Fix invalid disclosure date formats
  modules/auxiliary/gather/pimcore_creds_sqli.rb
  modules/auxiliary/scanner/memcached/memcached_amp.rb
  modules/auxiliary/scanner/memcached/memcached_udp_version.rb
  modules/auxiliary/scanner/telnet/satel_cmd_exec.rb
  modules/exploits/linux/http/dcos_marathon.rb
  modules/exploits/linux/http/docker_daemon_tcp.rb
  modules/exploits/linux/http/nagios_xi_chained_rce_2_electric_boogaloo.rb
  modules/exploits/linux/http/rancher_server.rb
  modules/exploits/multi/http/mantisbt_manage_proj_page_rce.rb
  modules/exploits/multi/misc/erlang_cookie_rce.rb
  modules/exploits/unix/http/pfsense_graph_injection_exec.rb
Labels: easy, rn-no-release-notes

#14220 fix vulnerability spelling
  documentation/modules/exploit/multi/http/vbulletin_getindexablecontent.md
  documentation/modules/exploit/windows/local/cve_2020_0787_bits_arbitrary_file_move.md
  modules/exploits/multi/http/agent_tesla_panel_rce.rb
Labels: easy, rn-no-release-notes

#14190 Add the DOMAIN option to the CVE-2020-0688 Exploit
  documentation/modules/exploit/windows/http/exchange_ecp_viewstate.md
  modules/exploits/windows/http/exchange_ecp_viewstate.rb
Labels: enhancement, module

#14028 Fix msf6 TLV_TYPE_PIVOT_STAGE_DATA_SIZE pivoting error
  lib/rex/post/meterpreter/client_core.rb
  lib/rex/post/meterpreter/core_ids.rb
  lib/rex/post/meterpreter/pivot.rb
Labels: bug, confirmed, meterpreter

#14163 SAP Internet Graphics Server (IGS) XMLCHART XXE attack (CVE-2018-2392 and CVE-2018-2393)
  documentation/modules/auxiliary/admin/sap/sap_igs_xmlchart_xxe.md
  modules/auxiliary/admin/sap/sap_igs_xmlchart_xxe.rb
Labels: docs, module

#14070 [GSOC] Tab-completion improved for module OPTIONS not available
  lib/msf/ui/console/command_dispatcher/core.rb
Labels: enhancement, library, usability

#14226 convert myworkspace.id to myworkspace_id for no db compat
  lib/msf/core/auxiliary/arista.rb
  lib/msf/core/auxiliary/brocade.rb
  lib/msf/core/auxiliary/cisco.rb
  lib/msf/core/auxiliary/f5.rb
  lib/msf/core/auxiliary/juniper.rb
  lib/msf/core/auxiliary/mikrotik.rb
  lib/msf/core/auxiliary/ubiquiti.rb
  modules/post/multi/gather/enum_hexchat.rb
  modules/post/solaris/escalate/srsexec_readline.rb
  modules/post/windows/escalate/golden_ticket.rb
Labels: bug, rn-fix

#14230 Update metasploit-payloads gem to 2.0.16
  Gemfile.lock
  metasploit-framework.gemspec
Labels: payload

#14238 Update sap_service_discovery.rb
  modules/auxiliary/scanner/sap/sap_service_discovery.rb
Labels: enhancement, module, rn-enhancement

#14233 Always show module actions within the info command
  lib/msf/base/serializer/readable_text.rb
Labels: bug

#14242 Remove modules whose deprecation date has past
  modules/auxiliary/admin/smb/psexec_command.rb
  modules/auxiliary/scanner/smb/smb1.rb
  modules/auxiliary/scanner/smb/smb2.rb
  modules/exploits/windows/smb/psexec_psh.rb
Labels: code quality, easy, module

#14235 Bugfix: Don't skip dumping RID 1001's hash with smart_hashdump
  documentation/modules/post/windows/gather/smart_hashdump.md
  modules/post/windows/gather/smart_hashdump.rb
Labels: bug, docs, module

#14243 Fix up disclosure date for zentao_pro_rce
  modules/exploits/windows/http/zentao_pro_rce.rb
Labels: bug, easy, module

#13817 CVE-2019-1458 chrome sandbox escape
  data/exploits/CVE-2019-1458/exploit.dll
  documentation/modules/exploit/multi/browser/chrome_object_create.md
  documentation/modules/exploit/windows/local/cve_2019_1458_wizardopium.md
  external/source/exploits/CVE-2019-1458/CVE-2019-1458.sln
  external/source/exploits/CVE-2019-1458/CVE-2019-1458.vcxproj
  external/source/exploits/CVE-2019-1458/LICENSE
  external/source/exploits/CVE-2019-1458/Makefile
  external/source/exploits/CVE-2019-1458/README.md
  external/source/exploits/CVE-2019-1458/dllmain.cpp
  external/source/exploits/CVE-2019-1458/exploit.cpp
  external/source/exploits/CVE-2019-1458/shellcode.asm
  lib/msf/core/payload/windows/x64/addr_loader.rb
  modules/exploits/multi/browser/chrome_object_create.rb
  modules/exploits/windows/local/cve_2019_1458_wizardopium.rb
Labels: docs, module

#14240 Add tab completion for run command
  lib/msf/ui/console/command_dispatcher.rb
  lib/msf/ui/console/command_dispatcher/auxiliary.rb
  lib/msf/ui/console/command_dispatcher/core.rb
  lib/msf/ui/console/command_dispatcher/evasion.rb
  lib/msf/ui/console/command_dispatcher/exploit.rb
  lib/msf/ui/console/command_dispatcher/payload.rb
  lib/msf/ui/console/command_dispatcher/post.rb
  lib/msf/ui/console/module_option_tab_completion.rb
  lib/rex/ui/text/dispatcher_shell.rb
Labels: enhancement

#14258 docs and rubocop for several post/windows/gather modules
  documentation/modules/post/windows/gather/credentials/windows_autologin.md
  documentation/modules/post/windows/gather/dnscache_dump.md
  documentation/modules/post/windows/gather/enum_ad_groups.md
  documentation/modules/post/windows/gather/enum_domain.md
  documentation/modules/post/windows/gather/enum_domain_group_users.md
  documentation/modules/post/windows/gather/enum_hostfile.md
  documentation/modules/post/windows/gather/lsa_secrets.md
  modules/post/windows/gather/dnscache_dump.rb
  modules/post/windows/gather/enum_domain_group_users.rb
  modules/post/windows/gather/enum_hostfile.rb
  modules/post/windows/gather/lsa_secrets.rb
Labels: bug, docs

#14285 Update documentation/modules/exploit/windows/http/sharepoint_ssi_viewstate.md
  documentation/modules/exploit/windows/http/sharepoint_ssi_viewstate.md
  modules/exploits/windows/http/sharepoint_ssi_viewstate.rb
Labels: docs, rn-no-release-notes

#14179 Add Login to User with Su on Linux / Unix Systems
  documentation/modules/exploit/linux/local/su_login.md
  modules/exploits/linux/local/su_login.rb
Labels: docs, module

#14288 Parameterise args to popen3()
  lib/msf/core/payload/apk.rb
Labels: bug, library

#14229 Add exploit for Telerik UI ASP.NET AJAX RadAsyncUpload (RAU) Deserialization
  data/templates/src/pe/dll/template.c
  data/templates/src/pe/dll/template.def
  data/templates/src/pe/dll/template.h
  data/templates/src/pe/dll/template.rc
  data/templates/src/pe/dll_mixed_mode/README.md
  data/templates/src/pe/dll_mixed_mode/build.bat
  data/templates/src/pe/dll_mixed_mode/template.cpp
  data/templates/template_x64_windows_mixed_mode.dll
  data/templates/template_x86_windows_mixed_mode.dll
  data/wordlists/telerik_ui_asp_net_ajax_versions.txt
  documentation/modules/exploit/windows/http/telerik_rau_deserialization.md
  lib/msf/util/dot_net_deserialization/assemblies.rb
  lib/msf/util/exe.rb
  modules/exploits/windows/http/telerik_rau_deserialization.rb
Labels: module

#14289 Add version check to exploit/windows/http/exchange_ecp_dlp_policy
  documentation/modules/exploit/windows/http/exchange_ecp_dlp_policy.md
  modules/exploits/windows/http/exchange_ecp_dlp_policy.rb
  modules/exploits/windows/http/sharepoint_ssi_viewstate.rb
Labels: docs, enhancement, module

#14296 move mercury_login.md to docs folder
  documentation/modules/exploit/windows/imap/mercury_login.md
Labels: docs, easy

#14300 Fixes and updates for the DRuby RCE module
  modules/exploits/linux/misc/drb_remote_codeexec.rb
Labels: bug, module

#14279 Fix incorrect offset in BPF sign extension LPE
  data/exploits/cve-2017-16995/exploit.c
  data/exploits/cve-2017-16995/exploit.out
Labels: bug, module

#14307 remove .keep relices from svn to git conversion 9yrs ago
  modules/exploits/multi/vnc/.keep
  scripts/resource/.keep
Labels: easy, rn-no-release-notes

#14311 Update enum_putty_saved_sessions.rb
  modules/post/windows/gather/enum_putty_saved_sessions.rb
Labels: enhancement, module, rn-enhancement

#14313 Add service stub encoder validation
  modules/exploits/windows/smb/ms17_010_psexec.rb
  modules/exploits/windows/smb/psexec.rb
Labels: bug, module

#14250 Fix up the DNS enumeration library so that AXFR records aren't displayed with stray [ and ] characters
  lib/msf/core/exploit/dns/enumeration.rb
  modules/auxiliary/gather/enum_dns.rb
Labels: bug, library

#14225 rescue SSLError in HTTP scanner check_setup
  lib/metasploit/framework/login_scanner/chef_webui.rb
  lib/metasploit/framework/login_scanner/glassfish.rb
  lib/metasploit/framework/login_scanner/http.rb
  lib/metasploit/framework/login_scanner/zabbix.rb
Labels: bug

#14312 Update debug command connection name logging
  lib/msf/ui/debug.rb
  spec/lib/msf/debug_spec.rb
Labels: enhancement, rn-no-release-notes

#14282 More descript error logging for external modules
  lib/msf/core/modules/external/shim.rb
  lib/msf/core/modules/loader/base.rb
Labels: library
