Repository rapid7/metasploit-framework, pull requests merged in 2021-08, with the labels that each got.

#15461 GitHub Actions: Termux issue label: auto close issue
  .github/workflows/labels.yml
Labels: termux

#15508 Update metasploit payloads gem to 2.0.50
  Gemfile.lock
  LICENSE_GEMS
  metasploit-framework.gemspec
Labels: rn-no-release-notes

#15503 Fix for file clean up in the Cisco Hyperflex file upload RCE module
  modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
Labels: bug, module

#15518 Bump rex-socket version to 0.1.32
  Gemfile.lock
Labels: rn-no-release-notes

#15327 Update rpc analyze command to support latest functionality
  lib/msf/core/analyze/result.rb
  lib/msf/core/rpc/v10/rpc_db.rb
  spec/api/json_rpc_spec.rb
  spec/file_fixtures/json_rpc/auxiliary/scanner/ssl/openssl_heartbleed.rb
  spec/file_fixtures/json_rpc/exploits/windows/smb/ms17_010_eternalblue.rb
  tools/dev/msfdb_ws
Labels: rn-enhancement

#15533 Update json rpc spec tests
  spec/api/json_rpc_spec.rb
Labels: rn-no-release-notes

#15536 Fix HiveNightmare Option Reference
  modules/post/windows/gather/credentials/windows_sam_hivenightmare.rb
Labels: module, bug, easy

#15520 Canon TR150 Print Driver Local Privilege Escalation
  documentation/modules/exploit/windows/local/canon_driver_privesc.md
  modules/exploits/windows/local/canon_driver_privesc.rb
Labels: module, docs

#15519 Lexmark Universal Print Driver Local Privilege Escalation
  documentation/modules/exploit/windows/local/lexmark_driver_privesc.md
  modules/exploits/windows/local/lexmark_driver_privesc.rb
Labels: module, docs

#15523 Add missing command names to session compatibility warning
  lib/msf/core/post_mixin.rb
Labels: library, enhancement

#15535 Update psexec module to use SMBSHARE option name for consistency
  documentation/modules/exploit/windows/smb/psexec.md
  modules/exploits/windows/smb/psexec.rb
Labels: module, enhancement, rn-enhancement, code quality

#15501 Push up working CVE-2019-11580 exploit and associated documentation
  documentation/modules/exploit/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.md
  modules/exploits/multi/http/atlassian_crowd_pdkinstall_plugin_upload_rce.rb
Labels: module, docs

#15544 Bump rex-encoder in Gemfile.lock to 0.1.6
  Gemfile.lock
Labels: rn-no-release-notes

#15545 Bump rex-bin-tools to 0.1.8
  Gemfile.lock
Labels: rn-no-release-notes

#15547 Bump rex-text to 0.2.36
  Gemfile.lock
Labels: rn-no-release-notes

#15303 Fix `dir` method for windows shell sessions
  lib/msf/core/post/file.rb
Labels: rn-fix, powershell

#15540 Add option for running `cmd_execute` in a subshell
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/sys.rb
Labels: bug, enhancement

#15525 Add Lucee Administrator CVE-2021-21307 exploit
  documentation/modules/exploit/linux/http/lucee_admin_imgprocess_file_write.md
  modules/exploits/linux/http/lucee_admin_imgprocess_file_write.rb
Labels: module, docs

#15546 Fix #15480, fix IgnoreUnknownPayloads for stageless reverse_http payloads
  lib/msf/core/handler/reverse_http.rb
  lib/msf/core/payload/transport_config.rb
  modules/payloads/singles/android/meterpreter_reverse_http.rb
  modules/payloads/singles/android/meterpreter_reverse_https.rb
Labels: bug

#15570 Fix smb enum gpp module
  documentation/modules/auxiliary/scanner/smb/smb_enum_gpp.md
  modules/auxiliary/scanner/smb/smb_enum_gpp.rb
Labels: module, bug

#15332 fix a localization issue and some other minor issues in `rename_file` method
  lib/msf/core/post/file.rb
Labels: library, GSoC, powershell

#15556 Add shell support to enum_unattended module
  modules/post/windows/gather/enum_unattend.rb
Labels: module, enhancement, GSoC

#15575 Update Gemfile.lock
  Gemfile.lock
Labels: rn-no-release-notes

#15578 Remove dead cisco_rv130_rmi_rce documentation
  documentation/modules/exploit/linux/http/cisco_rv130_rmi_rce.md
Labels: docs, bug, rn-no-release-notes

#15584 update wordpress themes and plugins list
  data/wordlists/wp-plugins.txt
  data/wordlists/wp-themes.txt
Labels: enhancement, easy

#15477 Add support for reading binary files for powershell session types
  lib/msf/core/post/file.rb
Labels: GSoC

#15375 Fix LDAP hashdump crash on null char
  lib/metasploit/framework/hashes/identify.rb
  lib/metasploit/framework/password_crackers/cracker.rb
  lib/metasploit/framework/password_crackers/hashcat/formatter.rb
  lib/metasploit/framework/password_crackers/jtr/formatter.rb
  modules/auxiliary/gather/ldap_hashdump.rb
Labels: module, bug, rn-fix

#15573 Default `simplify_module` to not load saved config
  lib/msf/base/simple/auxiliary.rb
  lib/msf/base/simple/evasion.rb
  lib/msf/base/simple/exploit.rb
  lib/msf/base/simple/framework.rb
  lib/msf/base/simple/post.rb
  lib/msf/ui/console/module_command_dispatcher.rb
  spec/lib/msf/ui/console/command_dispatcher/auxiliary_spec.rb
  spec/lib/msf/ui/console/command_dispatcher/exploit_spec.rb
Labels: library, bug

#15567 Add in Exploit for CVE-2021-3490 on Ubuntu 20.04, Ubuntu 20.10, Ubuntu 21.04, and Fedora Using chompie1337's PoC
  data/exploits/cve-2021-3490/fedora-5-10.bin
  data/exploits/cve-2021-3490/fedora-5-11.bin
  data/exploits/cve-2021-3490/fedora-5-7.bin
  data/exploits/cve-2021-3490/fedora-5-8.bin
  data/exploits/cve-2021-3490/fedora-5-9.bin
  data/exploits/cve-2021-3490/groovy.bin
  data/exploits/cve-2021-3490/hirsute.bin
  documentation/modules/exploit/linux/local/cve_2021_3490_ebpf_alu32_bounds_check_lpe.md
  external/source/exploits/CVE-2021-3490/Linux_LPE_eBPF_CVE-2021-3490/Makefile
  external/source/exploits/CVE-2021-3490/Linux_LPE_eBPF_CVE-2021-3490/README.md
  external/source/exploits/CVE-2021-3490/Linux_LPE_eBPF_CVE-2021-3490/bpf.c
  external/source/exploits/CVE-2021-3490/Linux_LPE_eBPF_CVE-2021-3490/exploit.c
  external/source/exploits/CVE-2021-3490/Linux_LPE_eBPF_CVE-2021-3490/include/bpf_defs.h
  external/source/exploits/CVE-2021-3490/Linux_LPE_eBPF_CVE-2021-3490/include/exploit_configs.h
  external/source/exploits/CVE-2021-3490/Linux_LPE_eBPF_CVE-2021-3490/include/kernel_defs.h
  external/source/exploits/CVE-2021-3490/Linux_LPE_eBPF_CVE-2021-3490/include/kmem_search.h
  external/source/exploits/CVE-2021-3490/Linux_LPE_eBPF_CVE-2021-3490/kmem_search.c
  modules/exploits/linux/local/cve_2021_3490_ebpf_alu32_bounds_check_lpe.rb
Labels: module, docs
