Repository rapid7/metasploit-framework, pull requests merged in 2021-09, with the labels that each got.

#15537 Add support for ruby 3
  .github/workflows/verify.yml
  Gemfile.lock
  lib/metasploit/framework/aws/client.rb
  lib/msf/core/auxiliary/ubiquiti.rb
  lib/msf/core/cert_provider.rb
  lib/msf/core/payload/android.rb
  lib/msf/core/post/windows/priv.rb
  lib/msf/core/web_services/http_db_manager_service.rb
  lib/rex/crypto/aes256.rb
  lib/rex/parser/net_sarang.rb
  lib/rex/proto/ntlm/crypt.rb
  lib/rex/proto/rfb/cipher.rb
  metasploit-framework.gemspec
  modules/auxiliary/gather/windows_secrets_dump.rb
  modules/auxiliary/server/openssl_altchainsforgery_mitm_proxy.rb
  modules/auxiliary/server/openssl_heartbeat_client_memory.rb
  modules/exploits/linux/http/empire_skywalker.rb
  modules/exploits/linux/http/github_enterprise_secret.rb
  modules/exploits/windows/backupexec/ssl_uaf.rb
  modules/post/multi/gather/lastpass_creds.rb
  modules/post/multi/gather/remmina_creds.rb
  modules/post/windows/gather/cachedump.rb
  modules/post/windows/gather/credentials/coreftp.rb
  modules/post/windows/gather/credentials/epo_sql.rb
  modules/post/windows/gather/credentials/securecrt.rb
  modules/post/windows/gather/credentials/smartermail.rb
  modules/post/windows/gather/hashdump.rb
  modules/post/windows/gather/smart_hashdump.rb
  modules/post/windows/manage/hashcarve.rb
  spec/lib/msf/core/exploit/remote/remote/http/http_cookie_jar_spec.rb
Labels: library, enhancement, rn-enhancement

#15629 exclude full json rpc path from zeitwerk
  lib/msf/core/rpc/json/rpc_command_factory.rb
  lib/msf_autoload.rb
Labels: library, bug

#15628 Fix #15615, refresh session info after running meterpreter > sysinfo
  lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/sys.rb
Labels: meterpreter, bug, rn-fix

#15603 Add Geutebruck CVE_2021_335XX command injection module
  documentation/modules/exploit/linux/http/geutebruck_cmdinject_cve_2021_335xx.md
  modules/exploits/linux/http/geutebruck_cmdinject_cve_2021_335xx.rb
Labels: module, docs

#15623 Creds command improvements
  lib/metasploit/framework/password_crackers/hashcat/formatter.rb
  lib/metasploit/framework/password_crackers/jtr/formatter.rb
  lib/msf/core/db_manager/cred.rb
  lib/msf/ui/console/command_dispatcher/creds.rb
  spec/lib/msf/ui/console/command_dispatcher/creds_spec.rb
Labels: library, enhancement

#15253 Add http/smb/mysql/postgres/ssh support in rhosts option
  lib/msf/base/simple/auxiliary.rb
  lib/msf/base/simple/evasion.rb
  lib/msf/base/simple/exploit.rb
  lib/msf/base/simple/post.rb
  lib/msf/core/auxiliary/drdos.rb
  lib/msf/core/auxiliary/scanner.rb
  lib/msf/core/data_store.rb
  lib/msf/core/exception.rb
  lib/msf/core/exploit.rb
  lib/msf/core/exploit/brute.rb
  lib/msf/core/exploit/remote/browser_exploit_server.rb
  lib/msf/core/exploit/remote/smb/client/local_paths.rb
  lib/msf/core/exploit/remote/smb/client/remote_paths.rb
  lib/msf/core/opt.rb
  lib/msf/core/opt_rhosts.rb
  lib/msf/core/option_container.rb
  lib/msf/core/rhosts_walker.rb
  lib/msf/ui/console/command_dispatcher/auxiliary.rb
  lib/msf/ui/console/command_dispatcher/core.rb
  lib/msf/ui/console/command_dispatcher/exploit.rb
  lib/msf/ui/console/command_dispatcher/post.rb
  lib/msf/ui/console/module_action_commands.rb
  lib/msf/ui/console/module_argument_parsing.rb
  lib/msf/ui/console/module_command_dispatcher.rb
  lib/msf/ui/formatter.rb
  lib/msf/ui/formatter/option_validate_error.rb
  modules/auxiliary/admin/smb/delete_file.rb
  modules/auxiliary/admin/smb/download_file.rb
  modules/auxiliary/admin/smb/upload_file.rb
  modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb
  modules/exploits/unix/webapp/thinkphp_rce.rb
  modules/exploits/windows/smb/ms17_010_psexec.rb
  modules/exploits/windows/smb/psexec.rb
  spec/file_fixtures/modules/payloads/singles/generic/no_session_payload.rb
  spec/lib/msf/core/exploit/smb/client/local_paths_spec.rb
  spec/lib/msf/core/exploit/smb/client/remote_paths_spec.rb
  spec/lib/msf/core/opt_rhosts_spec.rb
  spec/lib/msf/core/opt_spec.rb
  spec/lib/msf/core/option_container_spec.rb
  spec/lib/msf/core/rhosts_walker_spec.rb
  spec/lib/msf/ui/console/command_dispatcher/auxiliary_spec.rb
  spec/lib/msf/ui/console/command_dispatcher/exploit_spec.rb
  spec/msf/core/exception_spec.rb
  spec/msf/ui/console/module_argument_parsing_spec.rb
  spec/support/shared/contexts/msf/ui_driver.rb
Labels: enhancement, rn-enhancement, usability

#15522 Meterpreter interactive shell
  lib/msf/core/feature_manager.rb
  lib/rex/post/hwbridge/ui/console.rb
  lib/rex/post/meterpreter/channel.rb
  lib/rex/post/meterpreter/extensions/stdapi/command_ids.rb
  lib/rex/post/meterpreter/extensions/stdapi/tlv.rb
  lib/rex/post/meterpreter/ui/console.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/sys.rb
  lib/rex/post/meterpreter/ui/console/interactive_channel.rb
  lib/rex/ui/interactive.rb
  lib/rex/ui/text/input/readline.rb
Labels: library, enhancement

#15639 Fix typo in rename_file preventing Linux systems from renaming files
  lib/msf/core/post/file.rb
Labels: library, bug, easy

#15640 Add missing python3 shebang
  modules/auxiliary/gather/office365userenum.py
Labels: rn-fix

#15627 Update some post libs to use library methods defined in `file.rb`
  lib/msf/core/post/linux/kernel.rb
  lib/msf/core/post/linux/system.rb
Labels: library, enhancement

#15611 ProxyShell Improvements
  data/exploits/proxyshell/soap_autodiscover.xml.erb
  data/exploits/proxyshell/soap_getemails.xml.erb
  documentation/modules/exploit/windows/http/exchange_proxyshell_rce.md
  modules/exploits/windows/http/exchange_proxyshell_rce.rb
Labels: module, enhancement, rn-modules

#15651 Remove ruby3 label automation
  .github/workflows/labels.yml
Labels: rn-no-release-notes, ruby-3.0.0

#15634 Add DFLAG_BIG_CREATION to capability flags for erlang_cookie_rce.rb
  modules/exploits/multi/misc/erlang_cookie_rce.rb
Labels: rn-fix

#15655 Cleanup rbmysql options
  lib/rbmysql/protocol.rb
  modules/auxiliary/scanner/mysql/mysql_hashdump.rb
Labels: library, bug

#15645 Add Atlassian Confluence CVE-2021-26084 exploit
  documentation/modules/exploit/linux/http/atlassian_confluence_webwork_ognl_injection.md
  modules/exploits/linux/http/atlassian_confluence_webwork_ognl_injection.rb
Labels: module, docs

#15654 Fully receive stage - Encrypted Payloads
  lib/msf/core/payload/windows/encrypted_reverse_tcp.rb
Labels: bug, easy

#15278 Add OUTFILE and DATABASE options to zoomeye_search and enhance output saved
  documentation/modules/auxiliary/gather/zoomeye_search.md
  modules/auxiliary/gather/zoomeye_search.rb
Labels: module, docs, enhancement

#15671 Remove activemq assertion from integration tests
  spec/api/json_rpc_spec.rb
Labels: rn-no-release-notes

#15601 Add Geutebruck Post Exploitation Module
  documentation/modules/post/linux/manage/geutebruck_post_exp.md
  modules/post/linux/manage/geutebruck_post_exp.rb
Labels: module, docs

#15658 Add module for CVE-2021-32682
  documentation/modules/exploit/linux/http/elfinder_archive_cmd_injection.md
  modules/exploits/linux/http/elfinder_archive_cmd_injection.rb
Labels: module, docs

#15624 Add module for CVE-2020-27955
  documentation/modules/exploit/windows/http/git_lfs_rce.md
  lib/msf/core/constants.rb
  lib/msf/core/exploit/remote/http_server.rb
  modules/exploits/windows/http/git_lfs_rce.rb
Labels: module, library, docs

#15604 Add CVE-2021-33549 exploit for Geutebruck G-CAM
  documentation/modules/exploit/linux/http/geutebruck_instantrec_bof.md
  modules/exploits/linux/http/geutebruck_instantrec_bof.rb
Labels: module, docs

#15666 fix #15662, fix meterpreter download of utf8 filenames
  lib/rex/post/meterpreter/extensions/stdapi/fs/file.rb
Labels: meterpreter, bug, easy, rn-fix, ascii-utf8-issues

#15679 bug fix for tomcat_mgr_upload module not undeploying app after exploit
  modules/exploits/multi/http/tomcat_mgr_upload.rb
Labels: bug, easy

#15684 Improve interactive shell performance for pasted user input
  lib/rex/post/meterpreter/ui/console/interactive_channel.rb
  lib/rex/ui/text/input/readline.rb
Labels: rn-enhancement

#15695 Fix crash and add additional logging to the setuid nmap module
  lib/msf/core/post/file.rb
  modules/exploits/unix/local/setuid_nmap.rb
Labels: rn-fix

#15632 Winrm improvements
  documentation/modules/auxiliary/scanner/winrm/winrm_cmd.md
  documentation/modules/auxiliary/scanner/winrm/winrm_login.md
  lib/msf/base/sessions/command_shell.rb
  lib/msf/base/sessions/winrm_command_shell.rb
  lib/msf/core/session/interactive.rb
  lib/msf/core/session/provider/single_command_shell.rb
  lib/msf/core/session_manager.rb
  lib/net/winrm/connection.rb
  lib/net/winrm/ctrl_c.rb
  lib/net/winrm/receive_response_reader.rb
  lib/net/winrm/rex_http_transport.rb
  lib/net/winrm/stdin_shell.rb
  lib/rex/proto/http/client.rb
  modules/auxiliary/scanner/winrm/winrm_cmd.rb
  modules/auxiliary/scanner/winrm/winrm_login.rb
Labels: library, feature, enhancement

#15696 Display computer information gleaned from NTLM handshake in RDP
  lib/msf/core/exploit/remote/rdp.rb
  modules/auxiliary/scanner/rdp/rdp_scanner.rb
Labels: module, enhancement, rn-enhancement

#15600 Fixes issues with encrypted payloads by moving session bootstrap logic
  lib/msf/base/serializer/readable_text.rb
  lib/msf/base/sessions/command_shell.rb
  lib/msf/base/sessions/encrypted_shell.rb
  lib/msf/core/framework.rb
  lib/msf/core/payload/windows/encrypted_reverse_tcp.rb
Labels: bug

#15686 OptRegExp default value as string representation
  modules/exploits/linux/misc/saltstack_salt_unauth_rce.rb
Labels: bug, rn-fix

#15677 Add in Module for Netgear D7000 Authentication Bypass
  documentation/modules/auxiliary/admin/http/netgear_pnpx_getsharefolderlist_auth_bypass.md
  modules/auxiliary/admin/http/netgear_pnpx_getsharefolderlist_auth_bypass.rb
Labels: module, docs

#15594 only scan exploitable wordpress things
  data/wordlists/wp-exploitable-plugins.txt
  data/wordlists/wp-exploitable-themes.txt
  data/wordlists/wp-plugins.txt
  data/wordlists/wp-themes.txt
  documentation/modules/auxiliary/scanner/http/wordpress_scanner.md
  modules/auxiliary/scanner/http/wordpress_scanner.rb
  tools/dev/update_wordpress_vulnerabilities.rb
Labels: module, docs, enhancement, rn-enhancement

#15713 Update references to railgun to be consistent
  lib/rex/post/meterpreter/extensions/stdapi/railgun/util.rb
  modules/post/multi/gather/lastpass_creds.rb
  modules/post/windows/gather/credentials/enum_picasa_pwds.rb
  modules/post/windows/gather/credentials/outlook.rb
  modules/post/windows/gather/credentials/pulse_secure.rb
  modules/post/windows/gather/credentials/rdc_manager_creds.rb
  modules/post/windows/gather/credentials/skype.rb
  modules/post/windows/gather/credentials/tortoisesvn.rb
  modules/post/windows/gather/enum_chrome.rb
  modules/post/windows/gather/enum_ie.rb
  modules/post/windows/gather/memory_dump.rb
  modules/post/windows/gather/memory_grep.rb
  scripts/meterpreter/enum_chrome.rb
Labels: rn-no-release-notes

#15669 Add meterpreter compatibility metadata to screenshare module
  lib/msf/core/exploit/file_dropper.rb
  lib/msf/core/post_mixin.rb
  modules/post/multi/manage/screenshare.rb
Labels: module, library, enhancement

#15703 Fix Compiling Encrypted Payloads on MacOS
  lib/metasploit/framework/compiler/mingw.rb
  lib/msf/core/payload/windows/encrypted_payload_opts.rb
  lib/msf/core/payload/windows/encrypted_reverse_tcp.rb
Labels: bug

#15200 PackRat post exploitation modules based on a common mixin
  documentation/modules/post/windows/gather/credentials/aim.md
  documentation/modules/post/windows/gather/credentials/chrome.md
  documentation/modules/post/windows/gather/credentials/comodo.md
  documentation/modules/post/windows/gather/credentials/coolnovo.md
  documentation/modules/post/windows/gather/credentials/digsby.md
  documentation/modules/post/windows/gather/credentials/flock.md
  documentation/modules/post/windows/gather/credentials/gadugadu.md
  documentation/modules/post/windows/gather/credentials/icq.md
  documentation/modules/post/windows/gather/credentials/ie.md
  documentation/modules/post/windows/gather/credentials/incredimail.md
  documentation/modules/post/windows/gather/credentials/kakaotalk.md
  documentation/modules/post/windows/gather/credentials/kmeleon.md
  documentation/modules/post/windows/gather/credentials/line.md
  documentation/modules/post/windows/gather/credentials/maxthon.md
  documentation/modules/post/windows/gather/credentials/miranda.md
  documentation/modules/post/windows/gather/credentials/opera.md
  documentation/modules/post/windows/gather/credentials/operamail.md
  documentation/modules/post/windows/gather/credentials/postbox.md
  documentation/modules/post/windows/gather/credentials/qq.md
  documentation/modules/post/windows/gather/credentials/safari.md
  documentation/modules/post/windows/gather/credentials/seamonkey.md
  documentation/modules/post/windows/gather/credentials/srware.md
  documentation/modules/post/windows/gather/credentials/tango.md
  documentation/modules/post/windows/gather/credentials/thunderbird.md
  documentation/modules/post/windows/gather/credentials/tlen.md
  documentation/modules/post/windows/gather/credentials/viber.md
  documentation/modules/post/windows/gather/credentials/windowslivemail.md
  documentation/modules/post/windows/gather/credentials/xchat.md
  lib/msf/core/post/windows/packrat.rb
  modules/post/windows/gather/credentials/aim.rb
  modules/post/windows/gather/credentials/chrome.rb
  modules/post/windows/gather/credentials/comodo.rb
  modules/post/windows/gather/credentials/coolnovo.rb
  modules/post/windows/gather/credentials/digsby.rb
  modules/post/windows/gather/credentials/flock.rb
  modules/post/windows/gather/credentials/gadugadu.rb
  modules/post/windows/gather/credentials/icq.rb
  modules/post/windows/gather/credentials/ie.rb
  modules/post/windows/gather/credentials/incredimail.rb
  modules/post/windows/gather/credentials/kakaotalk.rb
  modules/post/windows/gather/credentials/kmeleon.rb
  modules/post/windows/gather/credentials/line.rb
  modules/post/windows/gather/credentials/maxthon.rb
  modules/post/windows/gather/credentials/miranda.rb
  modules/post/windows/gather/credentials/opera.rb
  modules/post/windows/gather/credentials/operamail.rb
  modules/post/windows/gather/credentials/postbox.rb
  modules/post/windows/gather/credentials/qq.rb
  modules/post/windows/gather/credentials/safari.rb
  modules/post/windows/gather/credentials/seamonkey.rb
  modules/post/windows/gather/credentials/srware.rb
  modules/post/windows/gather/credentials/tango.rb
  modules/post/windows/gather/credentials/thunderbird.rb
  modules/post/windows/gather/credentials/tlen.rb
  modules/post/windows/gather/credentials/viber.rb
  modules/post/windows/gather/credentials/windowslivemail.rb
  modules/post/windows/gather/credentials/xchat.rb
Labels: module, rn-modules, needs-linting

#15707 Add ECU Hard Reset for hwbridge
  documentation/modules/post/hardware/automotive/ecu_hard_reset.md
  modules/post/hardware/automotive/ecu_hard_reset.rb
Labels: needs-docs, needs-linting
