Repository rapid7/metasploit-framework, pull requests merged in 2021-04, with the labels that each got.

#14935 Add F5 iControl REST CVE-2021-22986 exploit
  documentation/modules/exploit/linux/http/f5_icontrol_rest_ssrf_rce.md
  modules/exploits/linux/http/f5_icontrol_rest_ssrf_rce.rb
Labels: docs, feature, hotness, module

#14813 dupscts_bof: Add additional targets and auto targeting
  documentation/modules/exploit/windows/http/dupscts_bof.md
  modules/exploits/windows/http/dupscts_bof.rb
Labels: enhancement, module, rn-modules

#14988 fix rails 5 bug for password cracker custom_wordlists
  lib/metasploit/framework/password_crackers/wordlist.rb
Labels: bug

#14975 Fix #14974, fix uninitialized constant in cve_2020_1054_drawiconex_lpe
  modules/exploits/windows/local/cve_2020_1054_drawiconex_lpe.rb
Labels: bug, module

#14991 Updated calls to describe method to fix crashes
  modules/auxiliary/fuzzers/ntp/ntp_protocol_fuzzer.rb
Labels: bug

#15008 Pin metasploit gems in preparation for rails 6
  Gemfile.lock
  metasploit-framework.gemspec
Labels: rn-no-release-notes, ruby-3.0.0

#14998 Change CVE reference from CVE Details to NVD
  documentation/modules/exploit/linux/http/rconfig_ajaxarchivefiles_rce.md
  documentation/modules/exploit/windows/misc/crosschex_device_bof.md
  lib/msf/core/module/reference.rb
  modules/exploits/windows/browser/ms05_054_onload.rb
  tools/modules/module_reference.rb
Labels: bug, easy, library

#14987 Update RbMysql to the most recent version
  lib/metasploit/framework/login_scanner/mysql.rb
  lib/msf/core/exploit/remote/mysql.rb
  lib/rbmysql.rb
  lib/rbmysql/README
  lib/rbmysql/charset.rb
  lib/rbmysql/compat.rb
  lib/rbmysql/constants.rb
  lib/rbmysql/error.rb
  lib/rbmysql/packet.rb
  lib/rbmysql/protocol.rb
  modules/auxiliary/scanner/mysql/mysql_authbypass_hashdump.rb
  modules/exploits/unix/webapp/wp_google_document_embedder_exec.rb
  spec/lib/metasploit/framework/login_scanner/mysql_spec.rb
Labels: bug, library

#14873 Handle modules failing to be created when checking compatibility
  lib/msf/core/exploit.rb
  msfvenom
Labels: bug

#14978 Gitea and Gogs Git Hooks RCE
  documentation/modules/exploit/multi/http/gitea_git_hooks_rce.md
  documentation/modules/exploit/multi/http/gogs_git_hooks_rce.md
  modules/exploits/multi/http/gitea_git_hooks_rce.rb
  modules/exploits/multi/http/gogs_git_hooks_rce.rb
Labels: docs, module

#15007 Add exploit for chrome CVE-2020-16040
  documentation/modules/exploit/multi/browser/chrome_simplifiedlowering_overflow.md
  modules/exploits/multi/browser/chrome_simplifiedlowering_overflow.rb
Labels: docs, module

#14833 Add an haserl-based exploit for Alpine linux
  documentation/modules/post/linux/gather/haserl_read.md
  modules/post/linux/gather/haserl_read.rb
Labels: docs, module

#14997 x64/shell_bind_tcp_random_port: rip one byte off
  modules/payloads/singles/linux/x64/shell_bind_tcp_random_port.rb
Labels: enhancement, payload

#15017 Update tomcat ghost module with default ports
  documentation/modules/auxiliary/admin/http/tomcat_ghostcat.md
  modules/auxiliary/admin/http/tomcat_ghostcat.rb
Labels: docs, enhancement, module

#14994 Updating screen_spy.rb to have a PID option for session migration
  documentation/modules/post/windows/gather/screen_spy.md
  modules/post/windows/gather/screen_spy.rb
Labels: enhancement, module

#15038 Fix Gem::Package NameError with Rex::Tar::Writer (exploit/linux/http/pulse_secure_gzip_rce)
  modules/exploits/linux/http/pulse_secure_gzip_rce.rb
Labels: bug, easy, module

#14701 Rename Nagios XI authenticated RCE module and integrate Nagios XI mixin
  documentation/modules/exploit/linux/http/nagios_xi_authenticated_rce.md
  documentation/modules/exploit/linux/http/nagios_xi_plugins_check_plugin_authenticated_rce.md
  modules/exploits/linux/http/nagios_xi_authenticated_rce.rb
  modules/exploits/linux/http/nagios_xi_plugins_check_plugin_authenticated_rce.rb
Labels: docs, enhancement, module, rn-enhancement

#15037 Update redis_login to check that authentication is required
  lib/msf/core/auxiliary/redis.rb
  modules/auxiliary/scanner/redis/redis_login.rb
Labels: enhancement, module

#14770 guard when spawn is used with TcpServer mixin
  lib/msf/core/exploit/remote/socket_server.rb
  modules/exploits/windows/ftp/freefloatftp_wbem.rb
  modules/exploits/windows/ftp/open_ftpd_wbem.rb
  modules/exploits/windows/ftp/quickshare_traversal_write.rb
  modules/exploits/windows/http/solarwinds_storage_manager_sql.rb
Labels: bug

#15043 Fix Python HTTP stage when LURI is mis-slashed
  lib/msf/core/payload/python/meterpreter_loader.rb
Labels: bug

#14700 Add Nagios XI Plugins Filename Authenticate RCE module and docs (CVE-2020-35578)
  documentation/modules/exploit/linux/http/nagios_xi_plugins_filename_authenticated_rce.md
  modules/exploits/linux/http/nagios_xi_plugins_filename_authenticated_rce.rb
Labels: docs, module

#14996 hashcat logic fixes for crackers
  lib/msf/core/auxiliary/password_cracker.rb
Labels: bug

#15047 Correct DNS PTR record crash
  lib/msf/core/exploit/remote/dns/enumeration.rb
Labels: bug, library

#15053 Move exploit/linux/http/citrix_dir_traversal_rce to exploit/freebsd
  documentation/modules/exploit/freebsd/http/citrix_dir_traversal_rce.md
  modules/exploits/freebsd/http/citrix_dir_traversal_rce.rb
Labels: bug, docs, easy, module

#15055 fix typos and documentation in chrome_simplifiedlowering_overflow
  documentation/modules/exploit/multi/browser/chrome_simplifiedlowering_overflow.md
  modules/exploits/multi/browser/chrome_simplifiedlowering_overflow.rb
Labels: easy

#14698 Add Nagios XI Mibs.php Authenticated RCE module and docs (CVE-2020-5791)
  documentation/modules/exploit/linux/http/nagios_xi_mibs_authenticated_rce.md
  modules/exploits/linux/http/nagios_xi_mibs_authenticated_rce.rb
Labels: docs, module, rn-modules

#15063 Add fix to nagios_xi_plugins_check_ping_authenticated_rce.rb to Ensure Old Versions Can Still Be Detected As Being Vulnerable
  modules/exploits/linux/http/nagios_xi_plugins_check_plugin_authenticated_rce.rb
Labels: bug, module, rn-fix

#15064 Fix Rex::Socket::SSHFactory NameError in exploit/linux/ssh/f5_bigip_known_privkey
  modules/exploits/linux/ssh/f5_bigip_known_privkey.rb
Labels: bug, easy, module

#14699 Add Nagios XI snmptrap RCE and docs (CVE-2020-5792)
  documentation/modules/exploit/linux/http/nagios_xi_snmptrap_authenticated_rce.md
  modules/exploits/linux/http/nagios_xi_snmptrap_authenticated_rce.rb
Labels: docs, module

#15070 Fix up wrong type field in nagios_xi_mibs_authenticated_rce.rb
  modules/exploits/linux/http/nagios_xi_mibs_authenticated_rce.rb
Labels: bug, easy, module, rn-fix

#15058 cockpit cms rce
  documentation/modules/exploit/multi/http/cockpit_cms_rce.md
  modules/exploits/multi/http/cockpit_cms_rce.rb
Labels: docs, module

#15072 remove is_root check from linux_hashdump module
  modules/post/linux/gather/hashdump.rb
Labels: enhancement, module

#15067 guard ssh connection reset
  lib/metasploit/framework/login_scanner/ssh.rb
Labels: bug, library

#15077 Update reverse_https.rb
  modules/payloads/stagers/multi/reverse_https.rb
Labels: easy

#15078 Update reverse_http.rb
  modules/payloads/stagers/multi/reverse_http.rb
Labels: easy, module

#15051 Automatically verify shell sessions
  lib/msf/base/sessions/command_shell.rb
  lib/msf/base/sessions/command_shell_options.rb
  lib/msf/base/sessions/meterpreter.rb
  lib/msf/core/exploit.rb
  lib/msf/core/handler.rb
Labels: enhancement, library, payload, usability

#14953 Drop python 3.6 string formatting syntax in rdp_web_login
  modules/auxiliary/scanner/http/rdp_web_login.py
Labels: bug, module

#15088 Fix a typo in Eclipse Equinox product name
  documentation/modules/exploit/multi/misc/osgi_console_exec.md
  modules/exploits/multi/misc/osgi_console_exec.rb
Labels: easy

#14977 Add Apache Druid CVE-2021-25646 RCE exploit
  documentation/modules/exploit/linux/http/apache_druid_js_rce.md
  modules/exploits/linux/http/apache_druid_js_rce.rb
Labels: docs, module

#15085 Add history avoidance for commands and remove leading spaces from readline input
  lib/msf/ui/console/command_dispatcher/core.rb
  lib/msf/ui/tip.rb
  lib/rex/ui/text/input/readline.rb
  lib/rex/ui/text/shell.rb
Labels: bug, feature, library

#15014 Added string PKey support for ssh module
  documentation/modules/auxiliary/scanner/ssh/ssh_login_pubkey.md
  lib/msf/core/auxiliary/command_shell.rb
  modules/auxiliary/scanner/ssh/ssh_login.rb
  modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb
Labels: enhancement

#15005 Add VMware vRealize Operations (vROps) Manager SSRF RCE (CVE-2021-21975 + CVE-2021-21983)
  documentation/modules/exploit/linux/http/vmware_vrops_mgr_ssrf_rce.md
  modules/exploits/linux/http/vmware_vrops_mgr_ssrf_rce.rb
Labels: docs, module

#15081 Adds error handling for `mssql_idf` when module returns no matching results
  modules/auxiliary/admin/mssql/mssql_idf.rb
Labels: bug, module

#15094 Fix #15091, fix sessions -c to use a subshell
  lib/msf/ui/console/command_dispatcher/core.rb
Labels: bug, payload

#14702 Add module Redis extractor
  documentation/modules/auxiliary/gather/redis_extractor.md
  modules/auxiliary/gather/redis_extractor.rb
Labels: docs, module, needs-linting

#15114 Fix issue in Redis modules when run against authenticated instances
  lib/msf/core/auxiliary/redis.rb
Labels: bug

#15086 Add exploit for CVE-2020-11857: Hardcoded SSH password on Micro Focus Operations Bridge Manager
  documentation/modules/exploit/linux/ssh/microfocus_obr_shrboadmin.md
  modules/exploits/linux/ssh/microfocus_obr_shrboadmin.rb
Labels: docs, module

#15090 Add exploit for CVE-2021-22502: Micro Focus Operations Bridge Reporter unauthenticated command injection
  documentation/modules/exploit/linux/http/microfocus_obr_cmd_injection.md
  modules/exploits/linux/http/microfocus_obr_cmd_injection.rb
Labels: docs, module

#14831 Add CookieJar support to http_client
  Gemfile.lock
  lib/msf/core/exploit/remote/http/http_cookie.rb
  lib/msf/core/exploit/remote/http/http_cookie_jar.rb
  lib/msf/core/exploit/remote/http_client.rb
  metasploit-framework.gemspec
  modules/exploits/multi/http/gitea_git_hooks_rce.rb
  modules/exploits/multi/http/gitlab_file_read_rce.rb
  modules/exploits/multi/http/gogs_git_hooks_rce.rb
  modules/exploits/multi/http/horizontcms_upload_exec.rb
  modules/exploits/windows/http/exchange_ecp_dlp_policy.rb
  spec/lib/msf/core/exploit/remote/remote/http/http_cookie_jar_spec.rb
  spec/lib/msf/core/exploit/remote/remote/http/http_cookie_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#15116 more flexible time parse
  lib/rex/parser/acunetix_document.rb
Labels: bug, library

#15087 Update Micro Focus Privesc exploit to support CVE-2020-11855
  documentation/modules/exploit/windows/local/microfocus_operations_privesc.md
  modules/exploits/windows/local/microfocus_operations_privesc.rb
Labels: docs, module, rn-modules
