Repository rapid7/metasploit-framework, pull requests merged in 2021-07, with the labels that each got.

#15366 Add limit to size of history files
  lib/rex/ui/text/shell.rb
  lib/rex/ui/text/shell/history_manager.rb
Labels: GSoC

#15320 Enables powershell sessions to use the read_file method
  lib/msf/core/post/file.rb
Labels: bug, rn-fix

#15399 Improve AutoCheck user experience (prints, etc.)
  lib/msf/core/exploit/remote/auto_check.rb
  spec/lib/msf/core/exploit/remote/auto_check_spec.rb
Labels: bug, code quality, library, rn-no-release-notes

#15398 Fix CheckCode in exploit/linux/http/cisco_hyperflex_hx_data_platform_cmd_exec
  documentation/modules/exploit/linux/http/cisco_hyperflex_hx_data_platform_cmd_exec.md
  modules/exploits/linux/http/cisco_hyperflex_hx_data_platform_cmd_exec.rb
Labels: bug, docs, module, rn-no-release-notes

#15385 Add Module For CVE-2021-1675 / CVE-2021-34527 AKA PrintNightmare
  documentation/modules/auxiliary/admin/dcerpc/cve_2021_1675_printnightmare.md
  modules/auxiliary/admin/dcerpc/cve_2021_1675_printnightmare.rb
Labels: docs, module

#15401 Improve here doc formatting in exploit/multi/http/weblogic_admin_handle_rce
  modules/exploits/multi/http/weblogic_admin_handle_rce.rb
Labels: bug, module, rn-no-release-notes

#15371 apport_abrt_chroot_priv_esc: check if apport-cli is in $PATH
  modules/exploits/linux/local/apport_abrt_chroot_priv_esc.rb
Labels: Stale, bug, module

#15368 Polkit D-Bus Authentication Bypass and Privilege Escalation (CVE-2021-3560)
  documentation/modules/exploit/linux/local/polkit_dbus_auth_bypass.md
  lib/msf/core/post/linux/system.rb
  metasploit-framework.gemspec
  modules/exploits/linux/local/polkit_dbus_auth_bypass.rb
Labels: docs, hotness, module

#15405 Update Gemfile.lock
  Gemfile.lock
Labels: bug

#15407 Backport print changes to recent modules
  documentation/modules/exploit/linux/http/cisco_hyperflex_hx_data_platform_cmd_exec.md
  documentation/modules/exploit/windows/http/netmotion_mobility_mvcutil_deserialization.md
  modules/exploits/linux/http/cisco_hyperflex_hx_data_platform_cmd_exec.rb
  modules/exploits/windows/http/netmotion_mobility_mvcutil_deserialization.rb
Labels: bug, docs, module, rn-no-release-notes

#15217 Combine eternalblue modules
  modules/auxiliary/scanner/smb/smb_ms17_010.rb
  modules/exploits/windows/smb/ms17_010_eternalblue.rb
  modules/exploits/windows/smb/ms17_010_eternalblue_win8.py
Labels: enhancement, rn-enhancement

#15154 Process memory dump
  documentation/modules/post/windows/gather/memory_dump.md
  lib/rex/post/meterpreter/extensions/stdapi/railgun/def/windows/def_dbghelp.rb
  lib/rex/post/meterpreter/extensions/stdapi/railgun/railgun.rb
  modules/post/windows/gather/memory_dump.rb
Labels: docs, module

#15386 Add module for CVE-2021-35464; pre-auth RCE in ForgeRock AM (and OpenAM) server
  documentation/modules/exploit/multi/http/cve_2021_35464_forgerock_openam.md
  modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
Labels: docs, module, rn-modules

#15254 Use Obfuscated Powershell Protection Bypasses
  Gemfile.lock
  LICENSE_GEMS
  data/evasion/windows/bypass_powershell_protections.erb.graphml
  data/shellcode/block_api.x64.graphml
  data/shellcode/block_api.x86.graphml
  documentation/modules/exploit/windows/smb/psexec.md
  lib/msf/core/exploit/powershell.rb
  lib/msf/core/exploit/remote/smb/client/psexec.rb
  lib/rex/parser/graphml.rb
  lib/rex/payloads/shuffle.rb
  modules/exploits/multi/script/web_delivery.rb
  modules/payloads/singles/cmd/windows/powershell_bind_tcp.rb
  modules/payloads/singles/cmd/windows/powershell_reverse_tcp.rb
  modules/payloads/singles/windows/powershell_bind_tcp.rb
  modules/payloads/singles/windows/powershell_reverse_tcp.rb
  modules/payloads/singles/windows/x64/powershell_bind_tcp.rb
  modules/payloads/singles/windows/x64/powershell_reverse_tcp.rb
  spec/lib/msf/core/exploit/powershell_spec.rb
Labels: enhancement, library, rn-enhancement

#15417 Fix #15254, set dynamic cached size on powershell payloads
  modules/payloads/singles/cmd/windows/powershell_bind_tcp.rb
  modules/payloads/singles/cmd/windows/powershell_reverse_tcp.rb
  modules/payloads/singles/windows/powershell_bind_tcp.rb
  modules/payloads/singles/windows/powershell_reverse_tcp.rb
  modules/payloads/singles/windows/x64/powershell_bind_tcp.rb
  modules/payloads/singles/windows/x64/powershell_reverse_tcp.rb
  spec/modules/payloads_spec.rb
Labels: bug, rn-no-release-notes

#15383 Add VMware vCenter Server CVE-2021-21985 exploit
  documentation/modules/exploit/linux/http/vmware_vcenter_vsan_health_rce.md
  modules/exploits/linux/http/vmware_vcenter_vsan_health_rce.rb
Labels: docs, module

#15421 Fix edge case in method overloading for exploit/linux/http/vmware_vcenter_vsan_health_rce
  documentation/modules/exploit/linux/http/vmware_vcenter_vsan_health_rce.md
  modules/exploits/linux/http/vmware_vcenter_vsan_health_rce.rb
Labels: bug, module, rn-no-release-notes

#15424 Add Simon Janusz to mail map
  .mailmap
Labels: rn-no-release-notes

#15431 Update module credits
  modules/exploits/multi/http/vmware_vcenter_uploadova_rce.rb
Labels: module, rn-no-release-notes

#15362 Debug cmd_exec again
  lib/msf/core/post/file.rb
  lib/msf/core/session/provider/single_command_shell.rb
Labels: cmd_exec is broken again, rn-fix

#15409 Improved PrintNightmare Check and DCERPC Library Bug Fixes
  documentation/modules/auxiliary/admin/dcerpc/cve_2021_1675_printnightmare.md
  lib/rex/proto/dcerpc/client.rb
  lib/rex/proto/dcerpc/response.rb
  modules/auxiliary/admin/dcerpc/cve_2021_1675_printnightmare.rb
Labels: bug, enhancement, library, module

#15438 Add new supported eternalblue targets to documentation
  documentation/modules/exploit/windows/smb/ms17_010_eternalblue.md
Labels: docs, easy

#15403 Change powershell platform to `windows` and add powershell support to some methods
  lib/msf/base/sessions/powershell.rb
  lib/msf/core/post/file.rb
  lib/msf/core/post/process.rb
Labels: GSoC, library, powershell

#15445 Fix the printed exploit target
  lib/msf/ui/console/command_dispatcher/exploit.rb
  spec/lib/msf/ui/console/command_dispatcher/exploit_spec.rb
Labels: bug, easy, library

#15443 Fix python3 compatibility with wmiexec module
  modules/auxiliary/scanner/smb/impacket/_msf_impacket.py
  modules/auxiliary/scanner/smb/impacket/wmiexec.py
Labels: bug

#15436 Ensure generated JSP variable names aren't Java keywords
  Gemfile.lock
  lib/msf/core/payload/jsp.rb
Labels: bug, rn-fix

#15449 Binom3 add CVE
  modules/auxiliary/scanner/http/binom3_login_config_pass_dump.rb
Labels: easy, module, rn-no-release-notes

#15402 [CVE-2021-24155] Wordpress Plugin Backup Guard < 1.6.0 - Authenticated Remote Code Execution
  documentation/modules/exploit/multi/http/wp_plugin_backup_guard_rce.md
  modules/exploits/multi/http/wp_plugin_backup_guard_rce.rb
Labels: docs, module

#15400 added Sage X3 modules
  documentation/modules/auxiliary/scanner/sage/x3_adxsrv_login.md
  documentation/modules/exploit/windows/sage/x3_adxsrv_auth_bypass_cmd_exec.md
  lib/metasploit/framework/login_scanner/x3.rb
  modules/auxiliary/scanner/sage/x3_adxsrv_login.rb
  modules/exploits/windows/sage/x3_adxsrv_auth_bypass_cmd_exec.rb
Labels: docs, library, module

#15211 CVE-2021-27850 Apache Tapestry HMAC secret key leak
  documentation/modules/auxiliary/gather/cve_2021_27850_apache_tapestry_hmac_key.md
  modules/auxiliary/gather/cve_2021_27850_apache_tapestry_hmac_key.rb
Labels: docs, module, rn-modules

#15444 Redefine powershell support for some file system methods
  lib/msf/core/post/file.rb
Labels: library

#15460 Fix localization issue in `copy_file` method
  lib/msf/core/post/file.rb
Labels: GSoC, bug, library

#15163 CVE-2021-31802 - R7000 v1.0.11.116 and Prior Unauthenticated RCE via Heap Overflow
  documentation/modules/auxiliary/admin/http/netgear_r7000_backup_cgi_heap_overflow_rce.md
  modules/auxiliary/admin/http/netgear_r7000_backup_cgi_heap_overflow_rce.rb
Labels: docs, module

#15462 [CVE-2021-36934] HiveNightmare aka SeriousSam - SAM hashes leak
  documentation/modules/post/windows/gather/credentials/windows_sam_hivenightmare.md
  modules/post/windows/gather/credentials/windows_sam_hivenightmare.rb
Labels: module
