Repository rapid7/metasploit-framework, pull requests merged in 2021-06, with the labels that each got.

#15225 Prevent TLD use in tests that use DomainName & remove HTTP::Cookie from Cookie initializer
  lib/msf/core/exploit/remote/http/http_cookie.rb
  lib/msf/core/exploit/remote/http/http_cookie_jar.rb
  lib/msf/core/exploit/remote/http_client.rb
  spec/lib/msf/core/exploit/remote/remote/http/http_cookie_spec.rb
Labels: bug, enhancement

#15289 Fix a typo in a Meterpreter command requirement
  lib/msf/core/post/windows/mssql.rb
Labels: bug, easy, library

#15292 Clean up exploit/linux/http/f5_icontrol_rest_ssrf_rce
  modules/exploits/linux/http/f5_icontrol_rest_ssrf_rce.rb
Labels: bug, module, rn-no-release-notes

#15294 Clean up NetMotion Mobility exploit and docs
  documentation/modules/exploit/windows/http/netmotion_mobility_mvcutil_deserialization.md
  modules/exploits/windows/http/netmotion_mobility_mvcutil_deserialization.rb
Labels: bug, docs, module, rn-no-release-notes

#15268 Fix syntax errors in auxiliary spec modules
  spec/file_fixtures/modules/auxiliary/auxiliary_tidy.rb
  spec/file_fixtures/modules/auxiliary/auxiliary_untidy.rb
Labels: ruby-3.0.0

#15231 Added module and documentation for SuiteCRM Log File RCE CVE-2020-28328
  documentation/modules/exploit/linux/http/suitecrm_log_file_rce.md
  modules/exploits/linux/http/suitecrm_log_file_rce.rb
Labels: docs, module

#15291 Remove Invalid Import Causing Crashes From FortiOS SSL VPN Credential Leak Module
  modules/auxiliary/gather/fortios_vpnssl_traversal_creds_leak.rb
Labels: bug, easy, module

#15281 Add Cisco HyperFlex HX Data Platform CVE-2021-1497/CVE-2021-1498 exploit
  documentation/modules/exploit/linux/http/cisco_hyperflex_hx_data_platform_cmd_exec.md
  modules/exploits/linux/http/cisco_hyperflex_hx_data_platform_cmd_exec.rb
Labels: docs, module

#15290 Stop raising a RuntimeError for invalid Meterpreter command wildcards
  lib/msf/core/post_mixin.rb
Labels: bug, easy, library

#15284 fix localization issue in module linux/gather/ppp_chap_secrets
  modules/post/linux/gather/pptpd_chap_secrets.rb
Labels: bug, module

#15300 Fix RuboCop issues with sudo_baron_samedit.rb
  modules/exploits/linux/local/sudo_baron_samedit.rb
Labels: code quality, easy, rn-no-release-notes

#15299 Ask for a CVE
  CONTRIBUTING.md
Labels: suggestion-docs

#15257 Fix A Meterpreter Compatibility Error Message
  lib/msf/core/post_mixin.rb
Labels: bug, easy, library, rn-fix

#15296 Enhance command_exists? method so that it falls to `which` in case the `command` fails
  lib/msf/core/post/common.rb
  lib/msf/core/post/linux/priv.rb
Labels: enhancement, library, rn-enhancement

#15264 Update JSON RPC servlet helper to symbolize params object
  lib/msf/core/web_services/servlet_helper.rb
Labels: ruby-3.0.0

#15305 NSClient++ 0.5.2.35 - Authenticated Remote Code Execution
  documentation/modules/exploit/windows/http/nscp_authenticated_rce.md
  modules/exploits/windows/http/nscp_authenticated_rce.rb
Labels: docs, module

#15323 Bump metasploit_payloads-mettle to 1.0.10
  Gemfile.lock
  metasploit-framework.gemspec
Labels: rn-no-release-notes

#15324 Bump metasploit-payloads gem to 2.0.47
  Gemfile.lock
  metasploit-framework.gemspec
Labels: rn-no-release-notes

#15328 Fix get_processes for some shell sessions
  lib/msf/core/session/provider/single_command_shell.rb
Labels: bug, library, rn-fix

#15187 msfdb default to database only
  lib/msf/ui/console/command_dispatcher/db.rb
  msfdb
Labels: enhancement, rn-enhancement

#15215 HashiCorp Nomad RCE
  documentation/modules/exploit/multi/misc/nomad_exec.md
  modules/exploits/multi/misc/nomad_exec.rb
Labels: module, rn-modules

#15337 Update apache_activemq_upload_jsp.rb to fix missing checks and add missing slashes to some requests
  documentation/modules/exploit/multi/http/apache_activemq_upload_jsp.md
  modules/exploits/multi/http/apache_activemq_upload_jsp.rb
Labels: bug, rn-fix

#15239 ipfire <= 2.25 Core Update 156 pakfire.cgi Authenticated RCE
  documentation/modules/exploit/linux/http/ipfire_pakfire_exec.md
  modules/exploits/linux/http/ipfire_pakfire_exec.rb
Labels: docs, module

#15345 fixed reference url
  modules/auxiliary/scanner/http/binom3_login_config_pass_dump.rb
  modules/auxiliary/scanner/http/gavazzi_em_login_loot.rb
Labels: rn-no-release-notes

#15314 Add Exploit For CVE-2021-31181 (SharePoint RCE)
  documentation/modules/exploit/windows/http/sharepoint_ssi_viewstate.md
  documentation/modules/exploit/windows/http/sharepoint_unsafe_control.md
  lib/msf/core/exploit/remote/http/sharepoint.rb
  modules/exploits/windows/http/sharepoint_ssi_viewstate.rb
  modules/exploits/windows/http/sharepoint_unsafe_control.rb
Labels: docs, module

#15109 Better handling for incompatible Meterpreter extensions and commands (Round 2)
  lib/rex/post/meterpreter/client_core.rb
  lib/rex/post/meterpreter/extension.rb
  lib/rex/post/meterpreter/extensions/mimikatz/command_ids.rb
  lib/rex/post/meterpreter/packet.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/extapi.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/lanattacks.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/priv.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi.rb
  lib/rex/ui/text/dispatcher_shell.rb
Labels: enhancement, library, rn-enhancement

#15316 Add a call to setsid when forking a new process
  lib/msf/core/payload/linux.rb
  lib/msf/core/payload/linux/reverse_tcp_x86.rb
  lib/msf/core/payload/linux/x64/reverse_tcp_x64.rb
Labels: enhancement, payload

#15333 Cisco HyperFlex File Upload RCE
  documentation/modules/exploit/linux/http/cisco_hyperflex_file_upload_rce.md
  modules/exploits/linux/http/cisco_hyperflex_file_upload_rce.rb
Labels: docs, module

#15352 Ensure msfdb reinit can be used for starting the database
  lib/msfdb_helpers/db_interface.rb
  lib/msfdb_helpers/pg_ctl.rb
  lib/msfdb_helpers/pg_ctlcluster.rb
  lib/msfdb_helpers/standalone.rb
  msfdb
Labels: bug, rn-fix

#15350 fix shellcode_inject module
  lib/msf/core/post/windows/process.rb
  modules/post/windows/gather/checkvm.rb
Labels: bug, easy, module, rn-fix

#15358 Fallback to Python3 in sshexec when it's available
  lib/msf/base/sessions/command_shell.rb
  modules/exploits/multi/ssh/sshexec.rb
Labels: enhancement, library

#15349 rConfig <= 3.9.6 - Authenticated RCE
  documentation/modules/exploit/linux/http/rconfig_vendors_auth_file_upload_rce.md
  modules/exploits/linux/http/rconfig_vendors_auth_file_upload_rce.rb
Labels: docs, module

#15282 [CVE-2019-15975] Cisco DCNM auth bypass
  documentation/modules/auxiliary/admin/networking/cisco_dcnm_auth_bypass.md
  modules/auxiliary/admin/networking/cisco_dcnm_auth_bypass.rb
Labels: docs, module, rn-modules

#15341 WordPress wpDiscuz Unauthenticated File Upload Vulnerability
  documentation/modules/exploit/unix/webapp/wp_wpdiscuz_unauthenticated_file_upload.md
  modules/exploits/unix/webapp/wp_wpdiscuz_unauthenticated_file_upload.rb
Labels: docs, module, needs-linting

#15107 Docker Container Escape via runC overwrite with RCE as root (CVE-2019-5736)
  data/exploits/CVE-2019-5736/CVE-2019-5736.x64.bin
  data/exploits/CVE-2019-5736/CVE-2019-5736.x86.bin
  documentation/modules/exploit/linux/local/docker_runc_escape.md
  external/source/exploits/CVE-2019-5736/CVE-2019-5736.c
  lib/msf/core/post/common.rb
  lib/msf/core/post/file.rb
  modules/exploits/linux/local/docker_runc_escape.rb
Labels: docs, module, rn-modules
