Repository rapid7/metasploit-framework, pull requests merged in 2021-11, with the labels that each got.

#15809 duplicator add check_plugin line
  data/wordlists/wp-exploitable-plugins.txt
  modules/exploits/multi/php/wp_duplicator_code_inject.rb
Labels: easy

#15782 Add CVE-2002-0422 Coverage to iis_internal_ip Auxiliary Module
  documentation/modules/auxiliary/scanner/http/iis_internal_ip.md
  modules/auxiliary/scanner/http/iis_internal_ip.rb
Labels: module, docs

#15816 GitLab Unauth Command Injection via ExifTool (CVE-2021-22205)
  documentation/modules/exploit/multi/http/gitlab_exif_rce.md
  modules/exploits/multi/http/gitlab_exif_rce.rb
Labels: module, docs

#15805 bump metasploit-payloads to 2.0.60
  Gemfile.lock
  LICENSE_GEMS
  metasploit-framework.gemspec
  modules/payloads/singles/python/meterpreter_bind_tcp.rb
  modules/payloads/singles/python/meterpreter_reverse_http.rb
  modules/payloads/singles/python/meterpreter_reverse_https.rb
  modules/payloads/singles/python/meterpreter_reverse_tcp.rb
Labels: rn-fix

#15825 Only Warn About Missing CVEs in Exploits
  tools/dev/msftidy.rb
Labels: msftidy, easy

#15828 Update README.md for DLL template injection with some minor additional notes
  external/source/rdll_template/README.md
Labels: docs, easy, rn-no-release-notes

#15776 Wordpress automatic plugin aux module
  data/wordlists/wp-exploitable-plugins.txt
  documentation/modules/auxiliary/admin/http/wp_automatic_plugin_privesc.md
  modules/auxiliary/admin/http/wp_automatic_plugin_privesc.rb
Labels: module, docs, hacktoberfest-accepted

#15818 Fix Partial WebSocket Reads
  lib/rex/proto/http/web_socket.rb
  spec/lib/rex/proto/http/web_socket/frame_spec.rb
Labels: library, bug, rn-fix

#15840 Give warning rather than failure when running DCSync as SYSTEM
  lib/rex/post/meterpreter/ui/console/command_dispatcher/kiwi.rb
Labels: library, bug

#15845 Don't getsystem if we are already SYSTEM
  lib/rex/post/meterpreter/ui/console/command_dispatcher/priv/elevate.rb
Labels: meterpreter, bug, easy, rn-fix

#15844 Add in new definitions to definitions.h
  external/source/include/windows/definitions.h
Labels: easy, rn-no-release-notes

#15802 Add Exploit for CVE-2021-38648 (OMIGOD LPE)
  data/exploits/CVE-2021-38648/README.md
  data/exploits/CVE-2021-38648/cve_2021_38648.py
  documentation/modules/exploit/linux/local/cve_2021_38648_omigod.md
  modules/exploits/linux/local/cve_2021_38648_omigod.rb
Labels: module, docs

#15846 Tab-complete for file downloads
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb
Labels: library, enhancement, easy

#15834 Add Exploit for CVE-2021-40449
  data/exploits/CVE-2021-40449/CVE-2021-40449.x64.dll
  documentation/modules/exploit/windows/local/cve_2021_40449.md
  external/source/exploits/CVE-2021-40449/CVE-2021-40449.sln
  external/source/exploits/CVE-2021-40449/CVE-2021-40449/CVE-2021-40449.vcxproj
  external/source/exploits/CVE-2021-40449/CVE-2021-40449/dllmain.c
  modules/exploits/windows/local/cve_2021_40449.rb
Labels: module, docs

#15820 Fix named pipe pivoting
  lib/metasploit/framework/data_service/remote/http/remote_session_data_service.rb
  lib/rex/post/meterpreter/pivot.rb
Labels: bug, rn-fix

#15847 Fix bug in tab completion in case-sensitive situations
  lib/rex/ui/text/input/readline.rb
Labels: library, bug

#15806 BillQuick Web Suite (CVE-2021-42258) SQLi
  documentation/modules/auxiliary/gather/billquick_txtid_sqli.md
  modules/auxiliary/gather/billquick_txtid_sqli.rb
Labels: module, docs, hacktoberfest-accepted

#15796 Support Pivoted SSL Connections (Server Edition)
  lib/msf/base/sessions/ssh_command_shell_bind.rb
  lib/rex/post/meterpreter/extensions/stdapi/net/socket_subsystem/tcp_server_channel.rb
Labels: enhancement

#15875 Bash payload works outside of bash context
  modules/exploits/unix/fileformat/metasploit_msfvenom_apk_template_cmd_injection.rb
  modules/payloads/singles/cmd/unix/reverse_bash.rb
  modules/payloads/singles/cmd/unix/reverse_bash_udp.rb
Labels: bug, payload

#15858 Add in Module for CVE-2021-42237 - Sitecore Experience Platform Pre-Auth Deserialization RCE
  documentation/modules/exploit/windows/http/sitecore_xp_cve_2021_42237.md
  modules/exploits/windows/http/sitecore_xp_cve_2021_42237.rb
Labels: module, docs

#15862 Expand environment variables on Linux
  lib/rex/post/meterpreter/extensions/stdapi/fs/file.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb
  test/modules/post/test/file.rb
Labels: enhancement

#15755 Azure Active Directory Login Scanner Module
  documentation/modules/auxiliary/scanner/http/azure_ad_login.md
  modules/auxiliary/scanner/http/azure_ad_login.rb
Labels: module, docs, rn-modules, hacktoberfest-accepted

#15887 Respect path expansion when performing path-based tab completion
  lib/rex/post/meterpreter/extensions/stdapi/fs/file.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb
Labels: library, enhancement

#15889 Add validation for resizeable interactive shells
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/sys.rb
  lib/rex/post/meterpreter/ui/console/interactive_channel.rb
Labels: enhancement

#15900 Update Azure AD Login Scanner Documentation
  documentation/modules/auxiliary/scanner/http/azure_ad_login.md
  modules/auxiliary/scanner/http/azure_ad_login.rb
Labels: docs, easy, rn-enhancement

#15899 Tell the user about `shell -it`
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/sys.rb
Labels: enhancement

#15898 trade `URI.encode` & `URI.escape` for Ruby 3
  lib/anemone/page.rb
  lib/msf/core/exploit/remote/web.rb
  lib/rex/google/geolocation.rb
  modules/auxiliary/admin/aws/aws_launch_instances.rb
  modules/auxiliary/dos/http/ms15_034_ulonglongadd.rb
  modules/auxiliary/gather/flash_rosetta_jsonp_url_disclosure.rb
  modules/auxiliary/scanner/http/ms15_034_http_sys_memory_dump.rb
  modules/exploits/linux/http/php_imap_open_rce.rb
  modules/exploits/linux/http/zenoss_showdaemonxmlconfig_exec.rb
  modules/exploits/multi/http/php_fpm_rce.rb
  modules/post/multi/escalate/aws_create_iam_user.rb
  modules/post/multi/gather/lastpass_creds.rb
Labels: enhancement, rn-enhancement

#15874 Add ManageEngine ADSelfService Plus CVE-2021-40539 exploit
  documentation/modules/exploit/windows/http/manageengine_adselfservice_plus_cve_2021_40539.md
  modules/exploits/windows/http/manageengine_adselfservice_plus_cve_2021_40539.rb
Labels: module, docs

#15915 ms05_039_pnp: Rename 'Windows 2000 SP4 English/French/German/Dutch' target to 'Windows 2000 SP4 Universal'
  modules/exploits/windows/smb/ms05_039_pnp.rb
Labels: module, enhancement

#15897 Fix #15896, write_file should return true on success
  lib/msf/core/post/file.rb
  test/modules/post/test/file.rb
Labels: bug, rn-fix, osx

#15918 ms07_029_msdns_zonename: Add additional Windows 2000/2003 target offsets
  modules/exploits/windows/dcerpc/ms07_029_msdns_zonename.rb
  modules/exploits/windows/smb/ms07_029_msdns_zonename.rb
Labels: module, enhancement

#15914 ms03_026_dcom: cleanup
  documentation/modules/exploit/windows/dcerpc/ms03_026_dcom.md
  modules/exploits/windows/dcerpc/ms03_026_dcom.rb
Labels: module, enhancement, rn-enhancement
