Repository rapid7/metasploit-framework, pull requests merged in 2021-12, with the labels that each got.

#15822 Add cve-2021-3493 module
  data/exploits/CVE-2021-3493/cve_2021_3493.aarch64.elf
  data/exploits/CVE-2021-3493/cve_2021_3493.x64.elf
  documentation/modules/exploit/linux/local/cve_2021_3493_overlayfs.md
  external/source/exploits/CVE-2021-3493/cve_2021_3493.c
  lib/msf/core/post/file.rb
  modules/exploits/linux/local/cve_2021_3493_overlayfs.rb
Labels: module, docs

#15937 Remove references to Sorted Set
  lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb
Labels: ruby-3.0.0

#15933 Add April fools module help banner
  data/logos/help-using-a-module.txt
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: rn-no-release-notes

#15929 ms08_067_netapi: Add nine Windows 2003 SP2 targets for various locales
  modules/exploits/windows/smb/ms08_067_netapi.rb
Labels: module, enhancement

#15905 Only normalize new/updated hosts after nmap import
  lib/msf/core/db_manager/import.rb
  lib/msf/core/db_manager/import/nmap.rb
  lib/rex/parser/nmap_document.rb
  lib/rex/parser/parsed_result.rb
Labels: enhancement

#15742 Added module for CVE-2021-40444
  data/exploits/CVE-2021-40444/cve-2021-40444.docx
  data/exploits/CVE-2021-40444/cve_2021_40444.js
  documentation/modules/exploit/windows/fileformat/word_mshtml_rce.md
  modules/exploits/windows/fileformat/word_mshtml_rce.rb
Labels: module, needs-docs, rn-modules, needs-linting, hacktoberfest-accepted

#15842 Add Meterpreter compatibility requirements to lib
  lib/msf/core/post/common.rb
  lib/msf/core/post/file.rb
  lib/msf/core/post/windows/accounts.rb
  lib/msf/core/post/windows/extapi.rb
  lib/msf/core/post/windows/file_info.rb
  lib/msf/core/post/windows/file_system.rb
  lib/msf/core/post/windows/kiwi.rb
  lib/msf/core/post/windows/ldap.rb
  lib/msf/core/post/windows/mssql.rb
  lib/msf/core/post/windows/net_api.rb
  lib/msf/core/post/windows/packrat.rb
  lib/msf/core/post/windows/powershell.rb
  lib/msf/core/post/windows/priv.rb
  lib/msf/core/post/windows/process.rb
  lib/msf/core/post/windows/reflective_dll_injection.rb
  lib/msf/core/post/windows/services.rb
  lib/msf/core/post/windows/user_profiles.rb
  lib/msf/core/post/windows/wmic.rb
  lib/msf/core/post_mixin.rb
Labels: library, enhancement

#15841 Rubocop Packrat mixin
  lib/msf/core/post/windows/packrat.rb
Labels: rn-no-release-notes, code quality

#15936 Update tomcat_mgr_default_userpass.txt
  data/wordlists/tomcat_mgr_default_pass.txt
  data/wordlists/tomcat_mgr_default_userpass.txt
  data/wordlists/tomcat_mgr_default_users.txt
Labels: enhancement, rn-enhancement

#15944 Add support and tests for long arguments to Rex Parser
  lib/msf/ui/console/command_dispatcher/core.rb
  lib/msf/ui/console/command_dispatcher/developer.rb
  lib/msf/ui/console/command_dispatcher/jobs.rb
  lib/msf/ui/console/command_dispatcher/modules.rb
  lib/msf/ui/console/module_action_commands.rb
  lib/msf/ui/console/module_argument_parsing.rb
  lib/rex/parser/arguments.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/net.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/sys.rb
  plugins/alias.rb
  spec/rex/parser/arguments_spec.rb
Labels: enhancement

#15779 Add Nil-Check in Auxiliary Report for Vuln Reporting
  lib/msf/core/auxiliary/report.rb
Labels: library, bug

#15970 Update log4shell documentation and default URI_FILE wordlist for scanning
  documentation/modules/auxiliary/scanner/http/log4shell_scanner.md
  modules/auxiliary/scanner/http/log4shell_scanner.rb
Labels: module, easy, rn-no-release-notes

#15882 Prevent payloads being used if can't clean up files
  lib/msf/base/sessions/command_shell.rb
  lib/msf/base/sessions/hwbridge.rb
  lib/msf/base/sessions/mainframe_shell.rb
  lib/msf/base/sessions/meterpreter.rb
  lib/msf/base/sessions/pingback.rb
  lib/msf/base/sessions/powershell.rb
  lib/msf/base/sessions/tty.rb
  lib/msf/base/sessions/vncinject.rb
  lib/msf/core/exploit.rb
  lib/msf/core/exploit/file_dropper.rb
  lib/msf/core/exploit_driver.rb
  lib/msf/core/payload.rb
  lib/msf/core/payload/pingback.rb
Labels: enhancement

#15831 More SSH Session Support
  lib/metasploit/framework/login_scanner/ssh.rb
  lib/metasploit/framework/ssh/platform.rb
  lib/msf/base/sessions/command_shell.rb
  lib/msf/base/sessions/command_shell_options.rb
  lib/msf/base/sessions/ssh_command_shell_bind.rb
  lib/msf/core/auxiliary/command_shell.rb
  lib/msf/core/handler/generic.rb
  modules/auxiliary/scanner/ssh/ssh_login.rb
  modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb
  modules/exploits/multi/ssh/sshexec.rb
  modules/payloads/singles/generic/ssh/interact.rb
Labels: library, enhancement

#15976 Update Log4Shell references and VCenter URI
  data/exploits/CVE-2021-44228/http_uris.txt
  documentation/modules/auxiliary/scanner/http/log4shell_scanner.md
  modules/auxiliary/scanner/http/log4shell_scanner.rb
Labels: module, easy

#15948 Wordpress wp_popular_posts rce (CVE-2021-42362)
  .github/PULL_REQUEST_TEMPLATE.md
  data/wordlists/wp-exploitable-plugins.txt
  data/wordlists/wp-plugins.txt
  data/wordlists/wp-themes.txt
  documentation/modules/exploit/multi/http/wp_popular_posts_rce.md
  modules/exploits/multi/http/wp_popular_posts_rce.rb
Labels: module, docs

#15954 grafana file read (CVE-2021-43798)
  data/wordlists/grafana_plugins.txt
  documentation/modules/auxiliary/scanner/http/grafana_plugin_traversal.md
  modules/auxiliary/scanner/http/grafana_plugin_traversal.rb
Labels: module, docs

#15955 BYOVD to Enable/Disable Windows Memory Protection
  data/exploits/dell_protect/dell_protect.x64.dll
  documentation/modules/post/windows/manage/dell_memory_protect.md
  external/source/exploits/dell_memory_protect/dell_memory_protect.sln
  external/source/exploits/dell_memory_protect/dell_memory_protect.vcxproj
  external/source/exploits/dell_memory_protect/dllmain.cpp
  external/source/exploits/dell_memory_protect/exploit.cpp
  modules/post/windows/manage/dell_memory_protect.rb
Labels: module, docs

#15950 Add ManageEngine ServiceDesk Plus CVE-2021-44077 exploit
  documentation/modules/exploit/windows/http/manageengine_servicedesk_plus_cve_2021_44077.md
  modules/exploits/windows/http/manageengine_servicedesk_plus_cve_2021_44077.rb
Labels: module, docs

#15986 bash_profile_persistence: Add notes and resolve rubocop violations
  modules/exploits/linux/local/bash_profile_persistence.rb
Labels: module, easy

#16003 expand version to 3.0.3 until 3.1 is handled
  .github/workflows/verify.yml
Labels: bug, ruby-compat, rn-fix

#15961 (Log4Shell playthings) Initial implementation of Rex LDAP Server
  data/exploits/ldap/msf.ldif
  documentation/modules/auxiliary/server/ldap.md
  lib/msf/core/exploit/remote/ldap.rb
  lib/msf/core/exploit/remote/ldap/server.rb
  lib/rex/proto/ldap.rb
  lib/rex/proto/ldap/server.rb
  modules/auxiliary/scanner/http/log4shell_scanner.rb
  modules/auxiliary/server/ldap.rb
Labels: module, library, docs, hotness, rn-modules
