Repository rapid7/metasploit-framework, pull requests merged in 2021-02, with the labels that each got.

#14707 Update bot label comments
  .github/label-actions.yml
Labels: rn-no-release-notes

#14713 Add documentation for auxiliary/scanner/redis/redis_login module.
  documentation/modules/auxiliary/scanner/redis/redis_login.md
Labels: docs

#14719 Bump rex-core to 0.1.15
  Gemfile.lock
Labels: library

#14715 CVE-2021-3156 Sudo LPE (AKA: Baron Samedit)
  data/exploits/CVE-2021-3156/exploit.c
  documentation/modules/exploit/linux/local/sudo_baron_samedit.md
  lib/msf/core/opt_base.rb
  lib/msf/core/post/linux/compile.rb
  modules/exploits/linux/local/sudo_baron_samedit.rb
Labels: docs, module

#14720 Fix missing vhost in rhost http url feature
  lib/msf/core/opt_http_rhost_url.rb
  spec/lib/msf/core/opt_http_rhost_url_spec.rb
Labels: bug, library

#14721 sudo_baron_samedit: Add target: Debian 10 x64, sudo v1.8.27, libc v2.28
  modules/exploits/linux/local/sudo_baron_samedit.rb
Labels: enhancement, module

#14725 move cve-2020-29583 to a better file
  data/wordlists/routers_userpass.txt
  data/wordlists/unix_passwords.txt
  data/wordlists/unix_users.txt
Labels: easy

#14728 update WPVDB link type
  documentation/modules/auxiliary/admin/http/wp_gdpr_compliance_privesc.md
  lib/msf/core/module/reference.rb
  tools/dev/msftidy.rb
  tools/modules/module_reference.rb
Labels: docs, enhancement, library

#14671 Add exploit for CVE-2020-11853: Micro Focus Multiple Products Authenticated Remote Code Execution
  documentation/modules/exploit/multi/http/microfocus_obm_auth_rce.md
  modules/exploits/multi/http/microfocus_obm_auth_rce.rb
Labels: docs, module

#14714 Update sqlite3 version
  Gemfile
  Gemfile.lock
Labels: ruby-3.0.0

#14708 add 10.13.1 and 10.13.2 offsets for the safari_proxy_object_type_confusion module
  modules/exploits/osx/browser/safari_proxy_object_type_confusion.rb
Labels: enhancement, module

#14607 Updates for Exchange ECP DLP Policy Exploit
  documentation/modules/exploit/windows/http/exchange_ecp_dlp_policy.md
  modules/exploits/windows/http/exchange_ecp_dlp_policy.rb
Labels: docs, hotness, module

#14741 Fix a target version discrepancy in the CVE-2020-17132 docs
  documentation/modules/exploit/windows/http/exchange_ecp_dlp_policy.md
Labels: bug, docs, rn-no-release-notes

#14733 Add latest Rubocop rules
  .rubocop.yml
  lib/msf/core/modules/external/shim.rb
  lib/msf/core/rpc/json/request.rb
  lib/rex/parser/fs/bitlocker.rb
  lib/rex/parser/nokogiri_doc_mixin.rb
  modules/auxiliary/admin/aws/aws_launch_instances.rb
  modules/auxiliary/admin/http/allegro_rompager_auth_bypass.rb
  modules/auxiliary/admin/http/ulterius_file_download.rb
  modules/auxiliary/dos/http/cable_haunt_websocket_dos.rb
  modules/auxiliary/gather/chrome_debugger.rb
  modules/exploits/linux/http/cve_2019_1663_cisco_rmi_rce.rb
  modules/exploits/multi/http/mantisbt_manage_proj_page_rce.rb
  modules/exploits/multi/http/solr_velocity_rce.rb
  modules/exploits/multi/http/vbulletin_getindexablecontent.rb
  modules/exploits/multi/misc/java_jmx_server.rb
  modules/exploits/unix/dhcp/rhel_dhcp_client_command_injection.rb
  modules/exploits/unix/http/schneider_electric_net55xx_encoder.rb
  modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
  modules/exploits/windows/smb/ms17_010_eternalblue.rb
  modules/post/windows/gather/credentials/vnc.rb
Labels: automation

#14747 Fix usage of `Failure::` constant
  lib/msf/core/auxiliary/mqtt.rb
  lib/msf/core/exploit.rb
  lib/msf/core/exploit/remote/zeromq.rb
  lib/msf/core/exploit/sqli/sqlitei/time_based_blind.rb
Labels: rn-enhancement

#14744 Add Klog Server authenticate.php user Unauthenticated Command Injection
  documentation/modules/exploit/linux/http/klog_server_authenticate_user_unauth_command_injection.md
  modules/exploits/linux/http/klog_server_authenticate_user_unauth_command_injection.rb
Labels: docs, module

#14751 msftidy: Fix exploit module checks for author and stack buffer overflow
  modules/exploits/linux/http/netgear_wnr2000_rce.rb
  modules/exploits/osx/local/nfs_mount_root.rb
  modules/exploits/windows/fileformat/ms_visual_basic_vbp.rb
  modules/exploits/windows/misc/plugx.rb
  tools/dev/msftidy.rb
Labels: easy, msftidy

#14602 Fix issue in length detection in Time Based MySQL injections, and enhance string hex encoding
  lib/msf/core/exploit/sqli/mysqli/common.rb
Labels: bug, library

#14730 Create exploit for CVE-2020-11858 / Micro Focus Operations Bridge Manager Local Privilege Escalation
  documentation/modules/exploit/windows/local/microfocus_operations_privesc.md
  modules/exploits/windows/local/microfocus_operations_privesc.rb
Labels: docs, module

#14738 Fix #14620, fix multi/manage/shell_to_meterpreter on macOS
  modules/post/multi/manage/shell_to_meterpreter.rb
Labels: bug, enhancement, meterpreter, osx

#14758 fix #14749, fix screenshot platform check
  lib/rex/post/meterpreter/extensions/stdapi/ui.rb
Labels: bug, easy, meterpreter

#14756 msftidy: Add info check for exploit module notes
  tools/dev/msftidy.rb
Labels: easy, msftidy

#14576 Wordpress Plugin: Chopslider 3 SQLi
  documentation/modules/auxiliary/scanner/http/wp_chopslider_id_sqli.md
  modules/auxiliary/scanner/http/wp_chopslider_id_sqli.rb
Labels: docs, module

#14772 Extract module data store to its own file
  lib/msf/core/data_store.rb
  lib/msf/core/module_data_store.rb
Labels: bug

#14780 Update metasploit-payloads gem to 2.0.34
  Gemfile.lock
  metasploit-framework.gemspec
  modules/payloads/singles/python/meterpreter_bind_tcp.rb
  modules/payloads/singles/python/meterpreter_reverse_http.rb
  modules/payloads/singles/python/meterpreter_reverse_https.rb
  modules/payloads/singles/python/meterpreter_reverse_tcp.rb
Labels: rn-no-release-notes

#14617 Better Handling For Incompatible Meterpreter Extensions and Commands
  lib/msf/base/sessions/meterpreter.rb
  lib/rex/post/meterpreter/client.rb
  lib/rex/post/meterpreter/client_core.rb
  lib/rex/post/meterpreter/extension_mapper.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb
  lib/rex/ui/text/dispatcher_shell.rb
  test/modules/post/test/meterpreter.rb
Labels: library, meterpreter, usability

#14748 Fix Auxiliary::AuthBrute when using DB_ALL_USERS and DB_ALL_PASS options
  lib/msf/core/auxiliary/auth_brute.rb
Labels: bug, database, library, module, rn-fix

#14740 CVE-2021-3156 Sudo LPE (AKA: Baron Samedit) Improvements
  data/exploits/CVE-2021-3156/exploit.c
  documentation/modules/exploit/linux/local/sudo_baron_samedit.md
  lib/msf/core/post/file.rb
  lib/msf/core/post/linux/compile.rb
  lib/msf/core/post/linux/system.rb
  modules/exploits/linux/local/sudo_baron_samedit.rb
Labels: enhancement, module

#14789 Fix session verification by checking TLV negotiation
  lib/msf/base/sessions/meterpreter.rb
  lib/msf/base/sessions/meterpreter_options.rb
  lib/rex/post/meterpreter/client_core.rb
Labels: bug, library, meterpreter

#14784 Update ScadaBR Credentials Dumper module
  documentation/modules/auxiliary/admin/http/scadabr_credential_dump.md
  modules/auxiliary/admin/http/scadabr_credential_dump.rb
Labels: bug, module

#14771 Add Apache Flink JAR Upload Java Code Execution
  documentation/modules/exploit/multi/http/apache_flink_jar_upload_exec.rb
  modules/exploits/multi/http/apache_flink_jar_upload_exec.rb
Labels: docs, module

#14766 Add Apache Flink JobManager Traversal
  documentation/modules/auxiliary/scanner/http/apache_flink_jobmanager_traversal.md
  modules/auxiliary/scanner/http/apache_flink_jobmanager_traversal.rb
Labels: docs, module

#14799 Fix missing constant error when accessing the api web service
  lib/msf/core/web_services/views/auth/account.erb
  lib/msf/core/web_services/views/auth/login.erb
Labels: bug

#14801 Re add color to search command
  Gemfile.lock
  lib/msf/ui/console/command_dispatcher/creds.rb
  lib/msf/ui/console/command_dispatcher/modules.rb
  spec/lib/msf/ui/console/command_dispatcher/creds_spec.rb
Labels: bug

#14802 Wrap kiwi cmd arguments in quotes
  lib/rex/post/meterpreter/ui/console/command_dispatcher/kiwi.rb
Labels: bug, easy, library, rn-fix

#14544 RDP Web Login User Enumeration Auxiliary Module
  documentation/modules/auxiliary/scanner/http/rdp_web_login.md
  lib/metasploit/framework/credential.rb
  lib/msf/core/module/external.rb
  lib/msf/core/modules/external/python/metasploit/module.py
  modules/auxiliary/scanner/http/rdp_web_login.py
Labels: docs, module, needs-linting

#14812 Add missing requires for scoks proxy
  lib/rex/proto/proxy/socks5/server_client.rb
Labels: bug

#14814 Disable Style/StringConcatenation Rubocop rule
  .rubocop.yml
Labels: rn-no-release-notes

#14783 Update KarjaSoft Sami FTP Server v2.0.2 USER Overflow module
  documentation/modules/exploit/windows/ftp/sami_ftpd_user.md
  modules/exploits/windows/ftp/sami_ftpd_user.rb
Labels: enhancement, module

#14518 add fortios path traversal (cve-2018-13379)
  documentation/modules/auxiliary/gather/fortios_vpnssl_traversal_creds_leak.md
  modules/auxiliary/gather/fortios_vpnssl_traversal_creds_leak.rb
Labels: docs, module
