Repository rapid7/metasploit-framework, pull requests merged in 2022-04, with the labels that each got.

#16320 Add debug option for windows meterpreter
  Gemfile.lock
  lib/msf/base/sessions/meterpreter_options.rb
  lib/msf/core/payload/windows/meterpreter_loader.rb
  lib/msf/core/payload/windows/x64/meterpreter_loader_x64.rb
  metasploit-framework.gemspec
  modules/payloads/singles/python/meterpreter_bind_tcp.rb
  modules/payloads/singles/python/meterpreter_reverse_http.rb
  modules/payloads/singles/python/meterpreter_reverse_https.rb
  modules/payloads/singles/python/meterpreter_reverse_tcp.rb
Labels: rn-enhancement

#16299 Make TLV Logging cache threadsafe
  lib/rex/post/meterpreter/command_mapper.rb
Labels: library, bug

#16408 postgres_copy_from_program_cmd_exec: Quote table name
  modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
Labels: module, bug

#16399 Add in CVE-2022-28381 - AllMediaServer 1.6 Buffer Overflow Exploit
  documentation/modules/exploit/windows/misc/cve_2022_28381_allmediaserver_bof.md
  modules/exploits/windows/misc/cve_2022_28381_allmediaserver_bof.rb
Labels: module, docs

#16403 Improve Qemu/KVM detection for BOCHS HW
  modules/post/windows/gather/checkvm.rb
Labels: enhancement

#16401 Add CVE-2022-22616 to gatekeeper bypass module
  documentation/modules/exploit/osx/browser/osx_gatekeeper_bypass.md
  modules/exploits/osx/browser/osx_gatekeeper_bypass.rb
Labels: module, rn-modules

#16082 Add ShadowMitmDispatcher to the smb_shadow module
  Gemfile.lock
  documentation/modules/exploit/windows/smb/smb_shadow.md
  lib/msf/core/exploit/smb/shadow_mitm_dispatcher.rb
  modules/exploits/windows/smb/smb_shadow.rb
Labels: module, library, enhancement, rn-modules

#15972 Updated log4shell HTTP scanner
  documentation/modules/auxiliary/scanner/http/log4shell_scanner.md
  modules/auxiliary/scanner/http/log4shell_scanner.rb
Labels: module, enhancement

#16419 Fix crash when sorting modules by disclosure date
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: library, bug, rn-fix

#16398 add missing payload tests
  spec/modules/payloads_spec.rb
  tools/modules/missing_payload_tests.rb
Labels: bug, rn-fix

#16373 Add initial ruby 3.1 support
  .github/workflows/verify.yml
  Gemfile.lock
  lib/msf/base/simple/auxiliary.rb
  lib/msf/base/simple/exploit.rb
  lib/msf/core/db_manager.rb
  lib/msf/core/exploit/remote/kerberos/client/as_request.rb
  lib/msf/core/exploit/remote/kerberos/client/tgs_request.rb
  lib/msf/core/exploit/remote/vim_soap.rb
  lib/msfenv.rb
  metasploit-framework.gemspec
  msfdb
  spec/api/json_rpc_spec.rb
  spec/file_fixtures/json_rpc/auxiliary/scanner/http/title.rb
  spec/lib/msf/ui/console/command_dispatcher/exploit_spec.rb
  spec/support/shared/contexts/msf/simple/framework.rb
Labels: ruby-compat

#16382 CVE-2022-26904 SuperProfile User Profile LPE
  LICENSE
  data/exploits/CVE-2022-26904/CVE-2022-26904.dll
  data/templates/src/pe/dll/template.c
  data/templates/src/pe/dll_gdiplus/template.c
  data/templates/template_x64_windows.dll
  data/templates/template_x86_windows.dll
  documentation/modules/exploit/windows/local/cve_2022_26904_superprofile.md
  external/source/exploits/CVE-2022-26904/SuperProfileDLL.sln
  external/source/exploits/CVE-2022-26904/SuperProfileDLL/NtDefine.h
  external/source/exploits/CVE-2022-26904/SuperProfileDLL/ProfSvcLPE.aps
  external/source/exploits/CVE-2022-26904/SuperProfileDLL/ProfSvcLPE.cpp
  external/source/exploits/CVE-2022-26904/SuperProfileDLL/ProfSvcLPE.h
  external/source/exploits/CVE-2022-26904/SuperProfileDLL/SuperProfileDLL.vcxproj
  external/source/exploits/CVE-2022-26904/SuperProfileDLL/Win-Ops-Master.cpp
  external/source/exploits/CVE-2022-26904/SuperProfileDLL/Win-Ops-Master.h
  external/source/exploits/CVE-2022-26904/SuperProfileDLL/dllmain.cpp
  external/source/exploits/CVE-2022-26904/SuperProfileDLL/resource.h
  modules/exploits/windows/local/cve_2022_26904_superprofile.rb
Labels: module, docs, rn-modules

#16418 Add debugging Meterpreter sessions navigation entry
  docs/build.rb
  docs/navigation.rb
Labels: docs

#16377 Add debug option to Python Meterpreter
  Gemfile.lock
  lib/msf/base/sessions/meterpreter_options.rb
  lib/msf/core/opt_meterpreter_debug_logging.rb
  lib/msf/core/payload/python/meterpreter_loader.rb
  metasploit-framework.gemspec
  modules/payloads/singles/python/meterpreter_bind_tcp.rb
  modules/payloads/singles/python/meterpreter_reverse_http.rb
  modules/payloads/singles/python/meterpreter_reverse_https.rb
  modules/payloads/singles/python/meterpreter_reverse_tcp.rb
  spec/lib/msf/core/opt_meterpreter_debug_logging_spec.rb
Labels: enhancement

#16396 Add toggleable logging to console & file to PHP Meterpreter
  Gemfile.lock
  metasploit-framework.gemspec
  modules/payloads/singles/php/meterpreter_reverse_tcp.rb
  modules/payloads/stages/php/meterpreter.rb
Labels: meterpreter, delayed, enhancement

#16221 Adjust wordpress_url_rest_api definition to support sites that don't place REST API under /index.php/
  lib/msf/core/exploit/remote/http/wordpress/uris.rb
Labels: library, bug, easy

#16451 Use debug versions of extensions if `MeterpreterDebugBuild` is enabled
  lib/msf/base/sessions/meterpreter.rb
  lib/msf/core/payload/windows/meterpreter_loader.rb
  lib/msf/core/payload/windows/x64/meterpreter_loader_x64.rb
  lib/rex/payloads/meterpreter/config.rb
  lib/rex/post/meterpreter/client.rb
  lib/rex/post/meterpreter/client_core.rb
  modules/payloads/singles/windows/meterpreter_bind_named_pipe.rb
  modules/payloads/singles/windows/meterpreter_bind_tcp.rb
  modules/payloads/singles/windows/meterpreter_reverse_http.rb
  modules/payloads/singles/windows/meterpreter_reverse_https.rb
  modules/payloads/singles/windows/meterpreter_reverse_ipv6_tcp.rb
  modules/payloads/singles/windows/meterpreter_reverse_tcp.rb
  modules/payloads/singles/windows/x64/meterpreter_bind_named_pipe.rb
  modules/payloads/singles/windows/x64/meterpreter_bind_tcp.rb
  modules/payloads/singles/windows/x64/meterpreter_reverse_http.rb
  modules/payloads/singles/windows/x64/meterpreter_reverse_https.rb
  modules/payloads/singles/windows/x64/meterpreter_reverse_ipv6_tcp.rb
  modules/payloads/singles/windows/x64/meterpreter_reverse_tcp.rb
  spec/lib/rex/post/meterpreter/client_core_spec.rb
Labels: library, enhancement

#16455 Remove railgun requirement from post file mixin
  lib/msf/core/post/file.rb
Labels: rn-fix

#16318 Added support to old key exchange algorithms
  lib/msf/core/exploit/remote/ssh.rb
  modules/exploits/unix/ssh/tectia_passwd_changereq.rb
Labels: library, bug

#16458 fortios_vpnssl_traversal_creds_leak: Add authors, notes, and references
  modules/auxiliary/gather/fortios_vpnssl_traversal_creds_leak.rb
Labels: module, enhancement, easy, rn-enhancement

#16461 Move getsimplecms_unauth_code_exec.md documentation to http dir
  documentation/modules/exploit/multi/http/getsimplecms_unauth_code_exec.md
Labels: docs, easy, rn-no-release-notes

#16359 Added Documentation for auxiliary/scanner/ip/ipidseq
  documentation/modules/auxiliary/scanner/ip/ipidseq.md
Labels: docs

#16426 Fix staged meterpreter on MacOS Monterey (12.2)
  data/meterpreter/x64_osx_stage
  external/source/shellcode/osx/stager/main.c
  modules/payloads/stages/osx/x64/meterpreter.rb
Labels: payload, rn-fix, osx

#16457 restore multi-char short flag support
  lib/rex/parser/arguments.rb
  spec/rex/parser/arguments_spec.rb
Labels: bug

#16476 msftidy: Prefer CVE references over cve.mitre.org URL references
  tools/dev/msftidy.rb
Labels: msftidy, easy

#16477 Modules: Prefer CVE references over cve.mitre.org URL references
  modules/auxiliary/admin/http/grafana_auth_bypass.py
  modules/exploits/linux/http/apache_druid_js_rce.rb
  modules/exploits/linux/http/efw_chpasswd_exec.rb
  modules/exploits/linux/http/supervisor_xmlrpc_exec.rb
  modules/exploits/linux/http/tp_link_ncxxx_bonjour_command_injection.rb
  modules/exploits/linux/local/netfilter_xtables_heap_oob_write_priv_esc.rb
  modules/exploits/multi/fileformat/archive_tar_arb_file_write.rb
  modules/exploits/multi/http/tomcat_jsp_upload_bypass.rb
  modules/exploits/unix/dhcp/rhel_dhcp_client_command_injection.rb
  modules/exploits/unix/ssh/arista_tacplus_shell.rb
  modules/exploits/windows/fileformat/vlc_mkv.rb
Labels: enhancement, rn-enhancement

#16379 Making SSH defaults widely used
  lib/metasploit/framework/login_scanner/ssh.rb
  lib/msf/core/exploit/remote/ssh.rb
  modules/auxiliary/scanner/ssh/apache_karaf_command_execution.rb
  modules/auxiliary/scanner/ssh/eaton_xpert_backdoor.rb
  modules/auxiliary/scanner/ssh/fortinet_backdoor.rb
  modules/auxiliary/scanner/ssh/juniper_backdoor.rb
  modules/auxiliary/scanner/ssh/libssh_auth_bypass.rb
  modules/auxiliary/scanner/ssh/ssh_enumusers.rb
  modules/exploits/apple_ios/ssh/cydia_default_ssh.rb
  modules/exploits/linux/http/alienvault_exec.rb
  modules/exploits/linux/http/cisco_firepower_useradd.rb
  modules/exploits/linux/http/ubiquiti_airos_file_upload.rb
  modules/exploits/linux/ssh/ceragon_fibeair_known_privkey.rb
  modules/exploits/linux/ssh/cisco_ucs_scpuser.rb
  modules/exploits/linux/ssh/exagrid_known_privkey.rb
  modules/exploits/linux/ssh/f5_bigip_known_privkey.rb
  modules/exploits/linux/ssh/ibm_drm_a3user.rb
  modules/exploits/linux/ssh/loadbalancerorg_enterprise_known_privkey.rb
  modules/exploits/linux/ssh/mercurial_ssh_exec.rb
  modules/exploits/linux/ssh/microfocus_obr_shrboadmin.rb
  modules/exploits/linux/ssh/quantum_dxi_known_privkey.rb
  modules/exploits/linux/ssh/quantum_vmpro_backdoor.rb
  modules/exploits/linux/ssh/solarwinds_lem_exec.rb
  modules/exploits/linux/ssh/symantec_smg_ssh.rb
  modules/exploits/linux/ssh/vmware_vdp_known_privkey.rb
  modules/exploits/linux/ssh/vyos_restricted_shell_privesc.rb
  modules/exploits/multi/ssh/sshexec.rb
  modules/exploits/unix/http/schneider_electric_net55xx_encoder.rb
  modules/exploits/unix/ssh/arista_tacplus_shell.rb
  modules/exploits/unix/ssh/array_vxag_vapv_privkey_privesc.rb
  modules/exploits/windows/ssh/sysax_ssh_username.rb
  spec/lib/metasploit/framework/login_scanner/ssh_spec.rb
Labels: bug, easy

#16437 add esxi to ssh_login platforms
  lib/metasploit/framework/ssh/platform.rb
Labels: library, enhancement, easy

#16479 Meterpreter's `reg setval` command: add support to binary data when setting a REG_BINARY key value
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/sys.rb
Labels: meterpreter, bug, rn-fix

#16438 smtp server can prompt for auth
  documentation/modules/auxiliary/server/capture/smtp.md
  modules/auxiliary/server/capture/smtp.rb
Labels: module, enhancement, easy

#16422 Add module for cve-2022-0995
  data/exploits/cve-2022-0995/cve-2022-0995.x64.elf
  documentation/modules/exploit/linux/local/cve_2022_0995_watch_queue.md
  external/source/exploits/cve-2022-0995/cve-2022-0995.c
  external/source/exploits/cve-2022-0995/cve-2022-0995_debug.c
  modules/exploits/linux/local/cve_2022_0995_watch_queue.rb
Labels: module, rn-modules

#16432 Enumerate Windows AV via WMI root\SecurityCenter2
  documentation/modules/post/windows/gather/enum_av.md
  modules/post/windows/gather/enum_av.rb
Labels: module, easy, needs-docs

#16450 VNC Keyboard Exec: Avoid typing too fast
  modules/exploits/multi/vnc/vnc_keyboard_exec.rb
Labels: module, bug, easy

#16486 Add initial pentesting docs section
  docs/Gemfile.lock
  docs/build.rb
  docs/navigation.rb
Labels: docs, rn-enhancement

#16504 Redis Sandbox Escape RCE (CVE-2022-0543)
  documentation/modules/exploit/linux/redis/redis_debian_sandbox_escape.md
  modules/exploits/linux/redis/redis_debian_sandbox_escape.rb
Labels: module, docs

#16509 Ensure HTML is escaped in markdown codeblocks
  documentation/modules/exploit/windows/smb/smb_relay.md
  lib/msf/util/document_generator/document_normalizer.rb
Labels: bug

#16439 [Test module] Remove obsolete PostgreSQL test module. Replace it with one for all the supported DBMS
  test/modules/auxiliary/test/sqli_test.rb
Labels: enhancement, rn-no-release-notes, test module

#16507 Add WSO2 file upload RCE module
  documentation/modules/exploit/multi/http/wso2_file_upload_rce.md
  modules/exploits/multi/http/wso2_file_upload_rce.rb
Labels: module, docs, rn-modules
