Repository rapid7/metasploit-framework, pull requests merged in 2022-11, with the labels that each got.

#17168 Add module for Webmin auth File Manager RCE (CVE-2022-0824)
  documentation/modules/exploit/linux/http/webmin_file_manager_rce.md
  lib/msf/core/exploit/remote/http/webmin.rb
  lib/msf/core/exploit/remote/http/webmin/check.rb
  lib/msf/core/exploit/remote/http/webmin/login.rb
  modules/exploits/linux/http/webmin_file_manager_rce.rb
Labels: module, docs

#17190 Fix the Netapi32 bufptr data type
  lib/msf/core/post/windows/accounts.rb
  lib/rex/post/meterpreter/extensions/stdapi/railgun/def/windows/def_netapi32.rb
  lib/rex/post/meterpreter/extensions/stdapi/railgun/library.rb
Labels: library, bug, rn-fix

#17213 Update identify hash library and call
  modules/post/linux/gather/vcenter_secrets_dump.rb
Labels: bug, rn-fix

#17192 Password Manager Pro password recovery post module
  documentation/modules/post/linux/gather/manageengine_password_manager_creds.md
  modules/post/linux/gather/manageengine_password_manager_creds.rb
Labels: module, docs

#17084 Add Kerberos keytab module
  documentation/modules/auxiliary/admin/kerberos/keytab.md
  lib/rex/proto/kerberos/credential_cache/krb5_ccache_credential_keyblock.rb
  lib/rex/proto/kerberos/credential_cache/krb5_ccache_principal.rb
  lib/rex/proto/kerberos/crypto.rb
  lib/rex/proto/kerberos/keytab.rb
  lib/rex/proto/kerberos/keytab/krb5_keytab.rb
  modules/auxiliary/admin/kerberos/keytab.rb
  spec/lib/rex/proto/kerberos/keytab/krb5_keytab_spec.rb
  spec/modules/auxiliary/admin/kerberos/keytab_spec.rb
Labels: module, library, docs

#17220 Fix pe inject payload crash
  lib/msf/core/payload/windows/pe_inject.rb
Labels: library, bug, easy

#17219 Fix broken zabbix_login scanner regex for new versions
  lib/metasploit/framework/login_scanner/zabbix.rb
Labels: bug, easy

#17225 Update YARD documentation to use proper @return instead of @returns
  lib/msf/core/rpc/json/client.rb
  lib/msf/core/rpc/json/dispatcher.rb
  lib/msf/core/rpc/json/dispatcher_helper.rb
  lib/msf/core/rpc/json/error.rb
  lib/msf/core/rpc/json/request.rb
  lib/msf/core/rpc/json/response.rb
  lib/msf/core/rpc/json/rpc_command.rb
  lib/msf/core/rpc/json/rpc_command_factory.rb
  lib/msf/core/rpc/json/v1_0/rpc_command.rb
Labels: library, docs, easy

#17122 Add in ESC Finder Module (ESC1-ESC3)
  documentation/modules/auxiliary/gather/ldap_esc_vulnerable_cert_finder.md
  lib/msf/core/exploit/remote/ldap.rb
  lib/rex/proto/ms_dtyp.rb
  modules/auxiliary/gather/ldap_esc_vulnerable_cert_finder.rb
  modules/auxiliary/gather/ldap_query.rb
Labels: module, needs-docs

#17234 Adds references to `info -d` command in `options` and `info` command outputs
  lib/msf/ui/console/command_dispatcher/common.rb
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: library, enhancement, rn-enhancement

#17211 Compress Python payloads before base64 encoding
  lib/msf/core/payload/python.rb
  modules/payloads/singles/cmd/unix/reverse_python_ssl.rb
  modules/payloads/singles/python/meterpreter_bind_tcp.rb
  modules/payloads/singles/python/meterpreter_reverse_http.rb
  modules/payloads/singles/python/meterpreter_reverse_https.rb
  modules/payloads/singles/python/meterpreter_reverse_tcp.rb
  modules/payloads/singles/python/pingback_bind_tcp.rb
  modules/payloads/singles/python/pingback_reverse_tcp.rb
  modules/payloads/singles/python/shell_bind_tcp.rb
  modules/payloads/singles/python/shell_reverse_tcp.rb
  modules/payloads/singles/python/shell_reverse_tcp_ssl.rb
  modules/payloads/singles/python/shell_reverse_udp.rb
  modules/payloads/stagers/python/bind_tcp.rb
  modules/payloads/stagers/python/bind_tcp_uuid.rb
  modules/payloads/stagers/python/reverse_http.rb
  modules/payloads/stagers/python/reverse_https.rb
  modules/payloads/stagers/python/reverse_tcp.rb
  modules/payloads/stagers/python/reverse_tcp_ssl.rb
  modules/payloads/stagers/python/reverse_tcp_uuid.rb
  spec/modules/payloads_spec.rb
Labels: library, payload, rn-enhancement

#17045 Add module for converting kerberos ticket formats
  lib/msf/core/exploit/remote/kerberos/ticket_converter.rb
  lib/rex/proto/kerberos/model/enc_kdc_response.rb
  lib/rex/proto/kerberos/model/enc_krb_cred_part.rb
  lib/rex/proto/kerberos/model/encrypted_data.rb
  lib/rex/proto/kerberos/model/encryption_key.rb
  lib/rex/proto/kerberos/model/krb_cred.rb
  lib/rex/proto/kerberos/model/krb_cred_info.rb
  lib/rex/proto/kerberos/model/principal_name.rb
  lib/rex/proto/kerberos/model/ticket.rb
  modules/auxiliary/admin/kerberos/ticket_converter.rb
  spec/lib/msf/core/exploit/remote/kerberos/ticket_converter_spec.rb
  spec/lib/rex/proto/kerberos/model/enc_krb_cred_part_spec.rb
  spec/lib/rex/proto/kerberos/model/krb_cred_info_spec.rb
  spec/lib/rex/proto/kerberos/model/krb_cred_spec.rb
Labels: module, library, docs

#17239 Fix broken kerberos login module
  lib/msf/core/exploit/remote/kerberos/client.rb
Labels: bug

#17223 Improves the `reload_lib -a` commands ability to track modified files
  lib/msf/ui/console/command_dispatcher/developer.rb
Labels: library, enhancement, rn-enhancement

#17229 Add post/multi/recon/reverse_lookup
  documentation/modules/post/multi/recon/reverse_lookup.md
  modules/post/multi/recon/reverse_lookup.rb
  modules/post/windows/gather/reverse_lookup.rb
  modules/post/windows/recon/resolve_ip.rb
Labels: module, enhancement

#17077 Add support for AES keys for silver/golden ticket forging
  documentation/modules/auxiliary/admin/kerberos/forge_ticket.md
  lib/msf/core/exploit/remote/kerberos/ticket.rb
  lib/rex/proto/kerberos/pac/priv_svr_checksum.rb
  lib/rex/proto/kerberos/pac/server_checksum.rb
  modules/auxiliary/admin/kerberos/forge_ticket.rb
  spec/lib/msf/core/exploit/remote/kerberos/ticket_spec.rb
Labels: module, library, docs

#17177 fix: Handle search terms ending in colons.
  lib/msf/core/modules/metadata/search.rb
  spec/lib/msf/core/modules/metadata/search_spec.rb
Labels: bug, rn-fix

#17244 Fix an error when a hostname fails to resolve
  lib/rex/post/meterpreter/extensions/stdapi/net/resolve.rb
Labels: bug, payload, rn-fix

#17252 Adds error handling for users who do not have git available on their environment
  lib/msf/ui/console/command_dispatcher/developer.rb
Labels: bug

#17261 Fix Port Forwarding For Ruby 3
  lib/rex/post/meterpreter/extensions/stdapi/net/socket_subsystem/tcp_server_channel.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/net.rb
Labels: library, bug

#17243 Improve tlv packet logging for railgun
  lib/rex/post/meterpreter/command_mapper.rb
Labels: library, enhancement, rn-enhancement

#17240 Update icpr_cert for requesting certs on behalf of users
  Gemfile.lock
  documentation/modules/auxiliary/admin/dcerpc/icpr_cert.md
  lib/rex/proto/crypto_asn1.rb
  lib/rex/proto/kerberos/model.rb
  modules/auxiliary/admin/dcerpc/icpr_cert.rb
  spec/modules/auxiliary/admin/dcerpc/icpr_cert_spec.rb
Labels: module, library, docs

#17257 Adding exploit for ChurchInfo 1.2.13-1.3.0 RCE (CVE-2021-43258)
  documentation/modules/exploit/multi/http/churchinfo_upload_exec.md
  modules/exploits/multi/http/churchinfo_upload_exec.rb
Labels: module, docs, rn-modules

#17285 tor_hiddenservices: Check locate command exists
  modules/post/linux/gather/tor_hiddenservices.rb
Labels: module, bug, easy

#17284 modules/post/linux/gather: Use Post::Linux::System.get_hostname method
  modules/post/linux/gather/enum_network.rb
  modules/post/linux/gather/tor_hiddenservices.rb
Labels: module, easy, code quality

#17288 Support for Windows Access mask to MsDtypAccessMask
  lib/rex/proto/ms_dtyp.rb
Labels: library, enhancement, rn-no-release-notes

#17273 F5 exploit module CVE-2022-41800 (authenticated RCE in RPM code)
  documentation/modules/exploit/linux/http/f5_icontrol_rpmspec_rce_cve_2022_41800.md
  modules/exploits/linux/http/f5_icontrol_rpmspec_rce_cve_2022_41800.rb
Labels: module, docs

#17296 add warning about external links
  documentation/modules/exploit/linux/http/github_enterprise_secret.md
  documentation/modules/exploit/linux/http/logsign_exec.md
  documentation/modules/exploit/linux/http/unraid_auth_bypass_exec.md
  documentation/modules/post/windows/gather/credentials/purevpn_cred_collector.md
Labels: docs

#17226 Module to request TGT/TGS Kerberos tickets from the KDC
  documentation/modules/auxiliary/admin/kerberos/get_ticket.md
  lib/msf/core/exploit/remote/kerberos/client.rb
  modules/auxiliary/admin/kerberos/get_ticket.rb
Labels: module, docs, feature-kerberos-authentication

#17087 remote control collection rce
  documentation/modules/exploit/windows/misc/remote_control_collection_rce.md
  modules/exploits/windows/misc/remote_control_collection_rce.rb
Labels: module, docs

#17299 Fixes #17227 - polkit_dbus_auth_bypass module when run from a command…
  lib/msf/core/session/provider/single_command_shell.rb
  modules/exploits/linux/local/polkit_dbus_auth_bypass.rb
Labels: module, library, bug

#17309 Fix crash in kerberos get ticket module
  modules/auxiliary/admin/kerberos/get_ticket.rb
Labels: bug, feature-kerberos-authentication
