Repository rapid7/metasploit-framework, pull requests merged in 2022-06, with the labels that each got.

#16435 Microsoft SQL Server injection support + BillQuick SQLi module update
  lib/msf/core/exploit/sqli/mssqli.rb
  lib/msf/core/exploit/sqli/mssqli/boolean_based_blind.rb
  lib/msf/core/exploit/sqli/mssqli/common.rb
  lib/msf/core/exploit/sqli/mssqli/time_based_blind.rb
  modules/auxiliary/gather/billquick_txtid_sqli.rb
Labels: module, library, enhancement, rn-enhancement

#16611 DotCMS File Upload to RCE Module (CVE-2022-26352)
  documentation/modules/exploit/multi/http/dotcms_file_upload_rce.md
  modules/exploits/multi/http/dotcms_file_upload_rce.rb
Labels: module

#16635 add. Supposed 0day MSWord RCE #Follina
  data/exploits/word_msdtjs.docx
  documentation/modules/exploit/windows/fileformat/word_msdtjs_rce.md
  modules/exploits/windows/fileformat/word_msdtjs_rce.rb
Labels: module, docs, rn-modules

#16583 Bump payloads version to 2.0.93
  Gemfile.lock
  metasploit-framework.gemspec
  modules/payloads/singles/php/meterpreter_reverse_tcp.rb
  modules/payloads/singles/python/meterpreter_bind_tcp.rb
  modules/payloads/singles/python/meterpreter_reverse_http.rb
  modules/payloads/singles/python/meterpreter_reverse_https.rb
  modules/payloads/singles/python/meterpreter_reverse_tcp.rb
  modules/payloads/singles/windows/meterpreter_bind_named_pipe.rb
  modules/payloads/singles/windows/meterpreter_bind_tcp.rb
  modules/payloads/singles/windows/meterpreter_reverse_http.rb
  modules/payloads/singles/windows/meterpreter_reverse_https.rb
  modules/payloads/singles/windows/meterpreter_reverse_ipv6_tcp.rb
  modules/payloads/singles/windows/meterpreter_reverse_tcp.rb
Labels: rn-no-release-notes

#16645 Weekly dependency updates for Gemfile.lock
  Gemfile.lock
Labels: rn-no-release-notes

#16615 Solicited multicast-address creation bugfix
  lib/msf/core/exploit/remote/ipv6.rb
Labels: library, bug

#16644 Add Exploit for CVE-2022-26134 (Confluence RCE)
  documentation/modules/exploit/multi/http/atlassian_confluence_namespace_ognl_injection.md
  modules/exploits/multi/http/atlassian_confluence_namespace_ognl_injection.rb
Labels: module, docs

#16658 Move kerberos tests to be under the remote folder
  spec/lib/msf/core/exploit/remote/kerberos/client/as_request_spec.rb
  spec/lib/msf/core/exploit/remote/kerberos/client/as_response_spec.rb
  spec/lib/msf/core/exploit/remote/kerberos/client/base_spec.rb
  spec/lib/msf/core/exploit/remote/kerberos/client/cache_credential_spec.rb
  spec/lib/msf/core/exploit/remote/kerberos/client/pac_spec.rb
  spec/lib/msf/core/exploit/remote/kerberos/client/tgs_request_spec.rb
  spec/lib/msf/core/exploit/remote/kerberos/client/tgs_response_spec.rb
Labels: rn-no-release-notes, feature-kerberos-authentication

#16651 [SQLi library] Ensure the encoder is always used in the #test_vulnerable methods
  lib/msf/core/exploit/sqli/mssqli/common.rb
  lib/msf/core/exploit/sqli/mysqli/common.rb
  lib/msf/core/exploit/sqli/postgresqli/common.rb
  lib/msf/core/exploit/sqli/sqlitei/common.rb
Labels: library, enhancement, rn-enhancement

#16665 Fix random compile c tool
  tools/exploit/random_compile_c.rb
Labels: bug, rn-fix

#16666 Correctly format the notes sections
  modules/auxiliary/admin/http/wp_automatic_plugin_privesc.rb
  modules/auxiliary/admin/http/wp_gdpr_compliance_privesc.rb
  modules/exploits/linux/misc/cisco_rv340_sslvpn.rb
  modules/exploits/unix/webapp/bolt_authenticated_rce.rb
  modules/exploits/windows/browser/malwarebytes_update_exec.rb
Labels: rn-no-release-notes

#16667 Weekly dependency updates for Gemfile.lock
  Gemfile.lock
Labels: rn-no-release-notes, automation

#16654 Add named pipe pivot documentation
  docs/metasploit-framework.wiki/Pivoting-in-Metasploit.md
Labels: docs

#16627 Add some error handling to update_payload_cache_size script
  tools/modules/update_payload_cached_sizes.rb
Labels: bug, easy, rn-fix

#16602 Fix error when service is already running and update exception documentation in lib/msf/core/post/windows/services.rb
  lib/msf/core/post/windows/services.rb
Labels: library, bug, rn-fix

#16678 Support decoding pa_data as part of kdc enc response
  lib/rex/proto/kerberos/model.rb
  lib/rex/proto/kerberos/model/element.rb
  lib/rex/proto/kerberos/model/enc_kdc_response.rb
  spec/lib/rex/proto/kerberos/model/enc_kdc_response_spec.rb
Labels: feature-kerberos-authentication

#16660 Fix Kerberos flags decoding logic
  lib/msf/core/exploit/remote/kerberos/client/cache_credential.rb
  lib/rex/proto/kerberos/model.rb
  lib/rex/proto/kerberos/model/enc_kdc_response.rb
  lib/rex/proto/kerberos/model/kdc_option_flag.rb
  lib/rex/proto/kerberos/model/kdc_option_flags.rb
  lib/rex/proto/kerberos/model/kdc_request_body.rb
  spec/lib/rex/proto/kerberos/model/enc_kdc_response_spec.rb
  spec/lib/rex/proto/kerberos/model/kdc_option_flags_spec.rb
Labels: feature-kerberos-authentication

#16650 Add #read_from_file for MSSQL and PostgreSQL, fix the MySQL implementation
  lib/msf/core/exploit/sqli/mssqli/common.rb
  lib/msf/core/exploit/sqli/mysqli/common.rb
  lib/msf/core/exploit/sqli/postgresqli/common.rb
  test/modules/auxiliary/test/sqli_test.rb
Labels: module, library, enhancement, rn-enhancement

#16625 Add Kerberos LoginScanner support
  Gemfile.lock
  documentation/modules/auxiliary/scanner/kerberos/kerberos_login.md
  lib/metasploit/framework/credential_collection.rb
  lib/metasploit/framework/login_scanner/base.rb
  lib/metasploit/framework/login_scanner/kerberos.rb
  lib/metasploit/framework/login_scanner/result.rb
  lib/msf/core/exploit/remote/kerberos/auth_brute.rb
  lib/msf/core/exploit/remote/kerberos/client.rb
  lib/msf/core/exploit/remote/kerberos/client/as_request.rb
  lib/msf/core/exploit/remote/kerberos/client/as_response.rb
  lib/msf/core/exploit/remote/kerberos/model/tgt_response.rb
  lib/rex/proto/kerberos/README.md
  lib/rex/proto/kerberos/crypto.rb
  lib/rex/proto/kerberos/crypto/rc4_hmac.rb
  lib/rex/proto/kerberos/model.rb
  lib/rex/proto/kerberos/model/error.rb
  modules/auxiliary/gather/kerberos_enumusers.rb
  modules/auxiliary/scanner/kerberos/kerberos_login.rb
  spec/lib/metasploit/framework/credential_collection_spec.rb
  spec/lib/metasploit/framework/login_scanner/kerberos_spec.rb
  spec/lib/msf/core/exploit/remote/kerberos/client_spec.rb
Labels: feature-kerberos-authentication

#16689 Update Kerberos to support host addresses in tickets
  lib/rex/proto/kerberos/model/address_type.rb
  lib/rex/proto/kerberos/model/enc_kdc_response.rb
  lib/rex/proto/kerberos/model/host_address.rb
  lib/rex/proto/kerberos/model/kdc_request_body.rb
  spec/lib/rex/proto/kerberos/model/enc_kdc_response_spec.rb
  spec/lib/rex/proto/kerberos/model/host_address_spec.rb
  spec/lib/rex/proto/kerberos/model/kdc_request_body_spec.rb
Labels: feature-kerberos-authentication

#16685 Add missing Kerberos encryption types
  lib/msf/core/exploit/remote/kerberos/client.rb
  lib/msf/core/exploit/remote/kerberos/client/as_request.rb
  lib/msf/core/exploit/remote/kerberos/client/as_response.rb
  lib/msf/core/exploit/remote/kerberos/client/base.rb
  lib/msf/core/exploit/remote/kerberos/client/cache_credential.rb
  lib/msf/core/exploit/remote/kerberos/client/pac.rb
  lib/msf/core/exploit/remote/kerberos/client/tgs_request.rb
  lib/msf/core/exploit/remote/kerberos/client/tgs_response.rb
  lib/rex/proto/kerberos/crypto.rb
  lib/rex/proto/kerberos/crypto/aes128_cts_sha1.rb
  lib/rex/proto/kerberos/crypto/aes256_cts_sha1.rb
  lib/rex/proto/kerberos/crypto/aes_block_cipher_base.rb
  lib/rex/proto/kerberos/crypto/asn1_utils.rb
  lib/rex/proto/kerberos/crypto/block_cipher_base.rb
  lib/rex/proto/kerberos/crypto/des3_cbc_sha1.rb
  lib/rex/proto/kerberos/crypto/des_cbc_md5.rb
  lib/rex/proto/kerberos/crypto/rc4_hmac.rb
  lib/rex/proto/kerberos/crypto/rsa_md5.rb
  lib/rex/proto/kerberos/model.rb
  lib/rex/proto/kerberos/model/authenticator.rb
  lib/rex/proto/kerberos/model/authorization_data.rb
  lib/rex/proto/kerberos/model/enc_kdc_response.rb
  lib/rex/proto/kerberos/model/encrypted_data.rb
  lib/rex/proto/kerberos/model/kdc_request.rb
  lib/rex/proto/kerberos/model/kdc_request_body.rb
  lib/rex/proto/kerberos/model/kdc_response.rb
  lib/rex/proto/kerberos/model/krb_error.rb
  lib/rex/proto/kerberos/model/pre_auth_data_entry.rb
  lib/rex/proto/kerberos/model/pre_auth_enc_time_stamp.rb
  lib/rex/proto/kerberos/model/pre_auth_etype_info2.rb
  lib/rex/proto/kerberos/model/pre_auth_etype_info2_entry.rb
  lib/rex/proto/kerberos/pac/type.rb
  modules/auxiliary/admin/kerberos/ms14_068_kerberos_checksum.rb
  spec/lib/msf/core/exploit/remote/kerberos/client/as_request_spec.rb
  spec/lib/msf/core/exploit/remote/kerberos/client/base_spec.rb
  spec/lib/msf/core/exploit/remote/kerberos/client/pac_spec.rb
  spec/lib/msf/core/exploit/remote/kerberos/client/tgs_request_spec.rb
  spec/lib/rex/proto/kerberos/credential_cache/cache_spec.rb
  spec/lib/rex/proto/kerberos/credential_cache/credential_spec.rb
  spec/lib/rex/proto/kerberos/credential_cache/key_block.rb
  spec/lib/rex/proto/kerberos/crypto/aes128_cts_sha1_spec.rb
  spec/lib/rex/proto/kerberos/crypto/aes256_cts_sha1_spec.rb
  spec/lib/rex/proto/kerberos/crypto/asn1_utils_spec.rb
  spec/lib/rex/proto/kerberos/crypto/des3_cbc_sha1_spec.rb
  spec/lib/rex/proto/kerberos/crypto/des_cbc_md5_spec.rb
  spec/lib/rex/proto/kerberos/crypto/rc4_hmac_spec.rb
  spec/lib/rex/proto/kerberos/model/ap_req_spec.rb
  spec/lib/rex/proto/kerberos/model/authenticator_spec.rb
  spec/lib/rex/proto/kerberos/model/checksum_spec.rb
  spec/lib/rex/proto/kerberos/model/enc_kdc_response_spec.rb
  spec/lib/rex/proto/kerberos/model/encrypted_data_spec.rb
  spec/lib/rex/proto/kerberos/model/etype_info2_spec.rb
  spec/lib/rex/proto/kerberos/model/kdc_request_body_spec.rb
  spec/lib/rex/proto/kerberos/model/krb_error_spec.rb
  spec/lib/rex/proto/kerberos/model/pre_auth_data_spec.rb
  spec/lib/rex/proto/kerberos/model/pre_auth_enc_time_stamp_spec.rb
  spec/lib/rex/proto/kerberos/model/pre_auth_pac_request_spec.rb
  spec/lib/rex/proto/kerberos/pac/priv_srv_checksum_spec.rb
  spec/lib/rex/proto/kerberos/pac/server_checksum_spec.rb
Labels: feature-kerberos-authentication

#16676 Add 6th `getsystem` technique - EFSRPC Named Pipe Impersonation (AKA EfsPotato)
  Gemfile.lock
  lib/rex/post/meterpreter/extensions/priv/priv.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/priv/elevate.rb
  metasploit-framework.gemspec
  modules/post/windows/escalate/getsystem.rb
Labels: meterpreter, delayed, enhancement, rn-modules

#16702 Fix reference URL link in hikvision_rtsp_bof.rb
  modules/exploits/linux/misc/hikvision_rtsp_bof.rb
Labels: easy

#16722 exploit/multi/misc/nomad_exec: Fix notes for SideEffects and Reliability
  modules/exploits/multi/misc/nomad_exec.rb
Labels: easy

#16721 Phpmailer arg injection update
  documentation/modules/exploit/multi/http/phpmailer_arg_injection.md
  modules/exploits/multi/http/phpmailer_arg_injection.rb
Labels: module, enhancement

#16705 Fix bugs in previous etypes work
  lib/msf/core/exploit/remote/kerberos/client.rb
Labels: feature-kerberos-authentication

#16729 Fix Rex Table crashing on unknown characters
  Gemfile.lock
Labels: library, bug, rn-fix

#16677 Add module for adding/deleting computers via MS-SAMR
  Gemfile.lock
  documentation/modules/auxiliary/admin/dcerpc/samr_computer.md
  modules/auxiliary/admin/dcerpc/samr_computer.rb
Labels: module, docs, rn-modules
