Repository rapid7/metasploit-framework, pull requests merged in 2022-10, with the labels that each got.

#17091 Modules: Fix Stability/SideEffects/Reliability notes for several modules
  modules/auxiliary/admin/http/tomcat_ghostcat.rb
  modules/auxiliary/dos/windows/http/http_sys_accept_encoding_dos_cve_2021_31166.rb
  modules/exploits/android/local/janus.rb
  modules/exploits/linux/http/bitbucket_git_cmd_injection.rb
  modules/exploits/linux/http/geutebruck_cmdinject_cve_2021_335xx.rb
  modules/exploits/linux/http/geutebruck_instantrec_bof.rb
  modules/exploits/multi/http/qdpm_authenticated_rce.rb
  modules/exploits/windows/local/vss_persistence.rb
  modules/post/windows/manage/persistence_exe.rb
Labels: bug, easy

#17006 Gather_RedisDesktopManager_Password
  documentation/modules/post/windows/gather/credentials/redis_desktop_manager.md
  modules/post/windows/gather/credentials/redis_desktop_manager.rb
Labels: module, docs

#17099 cve-2022-1329 (wordpress elementor plugin)
  data/wordlists/wp-exploitable-plugins.txt
  documentation/modules/exploit/multi/http/wp_plugin_elementor_auth_upload_rce.md
  modules/exploits/multi/http/wp_plugin_elementor_auth_upload_rce.rb
Labels: module, docs

#17067 remote mouse rce
  documentation/modules/exploit/windows/misc/remote_mouse_rce.md
  modules/exploits/windows/misc/remote_mouse_rce.rb
Labels: module, docs

#17093 CVE-2022-37706 Enlightenment linux priv esc
  documentation/modules/exploit/linux/local/ubuntu_enlightenment_mount_priv_esc.md
  modules/exploits/linux/local/ubuntu_enlightenment_mount_priv_esc.rb
Labels: module, docs

#17009 MobaXterm
  documentation/modules/post/windows/gather/credentials/moba_xterm.md
  modules/post/windows/gather/credentials/moba_xterm.rb
Labels: module, docs

#17075 Fix `gather/windows_secrets_dump` non-admin error
  modules/auxiliary/gather/windows_secrets_dump.rb
Labels: rn-fix

#17118 Fixes #16674 - Fixed "Manage Engine" and Updated the link
  documentation/modules/exploit/windows/http/manageengine_adshacluster_rce.md
  modules/exploits/windows/http/manageengine_adshacluster_rce.rb
Labels: module, rn-no-release-notes

#17057 Msf::Post::Windows::ExtAPI: Remove load_extapi method
  lib/msf/core/post/windows/accounts.rb
  lib/msf/core/post/windows/extapi.rb
  lib/msf/core/post/windows/ldap.rb
  modules/exploits/windows/local/wmi.rb
  modules/post/windows/gather/bitlocker_fvek.rb
  modules/post/windows/gather/credentials/domain_hashdump.rb
  modules/post/windows/gather/credentials/gpp.rb
  modules/post/windows/gather/enum_patches.rb
  modules/post/windows/manage/forward_pageant.rb
Labels: library

#17123 netrc and fetchmailrc docs
  documentation/modules/post/multi/gather/fetchmailrc_creds.md
  documentation/modules/post/multi/gather/netrc_creds.md
Labels: docs, rn-no-release-notes

#17092 netlm_downgrade: Cleanup and support non-Meterpreter sessions
  documentation/modules/post/windows/gather/netlm_downgrade.md
  modules/post/windows/gather/netlm_downgrade.rb
Labels: module, bug

#17116 Adding CVE-2022-22947 Spring Cloud Gateway RCE Exploit
  documentation/modules/exploit/linux/http/spring_cloud_gateway_rce.md
  modules/exploits/linux/http/spring_cloud_gateway_rce.rb
Labels: module, docs, rn-modules

#17032 Add module for pfSense pfBlockNG unauth RCE as root - CVE-2022-31814
  documentation/modules/exploit/unix/http/pfsense_pfblockerng_webshell.md
  modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb
Labels: module, docs, rn-modules

#16982 Update Dell iDRAC login scanner to work with v8 and v9
  data/wordlists/idrac_default_pass.txt
  documentation/modules/auxiliary/scanner/http/dell_idrac.md
  modules/auxiliary/scanner/http/dell_idrac.rb
Labels: enhancement

#17141 Check in zimbra_postfix_priv_esc.rb
  documentation/modules/exploit/linux/local/zimbra_postfix_priv_esc.md
  modules/exploits/linux/local/zimbra_postfix_priv_esc.rb
Labels: module, docs

#17165 Update commiters keys doc with updated info
  docs/metasploit-framework.wiki/Committer-Keys.md
  docs/metasploit-framework.wiki/Committer-Rights.md
Labels: docs, easy, rn-no-release-notes

#17050 Back from the dyld: a fileless loader. (Again.)
  data/meterpreter/x64_osx_stage
  external/source/shellcode/osx/stager/main.c
Labels: payload, enhancement

#17172 Msf::Post::File.append_file: Append not overwrite on *nix shell sessions
  lib/msf/core/post/file.rb
Labels: library, bug, rn-no-release-notes

#17071 Add in new LDAP queries to help with various attack paths
  data/auxiliary/gather/ldap_query/ldap_queries_default.yaml
Labels: module, enhancement

#17162 Add RCE module for CVE-2022-35914 php code injection
  documentation/modules/exploit/linux/http/glpi_htmlawed_php_injection.md
  modules/exploits/linux/http/glpi_htmlawed_php_injection.rb
Labels: module, docs, rn-modules

#17110 Look before leap (check files exist before doing other things)
  modules/exploits/linux/local/asan_suid_executable_priv_esc.rb
  modules/exploits/linux/local/glibc_ld_audit_dso_load_priv_esc.rb
  modules/exploits/linux/local/glibc_origin_expansion_priv_esc.rb
  modules/exploits/linux/local/hp_xglance_priv_esc.rb
  modules/exploits/linux/local/ktsuss_suid_priv_esc.rb
  modules/exploits/linux/local/libuser_roothelper_priv_esc.rb
  modules/exploits/linux/local/nested_namespace_idmap_limit_priv_esc.rb
  modules/exploits/linux/local/omniresolve_suid_priv_esc.rb
  modules/exploits/linux/local/polkit_dbus_auth_bypass.rb
  modules/exploits/linux/local/servu_ftp_server_prepareinstallation_priv_esc.rb
  modules/exploits/linux/local/systemtap_modprobe_options_priv_esc.rb
  modules/exploits/linux/local/vmware_mount.rb
  modules/exploits/unix/local/setuid_nmap.rb
  modules/post/multi/gather/aws_keys.rb
  modules/post/multi/gather/fetchmailrc_creds.rb
  modules/post/multi/gather/netrc_creds.rb
  modules/post/multi/recon/sudo_commands.rb
Labels: bug

#17164 Adding THEME_DIR option to wp_crop_rce exploit
  modules/exploits/multi/http/wp_crop_rce.rb
Labels: enhancement

#17185 Add additional usage tips
  lib/msf/ui/tip.rb
Labels: rn-enhancement

#17024 Add Meterpreter reg command documentation
  docs/build.rb
  docs/metasploit-framework.wiki/Meterpreter-Reg-Command.md
  docs/navigation.rb
Labels: docs, meterpreter

#17176 Python Meterpreter AES Constants
  lib/msf/core/payload/python/meterpreter_loader.rb
  modules/payloads/singles/python/meterpreter_bind_tcp.rb
  modules/payloads/singles/python/meterpreter_reverse_http.rb
  modules/payloads/singles/python/meterpreter_reverse_https.rb
  modules/payloads/singles/python/meterpreter_reverse_tcp.rb
Labels: library, payload

#17147 Add Vagrant Synced Folder Vagrantfile Breakout module
  documentation/modules/exploit/multi/local/vagrant_synced_folder_vagrantfile_breakout.md
  modules/exploits/multi/local/vagrant_synced_folder_vagrantfile_breakout.rb
Labels: module, docs

#17128 Adds support to specify a shared directory to iterate through and highlight keywords
  documentation/modules/auxiliary/scanner/smb/smb_enumshares.md
  modules/auxiliary/scanner/smb/smb_enumshares.rb
Labels: enhancement, needs-docs

#16871 Add vcenter_secrets_dump post module
  documentation/modules/post/linux/gather/vcenter_secrets_dump.md
  lib/msf/core/post/vcenter.rb
  lib/msf/core/post/vcenter/vcenter.rb
  modules/post/linux/gather/vcenter_secrets_dump.rb
  spec/lib/msf/core/post/vcenter/vcenter_spec.rb
Labels: module, library, docs

#17155 Remote mouse version updates
  documentation/modules/exploit/windows/misc/remote_mouse_rce.md
  modules/exploits/windows/misc/remote_mouse_rce.rb
Labels: enhancement

#17184 Support upload and download command for powershell and windows sessions
  lib/msf/base/sessions/command_shell.rb
Labels: bug, rn-enhancement

#17186 Fix broken file writes on windows when newlines are present
  lib/msf/core/post/file.rb
  spec/lib/msf/core/post/file_spec.rb
Labels: bug, rn-enhancement

#17195 Fix uploading binary file to windows shell command with identical name
  lib/msf/core/post/file.rb
Labels: bug, rn-enhancement

#17188 Fix the Python Meterpreter for v3.1-3.3
  data/meterpreter/python/met_aes.py
  data/meterpreter/python/met_rsa.py
  lib/msf/core/payload/python/meterpreter_loader.rb
  modules/payloads/singles/python/meterpreter_bind_tcp.rb
  modules/payloads/singles/python/meterpreter_reverse_http.rb
  modules/payloads/singles/python/meterpreter_reverse_https.rb
  modules/payloads/singles/python/meterpreter_reverse_tcp.rb
Labels: bug, payload, rn-fix
