Repository rapid7/metasploit-framework, pull requests merged in 2022-02, with the labels that each got.

#16132 [MySQL injection library] Avoid the use of '<>'
  lib/msf/core/exploit/sqli/mysqli/common.rb
Labels: library, enhancement

#16123 fix faulty URL ref #16078 removed faulty url
  modules/exploits/linux/http/cisco_ucs_rce.rb
Labels: module, easy

#15994 Fix #12895, fix console.read does not return command output
  lib/msf/ui/console/driver.rb
  lib/msf/ui/web/web_console.rb
Labels: library, bug

#16025 Fix msfdb init command failure when opting not to initialize webservices
  msfdb
Labels: bug, database

#16066 Fix params not being passed to scripts
  lib/msf/ui/console/command_dispatcher/core.rb
Labels: library, bug

#16142 Update metasploit-payloads gem to 2.0.72
  Gemfile.lock
  LICENSE_GEMS
  metasploit-framework.gemspec
Labels: library, bug, rn-fix

#16136 Add a port of PetitPotam to Metasploit
  Gemfile.lock
  LICENSE_GEMS
  documentation/modules/auxiliary/scanner/dcerpc/petitpotam.md
  modules/auxiliary/scanner/dcerpc/petitpotam.rb
Labels: module, docs, rn-modules

#16010 New module Zabbix systemrun rce
  documentation/modules/exploit/multi/http/zabbix_script_exec.md
  modules/exploits/multi/http/zabbix_script_exec.rb
Labels: module, docs

#16151 Add QEMU Monitor HMP 'migrate' Command Execution module
  documentation/modules/exploit/multi/misc/qemu_monitor_hmp_migrate_cmd_exec.md
  modules/exploits/multi/misc/qemu_monitor_hmp_migrate_cmd_exec.rb
Labels: module, docs

#16125 Add support for GXV3140 models and ARCH_CMD busybox telnetd payload
  documentation/modules/exploit/linux/http/grandstream_gxv3175_settimezone_unauth_cmd_exec.md
  documentation/modules/exploit/linux/http/grandstream_gxv31xx_settimezone_unauth_cmd_exec.md
  modules/exploits/linux/http/grandstream_gxv31xx_settimezone_unauth_cmd_exec.rb
Labels: module, enhancement

#16160 Don't crash when the hostname can't be determined
  lib/rex/ui/text/shell.rb
Labels: library, bug, easy, rn-fix

#16121 Fix exception in rhost during meterpreter staging
  lib/msf/core/post/common.rb
Labels: bug

#16147 Improve User List Generation For ssh_enumusers
  modules/auxiliary/scanner/ssh/ssh_enumusers.rb
Labels: module, bug, rn-fix

#16163 Add the ClaimsPrincipal .NET gadget chain
  lib/msf/util/dot_net_deserialization.rb
  lib/msf/util/dot_net_deserialization/formatters/soap_formatter.rb
  lib/msf/util/dot_net_deserialization/gadget_chains.rb
  lib/msf/util/dot_net_deserialization/gadget_chains/claims_principal.rb
  spec/lib/msf/util/dot_net_deserialization_spec.rb
Labels: library, enhancement, rn-enhancement

#16161 Updated user agent strings
  lib/rex/user_agent.rb
Labels: library, enhancement, rn-enhancement

#16184 Bump rex-powershell
  Gemfile.lock
Labels: rn-fix

#16087 Grandstream UCM62xx IP PBX Websocket Blind SQL Injection Credential Dump
  documentation/modules/auxiliary/gather/grandstream_ucm62xx_sql_account_guess.md
  modules/auxiliary/gather/grandstream_ucm62xx_sql_account_guess.rb
Labels: module, docs

#16117 Updates for Log4Shell
  documentation/modules/auxiliary/scanner/http/log4shell_scanner.md
  lib/msf/core/exploit/remote/jndi_injection.rb
  lib/msf/core/exploit/remote/log4_shell.rb
  modules/auxiliary/scanner/http/log4shell_scanner.rb
  modules/exploits/multi/http/log4shell_header_injection.rb
  modules/exploits/multi/http/ubiquiti_unifi_log4shell.rb
  modules/exploits/multi/http/vmware_vcenter_log4shell.rb
Labels: module, library, bug, code quality

#16159 Add module to CVE-2021-3129
  documentation/modules/exploit/multi/php/ignition_laravel_debug_rce.md
  modules/exploits/multi/php/ignition_laravel_debug_rce.rb
Labels: module, docs

#16192 Add ServerJang to session notifier to allow sending new session information to WeChat
  plugins/session_notifier.rb
Labels: feature, rn-enhancement

#16156 Microweber v1.2.10 Local File Inclusion (Authenticated)
  documentation/modules/auxiliary/gather/microweber_lfi.md
  modules/auxiliary/gather/microweber_lfi.rb
Labels: module, docs

#16061 Add support to retrieve user list from wp-json to wordpress_scanner module
  modules/auxiliary/scanner/http/wordpress_scanner.rb
Labels: module, enhancement

#16164 Create Module For CVE-2021-42321 - Exchange ChainedSerializationBinder Blacklist Typo Authenticated RCE
  documentation/modules/exploit/windows/http/exchange_chainedserializationbinder_denylist_typo_rce.md
  modules/exploits/windows/http/exchange_chainedserializationbinder_denylist_typo_rce.rb
Labels: module, docs

#16182 wordpress Secure Copy Content Protection and Content Locking Unauthenticated sqli (CVE-2021-24931)
  data/wordlists/wp-exploitable-plugins.txt
  documentation/modules/auxiliary/scanner/http/wp_secure_copy_content_protection_sqli.md
  modules/auxiliary/scanner/http/wp_secure_copy_content_protection_sqli.rb
Labels: module, docs

#16202 Add exploit for CVE-2022-21882 (Win32k LPE)
  data/exploits/CVE-2021-1732/CVE-2021-1732.x64.dll
  data/exploits/CVE-2022-21882/CVE-2022-21882.x64.dll
  documentation/modules/exploit/windows/local/cve_2021_1732_win32k.md
  documentation/modules/exploit/windows/local/cve_2022_21882_win32k.md
  external/source/exploits/CVE-2021-1732/CVE-2021-1732.sln
  external/source/exploits/CVE-2021-1732/exploit.c
  external/source/exploits/CVE-2022-21882/.gitignore
  external/source/exploits/CVE-2022-21882/CVE-2022-21882.sln
  external/source/exploits/CVE-2022-21882/CVE-2022-21882.vcxproj
  external/source/exploits/CVE-2022-21882/dllmain.c
  external/source/exploits/CVE-2022-21882/exploit.c
  external/source/exploits/CVE-2022-21882/exploit.h
  external/source/include/windows/common.h
  external/source/include/windows/definitions.h
  modules/exploits/windows/local/cve_2022_21882_win32k.rb
Labels: module, docs

#16204 Hikvision Unauthenticated RCE (CVE-2021-36260)
  documentation/modules/exploit/linux/http/hikvision_cve_2021_36260_blind.md
  modules/exploits/linux/http/hikvision_cve_2021_36260_blind.rb
Labels: module, docs

#16235 Msf::Payload::Apk: Fix apktool version check
  lib/msf/core/payload/apk.rb
Labels: bug, payload, easy, android

#16131 Wordpress Plugin Modern Events Calendar SQLi (CVE-2021-24946)
  data/wordlists/wp-exploitable-plugins.txt
  documentation/modules/auxiliary/scanner/http/wp_modern_events_calendar_sqli.md
  modules/auxiliary/scanner/http/wp_modern_events_calendar_sqli.rb
  modules/auxiliary/scanner/http/wp_registrationmagic_sqli.rb
Labels: module, docs

#16185 Firefox CVE-2020-26950 use after free browser exploit
  documentation/modules/exploit/multi/browser/firefox_jit_use_after_free.md
  lib/msf/core/exploit/remote/http_server/browser_exploit.rb
  modules/exploits/multi/browser/chrome_array_map.rb
  modules/exploits/multi/browser/chrome_jscreate_sideeffect.rb
  modules/exploits/multi/browser/chrome_object_create.rb
  modules/exploits/multi/browser/firefox_jit_use_after_free.rb
  modules/exploits/osx/browser/safari_in_operator_side_effect.rb
Labels: module, docs
