Repository rapid7/metasploit-framework, pull requests merged in 2022-09, with the labels that each got.

#16959 Add profiler options to the time command
  lib/msf/ui/console/command_dispatcher/developer.rb
Labels: enhancement, rn-enhancement

#16725 Add ManageEngine ADAudit Plus and DataSecurity Plus Xnode enum modules, docs and mixin (CVE-2020–11532)
  data/exploits/manageengine_xnode/CVE-2020-11532/adaudit_plus_xnode_conf.yaml
  data/exploits/manageengine_xnode/CVE-2020-11532/datasecurity_plus_xnode_conf.yaml
  documentation/modules/auxiliary/gather/manageengine_adaudit_plus_xnode_enum.md
  documentation/modules/auxiliary/gather/manageengine_datasecurity_plus_xnode_enum.md
  lib/msf/core/auxiliary/manage_engine_xnode.rb
  lib/msf/core/auxiliary/manage_engine_xnode/action.rb
  lib/msf/core/auxiliary/manage_engine_xnode/basic_checks.rb
  lib/msf/core/auxiliary/manage_engine_xnode/config.rb
  lib/msf/core/auxiliary/manage_engine_xnode/interact.rb
  lib/msf/core/auxiliary/manage_engine_xnode/process.rb
  modules/auxiliary/gather/manageengine_adaudit_plus_xnode_enum.rb
  modules/auxiliary/gather/manageengine_datasecurity_plus_xnode_enum.rb
Labels: module, library, docs, rn-modules

#16961 Add in Visual Studio Code .vscode directory to .gitignore
  .gitignore
Labels: easy, rn-modules

#16947 Golang formatted byte array support payload generation.
  Gemfile.lock
  lib/msf/base/simple/buffer.rb
Labels: library, msfvenom, enhancement, rn-enhancement

#16934 post/windows/gather/memory_dump: Support dumping processes by name
  documentation/modules/post/windows/gather/memory_dump.md
  modules/post/windows/gather/memory_dump.rb
Labels: module, enhancement, rn-enhancement

#16707 Add Silver and Golden ticket forging module
  documentation/modules/auxiliary/admin/kerberos/forge_ticket.md
  lib/msf/core/exploit/remote/kerberos/client/pac.rb
  lib/msf/core/exploit/remote/kerberos/ticket.rb
  lib/rex/proto/kerberos/model/authorization_data.rb
  lib/rex/proto/kerberos/model/ticket_enc_part.rb
  lib/rex/proto/kerberos/model/ticket_flag.rb
  lib/rex/proto/kerberos/model/ticket_flags.rb
  lib/rex/proto/kerberos/model/transited_encoding.rb
  lib/rex/proto/kerberos/pac.rb
  lib/rex/proto/kerberos/pac/logon_info.rb
  modules/auxiliary/admin/kerberos/forge_ticket.rb
  modules/auxiliary/admin/kerberos/ms14_068_kerberos_checksum.rb
  spec/lib/msf/core/exploit/remote/kerberos/ticket_spec.rb
  spec/lib/rex/proto/kerberos/model/authorization_data_spec.rb
  spec/lib/rex/proto/kerberos/model/ticket_enc_part_spec.rb
  spec/lib/rex/proto/kerberos/model/ticket_flags_spec.rb
  spec/lib/rex/proto/kerberos/model/transited_encoding_spec.rb
Labels: needs-docs, feature-kerberos-authentication

#16923 Cisco ASA-X with FirePOWER Services Authenticated Command Injection (CVE-2022-20828)
  documentation/modules/exploit/linux/http/cisco_asax_sfr_rce.md
  modules/exploits/linux/http/cisco_asax_sfr_rce.rb
Labels: module, docs, rn-modules

#16988 Fix typo in documentation links
  docs/metasploit-framework.wiki/Contributing-to-Metasploit.md
Labels: docs, bug, easy, rn-no-release-notes

#16948 Change mssql.rb to support username, password and database specifications in run_sql
  lib/msf/core/post/windows/mssql.rb
Labels: library, enhancement

#16968 Update enum_system.rb
  modules/post/linux/gather/enum_system.rb
Labels: rn-fix

#16973 Add MSFvenom support for Nim shellcode
  Gemfile.lock
  lib/msf/base/simple/buffer.rb
Labels: library, msfvenom, enhancement, rn-enhancement

#16901 killav: Cleanup and support non-meterpreter sessions
  documentation/modules/post/windows/manage/killav.md
  modules/post/windows/manage/killav.rb
Labels: module, enhancement, rn-enhancement

#16983 firefox_xpi_bootstrapped_addon: Add notes, description, references, docs
  documentation/modules/exploit/multi/browser/firefox_xpi_bootstrapped_addon.md
  modules/exploits/multi/browser/firefox_xpi_bootstrapped_addon.rb
Labels: module, docs, rn-enhancement

#16521 Add custom stage
  lib/msf/base/sessions/custom.rb
  lib/msf/core/handler/reverse_http.rb
  lib/msf/core/payload/custom.rb
  lib/msf/core/payload/custom/options.rb
  lib/msf/core/payload/stager.rb
  lib/msf/core/payload/windows/reverse_http.rb
  lib/msf/core/payload/windows/reverse_win_http.rb
  lib/msf/core/payload/windows/x64/reverse_http_x64.rb
  lib/msf/core/payload/windows/x64/reverse_win_http_x64.rb
  modules/payloads/stages/windows/custom.rb
  modules/payloads/stages/windows/x64/custom.rb
Labels: module, feature, payload, rn-modules

#16928 Msf::Post::Windows::Service: Multiple bug and consistency fixes
  lib/msf/core/post/windows/services.rb
Labels: library, bug, rn-fix

#16929 enum_services: Cleanup and support non-Meterpreter sessions
  documentation/modules/post/windows/gather/enum_services.md
  modules/post/windows/gather/enum_services.rb
Labels: module, enhancement

#16906 enum_snmp: Cleanup and support non-Meterpreter sessions
  documentation/modules/post/windows/gather/enum_snmp.md
  modules/post/windows/gather/enum_snmp.rb
Labels: module, bug

#16911 enum_ms_product_keys: Cleanup and support non-meterpreter sessions
  documentation/modules/post/windows/gather/enum_ms_product_keys.md
  modules/post/windows/gather/enum_ms_product_keys.rb
Labels: module, enhancement

#16828 SuiteCRM auth SQLi auxiliary module
  documentation/modules/auxiliary/gather/suite_crm_export_sqli.md
  modules/auxiliary/gather/suite_crm_export_sqli.rb
Labels: module, docs

#16976 Add documentation for kerberos ticket forging
  documentation/modules/auxiliary/admin/kerberos/forge_ticket.md
Labels: docs, enhancement

#17018 Add cidr mask defaults to route add command
  lib/msf/ui/console/command_dispatcher/core.rb
Labels: bug, rn-fix

#16930 scripts/resource/dev_checks: Add additional development-related modules
  scripts/resource/dev_checks.rc
Labels: bug, enhancement

#17013 Fix Jenkins Login For Newer Versions
  modules/exploits/multi/http/jenkins_script_console.rb
Labels: module, bug, rn-fix

#17014 Increase timeout for laravel rce check method
  modules/exploits/multi/php/ignition_laravel_debug_rce.rb
Labels: module, bug, rn-fix

#16998 Fix iax2 module crash
  lib/rex/proto/iax2/client.rb
Labels: bug

#16914 Add PAN-OS auth command injection module (CVE-2020-2038)
  documentation/modules/exploit/linux/http/panos_op_cmd_exec.md
  modules/exploits/linux/http/panos_op_cmd_exec.rb
Labels: module, docs

#17003 enum_patches: Cleanup, print patches as table, store patches as CSV
  documentation/modules/post/windows/gather/enum_patches.md
  modules/post/windows/gather/enum_patches.rb
Labels: module, enhancement, rn-enhancement

#16940 Rewrite datastore, and add support for option fallback lookups
  .github/workflows/verify.yml
  docs/metasploit-framework.wiki/How-to-use-datastore-options.md
  lib/msf/base/serializer/readable_text.rb
  lib/msf/core/data_store.rb
  lib/msf/core/data_store_with_fallbacks.rb
  lib/msf/core/exploit/powershell.rb
  lib/msf/core/exploit/remote/ftp.rb
  lib/msf/core/exploit/remote/ldap.rb
  lib/msf/core/exploit/remote/smb/client.rb
  lib/msf/core/exploit/remote/smb/client/authenticated.rb
  lib/msf/core/exploit_driver.rb
  lib/msf/core/feature_manager.rb
  lib/msf/core/framework.rb
  lib/msf/core/handler/bind_named_pipe.rb
  lib/msf/core/module/data_store.rb
  lib/msf/core/module/options.rb
  lib/msf/core/module_data_store.rb
  lib/msf/core/module_data_store_with_fallbacks.rb
  lib/msf/core/opt_base.rb
  lib/msf/core/option_container.rb
  lib/msf/core/post/windows/wmic.rb
  lib/msf/core/rhosts_walker.rb
  lib/msf/core/rpc/v10/rpc_core.rb
  lib/msf/ui/console/command_dispatcher/core.rb
  lib/msf/ui/console/command_dispatcher/exploit.rb
  lib/msf/ui/console/driver.rb
  lib/msf/ui/console/module_option_tab_completion.rb
  lib/rex/parser/arguments.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/lanattacks/dhcp.rb
  modules/auxiliary/admin/db2/db2rcmd.rb
  modules/auxiliary/admin/scada/modicon_password_recovery.rb
  modules/auxiliary/dos/windows/ftp/guildftp_cwdlist.rb
  modules/auxiliary/dos/windows/ftp/titan626_site.rb
  modules/auxiliary/dos/windows/ftp/vicftps50_list.rb
  modules/auxiliary/dos/windows/ftp/xmeasy560_nlst.rb
  modules/auxiliary/dos/windows/ftp/xmeasy570_nlst.rb
  modules/auxiliary/scanner/ftp/colorado_ftp_traversal.rb
  modules/auxiliary/server/ftp.rb
  modules/exploits/windows/ftp/ability_server_stor.rb
  modules/exploits/windows/ftp/freeftpd_pass.rb
  modules/exploits/windows/ftp/httpdx_tolog_format.rb
  modules/exploits/windows/ftp/oracle9i_xdb_ftp_unlock.rb
  modules/exploits/windows/local/powershell_remoting.rb
  modules/exploits/windows/smb/ms17_010_eternalblue.rb
  modules/exploits/windows/smb/netidentity_xtierrpcpipe.rb
  modules/post/windows/manage/change_password.rb
  spec/lib/metasploit/framework/aws/client_spec.rb
  spec/lib/msf/base/serializer/readable_text_spec.rb
  spec/lib/msf/core/data_store_with_fallbacks_spec.rb
  spec/lib/msf/core/exploit/browser_autopwn2_spec.rb
  spec/lib/msf/core/module_spec.rb
  spec/lib/msf/core/modules/loader/directory_spec.rb
  spec/lib/msf/core/rhosts_walker_spec.rb
  spec/lib/msf/ui/console/command_dispatcher/core_spec.rb
  spec/spec_helper.rb
  spec/support/matchers/match_table.rb
Labels: rn-enhancement

#17029 Add getsystem module docs
  documentation/modules/post/windows/escalate/getsystem.md
  modules/post/windows/escalate/getsystem.rb
Labels: module, docs

#16688 Add Mimipenguin
  Gemfile.lock
  documentation/modules/post/linux/gather/mimipenguin.md
  lib/metasploit/framework/hashes/identify.rb
  lib/msf/core/post/linux/process.rb
  lib/rex/post/meterpreter/extensions/stdapi/command_ids.rb
  lib/rex/post/meterpreter/extensions/stdapi/sys/process_subsystem/memory.rb
  lib/rex/post/meterpreter/extensions/stdapi/tlv.rb
  metasploit-framework.gemspec
  modules/payloads/singles/apple_ios/aarch64/meterpreter_reverse_http.rb
  modules/payloads/singles/apple_ios/aarch64/meterpreter_reverse_https.rb
  modules/payloads/singles/apple_ios/aarch64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/apple_ios/armle/meterpreter_reverse_http.rb
  modules/payloads/singles/apple_ios/armle/meterpreter_reverse_https.rb
  modules/payloads/singles/apple_ios/armle/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/aarch64/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/aarch64/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/aarch64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/armbe/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/armbe/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/armbe/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/armle/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/armle/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/armle/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/mips64/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/mips64/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/mips64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/mipsbe/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/mipsbe/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/mipsbe/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/mipsle/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/mipsle/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/mipsle/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/ppc/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/ppc/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/ppc/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/ppc64le/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/ppc64le/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/ppc64le/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/ppce500v2/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/ppce500v2/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/ppce500v2/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/x64/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/x64/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/x64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/x86/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/x86/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/x86/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/zarch/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/zarch/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/zarch/meterpreter_reverse_tcp.rb
  modules/payloads/singles/osx/x64/meterpreter_reverse_http.rb
  modules/payloads/singles/osx/x64/meterpreter_reverse_https.rb
  modules/payloads/singles/osx/x64/meterpreter_reverse_tcp.rb
  modules/post/linux/gather/mimipenguin.rb
Labels: module, docs, creds

#17023 Fix #16999 by using a compatible default action
  modules/post/windows/manage/rollback_defender_signatures.rb
Labels: module, easy, rn-fix

#17036 Fix #16684, Set @peer_info in #initialize
  lib/msf/core/session/interactive.rb
Labels: library, bug

#17002 Msf::Post::Windows: Replace load_extapi with ExtAPI capability check
  lib/msf/core/post/windows/accounts.rb
  lib/msf/core/post/windows/ldap.rb
  lib/msf/core/post/windows/wmic.rb
  modules/post/windows/gather/wmic_command.rb
Labels: library, enhancement, rn-enhancement

#16989 unified_remote exploit
  documentation/modules/exploit/windows/misc/unified_remote_rce.md
  modules/exploits/windows/misc/unified_remote_rce.rb
Labels: module, docs, rn-modules

#17042 Add exploit for CVE-2022-36804
  documentation/modules/exploit/linux/http/bitbucket_git_cmd_injection.md
  modules/exploits/linux/http/bitbucket_git_cmd_injection.rb
Labels: module, docs

#16732 VICIdial Multiple SQLi (CVE-2022-34876, CVE-2022-34877, CVE-2022-34878)
  documentation/modules/auxiliary/scanner/http/vicidial_multiple_sqli.md
  modules/auxiliary/scanner/http/vicidial_multiple_sqli.rb
Labels: module, docs, rn-modules

#17051 wmic_command: Cleanup
  documentation/modules/post/windows/gather/wmic_command.md
  modules/post/windows/gather/wmic_command.rb
Labels: module

#17052 Fix openssl unsafe legacy renegotiation disabled error
  Gemfile.lock
Labels: rn-fix

#17027 Add in docs site to banner
  lib/msf/ui/console/command_dispatcher/core.rb
Labels: library, docs, easy, rn-no-release-notes

#17049 enum_domain_group_users: Cleanup
  documentation/modules/post/windows/gather/enum_domain_group_users.md
  modules/post/windows/gather/enum_domain_group_users.rb
Labels: module

#17055 add new reference to bitbucket module
  modules/exploits/linux/http/bitbucket_git_cmd_injection.rb
Labels: rn-no-release-notes

#17015 improve http login result checks
  lib/metasploit/framework/login_scanner/http.rb
  modules/auxiliary/scanner/http/http_login.rb
Labels: library, enhancement

#17026 Update README.md and modernize links and explanations
  README.md
Labels: docs, rn-no-release-notes

#17056 Add git docs
  docs/build.rb
  docs/metasploit-framework.wiki/How-to-use-the-Git-mixin-to-write-an-exploit-module.md
  docs/navigation.rb
Labels: rn-no-release-notes

#17012 Veritas Backup Exec Agent Authentication Bypass RCE
  documentation/modules/exploit/multi/veritas/beagent_sha_auth_rce.md
  modules/exploits/multi/veritas/beagent_sha_auth_rce.rb
Labels: module, docs

#16985 wifi mouse rce - CVE-2022-3218
  documentation/modules/exploit/windows/misc/wifi_mouse_rce.md
  modules/exploits/windows/misc/wifi_mouse_rce.rb
Labels: module, docs, rn-modules

#17033 hikvision password reset via inproper authorization logic - CVE-2017-7921
  documentation/modules/auxiliary/admin/http/hikvision_unauth_pwd_reset_cve_2017_7921.md
  modules/auxiliary/admin/http/hikvision_unauth_pwd_reset_cve_2017_7921.rb
Labels: module, docs, rn-modules

#16994 Fix Multiple Registry Related Issues
  Gemfile.lock
  lib/msf/core/post/windows/registry.rb
  lib/rex/post/meterpreter/extensions/stdapi/constants.rb
  lib/rex/post/meterpreter/extensions/stdapi/sys/registry.rb
  lib/rex/post/meterpreter/extensions/stdapi/sys/registry_subsystem/registry_value.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/sys.rb
  metasploit-framework.gemspec
  modules/post/windows/gather/enum_shares.rb
  test/lib/module_test.rb
  test/modules/post/test/registry.rb
Labels: library, bug, rn-fix

#17054 Fix Adapted Single (Unstaged) Payloads
  lib/msf/core/payload/single.rb
  modules/payloads/singles/bsd/x64/exec.rb
  modules/payloads/singles/bsd/x86/exec.rb
  modules/payloads/singles/linux/armle/adduser.rb
  modules/payloads/singles/linux/armle/exec.rb
  modules/payloads/singles/linux/x64/exec.rb
  modules/payloads/singles/linux/x64/pingback_bind_tcp.rb
  modules/payloads/singles/linux/x64/pingback_reverse_tcp.rb
  modules/payloads/singles/linux/x64/shell_bind_ipv6_tcp.rb
  modules/payloads/singles/linux/x64/shell_bind_tcp_random_port.rb
  modules/payloads/singles/linux/x64/shell_reverse_ipv6_tcp.rb
  modules/payloads/singles/linux/x86/adduser.rb
  modules/payloads/singles/linux/x86/chmod.rb
  modules/payloads/singles/linux/x86/exec.rb
  modules/payloads/singles/linux/x86/read_file.rb
  modules/payloads/singles/linux/x86/shell_reverse_tcp_ipv6.rb
  modules/payloads/singles/osx/x86/exec.rb
Labels: bug, payload, rn-fix

#16960 Add in ruby/debug to Gemfile To Allow Users to Easily Debug Metasploit
  Gemfile
  Gemfile.lock
  external/vscode/launch.json
Labels: easy

#17025 Allow `user_id` to be configurable in ticket forging
  documentation/modules/auxiliary/admin/kerberos/forge_ticket.md
  lib/msf/core/exploit/remote/kerberos/client/pac.rb
  lib/msf/core/exploit/remote/kerberos/ticket.rb
  lib/rex/proto/kerberos/pac.rb
  modules/auxiliary/admin/kerberos/forge_ticket.rb
Labels: rn-enhancement, feature-kerberos-authentication

#16981 enum_domain_tokens: Cleanup and fix group member retrieval
  documentation/modules/post/windows/gather/enum_domain_tokens.md
  modules/post/windows/gather/enum_domain_tokens.rb
Labels: module, bug

#17064 Fix beagent sha auth linting
  modules/exploits/multi/veritas/beagent_sha_auth_rce.rb
Labels: rn-no-release-notes

#16794 Add exploit for CVE-2022-34918
  data/exploits/CVE-2022-34918/ubuntu.elf
  documentation/modules/exploit/linux/local/netfilter_nft_set_elem_init_privesc.md
  external/source/exploits/CVE-2022-34918/Makefile
  external/source/exploits/CVE-2022-34918/README.md
  external/source/exploits/CVE-2022-34918/inc/keyring.h
  external/source/exploits/CVE-2022-34918/inc/log.h
  external/source/exploits/CVE-2022-34918/inc/modprobe.h
  external/source/exploits/CVE-2022-34918/inc/netlink.h
  external/source/exploits/CVE-2022-34918/inc/nf_tables.h
  external/source/exploits/CVE-2022-34918/inc/simple_xattr.h
  external/source/exploits/CVE-2022-34918/inc/uring.h
  external/source/exploits/CVE-2022-34918/inc/util.h
  external/source/exploits/CVE-2022-34918/src/keyring.c
  external/source/exploits/CVE-2022-34918/src/main.c
  external/source/exploits/CVE-2022-34918/src/modprobe.c
  external/source/exploits/CVE-2022-34918/src/netlink.c
  external/source/exploits/CVE-2022-34918/src/nf_tables.c
  external/source/exploits/CVE-2022-34918/src/simple_xattr.c
  external/source/exploits/CVE-2022-34918/src/uring.c
  external/source/exploits/CVE-2022-34918/src/util.c
  modules/exploits/linux/local/netfilter_nft_set_elem_init_privesc.rb
Labels: module, docs

#17061 mobile mouse server exploit
  documentation/modules/exploit/windows/misc/mobile_mouse_rce.md
  modules/exploits/windows/misc/mobile_mouse_rce.rb
  modules/exploits/windows/misc/unified_remote_rce.rb
  modules/exploits/windows/misc/wifi_mouse_rce.rb
Labels: module, docs

#16673 qdPM 9.1 - Authenticated Remote Code Execution (CVE-2020-7246)
  documentation/modules/exploit/multi/http/qdpm_authenticated_rce.md
  modules/exploits/multi/http/qdpm_authenticated_rce.rb
Labels: module, docs

#17073 Fixes broken sessions in rservices modules
  modules/auxiliary/scanner/rservices/rexec_login.rb
  modules/auxiliary/scanner/rservices/rlogin_login.rb
  modules/auxiliary/scanner/rservices/rsh_login.rb
Labels: bug

#17048 enum_tokens: Cleanup
  documentation/modules/post/windows/gather/enum_tokens.md
  modules/post/windows/gather/enum_tokens.rb
Labels: module

#17078 Updates deprecated methods in rservices modules
  modules/auxiliary/scanner/rservices/rexec_login.rb
  modules/auxiliary/scanner/rservices/rlogin_login.rb
  modules/auxiliary/scanner/rservices/rsh_login.rb
Labels: module, bug

#17085 Update ranking for nft_set_elem_init
  modules/exploits/linux/local/netfilter_nft_set_elem_init_privesc.rb
Labels: easy, rn-no-release-notes

#16933 Add thycotic_secretserver_dump post module
  documentation/modules/post/windows/gather/credentials/thycotic_secretserver_dump.md
  modules/post/windows/gather/credentials/thycotic_secretserver_dump.rb
Labels: module, docs

#16995 Add TrustedSec's COFFLoader as Meterpreter Extension
  LICENSE
  data/headers/windows/c_payload_util/beacon.h
  docs/metasploit-framework.wiki/Meterpreter-ExecuteBof-Command.md
  docs/navigation.rb
  lib/rex/post/meterpreter/extensions/bofloader/bofloader.rb
  lib/rex/post/meterpreter/extensions/bofloader/command_ids.rb
  lib/rex/post/meterpreter/extensions/bofloader/tlv.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/bofloader.rb
Labels: meterpreter, delayed, enhancement, rn-enhancement
