Repository rapid7/metasploit-framework, pull requests merged in 2022-03, with the labels that each got.

#16228 Validate payload size even when not encoding
  lib/msf/core/encoded_payload.rb
Labels: bug, rn-fix

#16255 Update metasploit-payloads gem to 2.0.77 - Fix issue with kiwi_cmd arguments
  Gemfile.lock
  LICENSE_GEMS
  metasploit-framework.gemspec
Labels: rn-fix

#16257 Msf::Payload::Apk: Print warning if apktool version < 2.5.1
  lib/msf/core/payload/apk.rb
Labels: payload, usability

#16254 shodan_search default user-agent overwrite - fix #16189 and #16223
  modules/auxiliary/gather/shodan_search.rb
Labels: module, bug

#16245 pfSense Authenticated File Write (CVE-2021-41282)
  documentation/modules/exploit/unix/http/pfsense_diag_routes_webshell.md
  modules/exploits/unix/http/pfsense_diag_routes_webshell.rb
Labels: module, docs

#16265 Fix race condition in jobs cleanup that could allow it to clean up twice simultaneously
  lib/rex/job.rb
Labels: library, bug

#16219 Convert core enumextcmd & loadlib commands to human readable strings
  lib/rex/post/meterpreter/packet.rb
Labels: library, enhancement

#16270 Msf::Payload::Apk: raise if keytool cannot parse APK file or certificate
  lib/msf/core/payload/apk.rb
Labels: payload, android

#16269 Msf::Payload::Apk: Check Java is installed and apktool.jar exists
  lib/msf/core/payload/apk.rb
Labels: payload, android

#16145 Fix to_handler case sensitivity issue
  lib/msf/ui/console/command_dispatcher/payload.rb
Labels: library, bug, rn-fix

#16268 Update check comhijack
  modules/exploits/windows/local/bypassuac_comhijack.rb
Labels: bug, easy, rn-fix

#16258 Improve TLV Type handling
  lib/rex/post/meterpreter/command_mapper.rb
  lib/rex/post/meterpreter/extension_mapper.rb
  lib/rex/post/meterpreter/packet.rb
  spec/lib/rex/post/meterpreter/packet_spec.rb
Labels: library, enhancement

#16283 Msf::Payload::Apk: raise if APK is unsigned or generating new key fails
  lib/msf/core/payload/apk.rb
Labels: payload, android

#16288 Msf::Payload::Apk: raise if apktool output includes Java exceptions
  lib/msf/core/payload/apk.rb
Labels: payload, android

#16294 Msf::Payload::Apk: Replace jarsigner with apksigner
  lib/msf/core/payload/apk.rb
Labels: payload, enhancement, android

#16282 Add lcat command for meterpreter
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb
  test/functional/meterpreter/meterpreter_specs.rb
Labels: meterpreter, feature

#16286 post/windows/manage/persistence_exe: Replace IO.read with File.binread
  modules/post/windows/manage/persistence_exe.rb
Labels: module, bug

#16098 Update smb_relay to support smb 2 and smb3
  documentation/modules/auxiliary/server/capture/smb.md
  documentation/modules/exploit/windows/smb/smb_relay.md
  lib/msf/core/exploit/remote/smb/client/psexec.rb
  lib/msf/core/exploit/remote/smb/relay/ntlm/server.rb
  lib/msf/core/exploit/remote/smb/relay/ntlm/server_client.rb
  lib/msf/core/exploit/remote/smb/relay/provider/always_grant_access.rb
  lib/msf/core/exploit/remote/smb/relay/target_list.rb
  lib/msf/core/exploit/remote/smb/server/hash_capture.rb
  lib/msf_autoload.rb
  lib/rex/proto/smb/simple_client.rb
  modules/auxiliary/server/capture/smb.rb
  modules/exploits/windows/smb/psexec.rb
  modules/exploits/windows/smb/smb_relay.rb
  spec/lib/msf/exploit/remote/smb/relay/target_list_spec.rb
Labels: module, rn-modules

#16312 Fix arch check and on_session cd
  modules/exploits/linux/local/cve_2021_4034_pwnkit_lpe_pkexec.rb
Labels: bug, rn-fix

#16322 Fix hosts command bugs
  lib/msf/ui/console/command_dispatcher/db.rb
  spec/lib/msf/ui/console/command_dispatcher/db_spec.rb
Labels: bug, easy

#16303 CVE-2022-0847 (dirtypipe) a Linux LPE for Kernel 5.8 -> 5.16
  data/exploits/CVE-2022-0847/CVE-2022-0847-aarch64
  data/exploits/CVE-2022-0847/CVE-2022-0847-armle
  data/exploits/CVE-2022-0847/CVE-2022-0847-x64
  data/exploits/CVE-2022-0847/CVE-2022-0847-x86
  data/exploits/CVE-2022-0847/CVE-2022-0847.c
  data/exploits/CVE-2022-0847/Makefile
  documentation/modules/exploit/linux/local/cve_2022_0847_dirtypipe.md
  lib/msf/core/post/linux/kernel.rb
  modules/exploits/linux/local/cve_2022_0847_dirtypipe.rb
Labels: module

#16326 Fix SMB signing detection when SMB1 is disabled
  modules/auxiliary/scanner/smb/smb_version.rb
Labels: module, bug

#16252 GitLab GraphQL API Unauth User Enumeration (CVE-2021-4191)
  documentation/modules/auxiliary/scanner/http/gitlab_graphql_user_enum.md
  modules/auxiliary/scanner/http/gitlab_graphql_user_enum.rb
Labels: module, docs

#16334 Msf::Payload::Apk: Extract cert details from APK files not JAR signed
  lib/msf/core/payload/apk.rb
Labels: bug, payload, rn-fix, android

#16332 Msf::Payload::Apk: zipalign: align APK stored shared object files
  lib/msf/core/payload/apk.rb
Labels: bug, payload, easy, android

#16262 Use bash instead of netcat as a default payload
  lib/msf/ui/console/command_dispatcher/exploit.rb
Labels: library, enhancement

#16186 Add Python Meterpreter Command Payloads
  lib/msf/core/payload.rb
  lib/msf/core/payload/adapter.rb
  lib/msf/core/payload/python.rb
  lib/msf/core/payload/python/meterpreter_loader.rb
  lib/msf/core/payload/python/reverse_http.rb
  lib/msf/core/payload/python/send_uuid.rb
  lib/msf/core/payload/uuid/options.rb
  lib/msf/core/payload_set.rb
  modules/payloads/adapters/cmd/unix/python.rb
  modules/payloads/stages/python/meterpreter.rb
  spec/lib/msf/core/payload/python_spec.rb
Labels: module, payload, enhancement

#16324 Fix broken DNS native_server
  lib/rex/proto/dns/resolver.rb
  modules/auxiliary/server/dns/native_server.rb
Labels: module, bug

#16342 Update documentation/modules/payload/android/meterpreter/reverse_tcp.md to add in BlueStack reference and fix msftidy errors
  documentation/modules/payload/android/meterpreter/reverse_tcp.md
Labels: docs

#16347 Catch SocketError when normalizing the hostname
  lib/msf/core/db_manager/host.rb
  lib/msf/util/host.rb
Labels: library, bug

#16344 Add module for CVE-2022-21999 and More Railgun Definitions
  documentation/modules/exploit/windows/local/cve_2022_21999_spoolfool_privesc.md
  lib/rex/post/meterpreter/extensions/stdapi/railgun/def/windows/api_constants.rb
  lib/rex/post/meterpreter/extensions/stdapi/railgun/def/windows/def_advapi32.rb
  lib/rex/post/meterpreter/extensions/stdapi/railgun/def/windows/def_ntdll.rb
  lib/rex/post/meterpreter/extensions/stdapi/railgun/def/windows/def_spoolss.rb
  lib/rex/post/meterpreter/extensions/stdapi/railgun/def/windows/def_winspool.rb
  lib/rex/post/meterpreter/extensions/stdapi/railgun/railgun.rb
  modules/exploits/windows/local/cve_2022_21999_spoolfool_privesc.rb
Labels: module, library, docs

#16284 Add CVE-2021-31166 DoS Module
  documentation/modules/auxiliary/dos/windows/http/http_sys_accept_encoding_dos_cve_2021_31166.md
  modules/auxiliary/dos/windows/http/http_sys_accept_encoding_dos_cve_2021_31166.rb
Labels: module, docs, rn-modules, needs-linting

#16249 Add in Exchange Mixin - Initial Version with Version Detection
  data/exchange_versions.json
  lib/msf/core/exploit/remote/http/exchange.rb
  modules/exploits/windows/http/exchange_chainedserializationbinder_denylist_typo_rce.rb
Labels: module, library, enhancement

#16317 Free UDP ports after use
  lib/msf/core/exploit/remote/dns/server.rb
  lib/rex/proto/dns/server.rb
  modules/auxiliary/server/dns/native_server.rb
  modules/auxiliary/spoof/dns/native_spoofer.rb
  modules/auxiliary/spoof/llmnr/llmnr_response.rb
  modules/auxiliary/spoof/mdns/mdns_response.rb
  modules/auxiliary/spoof/nbns/nbns_response.rb
Labels: module, library, bug

#16309 Fix: Catch exception from net/ssh/connection/session.rb:381
  lib/metasploit/framework/login_scanner/ssh.rb
  modules/auxiliary/scanner/ssh/ssh_login.rb
Labels: library, bug

#16340 Msf::Payload::Apk: Try rebuilding APK with AAPT2 if rebuilding APK fails
  lib/msf/core/payload/apk.rb
Labels: bug, payload, android

#16358 Msf::Payload::Apk: find_hook_point: Return full packagename.classname
  lib/msf/core/payload/apk.rb
Labels: bug, payload, android

#16352 Add stale bot exemption for discussion label
  .github/workflows/schedule-stale.yml
Labels: automation, discussion

#16368 Conditionally recalculate in ModuleSet
  lib/msf/core/module_set.rb
  spec/support/shared/contexts/msf/simple/framework/modules/loading.rb
Labels: library, bug, rn-fix

#16298 Capture plugin
  data/capture_config.yaml
  plugins/capture.rb
Labels: enhancement, plugin

#16207 Fix vnc scanner module(s)
  documentation/modules/auxiliary/scanner/vnc/ard_root_pw.md
  documentation/modules/auxiliary/scanner/vnc/vnc_login.md
  documentation/modules/auxiliary/scanner/vnc/vnc_none_auth.md
  lib/rex/proto/rfb/client.rb
  lib/rex/proto/rfb/constants.rb
  modules/auxiliary/scanner/vnc/vnc_none_auth.rb
Labels: module, library, docs, bug, rn-fix

#16367 Fix character escaping in the apisix exploit
  modules/exploits/multi/http/apache_apisix_api_default_token_rce.rb
Labels: module, bug, easy, rn-fix

#16250 Update service mixins for NAT options
  lib/msf/core/exploit/remote/dns/server.rb
  lib/msf/core/exploit/remote/http_server.rb
  lib/msf/core/exploit/remote/ldap/server.rb
  lib/msf/core/exploit/remote/socket_server.rb
  lib/msf/core/exploit/remote/tcp_server.rb
  lib/rex/proto/proxy/socks4a.rb
  lib/rex/proto/proxy/socks5/server.rb
  modules/auxiliary/server/capture/smb.rb
  modules/auxiliary/server/socks_proxy.rb
  modules/exploits/multi/http/log4shell_header_injection.rb
Labels: library, enhancement

#16325 Replace IO read on binary files with File binread
  lib/metasploit/framework/compiler/windows.rb
  lib/metasploit/framework/data_service/remote/http/response_data_helper.rb
  lib/msf/core/auxiliary/auth_brute.rb
  lib/msf/core/auxiliary/ubiquiti.rb
  lib/msf/core/exploit/pdf_parse.rb
  lib/msf/core/exploit/remote/postgres.rb
  lib/msf/core/framework.rb
  lib/msf/core/payload/apk.rb
  lib/msf/util/java_deserialization.rb
  lib/rex/payloads/meterpreter/config.rb
  lib/rex/script.rb
  modules/auxiliary/admin/http/jboss_bshdeployer.rb
  modules/auxiliary/admin/http/jboss_deploymentfilerepository.rb
  modules/auxiliary/admin/http/supra_smart_cloud_tv_rfi.rb
  modules/auxiliary/admin/http/tomcat_utf8_traversal.rb
  modules/auxiliary/admin/http/trendmicro_dlp_traversal.rb
  modules/auxiliary/admin/networking/ubiquiti_config.rb
  modules/auxiliary/admin/scada/modicon_stux_transfer.rb
  modules/auxiliary/admin/smb/upload_file.rb
  modules/auxiliary/client/smtp/emailer.rb
  modules/auxiliary/docx/word_unc_injector.rb
  modules/auxiliary/dos/windows/browser/ms09_065_eot_integer.rb
  modules/auxiliary/fileformat/badpdf.rb
  modules/auxiliary/gather/cloud_lookup.rb
  modules/auxiliary/scanner/http/linksys_e1500_traversal.rb
  modules/auxiliary/scanner/http/netgear_sph200d_traversal.rb
  modules/auxiliary/scanner/http/tplink_traversal_noauth.rb
  modules/auxiliary/scanner/redis/file_upload.rb
  modules/auxiliary/scanner/smtp/smtp_enum.rb
  modules/auxiliary/server/ftp.rb
  modules/evasion/windows/process_herpaderping.rb
  modules/exploits/multi/fileformat/office_word_macro.rb
  modules/exploits/multi/http/mediawiki_thumb.rb
  modules/exploits/multi/http/splunk_upload_app_exec.rb
  modules/exploits/windows/browser/citrix_gateway_actx.rb
  modules/exploits/windows/fileformat/adobe_pdf_embedded_exe.rb
  modules/exploits/windows/fileformat/ms14_064_packager_python.rb
  modules/exploits/windows/fileformat/ms14_064_packager_run_as_admin.rb
  modules/exploits/windows/fileformat/office_ole_multiple_dll_hijack.rb
  modules/exploits/windows/local/cve_2020_17136.rb
  modules/exploits/windows/local/ms16_032_secondary_logon_handle_privesc.rb
  modules/exploits/windows/local/pxeexploit.rb
  modules/exploits/windows/smb/cve_2020_0796_smbghost.rb
  modules/payloads/singles/generic/custom.rb
  modules/payloads/stages/osx/armle/execute.rb
  modules/payloads/stages/windows/upexec.rb
  modules/post/osx/manage/sonic_pi.rb
  modules/post/windows/manage/pxeexploit.rb
  modules/post/windows/manage/shellcode_inject.rb
  scripts/meterpreter/metsvc.rb
  scripts/meterpreter/prefetchtool.rb
  spec/lib/rex/proto/acpp/message_spec.rb
  spec/lib/rex/proto/kademlia/bootstrap_response_spec.rb
  spec/lib/rex/proto/quake/message_spec.rb
  spec/lib/rex/proto/steam/message_spec.rb
  tools/dev/update_wordpress_vulnerabilities.rb
Labels: module, library, bug, rn-fix

#16371 Fix kubernetes websocket crash when identifying peer host
  lib/rex/proto/http/web_socket.rb
Labels: library, bug

#16386 Fix java rmi service undefined method wait
  lib/msf/core/exploit/remote/socket_server.rb
Labels: library, bug, rn-fix

#16364 Update auxiliary/spoof/dns/native_spoofer
  documentation/modules/auxiliary/spoof/dns/native_spoofer.md
  modules/auxiliary/spoof/dns/native_spoofer.rb
Labels: module, bug, rn-fix

#16395 Add exploit for CVE-2022-22963 (Spring Cloud Function SpEL RCE)
  documentation/modules/exploit/multi/http/spring_cloud_function_spel_injection.md
  modules/exploits/multi/http/spring_cloud_function_spel_injection.rb
Labels: module, docs, rn-modules
