Repository rapid7/metasploit-framework, pull requests merged in 2022-08, with the labels that each got.

#16839 Post::Windows::Registry: Fix shell_registry_[enumvals|getvaldata] error check
  lib/msf/core/post/windows/registry.rb
Labels: library, bug

#16832 Remove SCHELEVATOR echo statement as its not needed anymore
  modules/exploits/windows/local/ms10_092_schelevator.rb
Labels: module, enhancement, easy

#16837 MobileIron Core Log4Shell RCE Module (CVE-2021-44228)
  documentation/modules/exploit/linux/http/mobileiron_core_log4shell.md
  modules/exploits/linux/http/mobileiron_core_log4shell.rb
Labels: module, docs

#16833 Add easier way to delete host tags
  lib/msf/ui/console/command_dispatcher/db.rb
  spec/lib/msf/ui/console/command_dispatcher/db_spec.rb
Labels: library, enhancement, easy

#16852 Add CVE-2022-35405 Zoho Password Manager Pro XML-RPC Unauthenticated RCE
  documentation/modules/exploit/windows/http/zoho_password_manager_pro_xml_rpc_rce.md
  modules/exploits/windows/http/zoho_password_manager_pro_xml_rpc_rce.rb
Labels: module, docs

#16844 post/multi/gather/env: Cleanup and support non-Meterpreter sessions
  documentation/modules/post/multi/gather/env.md
  modules/post/multi/gather/env.rb
Labels: module, enhancement, rn-fix

#16842 Remove scripts/meterpreter/enum_powershell_env.rb
  scripts/meterpreter/enum_powershell_env.rb
Labels: enhancement

#16858 Update zerologon error handling to output invalid computer name details
  modules/auxiliary/admin/dcerpc/cve_2020_1472_zerologon.rb
Labels: module, enhancement, easy

#16788 A SCADA scanner module for BACnet protocol.
  documentation/modules/auxiliary/scanner/scada/bacnet_l3.md
  modules/auxiliary/scanner/scada/bacnet_l3.rb
Labels: module, docs

#16854 Add CVE-2022-31660 VMware Workspace ONE Access LPE
  documentation/modules/exploit/linux/local/vmware_workspace_one_access_certproxy_lpe.md
  lib/msf/core/post/file.rb
  lib/msf/core/post/linux/system.rb
  lib/msf/core/post/unix.rb
  modules/exploits/linux/local/vmware_workspace_one_access_certproxy_lpe.rb
  modules/post/multi/recon/sudo_commands.rb
Labels: module, docs

#16820 Fix Default Action Error In ldap_query Module
  modules/auxiliary/gather/ldap_query.rb
Labels: bug, easy

#16796 Add in exploit for CVE-2022-30333 - path traversal vulnerability in RARLAB UnRAR < 6.12
  documentation/modules/exploit/linux/fileformat/unrar_cve_2022_30333.md
  documentation/modules/exploit/linux/http/zimbra_unrar_cve_2022_30333.md
  lib/msf/core/exploit/format/rar_symlink_path_traversal.rb
  modules/exploits/linux/fileformat/unrar_cve_2022_30333.rb
  modules/exploits/linux/http/zimbra_unrar_cve_2022_30333.rb
Labels: module, docs, rn-modules

#16851 Add Cassandra Web file read auxiliary module
  documentation/modules/auxiliary/scanner/http/cassandra_web_file_read.md
  modules/auxiliary/scanner/http/cassandra_web_file_read.rb
Labels: module, docs

#16800 Add support for OpenSSL 3
  .github/workflows/verify.yml
  Gemfile.lock
  config/openssl.conf
  documentation/modules/auxiliary/scanner/ssl/openssl_heartbleed.md
  lib/msf/core/exploit/remote/http/typo3/login.rb
  lib/msf/core/exploit/remote/kerberos/client/as_request.rb
  lib/msf/core/modules/loader/base.rb
  lib/msf/util/windows_crypto_helpers.rb
  lib/msfenv.rb
  lib/rex/proto/rfb/cipher.rb
  modules/auxiliary/scanner/ssl/openssl_heartbleed.rb
  spec/spec_helper.rb
Labels: openssl3

#16807 New module for 0-day Zimbra privilege escalation ("slapper")
  documentation/modules/exploit/windows/local/zimbra_slapper_priv_esc.md
  modules/exploits/linux/local/zimbra_slapper_priv_esc.rb
Labels: module, docs

#16872 Post::Windows::Registry: Fix key and value parsing for shell sessions
  lib/msf/core/post/windows/registry.rb
Labels: library, bug, rn-fix

#16873 enum_artifacts: Cleanup and support non-meterpreter sessions
  documentation/modules/post/windows/gather/enum_artifacts.md
  modules/post/windows/gather/enum_artifacts.rb
Labels: module, enhancement

#16856 Webmin package updates RCE
  documentation/modules/exploit/linux/http/webmin_package_updates_rce.md
  modules/exploits/linux/http/webmin_package_updates_rce.rb
Labels: module, docs

#16875 Remove scripts/meterpreter/enum_putty.rb
  scripts/meterpreter/enum_putty.rb
Labels: enhancement

#16876 Remove scripts/meterpreter/enum_logged_on_users.rb
  scripts/meterpreter/enum_logged_on_users.rb
Labels: enhancement

#16878 enum_logged_on_users: Cleanup
  documentation/modules/post/windows/gather/enum_logged_on_users.md
  modules/post/windows/gather/enum_logged_on_users.rb
Labels: enhancement

#16841 enum_powershell_env: Cleanup and support non-Meterpreter sessions
  documentation/modules/post/windows/gather/enum_powershell_env.md
  modules/post/windows/gather/enum_powershell_env.rb
Labels: module, bug

#16882 Remove scripts/meterpreter/enum_shares.rb
  scripts/meterpreter/enum_shares.rb
Labels: enhancement

#16891 Remove scripts/meterpreter/enum_chrome.rb
  scripts/meterpreter/enum_chrome.rb
Labels: enhancement, rn-no-release-notes

#16890 Remove scripts/meterpreter/getgui.rb
  scripts/meterpreter/getgui.rb
Labels: enhancement

#16889 Remove scripts/meterpreter/get_valid_community.rb
  scripts/meterpreter/get_valid_community.rb
Labels: enhancement

#16888 Remove scripts/meterpreter/persistence.rb
  scripts/meterpreter/persistence.rb
Labels: enhancement

#16883 Deprecate srt_webdrive_priv script
  lib/msf/base/sessions/scriptable.rb
  scripts/meterpreter/srt_webdrive_priv.rb
Labels: enhancement, easy

#16884 Deprecate credcollect script
  lib/msf/base/sessions/scriptable.rb
  scripts/meterpreter/credcollect.rb
Labels: enhancement, easy

#16881 forward_pageant: Cleanup and fix default UNIX socket path
  documentation/modules/post/windows/manage/forward_pageant.md
  modules/post/windows/manage/forward_pageant.rb
Labels: bug

#16885 mv scripts/ps/msflag.ps1 data/post/powershell/msflag.ps1
  data/post/powershell/msflag.ps1
  modules/post/windows/manage/powershell/exec_powershell.rb
  modules/post/windows/manage/powershell/load_script.rb
  scripts/ps/msflag.ps1
Labels: enhancement, easy, rn-no-release-notes

#16902 Remove scripts/meterpreter/killav.rb
  scripts/meterpreter/killav.rb
Labels: enhancement

#16908 Deprecate dumplinks script
  lib/msf/base/sessions/scriptable.rb
  scripts/meterpreter/dumplinks.rb
Labels: enhancement, easy

#16910 Deprecate script arp_scanner
  lib/msf/base/sessions/scriptable.rb
  scripts/meterpreter/arp_scanner.rb
Labels: enhancement, easy

#16909 Deprecate get_pidgin_creds script
  lib/msf/base/sessions/scriptable.rb
  scripts/meterpreter/get_pidgin_creds.rb
Labels: enhancement, easy, rn-enhancement

#16905 Deprecate panda_2007_pavsrv51 script
  lib/msf/base/sessions/scriptable.rb
  scripts/meterpreter/panda_2007_pavsrv51.rb
Labels: enhancement, easy

#16809 Add exploit module for CVE-2022-2143
  documentation/modules/exploit/windows/http/advantech_iview_networkservlet_cmd_inject.md
  modules/exploits/windows/http/advantech_iview_networkservlet_cmd_inject.rb
Labels: module, docs, rn-modules

#16770 Kerberos CCache File Reuse
  lib/msf/core/exploit/remote/kerberos/client.rb
  lib/msf/core/exploit/remote/kerberos/client/ap_request.rb
  lib/msf/core/exploit/remote/kerberos/service_authenticator/base.rb
  lib/msf/core/exploit/remote/kerberos/service_authenticator/http.rb
  lib/msf/core/exploit/remote/kerberos/service_authenticator/ldap.rb
  lib/msf/core/exploit/remote/kerberos/service_authenticator/mssql.rb
  lib/msf/core/exploit/remote/kerberos/service_authenticator/smb.rb
  lib/msf/core/exploit/remote/ldap.rb
  lib/msf/core/exploit/remote/mssql.rb
  lib/msf/core/exploit/remote/smb/client.rb
  lib/msf/core/exploit/remote/smb/client/authenticated.rb
  lib/msf/core/exploit/remote/smb/client/kerberos_authentication.rb
  lib/msf/core/exploit/remote/winrm.rb
  lib/rex/proto/kerberos/credential_cache/krb5_ccache_principal.rb
  lib/rex/proto/kerberos/model/krb_cred_info.rb
  lib/rex/proto/kerberos/model/principal_name.rb
  modules/auxiliary/scanner/winrm/winrm_cmd.rb
  modules/auxiliary/scanner/winrm/winrm_login.rb
Labels: library, rn-enhancement, feature-kerberos-authentication

#16698 Adding Windows Automation
  docs/metasploit-framework.wiki/Nightly-Installers.md
Labels: docs

#16915 Add exploit for CVE-2022-23277 (Exchange RCE)
  data/exchange_versions.json
  documentation/modules/exploit/windows/http/exchange_chainedserializationbinder_denylist_typo_rce.md
  documentation/modules/exploit/windows/http/exchange_chainedserializationbinder_rce.md
  lib/msf/util/dot_net_deserialization.rb
  lib/msf/util/dot_net_deserialization/assemblies.rb
  lib/msf/util/dot_net_deserialization/gadget_chains.rb
  lib/msf/util/dot_net_deserialization/gadget_chains/data_set.rb
  lib/msf/util/dot_net_deserialization/gadget_chains/data_set_type_spoof.rb
  lib/msf/util/dot_net_deserialization/types.rb
  lib/msf/util/dot_net_deserialization/types/general.rb
  lib/msf/util/dot_net_deserialization/types/record_values.rb
  modules/exploits/windows/http/exchange_chainedserializationbinder_rce.rb
  spec/lib/msf/util/dot_net_deserialization_spec.rb
Labels: module, docs, rn-modules

#16912 Deprecate sound_recorder script
  lib/msf/base/sessions/scriptable.rb
  scripts/meterpreter/sound_recorder.rb
Labels: enhancement, easy

#16899 Deprecate domain_list_gen script
  lib/msf/base/sessions/scriptable.rb
  scripts/meterpreter/domain_list_gen.rb
Labels: enhancement, easy

#16907 ms10_092_schelevator: Cleanup
  documentation/modules/exploit/windows/local/ms10_092_schelevator.md
  modules/exploits/windows/local/ms10_092_schelevator.rb
Labels: module, enhancement

#16925 Fix a payload bug in unrar_cve_2022_30333
  documentation/modules/exploit/linux/fileformat/unrar_cve_2022_30333.md
  modules/exploits/linux/fileformat/unrar_cve_2022_30333.rb
Labels: module, bug, rn-fix

#16931 Stdapi::AudioOutput.play_file: raise if file +path+ is not readable
  lib/rex/post/meterpreter/extensions/stdapi/audio_output/audio_output.rb
Labels: library, meterpreter, bug, rn-fix

#16922 Exploit for Zimbra mboximport (CVE-2022-27925)
  documentation/modules/exploit/linux/http/zimbra_mboximport_cve_2022_27925.md
  modules/exploits/linux/http/zimbra_mboximport_cve_2022_27925.rb
Labels: module, docs, rn-modules

#16898 Msf::Post::Windows::Accounts: Add domain_controller? method
  lib/msf/core/post/windows/accounts.rb
  modules/post/windows/gather/credentials/domain_hashdump.rb
  modules/post/windows/gather/enum_domain_tokens.rb
  modules/post/windows/gather/ntds_grabber.rb
  modules/post/windows/gather/ntds_location.rb
  modules/post/windows/gather/smart_hashdump.rb
Labels: library, enhancement, rn-enhancement

#16936 Fix evasion module crashes
  lib/msf/core/evasion.rb
  lib/msf/core/exploit.rb
Labels: bug

#16701 Rewrite of Cisco ASA Clientless VPN Brute-force
  documentation/modules/auxiliary/scanner/http/cisco_asa_clientless_vpn.md
  lib/rex/proto/http/client.rb
  modules/auxiliary/scanner/http/cisco_asa_asdm.rb
  modules/auxiliary/scanner/http/cisco_asa_clientless_vpn.rb
Labels: module, docs, enhancement

#16935 Fix ssh server warnings on bootup with openssl 3
  lib/msf/core/handler/reverse_ssh.rb
Labels: openssl3

#16746 Fix individual mssql login crashes stopping further login attempts
  lib/metasploit/framework/login_scanner/mssql.rb
Labels: rn-enhancement

#16918 End the session when an HTTP/200 is received
  modules/exploits/linux/http/zimbra_unrar_cve_2022_30333.rb
Labels: module, bug, rn-fix

#16900 Msf::Post::Process: Add kill_process(pid) method
  lib/msf/core/post/process.rb
Labels: library, enhancement

#16869 Msf::Post::File.file_remote_digest[md5|sha1]: Cleanup and perform hashing remotely
  lib/msf/core/post/file.rb
Labels: library, bug, rn-fix

#16939 Add module for issuing certificates
  Gemfile.lock
  documentation/modules/auxiliary/admin/dcerpc/icpr_cert.md
  metasploit-framework.gemspec
  modules/auxiliary/admin/dcerpc/icpr_cert.rb
Labels: module, docs, rn-modules

#16786 Zyxel Firewall LPE (CVE-2022-30526)
  documentation/modules/exploit/linux/local/zyxel_suid_cp_lpe.md
  modules/exploits/linux/local/zyxel_suid_cp_lpe.rb
Labels: module, docs

#16955 Update ldap_query logic to handle binary data
  data/auxiliary/gather/ldap_query/ldap_queries_default.yaml
  modules/auxiliary/gather/ldap_query.rb
Labels: module, bug, rn-fix

#16903 enum_shares: Cleanup and support non-meterpreter sessions
  documentation/modules/post/windows/gather/enum_shares.md
  modules/post/windows/gather/enum_shares.rb
Labels: module, enhancement

#16958 Weekly dependency updates for Gemfile.lock
  Gemfile
  Gemfile.lock
  metasploit-framework.gemspec
Labels: rn-no-release-notes

#16750 Update jenkins_script_console.rb to remove deprecated sun.misc.BASE64Decoder class
  modules/exploits/multi/http/jenkins_script_console.rb
Labels: module, bug, needs-linting
