Repository rapid7/metasploit-framework, pull requests merged in 2022-07, with the labels that each got.

#16704 Fix bad loop terminator checks and data checks in memcached_extractor.rb
  modules/auxiliary/gather/memcached_extractor.rb
Labels: bug, rn-fix

#16723 Add FreeSwitch Login auxiliary module
  documentation/modules/auxiliary/scanner/misc/freeswitch_event_socket_login.md
  lib/metasploit/framework/login_scanner/freeswitch_event_socket.rb
  modules/auxiliary/scanner/misc/freeswitch_event_socket_login.rb
Labels: module, docs, rn-modules

#16731 Use proper permissions when opening a process
  lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb
Labels: bug, easy, rn-fix

#16719 Updated CCache Data Module
  lib/msf/core/exploit/remote/kerberos/client.rb
  lib/msf/core/exploit/remote/kerberos/client/cache_credential.rb
  lib/msf/core/exploit/remote/kerberos/client/tgs_response.rb
  lib/rex/proto/kerberos/credential_cache.rb
  lib/rex/proto/kerberos/credential_cache/cache.rb
  lib/rex/proto/kerberos/credential_cache/credential.rb
  lib/rex/proto/kerberos/credential_cache/element.rb
  lib/rex/proto/kerberos/credential_cache/key_block.rb
  lib/rex/proto/kerberos/credential_cache/krb5_ccache.rb
  lib/rex/proto/kerberos/credential_cache/krb5_ccache_credential.rb
  lib/rex/proto/kerberos/credential_cache/krb5_ccache_credential_address.rb
  lib/rex/proto/kerberos/credential_cache/krb5_ccache_credential_authdata.rb
  lib/rex/proto/kerberos/credential_cache/krb5_ccache_credential_keyblock.rb
  lib/rex/proto/kerberos/credential_cache/krb5_ccache_principal.rb
  lib/rex/proto/kerberos/credential_cache/primitive.rb
  lib/rex/proto/kerberos/credential_cache/primitive/krb5_ccache_address.rb
  lib/rex/proto/kerberos/credential_cache/primitive/krb5_ccache_bool.rb
  lib/rex/proto/kerberos/credential_cache/primitive/krb5_ccache_data.rb
  lib/rex/proto/kerberos/credential_cache/primitive/krb5_ccache_epoch.rb
  lib/rex/proto/kerberos/credential_cache/principal.rb
  lib/rex/proto/kerberos/credential_cache/time.rb
  lib/rex/proto/thrift.rb
  modules/exploits/linux/misc/nimbus_gettopologyhistory_cmd_exec.rb
  spec/lib/msf/core/exploit/remote/kerberos/client/cache_credential_spec.rb
  spec/lib/msf/core/exploit/remote/kerberos/client/tgs_response_spec.rb
  spec/lib/rex/proto/kerberos/credential_cache/cache_spec.rb
  spec/lib/rex/proto/kerberos/credential_cache/credential_spec.rb
  spec/lib/rex/proto/kerberos/credential_cache/key_block.rb
  spec/lib/rex/proto/kerberos/credential_cache/krb5_ccache_credential_address_spec.rb
  spec/lib/rex/proto/kerberos/credential_cache/krb5_ccache_credential_authdata_spec.rb
  spec/lib/rex/proto/kerberos/credential_cache/krb5_ccache_credential_keyblock_spec.rb
  spec/lib/rex/proto/kerberos/credential_cache/krb5_ccache_credential_spec.rb
  spec/lib/rex/proto/kerberos/credential_cache/krb5_ccache_principal_spec.rb
  spec/lib/rex/proto/kerberos/credential_cache/krb5_ccache_spec.rb
  spec/lib/rex/proto/kerberos/credential_cache/primitive/krb5_ccache_address_spec.rb
  spec/lib/rex/proto/kerberos/credential_cache/primitive/krb5_ccache_bool_spec.rb
  spec/lib/rex/proto/kerberos/credential_cache/primitive/krb5_ccache_data_spec.rb
  spec/lib/rex/proto/kerberos/credential_cache/primitive/krb5_ccache_epoch_spec.rb
  spec/lib/rex/proto/kerberos/credential_cache/principal_spec.rb
  spec/lib/rex/proto/kerberos/credential_cache/time_spec.rb
Labels: library, tests, feature-kerberos-authentication

#16716 Exploit::CmdStager: Expose CMDSTAGER::URIPATH option for HTTP stagers
  lib/msf/core/exploit/cmd_stager.rb
Labels: library, enhancement

#16567 Juniper config processor enhancements
  lib/msf/core/auxiliary/juniper.rb
  spec/lib/msf/core/auxiliary/juniper_spec.rb
Labels: library

#16670 Add initial smb kerberos authentication support
  Gemfile.lock
  lib/msf/core/exploit/remote/auth_option.rb
  lib/msf/core/exploit/remote/kerberos/client.rb
  lib/msf/core/exploit/remote/kerberos/client/tgs_request.rb
  lib/msf/core/exploit/remote/kerberos/client/tgs_response.rb
  lib/msf/core/exploit/remote/kerberos/service_authenticator/base.rb
  lib/msf/core/exploit/remote/kerberos/service_authenticator/smb.rb
  lib/msf/core/exploit/remote/smb/client.rb
  lib/msf/core/exploit/remote/smb/client/authenticated.rb
  lib/msf/core/exploit/remote/smb/client/kerberos_authentication.rb
  lib/msf/core/rhosts_walker.rb
  lib/msf/ui/console/module_argument_parsing.rb
  lib/rex/proto/gss.rb
  lib/rex/proto/kerberos/README.md
  lib/rex/proto/kerberos/model/ap_req.rb
  lib/rex/proto/kerberos/model/authenticator.rb
  lib/rex/proto/smb/simple_client.rb
  modules/auxiliary/admin/kerberos/ms14_068_kerberos_checksum.rb
  spec/lib/msf/core/exploit/remote/kerberos/service_authenticator/base_spec.rb
  spec/lib/msf/core/exploit/remote/smb/client/kerberos_authentication_spec.rb
  spec/lib/msf/core/rhosts_walker_spec.rb
  spec/msf/ui/console/module_argument_parsing_spec.rb
Labels: feature-kerberos-authentication

#16733 Add the dfscoerce module
  Gemfile.lock
  documentation/modules/auxiliary/scanner/dcerpc/dfscoerce.md
  modules/auxiliary/scanner/dcerpc/dfscoerce.rb
  modules/auxiliary/scanner/dcerpc/petitpotam.rb
Labels: module, docs, delayed, rn-modules

#16735 enable MeterpreterTryToFork by default for aerohive_netconfig_lfi_log_poison_rce
  documentation/modules/exploit/unix/webapp/aerohive_netconfig_lfi_log_poison_rce.md
  modules/exploits/unix/webapp/aerohive_netconfig_lfi_log_poison_rce.rb
Labels: module, enhancement

#16718 Fix `run_as` local exploit module on x64 systems
  lib/msf/core/post/windows/runas.rb
  modules/exploits/windows/local/run_as.rb
  spec/lib/msf/core/post/windows/runas_spec.rb
Labels: bug, easy, rn-fix

#16617 fix race condition when scanning short ranges
  modules/auxiliary/scanner/discovery/ipv6_neighbor.rb
Labels: module, bug

#16763 Fix crash in ms04-007-killbill
  modules/exploits/windows/smb/ms04_007_killbill.rb
Labels: module, rn-fix

#16700 LDAP Kerberos and NTLM authentication
  lib/msf/core/exploit/remote/kerberos/service_authenticator/ldap.rb
  lib/msf/core/exploit/remote/ldap.rb
Labels: library, feature-kerberos-authentication

#16764 Rex::Proto::Http: Add evasion options to shuffle GET / POST parameters
  lib/metasploit/framework/login_scanner/http.rb
  lib/msf/core/exploit/remote/http_client.rb
  lib/rex/proto/http/client.rb
  lib/rex/proto/http/client_request.rb
Labels: library, enhancement

#16747 add lotus domino hash extraction spec
  spec/file_fixtures/modules/auxiliary/lotus_domino_hash_response.xml
  spec/file_fixtures/modules/auxiliary/lotus_domino_hash_response_no_cred.xml
  spec/modules/auxiliary/scanner/lotus/lotus_domino_hashes_spec.rb
Labels: tests, rn-no-release-notes

#16766 update docs for Pro links
  docs/metasploit-framework.wiki/Downloads-by-Version.md
Labels: docs, rn-no-release-notes

#16744 Added Jboss remoting unified invoker RCE module
  documentation/modules/exploit/multi/misc/jboss_remoting_unified_invoker_rce.md
  modules/exploits/multi/misc/jboss_remoting_unified_invoker_rce.rb
Labels: module, docs

#16736 Confluence widget connector bugfix and linting
  modules/exploits/multi/http/confluence_widget_connector.rb
Labels: module, bug, rn-fix

#16727 exploits: Set tftphost option for modules which use Windows TFTP stager
  modules/exploits/multi/http/struts_code_exec.rb
  modules/exploits/multi/http/struts_code_exec_exception_delegator.rb
  modules/exploits/windows/antivirus/ams_xfr.rb
  modules/exploits/windows/http/ca_totaldefense_regeneratereports.rb
  modules/exploits/windows/http/osb_uname_jlist.rb
  modules/exploits/windows/iis/msadc.rb
  modules/exploits/windows/misc/altiris_ds_sqli.rb
  modules/exploits/windows/mssql/mssql_payload.rb
Labels: module, bug

#16762 Add exploit for CVE-2022-23642 Sourcegraph gitserver exec RCE
  documentation/modules/exploit/linux/http/sourcegraph_gitserver_sshcmd.md
  modules/exploits/linux/http/sourcegraph_gitserver_sshcmd.rb
Labels: module, docs, rn-modules

#16772 Add FtpHttp command stager - bump rex-exploitation gem from 0.1.31 to 0.1.33
  Gemfile.lock
Labels: enhancement

#16749 Winrm kerberos authentication support
  lib/metasploit/framework/login_scanner/http.rb
  lib/metasploit/framework/login_scanner/kerberos.rb
  lib/metasploit/framework/login_scanner/result.rb
  lib/metasploit/framework/login_scanner/winrm.rb
  lib/msf/core/exploit/remote/kerberos/client/tgs_request.rb
  lib/msf/core/exploit/remote/kerberos/service_authenticator/base.rb
  lib/msf/core/exploit/remote/kerberos/service_authenticator/http.rb
  lib/net/winrm/rex_http_transport.rb
  lib/rex/proto/gss.rb
  lib/rex/proto/gss/asn1.rb
  lib/rex/proto/gss/kerberos/message_encryptor.rb
  lib/rex/proto/http/client.rb
  lib/rex/proto/kerberos/client.rb
  lib/rex/proto/kerberos/crypto.rb
  lib/rex/proto/kerberos/crypto/aes_block_cipher_base.rb
  lib/rex/proto/kerberos/crypto/block_cipher_base.rb
  lib/rex/proto/kerberos/crypto/des3_cbc_sha1.rb
  lib/rex/proto/kerberos/crypto/des_cbc_md5.rb
  lib/rex/proto/kerberos/crypto/gss_new_encryption_type.rb
  lib/rex/proto/kerberos/crypto/rc4_hmac.rb
  lib/rex/proto/kerberos/crypto/utils.rb
  lib/rex/proto/kerberos/model.rb
  lib/rex/proto/kerberos/model/ap_rep.rb
  lib/rex/proto/kerberos/model/authenticator.rb
  lib/rex/proto/kerberos/model/enc_ap_rep_part.rb
  lib/rex/proto/kerberos/model/kdc_request_body.rb
  lib/rex/proto/kerberos/model/kdc_response.rb
  lib/rex/proto/kerberos/model/krb_cred.rb
  modules/auxiliary/scanner/winrm/winrm_cmd.rb
  modules/auxiliary/scanner/winrm/winrm_login.rb
  spec/lib/msf/core/exploit/remote/kerberos/client/tgs_request_spec.rb
  spec/lib/rex/proto/gss/kerberos/message_encryptor_spec.rb
  spec/lib/rex/proto/kerberos/crypto/aes128_cts_sha1_spec.rb
  spec/lib/rex/proto/kerberos/crypto/aes256_cts_sha1_spec.rb
  spec/lib/rex/proto/kerberos/crypto/des3_cbc_sha1_spec.rb
  spec/lib/rex/proto/kerberos/crypto/des_cbc_md5_spec.rb
  spec/lib/rex/proto/kerberos/crypto/rc4_hmac_spec.rb
  spec/lib/rex/proto/kerberos/model/ap_rep_spec.rb
Labels: feature

#16754 ms02_065_msadc: Cleanup and add additional offsets
  modules/exploits/windows/iis/ms02_065_msadc.rb
Labels: module, enhancement

#16761 ms01_023_printer: cleanup; use HttpClient; add additional targets
  documentation/modules/exploit/windows/iis/ms01_023_printer.md
  modules/exploits/windows/iis/ms01_023_printer.rb
Labels: module, enhancement

#16753 ms03_007_ntdll_webdav: Cleanup and add additional offsets
  documentation/modules/exploit/windows/iis/ms03_007_ntdll_webdav.md
  modules/exploits/windows/iis/ms03_007_ntdll_webdav.rb
Labels: module, enhancement

#16776 Add Rex::Exploitation::CmdStagerFtpHttp to Msf::Exploit::CmdStager
  lib/msf/core/exploit/cmd_stager.rb
Labels: library, enhancement, easy

#16789 Add openssl version to debug command
  lib/msf/ui/debug.rb
  spec/lib/msf/debug_spec.rb
Labels: openssl3

#16792 Widen rescue scope for reverse ssh handler
  lib/msf/core/handler/reverse_ssh.rb
Labels: openssl3

#16737 Remove initial code duplication between mssql clients
  lib/metasploit/framework/mssql/base.rb
  lib/metasploit/framework/mssql/client.rb
  lib/msf/core/exploit/remote/mssql.rb
Labels: library, enhancement

#16778 Deprecate checkvm script and update checkvm post module
  modules/post/windows/gather/checkvm.rb
  scripts/meterpreter/checkvm.rb
Labels: enhancement, rn-enhancement

#16797 Workflows: Labels: Fix typo
  .github/workflows/labels.yml
Labels: easy, rn-no-release-notes

#16774 Suggest a correct datastore option
  lib/msf/ui/console/command_dispatcher/core.rb
  spec/lib/msf/ui/console/command_dispatcher/core_spec.rb
Labels: library, enhancement

#16668 HTTP Crawler: don't expect page object for msg
  lib/msf/core/auxiliary/http_crawler.rb
  modules/auxiliary/scanner/http/crawler.rb
Labels: module, library, bug, rn-fix

#16813 Fix default LDAP query descriptions due to some typos
  data/auxiliary/gather/ldap_query/ldap_queries_default.yaml
Labels: easy, rn-no-release-notes

#16810 Fix --tag for 'hosts' -t | --tag cmd command
  lib/msf/ui/console/command_dispatcher/db.rb
  spec/lib/msf/ui/console/command_dispatcher/db_spec.rb
Labels: library, bug, rn-fix

#16760 Send delegated credentials using WinRM
  lib/msf/core/exploit/remote/kerberos/client.rb
  lib/msf/core/exploit/remote/kerberos/service_authenticator/base.rb
  lib/net/winrm/rex_http_transport.rb
  lib/rex/proto/kerberos/model.rb
  lib/rex/proto/kerberos/model/enc_krb_cred_part.rb
  lib/rex/proto/kerberos/model/krb_cred.rb
  lib/rex/proto/kerberos/model/krb_cred_info.rb
Labels: library, enhancement, feature-kerberos-authentication

#16094 Fix msfdb init command failure in systems that use the 'pg_ctl.rb' msfdb_helper
  lib/msfdb_helpers/db_interface.rb
  lib/msfdb_helpers/pg_ctl.rb
  msfdb
Labels: bug, database, rn-fix

#16739 Weekly dependency updates for Gemfile.lock
  Gemfile.lock
Labels: rn-no-release-notes, automation

#16824 Msf::Post::Windows::Priv: Fix is_admin? / is_system? for shell sessions
  lib/msf/core/post/windows/priv.rb
Labels: library, bug, rn-fix

#16831 Remove scripts/meterpreter/get_env.rb
  scripts/meterpreter/get_env.rb
Labels: enhancement, rn-enhancement

#16830 Remove scripts/meterpreter/getvncpw.rb
  scripts/meterpreter/getvncpw.rb
Labels: enhancement, rn-enhancement

#16825 Add better support for IMAP strings when capturing creds
  modules/auxiliary/server/capture/imap.rb
Labels: module, bug, rn-fix
