Repository rapid7/metasploit-framework, pull requests merged in 2023-11, with the labels that each got.

#18494 Add Exploit for AjaxPro Deserialization RCE (CVE 2021-23758)
  documentation/modules/exploit/windows/http/ajaxpro_deserialization_rce.md
  modules/exploits/windows/http/ajaxpro_deserialization_rce.rb
Labels: module, docs

#18481 MagnusBilling unauthenticated RCE [CVE-2023-30258]
  documentation/modules/exploit/linux/http/magnusbilling_unauth_rce_cve_2023_30258.md
  modules/exploits/linux/http/magnusbilling_unauth_rce_cve_2023_30258.rb
Labels: module, docs, rn-modules

#18503 Apache NiFi Creds Stealer (post module)
  documentation/modules/post/linux/gather/apache_nifi_credentials.md
  modules/post/linux/gather/apache_nifi_credentials.rb
Labels: module, docs

#18491 Add Module for PL/SQL Developer to gather credentials
  documentation/modules/post/windows/gather/credentials/plsql_developer.md
  modules/post/windows/gather/credentials/plsql_developer.rb
Labels: needs-linting

#18434 Zoneminder snapshot
  documentation/modules/exploit/unix/webapp/zoneminder_snapshots.md
  modules/exploits/unix/webapp/zoneminder_snapshots.rb
Labels: module, docs, rn-modules

#18448 corrected options confict between module and ldap mixin
  documentation/modules/auxiliary/admin/ldap/vmware_vcenter_vmdir_auth_bypass.md
  modules/auxiliary/admin/ldap/vmware_vcenter_vmdir_auth_bypass.rb
Labels: bug

#18558 Fix #18544: Support x64 in enum_chrome
  lib/rex/post/meterpreter/extensions/stdapi/railgun/def/windows/def_kernel32.rb
  modules/post/windows/gather/enum_chrome.rb
Labels: module, bug, rn-fix

#18564 Fix an uninitialized constant error in capture/http
  lib/rex/proto/http/server.rb
  lib/rex/proto/http/server_client.rb
Labels: module, bug, easy, rn-fix

#18547 Update ssh login pubkey module to correctly identify windows ssh platform
  lib/metasploit/framework/ssh/platform.rb
  spec/lib/metasploit/framework/ssh/platform_spec.rb
  spec/spec_helper.rb
Labels: library, bug, rn-fix

#18526 Add a command to customise DNS resolution (including through sessions)
  lib/msf/base/sessions/meterpreter.rb
  lib/msf/base/sessions/ssh_command_shell_bind.rb
  lib/msf/core/feature_manager.rb
  lib/msf/core/framework.rb
  lib/msf/core/session/comm.rb
  lib/msf/ui/console/command_dispatcher/core.rb
  lib/msf/ui/console/command_dispatcher/dns.rb
  lib/msf/ui/console/driver.rb
  lib/net/dns/resolver.rb
  lib/rex/proto/dns/cached_resolver.rb
  lib/rex/proto/dns/custom_nameserver_provider.rb
  lib/rex/proto/dns/resolver.rb
  spec/lib/rex/proto/dns/custom_nameserver_provider_spec.rb
Labels: feature, enhancement, rn-enhancement

#18565 Check the cache for a TGT without a host
  lib/msf/core/exploit/remote/kerberos/service_authenticator/base.rb
Labels: library, enhancement, rn-enhancement

#18567 Add Exploit Module for WP Royal Elementor Addons Unauthenticated File Upload (CVE-2023-5360)
  data/wordlists/wp-exploitable-plugins.txt
  documentation/modules/exploit/multi/http/wp_royal_elementor_addons_rce.md
  modules/exploits/multi/http/wp_royal_elementor_addons_rce.rb
Labels: module, docs
