Repository rapid7/metasploit-framework, pull requests merged in 2023-02, with the labels that each got.

#17301 cve-2022-1043: linux priv esc with kernel v5.12-rc3 to v5.14-rc7
  LICENSE
  data/exploits/CVE-2022-1043/pre_compiled
  documentation/modules/exploit/linux/local/cve_2022_1043_io_uring_priv_esc.md
  external/source/exploits/CVE-2022-1043/cve-2022-1043.c
  modules/exploits/linux/local/cve_2022_1043_io_uring_priv_esc.rb
Labels: module, docs

#17481 update http options module
  modules/auxiliary/scanner/http/options.rb
Labels: enhancement, rn-enhancement

#17406 Add veeam_credential_dump post module
  documentation/modules/post/windows/gather/credentials/veeam_credential_dump.md
  modules/post/windows/gather/credentials/veeam_credential_dump.rb
Labels: module, docs

#17580 Fix missed references to old wiki site and update them to point to new docs website
  docs/metasploit-framework.wiki/Metasploit-5.0-Release-Notes.md
  docs/metasploit-framework.wiki/Metasploit-6.0-Development-Notes.md
  docs/metasploit-framework.wiki/dev/Setting-Up-a-Metasploit-Development-Environment.md
  documentation/README.md
  modules/exploits/linux/local/cve_2022_1043_io_uring_priv_esc.rb
Labels: docs, easy, rn-no-release-notes

#17581 modules: Check datastore ForceExploit before checking if session is root
  modules/exploits/example_linux_priv_esc.rb
  modules/exploits/freebsd/local/intel_sysret_priv_esc.rb
  modules/exploits/freebsd/local/ip6_setpktopt_uaf_priv_esc.rb
  modules/exploits/freebsd/local/rtld_execl_priv_esc.rb
  modules/exploits/linux/local/abrt_sosreport_priv_esc.rb
  modules/exploits/linux/local/af_packet_chocobo_root_priv_esc.rb
  modules/exploits/linux/local/af_packet_packet_set_ring_priv_esc.rb
  modules/exploits/linux/local/asan_suid_executable_priv_esc.rb
  modules/exploits/linux/local/blueman_set_dhcp_handler_dbus_priv_esc.rb
  modules/exploits/linux/local/bpf_priv_esc.rb
  modules/exploits/linux/local/bpf_sign_extension_priv_esc.rb
  modules/exploits/linux/local/cve_2021_3490_ebpf_alu32_bounds_check_lpe.rb
  modules/exploits/linux/local/cve_2021_3493_overlayfs.rb
  modules/exploits/linux/local/cve_2021_4034_pwnkit_lpe_pkexec.rb
  modules/exploits/linux/local/cve_2022_0995_watch_queue.rb
  modules/exploits/linux/local/cve_2022_1043_io_uring_priv_esc.rb
  modules/exploits/linux/local/diamorphine_rootkit_signal_priv_esc.rb
  modules/exploits/linux/local/docker_daemon_privilege_escalation.rb
  modules/exploits/linux/local/exim4_deliver_message_priv_esc.rb
  modules/exploits/linux/local/glibc_realpath_priv_esc.rb
  modules/exploits/linux/local/hp_xglance_priv_esc.rb
  modules/exploits/linux/local/ktsuss_suid_priv_esc.rb
  modules/exploits/linux/local/lastore_daemon_dbus_priv_esc.rb
  modules/exploits/linux/local/libuser_roothelper_priv_esc.rb
  modules/exploits/linux/local/nested_namespace_idmap_limit_priv_esc.rb
  modules/exploits/linux/local/network_manager_vpnc_username_priv_esc.rb
  modules/exploits/linux/local/omniresolve_suid_priv_esc.rb
  modules/exploits/linux/local/ptrace_sudo_token_priv_esc.rb
  modules/exploits/linux/local/ptrace_traceme_pkexec_helper.rb
  modules/exploits/linux/local/rds_atomic_free_op_null_pointer_deref_priv_esc.rb
  modules/exploits/linux/local/rds_rds_page_copy_user_priv_esc.rb
  modules/exploits/linux/local/recvmmsg_priv_esc.rb
  modules/exploits/linux/local/reptile_rootkit_reptile_cmd_priv_esc.rb
  modules/exploits/linux/local/servu_ftp_server_prepareinstallation_priv_esc.rb
  modules/exploits/linux/local/sock_sendpage.rb
  modules/exploits/linux/local/systemtap_modprobe_options_priv_esc.rb
  modules/exploits/linux/local/ubuntu_enlightenment_mount_priv_esc.rb
  modules/exploits/linux/local/ufo_privilege_escalation.rb
  modules/exploits/linux/local/vcenter_java_wrapper_vmon_priv_esc.rb
  modules/exploits/linux/local/vmware_alsa_config.rb
  modules/exploits/linux/local/vmwgfx_fd_priv_esc.rb
  modules/exploits/openbsd/local/dynamic_loader_chpass_privesc.rb
  modules/exploits/osx/local/vmware_fusion_lpe.rb
  modules/exploits/qnx/local/ifwatchd_priv_esc.rb
Labels: module, rn-enhancement, code quality

#17561 Fix input and output buffers for some mislabeled functions in def_iphlpapi.rb
  lib/rex/post/meterpreter/extensions/stdapi/railgun/def/windows/def_iphlpapi.rb
  lib/rex/post/meterpreter/extensions/stdapi/railgun/library.rb
Labels: library, bug, rn-fix

#16946 Add row indicator to `show targets` command
  Gemfile.lock
  lib/msf/base/serializer/readable_text.rb
  lib/msf/ui/console/command_dispatcher/core.rb
  lib/msf/ui/console/command_dispatcher/modules.rb
  lib/msf/ui/console/table_print/omit_column_header.rb
  lib/msf/ui/console/table_print/row_indicator_styler.rb
  lib/rex/ui/text/dispatcher_shell.rb
  modules/post/multi/manage/autoroute.rb
  scripts/meterpreter/autoroute.rb
Labels: enhancement

#17585 Added missing session types to dirty_cow module
  documentation/modules/exploit/osx/local/mac_dirty_cow.md
  modules/exploits/osx/local/mac_dirty_cow.rb
Labels: rn-no-release-notes

#17392 Add a privilege escalation module for F5 that uses the unsecured MCP socket to create a new root account
  documentation/modules/exploit/linux/local/f5_create_user.md
  modules/exploits/linux/local/f5_create_user.rb
Labels: module, docs

#17398 Update cmdstager docs
  docs/metasploit-framework.wiki/How-to-use-command-stagers.md
Labels: docs, rn-wiki

#17371 Lenovo Diagnostics Driver Privilege Escalation (CVE-2022-3699)
  data/exploits/CVE-2022-3699/CVE-2022-3699.x64.dll
  documentation/modules/exploit/windows/local/cve_2022_3699_lenovo_diagnostics_driver.md
  external/source/exploits/CVE-2022-3699/CVE-2022-3699.sln
  external/source/exploits/CVE-2022-3699/CVE-2022-3699/CVE-2022-3699.vcxproj
  external/source/exploits/CVE-2022-3699/CVE-2022-3699/LenovoMemoryMgr.cpp
  external/source/exploits/CVE-2022-3699/CVE-2022-3699/LenovoMemoryMgr.h
  external/source/exploits/CVE-2022-3699/CVE-2022-3699/dllmain.cpp
  external/source/exploits/CVE-2022-3699/CVE-2022-3699/exploit.cpp
  external/source/exploits/CVE-2022-3699/CVE-2022-3699/exploit.h
  external/source/include/windows/common.h
  modules/exploits/windows/local/cve_2022_3699_lenovo_diagnostics_driver.rb
Labels: module, docs, rn-modules

#17587 Update wiki to use latest ruby conventions
  docs/metasploit-framework.wiki/Creating-Metasploit-Framework-LoginScanners.md
  docs/metasploit-framework.wiki/Get-Started-Writing-an-Exploit.md
  docs/metasploit-framework.wiki/How-to-Send-an-HTTP-Request-Using-HttpClient.md
  docs/metasploit-framework.wiki/How-to-deprecate-a-Metasploit-module.md
  docs/metasploit-framework.wiki/How-to-get-started-with-writing-an-auxiliary-module.md
  docs/metasploit-framework.wiki/How-to-use-command-stagers.md
  docs/metasploit-framework.wiki/How-to-use-datastore-options.md
  docs/metasploit-framework.wiki/How-to-write-a-HTTP-LoginScanner-Module.md
  docs/metasploit-framework.wiki/How-to-write-a-browser-exploit-using-BrowserExploitServer.md
  docs/metasploit-framework.wiki/How-to-write-a-browser-exploit-using-HttpServer.md
  docs/metasploit-framework.wiki/How-to-write-a-module-using-HttpServer-and-HttpClient.md
  docs/metasploit-framework.wiki/Module-Reference-Identifiers.md
Labels: rn-wiki

#17452 Fix import-dev-keys.sh
  docs/metasploit-framework.wiki/Committer-Keys.md
  tools/dev/import-dev-keys.sh
Labels: rn-no-release-notes

#17591 Fix metasm_shell by requiring readline
  lib/rex/ui/text/shell.rb
  tools/exploit/metasm_shell.rb
  tools/exploit/nasm_shell.rb
Labels: bug, easy, rn-fix

#17597 qubes_mirage_firewall_dos: Fix notes for SideEffects and Reliability
  modules/auxiliary/dos/mirageos/qubes_mirage_firewall_dos.rb
Labels: easy

#17595 Documentation update to reflect Address instead of Host in ReverseListener setup
  docs/metasploit-framework.wiki/Debugging-Dead-Meterpreter-Sessions.md
Labels: docs, easy, rn-no-release-notes

#17483 tomcat 8 priv esc on ubuntu (cve-2016-1240)
  data/exploits/CVE-2016-1240/privesc_preload.c
  data/exploits/CVE-2016-1240/stub.so
  documentation/modules/exploit/linux/local/tomcat_ubuntu_log_init_priv_esc.md
  modules/exploits/linux/local/tomcat_ubuntu_log_init_priv_esc.rb
Labels: module, docs

#17598 modules/exploits/unix/local: Add Notes and resolve RuboCop violations
  modules/exploits/unix/local/at_persistence.rb
  modules/exploits/unix/local/chkrootkit.rb
  modules/exploits/unix/local/emacs_movemail.rb
  modules/exploits/unix/local/exim_perl_startup.rb
  modules/exploits/unix/local/netbsd_mail_local.rb
  modules/exploits/unix/local/setuid_nmap.rb
Labels: code quality

#17527 ManageEngine ServiceDesk Plus RCE (CVE-2022-47966)
  documentation/modules/exploit/multi/http/manageengine_servicedesk_plus_saml_rce_cve_2022_47966.md
  modules/exploits/multi/http/manageengine_servicedesk_plus_saml_rce_cve_2022_47966.rb
Labels: module, docs

#17494 Add NagiosXI authenticated RCE (CVE-2021-25296, CVE-2021-25297,CVE-2021-25298) exploit module
  documentation/modules/exploit/linux/http/nagios_xi_configwizards_authenticated_rce.md
  modules/exploits/linux/http/nagios_xi_configwizards_authenticated_rce.rb
Labels: module, docs, rn-modules

#17556 ManageEngine ADSelfService Plus RCE (CVE-2022-47966)
  documentation/modules/exploit/multi/http/manageengine_adselfservice_plus_saml_rce_cve_2022_47966.md
  modules/exploits/multi/http/manageengine_adselfservice_plus_saml_rce_cve_2022_47966.rb
Labels: module, docs

#17614 Weekly dependency updates for Gemfile.lock
  Gemfile.lock
Labels: rn-no-release-notes

#17615 Add missing module notes for stability reliability and side effects
  modules/auxiliary/admin/http/ibm_drm_download.rb
  modules/auxiliary/admin/http/netgear_r6700_pass_reset.rb
  modules/auxiliary/admin/networking/arista_config.rb
  modules/auxiliary/admin/networking/cisco_vpn_3000_ftp_bypass.rb
  modules/auxiliary/admin/networking/f5_config.rb
  modules/auxiliary/admin/networking/juniper_config.rb
  modules/auxiliary/admin/networking/mikrotik_config.rb
  modules/auxiliary/admin/networking/vyos_config.rb
  modules/auxiliary/admin/sap/cve_2020_6207_solman_rce.rb
  modules/auxiliary/admin/sap/cve_2020_6287_ws_add_user.rb
  modules/auxiliary/admin/sap/sap_igs_xmlchart_xxe.rb
  modules/auxiliary/dos/dns/bind_tsig_badtime.rb
  modules/auxiliary/dos/http/cable_haunt_websocket_dos.rb
  modules/auxiliary/gather/peplink_bauth_sqli.rb
  modules/auxiliary/gather/redis_extractor.rb
  modules/auxiliary/gather/saltstack_salt_root_key.rb
  modules/auxiliary/gather/shodan_host.rb
  modules/auxiliary/gather/vbulletin_getindexablecontent_sqli.rb
  modules/auxiliary/gather/zookeeper_info_disclosure.rb
  modules/auxiliary/scanner/http/limesurvey_zip_traversals.rb
  modules/auxiliary/scanner/http/springcloud_directory_traversal.rb
  modules/auxiliary/scanner/http/synology_forget_passwd_user_enum.rb
  modules/auxiliary/scanner/http/wp_duplicator_file_read.rb
  modules/auxiliary/scanner/http/zenload_balancer_traversal.rb
  modules/auxiliary/scanner/scada/modbus_banner_grabbing.rb
  modules/auxiliary/server/teamviewer_uri_smb_redirect.rb
  modules/auxiliary/sqli/dlink/dlink_central_wifimanager_sqli.rb
  modules/exploits/multi/http/atutor_upload_traversal.rb
  modules/post/android/local/koffee.rb
  modules/post/linux/gather/enum_containers.rb
  modules/post/linux/gather/haserl_read.rb
  modules/post/multi/gather/enum_hexchat.rb
  modules/post/multi/gather/enum_software_versions.rb
  modules/post/multi/gather/saltstack_salt.rb
  modules/post/multi/gather/unix_cached_ad_hashes.rb
  modules/post/multi/gather/unix_kerberos_tickets.rb
  modules/post/multi/sap/smdagent_get_properties.rb
  modules/post/networking/gather/enum_cisco.rb
  modules/post/networking/gather/enum_f5.rb
  modules/post/networking/gather/enum_mikrotik.rb
  modules/post/networking/gather/enum_vyos.rb
  modules/post/osx/escalate/tccbypass.rb
  modules/post/osx/gather/gitignore.rb
  modules/post/windows/gather/avast_memory_dump.rb
  modules/post/windows/gather/credentials/pulse_secure.rb
  modules/post/windows/gather/credentials/xshell_xftp_password.rb
  modules/post/windows/gather/enum_onedrive.rb
  modules/post/windows/gather/exchange.rb
  modules/post/windows/gather/forensics/fanny_bmp_check.rb
  modules/post/windows/manage/add_user.rb
  modules/post/windows/manage/execute_dotnet_assembly.rb
  modules/post/windows/manage/install_python.rb
Labels: rn-enhancement

#17607 Fortra deserialization RCE CVE-2023-0669 (ETR)
  modules/exploits/multi/http/fortra_goanywhere_rce_cve_2023_0669.md
  modules/exploits/multi/http/fortra_goanywhere_rce_cve_2023_0669.rb
Labels: module, docs, rn-modules

#17619 Run rubocop on exploit modules
  .rubocop.yml
  modules/exploits/linux/http/axis_app_install.rb
  modules/exploits/linux/http/ibm_drm_rce.rb
  modules/exploits/linux/http/linuxki_rce.rb
  modules/exploits/linux/http/pandora_fms_events_exec.rb
  modules/exploits/linux/local/docker_privileged_container_escape.rb
  modules/exploits/linux/local/su_login.rb
  modules/exploits/linux/local/sudo_baron_samedit.rb
  modules/exploits/linux/misc/tplink_archer_a7_c7_lan_rce.rb
  modules/exploits/linux/redis/redis_debian_sandbox_escape.rb
  modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
  modules/exploits/multi/http/gitlab_file_read_rce.rb
  modules/exploits/multi/misc/ibm_tm1_unauth_rce.rb
  modules/exploits/windows/http/exchange_proxylogon_rce.rb
  modules/exploits/windows/http/hpe_sim_76_amf_deserialization.rb
  modules/exploits/windows/http/sharepoint_workflows_xoml.rb
  modules/exploits/windows/local/cve_2020_1054_drawiconex_lpe.rb
  modules/exploits/windows/local/lexmark_driver_privesc.rb
  modules/exploits/windows/local/ntusermndragover.rb
  modules/exploits/windows/local/tokenmagic.rb
  modules/exploits/windows/nimsoft/nimcontroller_bof.rb
Labels: rn-no-release-notes

#17623 Move fortra_goanywhere_rce_cve_2023_0669 module documentation to documentation directory
  documentation/modules/exploit/multi/http/fortra_goanywhere_rce_cve_2023_0669.md
Labels: docs, easy

#17592 Fix bypassuac_injection_winsxs for x64
  lib/rex/post/meterpreter/extensions/stdapi/railgun/def/windows/def_kernel32.rb
  modules/exploits/windows/local/bypassuac_injection_winsxs.rb
Labels: module, library, bug, rn-fix

#17625 Add credit for CVE-2023-0669; fix path in docs
  documentation/modules/exploit/multi/http/fortra_goanywhere_rce_cve_2023_0669.md
  modules/exploits/multi/http/fortra_goanywhere_rce_cve_2023_0669.rb
Labels: rn-no-release-notes

#17626 Fix Frycos author name in fortra_goanywhere_rce_cve_2023_0669.rb
  modules/exploits/multi/http/fortra_goanywhere_rce_cve_2023_0669.rb
Labels: rn-no-release-notes

#17599 Cisco RV LAN Exploit - CVE-2022-20705 and CVE-2022-20707
  documentation/modules/exploit/linux/http/cisco_rv340_lan.md
  modules/exploits/linux/http/cisco_rv340_lan.rb
Labels: module, docs, rn-modules

#17281 Added module for CVE-2022-2992 - Gitlab Remote Command Execution via Github import
  documentation/modules/exploit/multi/http/gitlab_github_import_rce_cve_2022_2992.md
  lib/msf/core/exploit/remote/http/gitlab.rb
  lib/msf/core/exploit/remote/http/gitlab/access_tokens.rb
  lib/msf/core/exploit/remote/http/gitlab/authenticate.rb
  lib/msf/core/exploit/remote/http/gitlab/error.rb
  lib/msf/core/exploit/remote/http/gitlab/form.rb
  lib/msf/core/exploit/remote/http/gitlab/form/access_tokens.rb
  lib/msf/core/exploit/remote/http/gitlab/form/authenticate.rb
  lib/msf/core/exploit/remote/http/gitlab/groups.rb
  lib/msf/core/exploit/remote/http/gitlab/helpers.rb
  lib/msf/core/exploit/remote/http/gitlab/import.rb
  lib/msf/core/exploit/remote/http/gitlab/rest.rb
  lib/msf/core/exploit/remote/http/gitlab/rest/v4.rb
  lib/msf/core/exploit/remote/http/gitlab/rest/v4/access_tokens.rb
  lib/msf/core/exploit/remote/http/gitlab/rest/v4/groups.rb
  lib/msf/core/exploit/remote/http/gitlab/rest/v4/import.rb
  lib/msf/core/exploit/remote/http/gitlab/rest/v4/version.rb
  lib/msf/core/exploit/remote/http/gitlab/version.rb
  lib/msf/core/exploit/ruby_deserialization.rb
  lib/msf/util/ruby_deserialization.rb
  modules/exploits/multi/http/gitlab_github_import_rce_cve_2022_2992.rb
Labels: module, library, docs

#17645 Fix bootup git warnings on arch
  lib/metasploit/framework/version.rb
Labels: bug, rn-fix

#17594 Add larger DLL templates
  data/templates/src/pe/README.md
  data/templates/src/pe/build_dlls.bat
  data/templates/src/pe/dll/build.bat
  data/templates/src/pe/dll/template.h
  data/templates/src/pe/dll_gdiplus/build.bat
  data/templates/src/pe/dll_gdiplus/build.sh
  data/templates/src/pe/dll_gdiplus/exports.h
  data/templates/src/pe/dll_gdiplus/template.c
  data/templates/src/pe/dll_gdiplus/template.def
  data/templates/src/pe/dll_gdiplus/template.rc
  data/templates/src/pe/dll_mixed_mode/build.bat
  data/templates/template_x64_windows.256kib.dll
  data/templates/template_x64_windows.dll
  data/templates/template_x64_windows_dccw_gdiplus.256kib.dll
  data/templates/template_x64_windows_dccw_gdiplus.dll
  data/templates/template_x64_windows_mixed_mode.256kib.dll
  data/templates/template_x64_windows_mixed_mode.dll
  data/templates/template_x86_windows.256kib.dll
  data/templates/template_x86_windows.dll
  data/templates/template_x86_windows_dccw_gdiplus.256kib.dll
  data/templates/template_x86_windows_dccw_gdiplus.dll
  data/templates/template_x86_windows_mixed_mode.256kib.dll
  data/templates/template_x86_windows_mixed_mode.dll
  lib/msf/util/exe.rb
Labels: library, enhancement, rn-enhancement

#17637 Add module information to docs site
  docs/_includes/header_custom.html
  docs/_includes/js/custom.js
  docs/_plugins/metasploit_stats.rb
  docs/assets/css/main.css
  docs/metasploit-framework.wiki/Modules.md
  docs/navigation.rb
Labels: rn-wiki

#17660 Move temp storage of reg hives to %TEMP%
  modules/auxiliary/gather/windows_secrets_dump.rb
Labels: module, bug, rn-fix

#17663 fixing case insensitive issue for show options #17459
  lib/msf/core/module/has_actions.rb
Labels: library, bug

#17652 Add Exploit For CVE-2023-0297 (pyLoad js2py Execution)
  documentation/modules/exploit/linux/http/pyload_js2py_exec.md
  modules/exploits/linux/http/pyload_js2py_exec.rb
Labels: module, docs, rn-modules

#17640 Module for authenticated Froxlor RCE (CVE-2023-0315)
  documentation/modules/exploit/linux/http/froxlor_log_path_rce.md
  modules/exploits/linux/http/froxlor_log_path_rce.rb
Labels: module, docs

#17691 Fix module spec test failing on local machine
  lib/rex/proto/http/web_socket.rb
Labels: rn-no-release-notes

#17690 Update inspect ticket tests to use the local timezone
  lib/rex/proto/kerberos/credential_cache/krb5_ccache_presenter.rb
  spec/lib/rex/proto/kerberos/credential_cache/krb5_ccache_presenter_spec.rb
  spec/modules/auxiliary/admin/kerberos/inspect_ticket_spec.rb
Labels: library, bug

#17562 Fix incorrect definitions for ldap_search functions in def_wldap32.rb
  lib/msf/core/post/windows/ldap.rb
  lib/rex/post/meterpreter/extensions/stdapi/railgun/def/windows/def_wldap32.rb
  lib/rex/post/meterpreter/extensions/stdapi/railgun/library.rb
  lib/rex/post/meterpreter/extensions/stdapi/railgun/library_function.rb
  lib/rex/post/meterpreter/extensions/stdapi/railgun/multicall.rb
Labels: library, bug, rn-fix

#17672 Disable clamav via unix socket
  documentation/modules/post/linux/manage/disable_clamav.md
  modules/post/linux/manage/disable_clamav.rb
Labels: module, docs

#17687 Additional documentation for HTTPRawHeaders Option
  docs/metasploit-framework.wiki/Metasploit-Guide-HTTP.md
Labels: rn-wiki

#17697 Froxlor 2.0.7 is actually vulnerable too
  documentation/modules/exploit/linux/http/froxlor_log_path_rce.md
  modules/exploits/linux/http/froxlor_log_path_rce.rb
Labels: module, easy, rn-fix

#17695 Remove the LDAP collection prject
  docs/metasploit-framework.wiki/GSoC-2023-Project-Ideas.md
Labels: easy, rn-wiki

#17700 Fix argument validation for the route command
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/net.rb
Labels: library, bug, rn-fix

#17701 Typo in psexec.rb
  lib/msf/core/exploit/remote/smb/client/psexec.rb
Labels: library, rn-no-release-notes

#17696 Update metasploit-payloads gem to 2.0.113
  Gemfile.lock
  LICENSE_GEMS
  metasploit-framework.gemspec
Labels: bug, payload, enhancement

#17680 Improve UX of module explorer on docs.metasploit.com
  docs/_includes/js/custom.js
  docs/_plugins/metasploit_stats.rb
  docs/assets/css/main.css
  docs/metasploit-framework.wiki/Modules.md
Labels: enhancement, rn-wiki

#17698 Fix #17629 #query_ldap issues
  lib/msf/core/post/windows/ldap.rb
  lib/rex/post/meterpreter/extensions/stdapi/railgun/railgun.rb
  modules/post/windows/gather/enum_ad_users.rb
Labels: library, rn-fix

#17699 Add in SCHANNEL support for LDAP
  lib/msf/core/exploit/remote/auth_option.rb
  lib/msf/core/exploit/remote/ldap.rb
  modules/auxiliary/admin/ldap/rbcd.rb
  modules/auxiliary/gather/ldap_esc_vulnerable_cert_finder.rb
  modules/auxiliary/gather/ldap_query.rb
Labels: library, enhancement, rn-enhancement

#17624 Oracle E-Business Suite Exploit module - CVE-2022-21587 (ETR)
  documentation/modules/exploit/linux/http/oracle_ebs_rce_cve_2022_21587.md
  modules/exploits/linux/http/oracle_ebs_rce_cve_2022_21587.rb
Labels: module, docs
