Repository rapid7/metasploit-framework, pull requests merged in 2023-07, with the labels that each got.

#18122 rocketmq version lib
  lib/msf/core/auxiliary/rocketmq.rb
  modules/auxiliary/scanner/misc/rocketmq_version.rb
  spec/lib/msf/core/auxiliary/rocketmq_spec.rb
Labels: library, enhancement

#18166 Handle nil error when creating adapted payloads
  lib/msf/core/payload_set.rb
Labels: rn-fix

#18082 Apache RocketMQ update config RCE (CVE-2023-33246)
  documentation/modules/exploit/multi/http/apache_rocketmq_update_config.md
  modules/exploits/multi/http/apache_rocketmq_update_config.rb
Labels: module, docs, rn-modules

#18144 Tweak capture plugin help
  docs/metasploit-framework.wiki/How-To-Use-The-Capture-Plugin.md
  docs/navigation.rb
  plugins/capture.rb
  spec/plugins/capture_spec.rb
Labels: bug, plugin

#18169 Add centralized Metasploit plugin documentation
  docs/metasploit-framework.wiki/How-To-Use-Plugins.md
  docs/metasploit-framework.wiki/How-To-Use-The-Capture-Plugin.md
  docs/navigation.rb
  lib/msf/ui/console/command_dispatcher/core.rb
  plugins/db_credcollect.rb
  plugins/event_tester.rb
  plugins/ffautoregen.rb
  plugins/libnotify.rb
  plugins/msfd.rb
  plugins/session_notifier.rb
  plugins/session_tagger.rb
  plugins/thread.rb
  plugins/token_adduser.rb
  plugins/token_hunter.rb
  plugins/wiki.rb
Labels: rn-wiki

#18164 WooCommerce Payments auth bypass and priv esc
  data/wordlists/wp-exploitable-plugins.txt
  documentation/modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.md
  modules/auxiliary/scanner/http/wp_woocommerce_payments_add_user.rb
Labels: module, docs

#18178 update reference format for entry in rapid7.com
  modules/exploits/windows/smb/ms08_067_netapi.rb
Labels: easy, rn-no-release-notes

#18170 Add module for SmarterMail Build 6985 - dotNET Deserialization Remote Code Execution (CVE-2019-7214)
  documentation/modules/exploit/windows/http/smartermail_rce.md
  modules/exploits/windows/http/smartermail_rce.rb
Labels: module, docs

#17861 CVE-2023-27253 - pfSense Config Data Remote Command Execution as root
  documentation/modules/exploit/unix/http/pfsense_config_data_exec.md
  modules/exploits/unix/http/pfsense_config_data_exec.rb
Labels: module, docs

#18186 Add syntax highlighting to multiple code snippets
  docs/metasploit-framework.wiki/Committer-Keys.md
  docs/metasploit-framework.wiki/Creating-Metasploit-Framework-LoginScanners.md
  docs/metasploit-framework.wiki/How-To-Use-Plugins.md
  docs/metasploit-framework.wiki/How-to-log-in-Metasploit.md
  docs/metasploit-framework.wiki/How-to-obfuscate-JavaScript-in-Metasploit.md
  docs/metasploit-framework.wiki/How-to-use-Metasploit-JSON-RPC.md
  docs/metasploit-framework.wiki/How-to-use-command-stagers.md
  docs/metasploit-framework.wiki/How-to-use-fetch-payloads.md
  docs/metasploit-framework.wiki/Landing-Pull-Requests.md
  docs/metasploit-framework.wiki/Meterpreter-ExecuteBof-Command.md
  docs/metasploit-framework.wiki/Meterpreter-Reg-Command.md
  docs/metasploit-framework.wiki/Meterpreter-Sleep-Control.md
  docs/metasploit-framework.wiki/Meterpreter-Stageless-Mode.md
  docs/metasploit-framework.wiki/Meterpreter-Timeout-Control.md
  docs/metasploit-framework.wiki/Meterpreter-Transport-Control.md
  docs/metasploit-framework.wiki/Module-Documentation.md
  docs/metasploit-framework.wiki/Nightly-Installers.md
  docs/metasploit-framework.wiki/Pivoting-in-Metasploit.md
  docs/metasploit-framework.wiki/Python-Extension.md
  docs/metasploit-framework.wiki/Remote-Branch-Pruning.md
  docs/metasploit-framework.wiki/Rolling-back-merges.md
  docs/metasploit-framework.wiki/Running-Private-Modules.md
  docs/metasploit-framework.wiki/dev/Setting-Up-a-Metasploit-Development-Environment.md
  docs/metasploit-framework.wiki/git/Git-cheatsheet.md
  docs/metasploit-framework.wiki/git/Using-Git.md
  docs/metasploit-framework.wiki/kerberos/kerberoasting.md
Labels: rn-wiki

#17681 Add datastore option for Jenkins home directory
  documentation/modules/post/multi/gather/jenkins_gather.md
  modules/post/multi/gather/jenkins_gather.rb
Labels: module, docs, enhancement

#18213 Fix evasion windows syscall inject module crash
  lib/metasploit/framework/compiler/mingw.rb
  lib/msf/base/simple/evasion.rb
Labels: bug

#18221 Add wd_mycloud_unauthenticated_cmd_injection module and docs (CVE-2016-10108 and CVE-2018-17153)
  documentation/modules/exploit/linux/http/wd_mycloud_unauthenticated_cmd_injection.md
  modules/exploits/linux/http/wd_mycloud_unauthenticated_cmd_injection.rb
Labels: module, docs, rn-modules
