Repository rapid7/metasploit-framework, pull requests merged in 2023-06, with the labels that each got.

#17430 AWS SSM Sessions
  Gemfile.lock
  documentation/modules/auxiliary/cloud/aws/enum_ssm.md
  lib/msf/base/sessions/aws_ssm_command_shell_bind.rb
  lib/msf/base/sessions/command_shell.rb
  lib/msf/base/sessions/powershell.rb
  lib/msf/core/handler/bind_aws_ssm.rb
  lib/msf/core/post_mixin.rb
  lib/rex/proto/http/web_socket.rb
  lib/rex/proto/http/web_socket/amazon_ssm.rb
  metasploit-framework.gemspec
  modules/auxiliary/cloud/aws/enum_ssm.rb
  modules/payloads/singles/generic/shell_bind_aws_ssm.rb
Labels: module, needs-docs, rn-modules

#18003 Archer c7 traversal
  documentation/modules/auxiliary/scanner/http/archer_c7_traversal.md
  modules/auxiliary/scanner/http/archer_c7_traversal.rb
Labels: module, docs, rn-modules

#17868 Improve check_host return code handling
  modules/auxiliary/scanner/http/ms15_034_http_sys_memory_dump.rb
Labels: module, enhancement, rn-enhancement

#18056 Modify command stagers to not go over 100%
  lib/msf/core/exploit/cmd_stager.rb
Labels: library, bug, rn-fix

#18002 Added cmd useradd payload
  modules/payloads/singles/cmd/unix/adduser.rb
Labels: payload, rn-modules

#18055 Update post/multi/gather/aws_keys to run against linux sessions
  modules/post/multi/gather/aws_keys.rb
Labels: module, bug, easy, rn-fix

#18018 Add in CVE-2023-29084 - Zoho ManageEngine ADManager Plus ChangePasswordAction Authenticated Command Injection
  documentation/modules/exploit/windows/http/manageengine_admanager_plus_cve_2023_29084_auth_cmd_injection.md
  lib/msf/core/post/windows.rb
  modules/encoders/cmd/powershell_base64.rb
  modules/exploits/windows/http/manageengine_admanager_plus_cve_2023_29084_auth_cmd_injection.rb
Labels: module, docs

#18062 Created mixin to retrieve the architecture of the current shell.
  lib/msf/core/post/architecture.rb
  modules/post/multi/manage/shell_to_meterpreter.rb
Labels: library, enhancement, rn-enhancement

#17917 shell_to_meterpreter: Support using bind payloads with PAYLOAD_OVERRIDE
  modules/post/multi/manage/shell_to_meterpreter.rb
Labels: module, bug, rn-fix

#18039 gitlab file read CVE-2023-2825
  documentation/modules/auxiliary/gather/gitlab_authenticated_subgroups_file_read.md
  modules/auxiliary/gather/gitlab_authenticated_subgroups_file_read.rb
Labels: module, docs, rn-modules

#18072 Add CVE-2023-1133 - .NET Deserialization exploit for Delta Electronics InfraSuite Device Master
  documentation/modules/exploit/windows/misc/delta_electronics_infrasuite_deserialization.md
  modules/exploits/windows/misc/delta_electronics_infrasuite_deserialization.rb
Labels: module, docs

#18040 changing payload structure of python's reverse_tcp for fixing windows…
  modules/payloads/singles/cmd/unix/reverse_python_ssl.rb
  modules/payloads/singles/python/shell_bind_tcp.rb
  modules/payloads/singles/python/shell_reverse_sctp.rb
  modules/payloads/singles/python/shell_reverse_tcp.rb
  modules/payloads/singles/python/shell_reverse_tcp_ssl.rb
  modules/payloads/singles/python/shell_reverse_udp.rb
Labels: bug, payload, rn-fix

#18016 CVE-2023-28771 - Zyxel Command Injection
  documentation/modules/exploit/linux/misc/zyxel_ike_decoder_rce_cve_2023_28771.md
  modules/exploits/linux/misc/zyxel_ike_decoder_rce_cve_2023_28771.rb
Labels: module, docs

#18058 Improve code navigation docs and add debugging page
  docs/metasploit-framework.wiki/Navigating-and-Understanding-Metasploits-Codebase.md
  external/vscode/launch.json
Labels: rn-wiki

#18070 TerraMaster unauthicated RCE a.k.a. TerrorMaster 2 [CVE-2021-45837]
  documentation/modules/exploit/linux/http/terramaster_unauth_rce_cve_2021_45837.md
  modules/exploits/linux/http/terramaster_unauth_rce_cve_2021_45837.rb
Labels: module, docs

#17946 CVE-2023-21839 - Oracle Weblogic PreAuth Remote Command Execution via ForeignOpaqueReference IIOP Deserialization
  Gemfile.lock
  data/exploits/CVE-2023-21839/PayloadRuns.class
  data/exploits/CVE-2023-21839/PayloadRuns.java
  documentation/modules/exploit/multi/iiop/cve_2023_21839_weblogic_rce.md
  lib/msf/core/exploit/remote/jndi_injection.rb
  modules/exploits/multi/iiop/cve_2023_21839_weblogic_rce.rb
Labels: module, docs

#18063 TerraMaster unauthicated RCE a.k.a. TerrorMaster 1 [CVE-2020-35665]
  documentation/modules/exploit/linux/http/terramaster_unauth_rce_cve_2020_35665.md
  modules/exploits/linux/http/terramaster_unauth_rce_cve_2020_35665.rb
Labels: module, docs

#17942 Improve AMSI bypass for the `web_delivery` module
  Gemfile.lock
  data/evasion/windows/bypass_powershell_protections.erb.graphml
  lib/msf/core/exploit/powershell.rb
  modules/exploits/multi/script/web_delivery.rb
Labels: module, enhancement, rn-enhancement

#18090 Update the exported keytab table entries to sort by db insert id
  modules/auxiliary/admin/kerberos/keytab.rb
  spec/modules/auxiliary/admin/kerberos/keytab_spec.rb
Labels: rn-fix

#18086 TerraMaster unauthicated RCE a.k.a. TerrorMaster 3 [CVE-2022-24990]
  documentation/modules/exploit/linux/http/terramaster_unauth_rce_cve_2022_24990.md
  modules/exploits/linux/http/terramaster_unauth_rce_cve_2022_24990.rb
Labels: module, docs

#18075 RocketMQ version scanner
  data/rocketmq_versions_list.json
  documentation/modules/auxiliary/scanner/misc/rocketmq_version.md
  modules/auxiliary/scanner/misc/rocketmq_version.rb
Labels: module, docs

#18097 Fix python meterpreter crashing when extracting osx network configuration
  Gemfile.lock
  metasploit-framework.gemspec
Labels: rn-fix

#18098 Fix rex-text crashes when running ruby 3.3
  Gemfile.lock
Labels: rn-fix

#18099 Fix python meterpreter subprocess deadlock and file descriptor leak
  Gemfile.lock
  metasploit-framework.gemspec
Labels: rn-fix

#18101 Fix osx route command when mac addresses are split by dots
  Gemfile.lock
  metasploit-framework.gemspec
Labels: rn-fix

#18102 Fix false negatives on files not existing on windows python meterpreter
  Gemfile.lock
  metasploit-framework.gemspec
Labels: rn-fix

#17781 Improve mingw includes utilizing ```-iquote``` option to simply include headers from any custom directory
  lib/metasploit/framework/compiler/mingw.rb
Labels: library, enhancement

#17670 feat: created module to exploit CVE-2019-16328
  documentation/modules/auxiliary/scanner/http/rpyc_rce.md
  modules/auxiliary/scanner/http/rpyc_rce.py
Labels: module, docs, external modules, rn-modules

#18111 Fix unitialized constant error when meterpreter registry key reads timeout
  lib/msf/core/post/windows/registry.rb
Labels: rn-fix

#18106 Update SessionTLVLogging to no longer truncate useful values
  lib/rex/post/meterpreter/packet.rb
Labels: rn-enhancement

#18105 Fix time command bug when running complex commands
  lib/msf/ui/console/command_dispatcher/developer.rb
Labels: rn-fix

#18107 Extract rspec wait for expect helper
  spec/api/json_rpc_spec.rb
  spec/support/shared/contexts/wait_for_expect.rb
Labels: rn-no-release-notes

#18110 Add namespaced test module logging
  test/lib/module_test.rb
Labels: rn-enhancement

#18054 Fix issue with info command and IP address check
  lib/msf/core/opt_address_routable.rb
  lib/msf/core/payload/adapter/fetch.rb
Labels: bug

#18094 Fix an edge case in .to_win32pe
  lib/msf/util/exe.rb
Labels: library, bug, rn-fix

#18124 Fix broken post test extapi tests
  test/modules/post/test/extapi.rb
Labels: rn-fix

#18126 Add additional logging to post test file
  test/modules/post/test/file.rb
Labels: rn-enhancement

#18127 Add railgun reverse lookup tests for osx and linux
  test/modules/post/test/railgun_reverse_lookups.rb
Labels: rn-enhancement

#17576 Update add_host_tag and delete_host_tag to properly handle tagging multiple hosts and then deleting these tags
  lib/metasploit/framework/data_service/proxy/host_data_proxy.rb
  lib/msf/core/db_manager/host.rb
  lib/msf/ui/console/command_dispatcher/db.rb
Labels: bug

#18118 Update UA strings for June 2023
  lib/rex/user_agent.rb
Labels: rn-enhancement

#18104 Fix issue that falsely caused empty file reads on meterpreter
  lib/msf/core/post/file.rb
Labels: rn-fix

#18065 Updates `jenkins_gather` module to work with newer version of Jenkins
  documentation/modules/post/multi/gather/jenkins_gather.md
  modules/post/multi/gather/jenkins_gather.rb
Labels: rn-fix

#18139 Fix windows python meterpreter getuid intermittent crash
  Gemfile.lock
  metasploit-framework.gemspec
Labels: rn-fix

#17959 rescue login scanner attempts
  docs/metasploit-framework.wiki/Creating-Metasploit-Framework-LoginScanners.md
  lib/metasploit/framework/login_scanner/base.rb
  lib/metasploit/framework/login_scanner/postgres.rb
  lib/metasploit/framework/login_scanner/snmp.rb
Labels: library, enhancement

#18134 Added exploit for CVE-2023-25194
  documentation/modules/exploit/multi/http/apache_druid_cve_2023_25194.md
  modules/exploits/multi/http/apache_druid_cve_2023_25194.rb
Labels: module, docs

#18141 Remove flaky redundant test
  spec/lib/msf/util/java_deserialization_spec.rb
Labels: rn-no-release-notes

#17796 AWS EC2 enum: implement reporting
  modules/auxiliary/cloud/aws/enum_ec2.rb
Labels: module, blocked, enhancement

#18146 Fix windows Meterpreter clipboard manipulation access denied errors
  Gemfile.lock
  metasploit-framework.gemspec
Labels: rn-fix

#18152 Update PHP Meterpreter to correctly show file sizes for large files
  Gemfile.lock
  metasploit-framework.gemspec
Labels: rn-fix
