Repository rapid7/metasploit-framework, pull requests merged in 2023-08, with the labels that each got.

#18209 Fix bypassuac_comhijack module crash
  modules/exploits/windows/local/bypassuac_comhijack.rb
  modules/exploits/windows/local/bypassuac_dotnet_profiler.rb
Labels: bug

#18243 Fix appscan import failure on empty proof
  lib/rex/parser/appscan_document.rb
Labels: rn-fix

#18203 Fix libssh_auth_bypass crash on newer versions of Ruby
  documentation/modules/auxiliary/scanner/ssh/libssh_auth_bypass.md
  modules/auxiliary/scanner/ssh/libssh_auth_bypass.rb
Labels: bug, rn-fix

#18223 Fix broken msfconsole histories when switching between shell sessions
  lib/msf/base/sessions/command_shell.rb
  lib/msf/core/feature_manager.rb
  lib/msf/ui/console/command_dispatcher/developer.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb
  lib/rex/ui/text/shell.rb
  lib/rex/ui/text/shell/history_manager.rb
  spec/lib/rex/ui/text/shell/history_manager_spec.rb
Labels: rn-enhancement

#18211 Add module and documentation for Subrion CMS v4.2.1 RCE
  documentation/modules/exploit/multi/http/subrion_cms_file_upload_rce.md
  modules/exploits/multi/http/subrion_cms_file_upload_rce.rb
Labels: module, docs, rn-modules

#18244 Update payload size warnings to errors on CI
  lib/msf/core/handler/bind_aws_instance_connect.rb
  spec/modules/payloads_spec.rb
  spec/support/shared/contexts/untested_payloads.rb
Labels: rn-enhancement

#18260 Update aws instance connect EC2_ID validation
  lib/msf/core/handler/bind_aws_instance_connect.rb
Labels: rn-fix

#18231 fix for issue #18219, allow index selection for favorites
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: rn-enhancement

#18191 Improve post/linux/gather/checkcontainer
  modules/post/linux/gather/checkcontainer.rb
Labels: enhancement

#18232 metabase setup token rce (cve-2023-38646)
  documentation/modules/exploit/linux/http/metabase_setup_token_rce.md
  modules/exploits/linux/http/metabase_setup_token_rce.rb
Labels: module, docs, rn-modules

#18263 Add RaspAP Unauthenticated Command Injection (CVE-2022-39986) Exploit
  documentation/modules/exploit/unix/http/raspap_rce.md
  modules/exploits/unix/http/raspap_rce.rb
Labels: module, docs

#18288 Revert "Revert "Add Meterpreter sanity tests to CI""
  .github/workflows/acceptance.yml
  .github/workflows/verify.yml
  Gemfile
  Gemfile.lock
  lib/msf/core/post/windows/registry.rb
  lib/msf/core/post/windows/services.rb
  spec/acceptance/README.md
  spec/acceptance/child_process_spec.rb
  spec/acceptance/meterpreter_spec.rb
  spec/acceptance_spec_helper.rb
  spec/allure_config.rb
  spec/spec_helper.rb
  spec/support/acceptance/child_process.rb
  spec/support/acceptance/countdown.rb
  spec/support/acceptance/line_validation.rb
  spec/support/acceptance/meterpreter.rb
  spec/support/acceptance/meterpreter/java.rb
  spec/support/acceptance/meterpreter/mettle.rb
  spec/support/acceptance/meterpreter/php.rb
  spec/support/acceptance/meterpreter/python.rb
  spec/support/acceptance/meterpreter/windows_meterpreter.rb
  spec/support/acceptance/port_allocator.rb
  test/modules/post/test/file.rb
  test/modules/post/test/meterpreter.rb
Labels: rn-enhancement

#18289 Fix a typo in the docs
  documentation/modules/exploit/freebsd/http/citrix_formssso_target_rce.md
Labels: docs, bug, easy

#18226 H2 Web Interface RCE (nocve, its a feature!)
  documentation/modules/exploit/linux/http/h2_webinterface_rce.md
  modules/exploits/linux/http/h2_webinterface_rce.rb
Labels: module, docs

#18280 Add Maltrail Unauthenticated RCE exploit
  documentation/modules/exploit/unix/http/maltrail_rce.md
  modules/exploits/unix/http/maltrail_rce.rb
Labels: module, docs

#18253 Add CVE-2023-34634, Greenshot Fileformat exploit
  LICENSE
  data/exploits/cve-2023-34634/test.png
  documentation/modules/exploit/windows/fileformat/greenshot_deserialize_cve_2023_34634.md
  modules/exploits/windows/fileformat/greenshot_deserialize_cve_2023_34634.rb
Labels: module, docs, rn-modules

#18275 Update java reverse http and https to be dynamic
  modules/payloads/stagers/java/reverse_http.rb
  modules/payloads/stagers/java/reverse_https.rb
  spec/api/json_rpc_spec.rb
  spec/modules/payloads_spec.rb
Labels: bug, rn-fix

#18123 Add exploit for unauth RCE Jorani
  documentation/modules/exploit/multi/php/jorani_path_trav.md
  modules/exploits/multi/php/jorani_path_trav.rb
Labels: module, docs

#18287 Fix a stack trace in forge_ticket when SPN is blank
  modules/auxiliary/admin/kerberos/forge_ticket.rb
Labels: module, bug, easy

#18272 Bug fix for issue 18237 (CVE-2023-26360 against ColdFusion deployed in a Development profile)
  modules/exploits/multi/http/adobe_coldfusion_rce_cve_2023_26360.rb
Labels: bug, rn-fix

#18306 Fix an error in ThriftMessageType
  lib/rex/proto/thrift.rb
Labels: library, bug, easy, rn-fix

#18233 Chamilo unauthenticed RCE [CVE-2023-34960]
  documentation/modules/exploit/linux/http/chamilo_unauth_rce_cve_2023_34960.md
  modules/exploits/linux/http/chamilo_unauth_rce_cve_2023_34960.rb
Labels: module, docs, rn-modules

#18257 apache nifi h2 rce (CVE-2023-34468)
  documentation/modules/exploit/linux/http/apache_nifi_h2_rce.md
  documentation/modules/exploit/multi/http/apache_nifi_processor_rce.md
  lib/msf/core/exploit/remote/http/nifi.rb
  lib/msf/core/exploit/remote/http/nifi/auth.rb
  lib/msf/core/exploit/remote/http/nifi/dbconnectionpool.rb
  lib/msf/core/exploit/remote/http/nifi/processor.rb
  modules/auxiliary/scanner/http/apache_nifi_version.rb
  modules/exploits/linux/http/apache_nifi_h2_rce.rb
  modules/exploits/multi/http/apache_nifi_processor_rce.rb
  spec/lib/msf/core/exploit/http/nifi/auth_spec.rb
  spec/lib/msf/core/exploit/http/nifi/dbconnectionpool_spec.rb
  spec/lib/msf/core/exploit/http/nifi/processor_spec.rb
  spec/lib/msf/core/exploit/http/nifi_spec.rb
Labels: module, library, docs, rn-modules

#18309 Stream LDAP query results
  modules/auxiliary/gather/ldap_query.rb
Labels: module, enhancement, rn-enhancement
