Repository rapid7/metasploit-framework, pull requests merged in 2023-05, with the labels that each got.

#17910 Fixes `couchdb_login`'s login logic
  documentation/modules/auxiliary/scanner/couchdb/couchdb_login.md
  modules/auxiliary/scanner/couchdb/couchdb_login.rb
Labels: bug

#17960 lock msgpack until build resolved
  Gemfile.lock
  metasploit-framework.gemspec
Labels: rn-no-release-notes

#17911 Update setting missing datastore values to a warning instead of an error
  lib/msf/ui/console/command_dispatcher/core.rb
Labels: bug

#17915 Icinga Web 2 Arbitrary File Read (CVE-2022-24716)
  documentation/modules/auxiliary/scanner/http/icinga_static_library_file_directory_traversal.md
  modules/auxiliary/scanner/http/icinga_static_library_file_directory_traversal.rb
Labels: module, docs, rn-modules

#17133 Add manageengine adaudit plus authenticated rce module and docs - CVE-2021-42847
  documentation/modules/exploit/windows/http/manageengine_adaudit_plus_authenticated_rce.md
  lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus.rb
  lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/json_post_data.rb
  lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/login.rb
  lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/status_codes.rb
  lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/target_info.rb
  lib/msf/core/exploit/remote/http/manage_engine_adaudit_plus/uris.rb
  lib/rex/proto/ms_dtyp.rb
  modules/exploits/windows/http/manageengine_adaudit_plus_authenticated_rce.rb
Labels: module, docs, rn-modules

#17968 Fix a bug in ACE processing when searching for ESC vulnerabilities
  modules/auxiliary/gather/ldap_esc_vulnerable_cert_finder.rb
Labels: module, bug, rn-fix

#17881 Zyxel chained RCE using LFI and weak password derivation algorithm
  documentation/modules/exploit/linux/http/zyxel_lfi_unauth_ssh_rce.md
  modules/exploits/linux/http/zyxel_lfi_unauth_ssh_rce.rb
Labels: module, docs, rn-modules

#17964 Pentaho Business Server Auth Bypass and SSTI
  documentation/modules/exploit/multi/http/pentaho_business_server_authbypass_and_ssti.md
  modules/exploits/multi/http/pentaho_business_server_authbypass_and_ssti.rb
Labels: module, docs, rn-modules

#17984 Fix kerberos datastore name typo in winrm docs
  docs/metasploit-framework.wiki/Metasploit-Guide-WinRM.md
Labels: rn-wiki

#17807 Add in documentation on Metasploit's file system
  app/README.md
  config/README.md
  data/README.md
  db/README.md
  docker/README.md
  docs/navigation.rb
  documentation/README.md
  external/README.md
  lib/README.md
  modules/README.md
  plugins/README.md
  script/README.md
  scripts/README.md
  spec/README.md
  test/README.md
  tools/README.md
Labels: rn-enhancement

#17967 Fix ruby 3.1 crashes and resource leaks when garbage collecting meterpreter resources
  lib/msf/core/framework.rb
  lib/rex/post/meterpreter/channel.rb
  lib/rex/post/meterpreter/extensions/stdapi/sys/event_log.rb
  lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb
  lib/rex/post/meterpreter/extensions/stdapi/sys/registry_subsystem/registry_key.rb
  lib/rex/post/meterpreter/extensions/stdapi/sys/registry_subsystem/remote_registry_key.rb
  lib/rex/post/meterpreter/extensions/stdapi/sys/thread.rb
Labels: library, bug, rn-fix

#17990 ibstat_path: Use AutoCheck, add Notes, resolve Rubocop violations
  modules/exploits/aix/local/ibstat_path.rb
Labels: module, code quality

#17979 Add exploit for Ivanti Avalanche file upload - CVE-2023-28128
  documentation/modules/exploit/windows/http/ivanti_avalanche_filestoreconfig_upload.md
  modules/exploits/windows/http/ivanti_avalanche_filestoreconfig_upload.rb
Labels: module, docs, rn-modules

#17991 Add config for Solargraph to aid IDEs
  .gitignore
  .solargraph.yml
Labels: enhancement, rn-enhancement

#17993 Add invscout RPM Privilege Escalation
  documentation/modules/exploit/aix/local/invscout_rpm_priv_esc.md
  modules/exploits/aix/local/invscout_rpm_priv_esc.rb
Labels: module, docs

#18005 Fix crash when running a module through socks 4a proxy
  Gemfile.lock
Labels: rn-fix

#18006 Fix error when msfconsole opens browser links without a display present
  Gemfile.lock
Labels: rn-fix

#17782 Add http wget cmd based fetch payload for linux x64
  docs/metasploit-framework.wiki/How-to-use-fetch-payloads.md
  docs/navigation.rb
  lib/msf/core/exploit/remote/smb/client/psexec.rb
  lib/msf/core/payload/adapter/fetch.rb
  lib/msf/core/payload/adapter/fetch/http.rb
  lib/msf/core/payload/adapter/fetch/https.rb
  lib/msf/core/payload/adapter/fetch/linux_options.rb
  lib/msf/core/payload/adapter/fetch/server/http.rb
  lib/msf/core/payload/adapter/fetch/server/https.rb
  lib/msf/core/payload/adapter/fetch/server/tftp.rb
  lib/msf/core/payload/adapter/fetch/tftp.rb
  lib/msf/core/payload/adapter/fetch/windows_options.rb
  lib/msf/core/payload/windows/x64/reverse_http_x64.rb
  modules/exploits/linux/http/glpi_htmlawed_php_injection.rb
  modules/exploits/multi/ssh/sshexec.rb
  modules/payloads/adapters/cmd/linux/http/x64.rb
  modules/payloads/adapters/cmd/linux/https/x64.rb
  modules/payloads/adapters/cmd/linux/tftp/x64.rb
  modules/payloads/adapters/cmd/windows/http/x64.rb
  modules/payloads/adapters/cmd/windows/https/x64.rb
  modules/payloads/adapters/cmd/windows/tftp/x64.rb
  spec/modules/payloads_spec.rb
Labels: payload, needs-docs

#18010 Fix edgecase crash when running smb_login with Kerberos auth activated
  lib/metasploit/framework/login_scanner/smb.rb
Labels: rn-fix

#17965 Add module for managing AD CS certificate templates (facilitates ESC4)
  data/auxiliary/admin/ldap/ad_cs_cert_template/esc1_template.yaml
  docs/metasploit-framework.wiki/ad-certificates/Attacking-AD-CS-ESC-Vulnerabilities.md
  docs/navigation.rb
  documentation/modules/auxiliary/admin/ldap/ad_cs_cert_template.md
  lib/msf/core/exploit/remote/ldap.rb
  lib/rex/proto/ldap.rb
  lib/rex/proto/ms_crtd.rb
  lib/rex/proto/ms_dtyp.rb
  lib/rex/proto/secauthz/well_known_sids.rb
  modules/auxiliary/admin/ldap/ad_cs_cert_template.rb
  spec/lib/rex/proto/ms_dtyp/ms_dtyp_security_descriptor_spec.rb
Labels: module, library, rn-modules

#18009 Updates the msfdb default prompts for webservice
  msfdb
Labels: rn-fix

#18025 apache nifi version scanner
  documentation/modules/auxiliary/scanner/http/apache_nifi_version.md
  modules/auxiliary/scanner/http/apache_nifi_version.rb
Labels: module, docs

#18004 CVE-2011-0762 VSFTPD DOS attack
  documentation/modules/auxiliary/dos/ftp/vsftpd_232.md
  modules/auxiliary/dos/ftp/vsftpd_232.rb
Labels: module, docs, needs-linting

#18041 Minor fix in vsftpd_232.md docs
  documentation/modules/auxiliary/dos/ftp/vsftpd_232.md
Labels: rn-no-release-notes

#18019 Fixes validation for `to_handler` command for Evasion and Payload modules
  lib/msf/base/simple/exploit.rb
  lib/msf/ui/console/command_dispatcher/evasion.rb
  lib/msf/ui/console/command_dispatcher/payload.rb
Labels: rn-fix

#17899 Dolibarr 16 unauthenticated contact database dump
  documentation/modules/auxiliary/scanner/http/dolibarr_16_contact_dump.md
  modules/auxiliary/scanner/http/dolibarr_16_contact_dump.rb
Labels: module, docs, rn-modules

#18036 Fix incorrect error handling in ibm sametime enumerate users
  modules/auxiliary/gather/ibm_sametime_enumerate_users.rb
Labels: module, bug

#18031 Improve help for "edit" and "log" commands
  lib/msf/ui/console/command_dispatcher/developer.rb
Labels: library, enhancement

#18030 Fix missing return in HTTP CmdStagers
  lib/msf/core/exploit/cmd_stager/http.rb
Labels: bug, rn-fix

#18028 Add Apache NiFi login scanner module
  documentation/modules/auxiliary/scanner/http/apache_nifi_login.md
  modules/auxiliary/scanner/http/apache_nifi_login.rb
Labels: module, docs, rn-modules

#18026 Fix non-deterministic test module load failures
  test/modules/post/test/extapi.rb
  test/modules/post/test/get_env.rb
  test/modules/post/test/meterpreter.rb
  test/modules/post/test/railgun.rb
  test/modules/post/test/railgun_reverse_lookups.rb
  test/modules/post/test/registry.rb
  test/modules/post/test/search.rb
  test/modules/post/test/services.rb
  test/modules/post/test/unix.rb
Labels: module, bug, rn-fix
