Repository rapid7/metasploit-framework, pull requests merged in 2023-09, with the labels that each got.

#18125 Capture Bind request with Simple Authentication
  documentation/modules/auxiliary/server/capture/ldap.md
  modules/auxiliary/server/capture/ldap.rb
Labels: module, rn-modules, GSoC

#18281 Detection module for CVE-2023-21554 - QueueJumper
  documentation/modules/auxiliary/scanner/msmq/cve_2023_21554_queuejumper.md
  modules/auxiliary/scanner/msmq/cve_2023_21554_queuejumper.rb
Labels: module, rn-modules

#18313 SolarView Compact Unauthenticed RCE [CVE-2023-23333]
  documentation/modules/exploit/linux/http/solarview_unauth_rce_cve_2023_23333.md
  modules/exploits/linux/http/solarview_unauth_rce_cve_2023_23333.rb
Labels: module, docs

#18286 roundcube arbitrary file read (CVE-2017-16651)
  documentation/modules/auxiliary/gather/roundcube_auth_file_read.md
  modules/auxiliary/gather/roundcube_auth_file_read.rb
Labels: module, docs

#18190 Improve post/linux/gather/checkvm
  modules/post/linux/gather/checkvm.rb
Labels: enhancement

#18179 Improve post/windows/gather/checkvm
  modules/post/windows/gather/checkvm.rb
Labels: enhancement

#18322 Elasticsearch Memory Disclosure (CVE-2021-22145)
  documentation/modules/auxiliary/scanner/http/elasticsearch_memory_disclosure.md
  modules/auxiliary/scanner/http/elasticsearch_memory_disclosure.rb
Labels: module, docs

#18329 Add LG Simple Editor Unauthenticated RCE (CVE-2023-40498) Exploit
  documentation/modules/exploit/windows/http/lg_simple_editor_rce.md
  modules/exploits/windows/http/lg_simple_editor_rce.rb
Labels: module, docs

#18302 Sonicwall rce CVE-2023-34124
  documentation/modules/exploit/multi/http/sonicwall_shell_injection_cve_2023_34124.md
  modules/exploits/multi/http/sonicwall_shell_injection_cve_2023_34124.rb
Labels: module, docs, rn-modules

#18316 Kibana Timelion Prototype Pollution RCE (CVE-2019-7609)
  documentation/modules/exploit/linux/http/kibana_timelion_prototype_pollution_rce.md
  modules/exploits/linux/http/kibana_timelion_prototype_pollution_rce.rb
Labels: module, docs

#18350 Add opentsdb_key_cmd_injection exploit module and docs
  documentation/modules/exploit/linux/http/opentsdb_key_cmd_injection.md
  modules/exploits/linux/http/opentsdb_key_cmd_injection.rb
Labels: needs-docs

#18290 Prometheus API & Prometheus Node Exporter Interrogator
  documentation/modules/auxiliary/gather/prometheus_api_gather.md
  documentation/modules/auxiliary/gather/prometheus_node_exporter_gather.md
  lib/msf/core/auxiliary/prometheus.rb
  modules/auxiliary/gather/prometheus_api_gather.rb
  modules/auxiliary/gather/prometheus_node_exporter_gather.rb
  spec/lib/msf/core/auxiliary/prometheus_spec.rb
Labels: module, library, docs, tests

#18273 Add VMware vRealize Log Insight unauthenticated RCE exploit
  documentation/modules/exploit/linux/http/vmware_vrli_rce.md
  modules/exploits/linux/http/vmware_vrli_rce.rb
Labels: module, docs

#18354 Show the tip while MSF is loading
  lib/metasploit/framework/command/console.rb
  lib/msf/ui/console/command_dispatcher/core.rb
Labels: enhancement, rn-enhancement

#18349 Add Meterpreter compatibility matrix generation
  .github/workflows/acceptance.yml
  scripts/resource/meterpreter_compatibility.rc
  spec/acceptance/README.md
  spec/acceptance/meterpreter_spec.rb
  spec/tools/dev/report_generation/support_matrix/generate_spec.rb
  tools/dev/report_generation/support_matrix/generate.rb
  tools/dev/report_generation/support_matrix/template.erb
Labels: rn-enhancement

#17970 Fix #17969 Assign empty hash to variable status
  plugins/nessus.rb
Labels: bug, plugin

#18343 Update rex-socket gem to 0.1.53
  Gemfile.lock
  LICENSE_GEMS
Labels: rn-no-release-notes

#18180 Apache Supserset Priv Esc (CVE-2023-27524) and Flask unsign Library
  LICENSE
  data/wordlists/flask_secret_keys.txt
  data/wordlists/superset_secret_keys.txt
  documentation/modules/auxiliary/gather/apache_superset_cookie_sig_priv_esc.md
  documentation/modules/auxiliary/gather/python_flask_cookie_signer.md
  lib/msf/core/exploit/remote/http/flask_unsign.rb
  modules/auxiliary/gather/apache_superset_cookie_sig_priv_esc.rb
  modules/auxiliary/gather/python_flask_cookie_signer.rb
  spec/lib/msf/core/exploit/remote/http/flask_unsign/session_spec.rb
Labels: module, library, docs

#18330 Ivanti Sentry MICSLogService Auth Bypass resulting in RCE (CVE-2023-38035)
  documentation/modules/exploit/linux/http/ivanti_sentry_misc_log_service.md
  modules/exploits/linux/http/ivanti_sentry_misc_log_service.rb
Labels: module, docs, rn-modules

#18250 CVE-2023-28252: Windows CLFS Driver Privilege Escalation
  data/exploits/CVE-2023-28252/CVE-2023-28252.x64.dll
  documentation/modules/exploit/windows/local/cve_2023_28252_clfs_driver.md
  external/source/exploits/CVE-2023-28252/CVE-2023-28252.sln
  external/source/exploits/CVE-2023-28252/CVE-2023-28252/CVE-2023-28252.vcxproj
  external/source/exploits/CVE-2023-28252/CVE-2023-28252/clfs_eop.cpp
  external/source/exploits/CVE-2023-28252/CVE-2023-28252/clfs_eop.h
  external/source/exploits/CVE-2023-28252/CVE-2023-28252/crc32.h
  external/source/exploits/CVE-2023-28252/CVE-2023-28252/dllmain.cpp
  external/source/exploits/CVE-2023-28252/CVE-2023-28252/exploit.cpp
  external/source/exploits/CVE-2023-28252/CVE-2023-28252/exploit.h
  external/source/exploits/CVE-2023-28252/CVE-2023-28252/ntos.h
  external/source/exploits/CVE-2023-28252/CVE-2023-28252/ntoskrnl.lib
  modules/exploits/windows/local/cve_2023_28252_clfs_driver.rb
Labels: module, docs

#18361 Adds new search keywords to msfconsole
  lib/msf/core/modules/metadata/search.rb
  lib/msf/ui/console/command_dispatcher/modules.rb
  spec/lib/msf/core/modules/metadata/search_spec.rb
Labels: enhancement

#18369 Fix opt address local crash when ipaddr is nil
  lib/msf/core/opt_address_local.rb
  spec/lib/msf/core/opt_address_local_spec.rb
Labels: rn-fix

#18370 Fix msfrpc hanging when updating saved command history
  lib/metasploit/framework/spec/threads/suite.rb
  lib/msf/base/sessions/command_shell.rb
  lib/msf/core/framework.rb
  lib/msf/ui/console/command_dispatcher/developer.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb
  lib/rex/ui/text/shell.rb
  lib/rex/ui/text/shell/history_manager.rb
Labels: rn-fix

#18321 Add Ivanti Avalanche MDM Buffer Overflow Exploit (CVE-2023-32560)
  documentation/modules/exploit/windows/misc/ivanti_avalanche_mdm_bof.md
  modules/exploits/windows/misc/ivanti_avalanche_mdm_bof.rb
Labels: module, docs, rn-modules

#18378 Remove left behind debug logging from prometheus exporter
  lib/msf/core/auxiliary/prometheus.rb
Labels: rn-fix

#18283 Apache Airflow 1.10.10 - Example DAG Remote Code Execution (CVE-2020-11978 + CVE-2020-13927)
  documentation/modules/exploit/linux/http/apache_airflow_dag_rce.md
  modules/exploits/linux/http/apache_airflow_dag_rce.rb
Labels: module, docs

#18333 Lexmark Device Embedded Web Server RCE (CVE-2023-26068)
  documentation/modules/exploit/linux/http/lexmark_faxtrace_settings.md
  modules/exploits/linux/http/lexmark_faxtrace_settings.rb
  modules/payloads/singles/cmd/unix/reverse_socat_tcp.rb
  spec/modules/payloads_spec.rb
Labels: module, docs, rn-modules

#18365 TOTOLINK X5000R Wireless GigaBit Router Unauthenticed RCE [CVE-2023-30013]
  documentation/modules/exploit/linux/http/totolink_unauth_rce_cve_2023_30013.md
  modules/exploits/linux/http/totolink_unauth_rce_cve_2023_30013.rb
Labels: module, docs, rn-modules

#18408 JetBrains TeamCity CVE-2023-42793
  documentation/modules/exploit/multi/http/jetbrains_teamcity_rce_cve_2023_42793.md
  modules/exploits/multi/http/jetbrains_teamcity_rce_cve_2023_42793.rb
Labels: module, docs, rn-modules

#18389 Juniper Junos OS PHPRC Manipulation RCE (CVE-2023-36845)
  documentation/modules/exploit/freebsd/http/junos_phprc_auto_prepend_file.md
  modules/exploits/freebsd/http/junos_phprc_auto_prepend_file.rb
Labels: module, docs, rn-modules
