Repository rapid7/metasploit-framework, pull requests merged in 2023-10, with the labels that each got.

#18197 Ldap login scanner module
  lib/metasploit/framework/credential_collection.rb
  lib/metasploit/framework/ldap/client.rb
  lib/metasploit/framework/login_scanner/ldap.rb
  lib/msf/core/auxiliary/auth_brute.rb
  lib/msf/core/exploit/remote/ldap.rb
  modules/auxiliary/scanner/ldap/ldap_login.rb
  modules/auxiliary/scanner/smb/smb_login.rb
  spec/lib/metasploit/framework/login_scanner/ldap_spec.rb
  spec/lib/msf/core/exploit/remote/ldap_spec.rb
Labels: module

#18347 Update check method docs
  docs/metasploit-framework.wiki/How-to-write-a-check-method.md
Labels: rn-wiki

#18414 Exploit module for CVE-2023-40044 (WS_FTP unauthenticated RCE)
  documentation/modules/exploit/windows/http/ws_ftp_rce_cve_2023_40044.md
  modules/exploits/windows/http/ws_ftp_rce_cve_2023_40044.rb
Labels: module, docs, hotness, rn-modules

#18412 Add a couple of tips
  lib/msf/ui/tip.rb
Labels: easy

#17919 Post::Windows::Service: Support start/stop service on shell sessions
  lib/msf/core/post/windows/services.rb
Labels: library, enhancement

#18425 Add history support to nasm and metasm shells
  lib/rex/ui/text/shell.rb
  lib/rex/ui/text/shell/history_manager.rb
  tools/exploit/metasm_shell.rb
  tools/exploit/nasm_shell.rb
Labels: rn-fix

#18394 Add documentation for auxiliary/scanner/http/http_traversal module
  documentation/modules/auxiliary/scanner/http/http_traversal.md
Labels: rn-enhancement

#18171 Enable using modules when deferred loading is turned on
  lib/metasploit/framework/parsed_options/base.rb
  lib/msf/base/simple/framework.rb
  lib/msf/base/simple/framework/module_paths.rb
  lib/msf/base/simple/statistics.rb
  lib/msf/core/feature_manager.rb
  lib/msf/core/module_manager/cache.rb
  lib/msf/core/module_set.rb
  lib/msf/core/modules/metadata/cache.rb
  lib/msf/core/modules/metadata/stats.rb
  lib/msf/core/payload_set.rb
  lib/msf/ui/console/command_dispatcher/modules.rb
  lib/msf/ui/console/driver.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb
Labels: rn-enhancement

#18417 Kibana < 7.6.3 Upgrade Assistant Telemetry RCE (No-CVE)
  documentation/modules/exploit/linux/http/kibana_upgrade_assistant_telemetry_rce.md
  modules/exploits/linux/http/kibana_upgrade_assistant_telemetry_rce.rb
Labels: module, docs

#18435 wiki spelling fixes
  docs/metasploit-framework.wiki/Bundled-Modules-Proposal.md
  docs/metasploit-framework.wiki/GSoC-2020-Project-Ideas.md
  docs/metasploit-framework.wiki/GSoC-2021-Project-Ideas.md
  docs/metasploit-framework.wiki/GSoC-2022-Project-Ideas.md
  docs/metasploit-framework.wiki/Hashes-and-Password-Cracking.md
  docs/metasploit-framework.wiki/How-to-Send-an-HTTP-Request-Using-HttpClient.md
  docs/metasploit-framework.wiki/How-to-use-Metasploit-Framework-Compiler-Windows-to-compile-C-code.md
  docs/metasploit-framework.wiki/How-to-use-command-stagers.md
  docs/metasploit-framework.wiki/How-to-use-fetch-payloads.md
  docs/metasploit-framework.wiki/How-to-use-the-Msf-Exploit-Remote-Tcp-mixin.md
  docs/metasploit-framework.wiki/How-to-write-a-HTTP-LoginScanner-Module.md
  docs/metasploit-framework.wiki/How-to-write-a-browser-exploit-using-HttpServer.md
  docs/metasploit-framework.wiki/How-to-write-a-check-method.md
  docs/metasploit-framework.wiki/MSF6-Feature-Proposals.md
  docs/metasploit-framework.wiki/Metasploit-Guide-LDAP.md
  docs/metasploit-framework.wiki/Metasploit-Guide-Post-Gather-Modules.md
  docs/metasploit-framework.wiki/Metasploit-Guide-SMB.md
  docs/metasploit-framework.wiki/Meterpreter-ExecuteBof-Command.md
  docs/metasploit-framework.wiki/Meterpreter-Reliable-Network-Communication.md
  docs/metasploit-framework.wiki/Meterpreter-Sleep-Control.md
  docs/metasploit-framework.wiki/Meterpreter-Stageless-Mode.md
  docs/metasploit-framework.wiki/Meterpreter-Timeout-Control.md
  docs/metasploit-framework.wiki/Meterpreter-Transport-Control.md
  docs/metasploit-framework.wiki/Meterpreter-Wishlist.md
  docs/metasploit-framework.wiki/Oracle-Usage.md
  docs/metasploit-framework.wiki/Pivoting-in-Metasploit.md
  docs/metasploit-framework.wiki/Python-Extension.md
  docs/metasploit-framework.wiki/The-ins-and-outs-of-HTTP-and-HTTPS-communications-in-Meterpreter-and-Metasploit-Stagers.md
  docs/metasploit-framework.wiki/Unstable-Modules.md
  docs/metasploit-framework.wiki/kerberos/service_authentication.md
Labels: docs, rn-wiki

#18383 Makes improvements to enum_computers module
  modules/post/windows/gather/enum_computers.rb
Labels: enhancement, rn-enhancement

#18351 Apache Superset RCE (CVE-2023-37941)
  docs/metasploit-framework.wiki/Hashes-and-Password-Cracking.md
  documentation/modules/auxiliary/gather/apache_superset_cookie_sig_priv_esc.md
  documentation/modules/exploit/linux/http/apache_superset_cookie_sig_rce.md
  lib/metasploit/framework/hashes.rb
  lib/metasploit/framework/password_crackers/cracker.rb
  lib/metasploit/framework/password_crackers/hashcat/formatter.rb
  lib/msf/util/python_deserialization.rb
  modules/auxiliary/analyze/crack_webapps.rb
  modules/auxiliary/gather/apache_superset_cookie_sig_priv_esc.rb
  modules/exploits/linux/http/apache_superset_cookie_sig_rce.rb
  spec/lib/metasploit/framework/hashes/identify_spec.rb
Labels: module, docs

#18443 Fix reverse ssh handler warnings on windows bootup
  lib/msf/core/handler/reverse_ssh.rb
Labels: rn-fix

#18438 Improve UX for database management prompts
  msfdb
Labels: enhancement, rn-enhancement

#18449 Update mysql authbypass hashdump module to correctly close sockets
  modules/auxiliary/scanner/mysql/mysql_authbypass_hashdump.rb
Labels: rn-fix

#18442 Improve stability of msfdb initialization on windows environments
  lib/msfdb_helpers/pg_ctl.rb
Labels: rn-fix

#17689 adding a new column cracked password in creds command to show cracked…
  lib/msf/ui/console/command_dispatcher/creds.rb
  spec/lib/msf/ui/console/command_dispatcher/creds_spec.rb
Labels: library, enhancement

#18452 Update Writing Module Docs to reference msftidy_docs.rb
  docs/metasploit-framework.wiki/Writing-Module-Documentation.md
Labels: docs, easy

#18461 CVE-2023-22515 - Atlassian Confluence unauthenticated RCE exploit module
  documentation/modules/exploit/multi/http/atlassian_confluence_rce_cve_2023_22515.md
  modules/exploits/multi/http/atlassian_confluence_rce_cve_2023_22515.rb
Labels: module, docs, rn-modules

#18421 Save Kerberos tickets in the MSF cache upon a successful login
  documentation/modules/auxiliary/scanner/kerberos/kerberos_login.md
  lib/msf/core/exploit/remote/kerberos/auth_brute.rb
Labels: enhancement, rn-enhancement

#18400 Kerberos ticket_search fix passing in a workspace
  lib/msf/core/exploit/remote/kerberos/ticket/storage/base.rb
Labels: rn-fix

#18373 Add DB Stats Command to Console
  lib/msf/ui/console/command_dispatcher/db.rb
  lib/msf/ui/console/command_dispatcher/db/klist.rb
Labels: msfconsole, enhancement, rn-enhancement

#18470 Adds wiki guide for session searching
  docs/metasploit-framework.wiki/Managing-Sessions.md
  docs/navigation.rb
  lib/msf/ui/console/command_dispatcher/core.rb
  spec/lib/msf/ui/console/command_dispatcher/core_spec.rb
Labels: docs, enhancement

#18460 VMWare Aria Operations for Networks (vRealize Network Insight) Static SSH key RCE
  data/exploits/CVE-2023-34039/id_rsa_vnera_keypair_6.0.0_platform
  data/exploits/CVE-2023-34039/id_rsa_vnera_keypair_6.0.0_proxy
  data/exploits/CVE-2023-34039/id_rsa_vnera_keypair_6.1.0_platform
  data/exploits/CVE-2023-34039/id_rsa_vnera_keypair_6.1.0_proxy
  data/exploits/CVE-2023-34039/id_rsa_vnera_keypair_6.10.0_collector
  data/exploits/CVE-2023-34039/id_rsa_vnera_keypair_6.10.0_platform
  data/exploits/CVE-2023-34039/id_rsa_vnera_keypair_6.2.0_collector
  data/exploits/CVE-2023-34039/id_rsa_vnera_keypair_6.2.0_platform
  data/exploits/CVE-2023-34039/id_rsa_vnera_keypair_6.3.0_collector
  data/exploits/CVE-2023-34039/id_rsa_vnera_keypair_6.3.0_platform
  data/exploits/CVE-2023-34039/id_rsa_vnera_keypair_6.4.0_collector
  data/exploits/CVE-2023-34039/id_rsa_vnera_keypair_6.4.0_platform
  data/exploits/CVE-2023-34039/id_rsa_vnera_keypair_6.5.0_collector
  data/exploits/CVE-2023-34039/id_rsa_vnera_keypair_6.5.0_platform
  data/exploits/CVE-2023-34039/id_rsa_vnera_keypair_6.6.0_collector
  data/exploits/CVE-2023-34039/id_rsa_vnera_keypair_6.6.0_platform
  data/exploits/CVE-2023-34039/id_rsa_vnera_keypair_6.7.0_collector
  data/exploits/CVE-2023-34039/id_rsa_vnera_keypair_6.7.0_platform
  data/exploits/CVE-2023-34039/id_rsa_vnera_keypair_6.8.0_collector
  data/exploits/CVE-2023-34039/id_rsa_vnera_keypair_6.8.0_platform
  data/exploits/CVE-2023-34039/id_rsa_vnera_keypair_6.9.0_collector
  data/exploits/CVE-2023-34039/id_rsa_vnera_keypair_6.9.0_platform
  documentation/modules/exploit/linux/ssh/vmware_vrni_known_privkey.md
  modules/exploits/linux/ssh/vmware_vrni_known_privkey.rb
Labels: module, docs, rn-modules

#18403 Fix FileDropper to properly clone string variables before storing them
  lib/msf/core/exploit/file_dropper.rb
Labels: library, bug

#18466 Replace grep with getent in entrypoint.sh
  docker/entrypoint.sh
Labels: enhancement

#18299 extend error message for timeouts to include more detail to user
  lib/msf/ui/console/command_dispatcher/core.rb
  lib/rex/post/meterpreter/ui/console.rb
  lib/rex/ui/interactive.rb
Labels: enhancement

#18348 Splunk account take over (CVE-2023-32707) leading to RCE
  documentation/modules/exploit/multi/http/splunk_privilege_escalation_cve_2023_32707.md
  modules/exploits/multi/http/splunk_privilege_escalation_cve_2023_32707.rb
Labels: module, rn-modules

#18492 Add module for Citrix Bleed (CVE-2023-4966)
  documentation/modules/auxiliary/scanner/http/citrix_bleed_cve_2023_4966.md
  modules/auxiliary/scanner/http/citrix_bleed_cve_2023_4966.rb
Labels: module, docs, rn-modules

#18454 Appletv Login and Axis Login Documentation Added.
  documentation/modules/auxiliary/scanner/http/appletv_login.md
  documentation/modules/auxiliary/scanner/http/axis_login.md
Labels: docs
