Repository rapid7/metasploit-framework, pull requests merged in 2024-11, with the labels that each got.

#19518 Add support for RISC-V 32-bit / 64-bit Little Endian payloads
  data/templates/src/elf/dll/elf_dll_riscv32le_template.s
  data/templates/src/elf/dll/elf_dll_riscv64le_template.s
  data/templates/src/elf/exe/elf_riscv32le_template.s
  data/templates/src/elf/exe/elf_riscv64le_template.s
  data/templates/template_riscv32le_linux.bin
  data/templates/template_riscv32le_linux_dll.bin
  data/templates/template_riscv64le_linux.bin
  data/templates/template_riscv64le_linux_dll.bin
  lib/msf/util/exe.rb
  modules/nops/riscv32le/simple.rb
  modules/nops/riscv64le/simple.rb
  modules/payloads/singles/linux/riscv32le/exec.rb
  modules/payloads/singles/linux/riscv32le/reboot.rb
  modules/payloads/singles/linux/riscv64le/exec.rb
  modules/payloads/singles/linux/riscv64le/reboot.rb
  spec/modules/payloads_spec.rb
Labels: payload, rn-modules

#19573 Update to Ruby 3.2
  .github/workflows/verify.yml
  .ruby-version
  Dockerfile
  docs/.ruby-version
  docs/metasploit-framework.wiki/dev/Setting-Up-a-Metasploit-Development-Environment.md
Labels: rn-enhancement

#19404 SMB to NTLM HTTP Relay with ESC8 module
  data/capture_config.yaml
  docs/metasploit-framework.wiki/ad-certificates/Attacking-AD-CS-ESC-Vulnerabilities.md
  docs/metasploit-framework.wiki/ad-certificates/overview.md
  documentation/modules/auxiliary/gather/ldap_esc_vulnerable_cert_finder.md
  documentation/modules/auxiliary/server/relay/esc8.md
  lib/msf/core/exploit/remote/http_client.rb
  lib/msf/core/exploit/remote/smb/log_adapter.rb
  lib/msf/core/exploit/remote/smb/relay/ntlm/server.rb
  lib/msf/core/exploit/remote/smb/relay/ntlm/server_client.rb
  lib/msf/core/exploit/remote/smb/relay/ntlm/target.rb
  lib/msf/core/exploit/remote/smb/relay/ntlm/target/http/client.rb
  lib/msf/core/exploit/remote/smb/relay/ntlm/target/smb/client.rb
  lib/msf/core/exploit/remote/smb/relay/target_list.rb
  lib/msf/core/exploit/remote/smb/relay_server.rb
  lib/msf/core/exploit/remote/smb/server/hash_capture.rb
  lib/rex/proto/http/client.rb
  lib/rex/proto/smb/server.rb
  modules/auxiliary/server/relay/esc8.rb
  modules/exploits/windows/smb/smb_relay.rb
  spec/lib/msf/exploit/remote/smb/relay/target_list_spec.rb
Labels: needs-docs, rn-modules

#19620 Fixed spelling errors in command usage
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/ui.rb
Labels: easy, rn-no-release-notes

#19610 Updates report summary mixin with an additional fallback when finding creds
  lib/msf/core/auxiliary/report_summary.rb
Labels: rn-fix

#19369 Update README.md
  README.md
Labels: docs, easy, rn-documentation

#19623 Fix Kerberos cache storage exception
  lib/msf/core/exploit/remote/kerberos/ticket/storage/read_mixin.rb
Labels: library, bug, easy, rn-fix

#19640 Pyload RCE (CVE-2024-39205) with js2py sandbox escape (CVE-2024-28397)
  Gemfile.lock
  documentation/modules/exploit/linux/http/pyload_js2py_cve_2024_39205.md
  modules/exploits/linux/http/pyload_js2py_cve_2024_39205.rb
Labels: module, docs

#19643 Dcsync individual
  Gemfile.lock
  documentation/modules/auxiliary/gather/windows_secrets_dump.md
  modules/auxiliary/gather/windows_secrets_dump.rb
Labels: module, enhancement, rn-enhancement

#19658 Fix `auxiliary/admin/kerberos/get_ticket` issue on Windows
  modules/auxiliary/admin/kerberos/get_ticket.rb
Labels: bug

#19624 Fix a crash with the `admin/dcerpc/icpr_cert` module and OpenSSL 3.4.0
  documentation/modules/auxiliary/server/relay/esc8.md
  lib/msf/core/exploit/remote/ms_icpr.rb
  lib/msf/core/exploit/remote/smb/relay_server.rb
  lib/rex/proto/x509/request.rb
  modules/auxiliary/server/relay/esc8.rb
  spec/lib/msf/core/exploit/remote/ms_icpr_spec.rb
  spec/modules/auxiliary/admin/dcerpc/icpr_cert_spec.rb
Labels: bug

#19659 Fix IRB deadlock recursive locking on Ctrl+C
  lib/rex/ui/text/irb_shell.rb
Labels: rn-no-release-notes

#19593 Add exploit for CVE-2023-28324 (Unauthenticated RCE in Ivanti EPM)
  documentation/modules/exploit/windows/misc/ivanti_agent_portal_cmdexec.md
  lib/msf/util/dot_net_deserialization/enums.rb
  lib/msf/util/dot_net_deserialization/types.rb
  lib/msf/util/dot_net_deserialization/types/common_structures.rb
  lib/msf/util/dot_net_deserialization/types/general.rb
  lib/msf/util/dot_net_deserialization/types/record_values.rb
  lib/rex/proto/ms_nrtp/client.rb
  lib/rex/proto/ms_nrtp/enums.rb
  lib/rex/proto/ms_nrtp/ms_nrtp_counted_string.rb
  lib/rex/proto/ms_nrtp/ms_nrtp_header.rb
  lib/rex/proto/ms_nrtp/ms_nrtp_message.rb
  modules/exploits/windows/misc/ivanti_agent_portal_cmdexec.rb
Labels: module, docs

#19584 Add module: Judge0 sandbox escape CVE-2024-28185, CVE-2024-28189
  documentation/modules/exploit/linux/http/judge0_sandbox_escape_cve_2024_28189.md
  modules/exploits/linux/http/judge0_sandbox_escape_cve_2024_28189.rb
Labels: module, docs, rn-modules

#19531 ProjectSend r1335 - r1605 RCE module
  documentation/modules/exploit/linux/http/projectsend_unauth_rce.md
  modules/exploits/linux/http/projectsend_unauth_rce.rb
Labels: module, docs

#19672 Added mwalas-r7 to the mail map
  .mailmap
Labels: rn-no-release-notes

#19630 Exploit module for IPP attributes remote code execution - OpenPrinting CUPS
  documentation/modules/exploit/multi/misc/cups_ipp_remote_code_execution.md
  lib/rex/proto/dns/server.rb
  lib/rex/proto/mdns/server.rb
  modules/exploits/multi/misc/cups_ipp_remote_code_execution.rb
Labels: module, docs

#19651 Give likely Windows versions for SMB v2-3
  lib/msf/core/windows_version.rb
  modules/auxiliary/scanner/smb/smb_version.rb
  spec/lib/msf/core/windows_version_spec.rb
Labels: module, enhancement, rn-enhancement

#19582 Acronis Cyber Backup/Protect Info Disclosure [CVE-2022-30995]
  documentation/modules/auxiliary/gather/acronis_cyber_protect_machine_info_disclosure.md
  lib/msf/core/exploit/remote/http/acronis_cyber.rb
  modules/auxiliary/gather/acronis_cyber_protect_machine_info_disclosure.rb
Labels: module, docs, rn-modules

#19583 Acronis Cyber Backup/Protect RCE [CVE-2022-3405]
  documentation/modules/exploit/multi/acronis_cyber_protect_unauth_rce_cve_2022_3405.md
  modules/exploits/multi/acronis_cyber_protect_unauth_rce_cve_2022_3405.rb
Labels: module, docs

#19596 New Exploit: Wordpress Plugin Post SMTP Account Takeover
  data/wordlists/wp-exploitable-plugins.txt
  documentation/modules/auxiliary/admin/http/wp_post_smtp_acct_takeover.md
  lib/msf/core/exploit/remote/http/wordpress/users.rb
  modules/auxiliary/admin/http/wp_post_smtp_acct_takeover.rb
Labels: module, docs, rn-modules

#19622 Update Windows Installation instruction in Setting-Up-a-Metasploit-Development-Environment.md
  docs/metasploit-framework.wiki/dev/Setting-Up-a-Metasploit-Development-Environment.md
Labels: rn-documentation
