Repository rapid7/metasploit-framework, pull requests merged in 2024-06, with the labels that each got.

#19208 Add exploit module for CVE-2024-5084: WordPress Hash Form Plugin RCE
  data/wordlists/wp-exploitable-plugins.txt
  data/wordlists/wp-plugins.txt
  documentation/modules/exploit/multi/http/wp_hash_form_rce.md
  modules/exploits/multi/http/wp_hash_form_rce.rb
Labels: module, docs, rn-modules

#19227 Moodle::Login.moodle_login: fix login success verification regex
  lib/msf/core/exploit/remote/http/moodle/login.rb
Labels: library, bug

#19199 Improves UX for scanner/login modules
  lib/msf/core/auxiliary/report_summary.rb
  lib/msf/core/feature_manager.rb
  modules/auxiliary/cloud/aws/enum_ssm.rb
  modules/auxiliary/scanner/ldap/ldap_login.rb
  modules/auxiliary/scanner/mssql/mssql_login.rb
  modules/auxiliary/scanner/mysql/mysql_login.rb
  modules/auxiliary/scanner/postgres/postgres_login.rb
  modules/auxiliary/scanner/rservices/rexec_login.rb
  modules/auxiliary/scanner/rservices/rlogin_login.rb
  modules/auxiliary/scanner/rservices/rsh_login.rb
  modules/auxiliary/scanner/smb/smb_login.rb
  modules/auxiliary/scanner/ssh/eaton_xpert_backdoor.rb
  modules/auxiliary/scanner/ssh/fortinet_backdoor.rb
  modules/auxiliary/scanner/ssh/libssh_auth_bypass.rb
  modules/auxiliary/scanner/ssh/ssh_login.rb
  modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb
  modules/auxiliary/scanner/telnet/brocade_enable_login.rb
  modules/auxiliary/scanner/telnet/telnet_login.rb
  modules/auxiliary/scanner/winrm/winrm_login.rb
Labels: enhancement, rn-enhancement

#19235 Fixes an issue where zip paths were not being created correctly for Java payloads
  lib/msf/core/payload/java.rb
Labels: rn-fix

#19245 dledda-mailmap
  .mailmap
Labels: easy, rn-no-release-notes

#19248 remove duplicated rescue
  lib/msf/core/handler/reverse_http.rb
Labels: rn-fix

#19246 Dry BUNDLER_WITHOUT config
  .github/workflows/acceptance.yml
  .github/workflows/labels.yml
  .github/workflows/ldap_acceptance.yml
  .github/workflows/lint.yml
  .github/workflows/mssql_acceptance.yml
  .github/workflows/mysql_acceptance.yml
  .github/workflows/postgres_acceptance.yml
  .github/workflows/smb_acceptance.yml
  .github/workflows/verify.yml
Labels: rn-no-release-notes

#18998 VSCode exploit for ipynb integration (CVE-2022-41034)
  documentation/modules/exploit/multi/misc/vscode_ipynb_remote_dev_exec.md
  modules/exploits/multi/misc/vscode_ipynb_remote_dev_exec.rb
Labels: module, docs

#19191 Support Ruby 3.4.0-preview1
  .github/workflows/verify.yml
  Gemfile.lock
  metasploit-framework.gemspec
  modules/auxiliary/crawler/msfcrawler.rb
Labels: rn-enhancement

#19251 Reintroduce windows acceptance tests
  .github/workflows/acceptance.yml
Labels: rn-no-release-notes

#19239 Zoomeye
  modules/auxiliary/gather/zoomeye_search.rb
Labels: rn-enhancement

#19240 Rejetto HTTP File Server (HFS) 2.x - Unauthenticated RCE exploit module (CVE-2024-23692)
  documentation/modules/exploit/windows/http/rejetto_hfs_rce_cve_2024_23692.md
  modules/exploits/windows/http/rejetto_hfs_rce_cve_2024_23692.rb
Labels: module, docs, rn-modules

#19242 Add exploit for CVE-2024-4358 (Telerik Report Server Auth Bypass)
  documentation/modules/auxiliary/scanner/http/telerik_report_server_auth_bypass.md
  modules/auxiliary/scanner/http/telerik_report_server_auth_bypass.rb
Labels: module, docs, rn-modules

#19223 wp_ajax_load_more_file_upload.rb : Updated original author
  modules/exploits/unix/webapp/wp_ajax_load_more_file_upload.rb
Labels: easy, rn-no-release-notes

#19225 Add android link to issues template
  .github/ISSUE_TEMPLATE/config.yml
Labels: docs, easy, rn-enhancement

#19243 Add exploit for CVE-2024-1800 (Telerik Report Deserialization RCE)
  documentation/modules/exploit/windows/http/telerik_report_server_deserialization.md
  modules/exploits/windows/http/telerik_report_server_deserialization.rb
Labels: module, docs, rn-modules

#19196 Cacti import package RCE (CVE-2024-25641)
  documentation/modules/exploit/multi/http/cacti_package_import_rce.md
  lib/msf/core/exploit/cacti.rb
  modules/exploits/multi/http/cacti_package_import_rce.rb
  modules/exploits/multi/http/cacti_pollers_sqli_rce.rb
Labels: module, docs

#19221 Auxiliary module for CVE-2024-24919 - Check Point Security Gateway arbitrary file read
  documentation/modules/auxiliary/gather/checkpoint_gateway_fileread_cve_2024_24919.md
  modules/auxiliary/gather/checkpoint_gateway_fileread_cve_2024_24919.rb
Labels: module, docs, rn-modules

#19229 Junos OS PHPRC: Added features for interactive ssh jailbreak
  documentation/modules/exploit/freebsd/http/junos_phprc_auto_prepend_file.md
  modules/exploits/freebsd/http/junos_phprc_auto_prepend_file.rb
Labels: rn-enhancement

#19261 Fix the powershell_base64 encoder
  lib/msf/core/post/windows.rb
  modules/encoders/cmd/powershell_base64.rb
Labels: rn-fix

#19257 Update docs ruby version
  docs/.ruby-version
Labels: rn-no-release-notes

#19260 Update windows acceptance tests
  .github/workflows/acceptance.yml
  lib/metasploit/framework.rb
  lib/msf/core/db_manager/import.rb
  lib/msf/core/exploit/capture.rb
  lib/msf_autoload.rb
  modules/auxiliary/scanner/scada/profinet_siemens.rb
Labels: rn-no-release-notes

#19249 Apache OFBiz Directory Traversal RCE [CVE-2024-32113]
  documentation/modules/exploit/multi/http/apache_ofbiz_forgot_password_directory_traversal.md
  modules/exploits/multi/http/apache_ofbiz_forgot_password_directory_traversal.rb
Labels: module, docs, rn-modules

#19247 Add exploit module for the new PHP CGI Argument Injection vuln (CVE-2024-4577)
  documentation/modules/exploit/windows/http/php_cgi_arg_injection_rce_cve_2024_4577.md
  modules/exploits/windows/http/php_cgi_arg_injection_rce_cve_2024_4577.rb
Labels: module, docs, rn-modules

#19253 Corrected a mistaken CVE-ID in exploit references.
  modules/exploits/unix/http/zivif_ipcheck_exec.rb
Labels: module, bug, easy, rn-fix

#19176 Adding Arch parameter to dnn_cookie_deserialization_rce module
  modules/exploits/windows/http/dnn_cookie_deserialization_rce.rb
Labels: module, bug, rn-fix, confirmed

#19255 Add auxiliary module for SolarWinds Serv-U directory transversal vulnerability (CVE-2024-28995)
  documentation/modules/auxiliary/gather/solarwinds_servu_fileread_cve_2024_28995.md
  modules/auxiliary/gather/solarwinds_servu_fileread_cve_2024_28995.rb
Labels: module, docs, rn-modules

#19270 Update Github runners
  .github/workflows/acceptance.yml
Labels: rn-no-release-notes

#19275 Add adeherdt-r7 to the mail map
  .mailmap
Labels: rn-no-release-notes

#19284 Fix redis_login scanner when auth is enabled
  documentation/modules/auxiliary/scanner/redis/redis_login.md
  lib/metasploit/framework/credential_collection.rb
  spec/lib/metasploit/framework/private_credential_collection_spec.rb
Labels: rn-fix

#19287 MS-9454 Redis Scanner: Support newer versions
  documentation/modules/auxiliary/scanner/redis/redis_login.md
  lib/metasploit/framework/login_scanner/redis.rb
  lib/msf/core/auxiliary/redis.rb
  lib/rex/proto/redis.rb
  lib/rex/proto/redis/base.rb
  lib/rex/proto/redis/version6.rb
  modules/auxiliary/scanner/redis/redis_login.rb
  spec/lib/metasploit/framework/login_scanner/redis_spec.rb
Labels: rn-enhancement

#19289 Update apache_nifi_credentials algo regex
  modules/post/linux/gather/apache_nifi_credentials.rb
Labels: bug
