Repository rapid7/metasploit-framework, pull requests merged in 2024-03, with the labels that each got.

#18827 Add module for BoidCMS Authenticated RCE CVE-2023-38836
  documentation/modules/exploit/multi/http/cve_2023_38836_boidcms.md
  modules/exploits/multi/http/cve_2023_38836_boidcms.rb
Labels: module, docs, rn-modules

#18905 Update the SMB session `pwd` command output to be in line with SMB client output
  lib/rex/post/smb/ui/console/command_dispatcher/shares.rb
Labels: rn-enhancement

#18875 Add conditional option validation depending on SESSION/RHOST connection
  lib/msf/core/module/options.rb
  lib/msf/core/option_group.rb
  lib/msf/core/optional_session.rb
  lib/msf/core/optional_session/mssql.rb
  lib/msf/core/optional_session/mysql.rb
  lib/msf/core/optional_session/postgresql.rb
  lib/msf/core/optional_session/smb.rb
  lib/msf/ui/formatter/option_validate_error.rb
  spec/lib/msf/core/option_group_spec.rb
  spec/lib/msf/core/optional_session/mssql_spec.rb
  spec/lib/msf/core/optional_session/mysql_spec.rb
  spec/lib/msf/core/optional_session/postgresql_spec.rb
  spec/lib/msf/core/optional_session/smb_spec.rb
  spec/lib/msf/ui/console/command_dispatcher/auxiliary_spec.rb
  spec/lib/msf/ui/console/command_dispatcher/exploit_spec.rb
  spec/support/shared/examples/msf/core/optional_session.rb
Labels: rn-enhancement

#18796 Enhance ManageEngine Endpoint Central and ServiceDesk Plus CVE-2022-47966
  modules/exploits/multi/http/manageengine_servicedesk_plus_saml_rce_cve_2022_47966.rb
  modules/exploits/windows/http/manageengine_endpoint_central_saml_rce_cve_2022_47966.rb
Labels: enhancement, rn-enhancement

#18923 Use HTTPS link for postgres_sql reference
  modules/auxiliary/admin/postgres/postgres_sql.rb
Labels: rn-no-release-notes

#18844 Bugfix Msf::Exploit::FileDropper.file_dropper_exist? for Windows sessions
  lib/msf/core/exploit/file_dropper.rb
Labels: library, bug, rn-fix

#18921 Add ip to smb session prompt
  lib/rex/post/smb/ui/console.rb
Labels: library, enhancement, rn-enhancement

#18715 Add Splunk library
  lib/msf/core/exploit/remote/http/splunk.rb
  lib/msf/core/exploit/remote/http/splunk/apps.rb
  lib/msf/core/exploit/remote/http/splunk/base.rb
  lib/msf/core/exploit/remote/http/splunk/helpers.rb
  lib/msf/core/exploit/remote/http/splunk/login.rb
  lib/msf/core/exploit/remote/http/splunk/uris.rb
  lib/msf/core/exploit/remote/http/splunk/version.rb
  modules/exploits/multi/http/splunk_privilege_escalation_cve_2023_32707.rb
Labels: module, library

#18924 Allow selecting auxiliary modules in RPC
  lib/msf/core/rpc/v10/rpc_module.rb
Labels: rn-no-release-notes

#18686 ssh_version module
  documentation/modules/auxiliary/scanner/ssh/ssh_version.md
  modules/auxiliary/scanner/ssh/ssh_version.rb
Labels: module, enhancement, rn-enhancement

#18926 Updates new sessions to have a consistent local file system API
  lib/msf/ui/console/command_dispatcher/local_file_system.rb
  lib/msf/ui/console/local_file_system.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/stdapi/fs.rb
  lib/rex/post/mssql/ui/console.rb
  lib/rex/post/mysql/ui/console.rb
  lib/rex/post/postgresql/ui/console.rb
  lib/rex/post/smb/ui/console.rb
Labels: rn-enhancement

#18716 gitlab password reset account takeover (CVE-2023-7028)
  documentation/modules/auxiliary/admin/http/gitlab_password_reset_account_takeover.md
  modules/auxiliary/admin/http/gitlab_password_reset_account_takeover.rb
Labels: module, docs, rn-modules

#18775 Adding new module for MinIO (CVE-2023-28432)
  documentation/modules/auxiliary/gather/minio_bootstrap_verify_info_disc.md
  modules/auxiliary/gather/minio_bootstrap_verify_info_disc.rb
Labels: module, docs, rn-modules

#18944 Fix saving and loading DNS rules from the config
  lib/rex/proto/dns/custom_nameserver_provider.rb
Labels: bug, feature, rn-fix

#18868 Add documentation for the new DNS command
  docs/metasploit-framework.wiki/How-to-Configure-DNS.md
  docs/navigation.rb
Labels: docs, rn-documentation

#18835 clean up code duplication
  modules/exploits/windows/mssql/mssql_payload.rb
Labels: rn-enhancement

#18951 Update acceptance test readme
  spec/acceptance/README.md
Labels: rn-documentation

#18952 Updates Postgres hashdump module to now work with newer versions of Postgres
  modules/auxiliary/scanner/postgres/postgres_hashdump.rb
Labels: rn-fix

#18949 The DNS feature requires a restart, so flag it
  docs/metasploit-framework.wiki/How-to-Configure-DNS.md
  lib/msf/core/feature_manager.rb
  lib/msf/core/framework.rb
  lib/msf/ui/console/command_dispatcher/dns.rb
  lib/msf/ui/console/driver.rb
  lib/rex/proto/dns/custom_nameserver_provider.rb
Labels: library, bug, rn-fix

#18954 Ensure modules honor spooler settings
  lib/msf/ui/console/command_dispatcher/core.rb
Labels: rn-fix

#18922 JetBrains TeamCity Unauthenticated RCE exploit module (CVE-2024-27198)
  documentation/modules/exploit/multi/http/jetbrains_teamcity_rce_cve_2024_27198.md
  modules/exploits/multi/http/jetbrains_teamcity_rce_cve_2024_27198.rb
Labels: module, docs, rn-modules

#18895 Add upload/download/delete/mkdir/rmdir to smb session
  Gemfile.lock
  lib/msf/base/sessions/smb.rb
  lib/rex/ntpath.rb
  lib/rex/post/smb/ui/console.rb
  lib/rex/post/smb/ui/console/command_dispatcher.rb
  lib/rex/post/smb/ui/console/command_dispatcher/shares.rb
  lib/rex/proto/smb/simple_client.rb
  lib/rex/proto/smb/simple_client/open_file.rb
  lib/rex/proto/smb/simple_client/open_pipe.rb
  metasploit-framework.gemspec
  spec/lib/rex/ntpath_spec.rb
  spec/lib/rex/post/smb/ui/console/command_dispatcher/core_spec.rb
  spec/lib/rex/post/smb/ui/console/command_dispatcher/shares_spec.rb
Labels: rn-enhancement

#18965 Remove stale documentation link
  README.md
Labels: rn-documentation

#18947 Fix inconsistent casing in windows/local/wmi_persistence
  modules/exploits/windows/local/wmi_persistence.rb
Labels: bug, rn-fix

#18974 Consistently refer to black hole as two words
  lib/msf/ui/console/command_dispatcher/dns.rb
  lib/rex/proto/dns/resolver.rb
Labels: rn-fix

#18960 Improves handling of dying SMB and SQL sessions
  Gemfile.lock
  lib/postgres/postgres-pr/message.rb
  lib/rex/post/mysql/ui/console/command_dispatcher/client.rb
  lib/rex/post/smb/ui/console.rb
  lib/rex/post/sql/ui/console/command_dispatcher/client.rb
Labels: rn-enhancement

#18978 Add user affordance for scanner modules that can create a new session
  modules/auxiliary/scanner/mssql/mssql_login.rb
  modules/auxiliary/scanner/mysql/mysql_login.rb
  modules/auxiliary/scanner/postgres/postgres_login.rb
  modules/auxiliary/scanner/smb/smb_login.rb
Labels: rn-enhancement

#18957 Bump Metasploit version to 6.4.0
  Gemfile.lock
  docs/metasploit-framework.wiki/How-to-Configure-DNS.md
  lib/metasploit/framework/version.rb
  lib/msf/core/feature_manager.rb
Labels: rn-enhancement

#18618 Add OpenNMS Horizon privesc and authenticated RCE exploit and docs
  documentation/modules/exploit/linux/http/opennms_horizon_authenticated_rce.md
  modules/exploits/linux/http/opennms_horizon_authenticated_rce.rb
Labels: module, docs

#18980 adds help command to basic shells
  lib/msf/base/sessions/command_shell.rb
Labels: rn-enhancement

#18985 Fixes store_valid_credential conditional logic for `unix/webapp/wp_admin_shell_upload` module
  modules/exploits/unix/webapp/wp_admin_shell_upload.rb
Labels: rn-fix

#19006 Fixes WMAP plugin loading failures
  lib/msf/core/module_set.rb
Labels: rn-fix

#18721 SharePoint Unauth RCE Exploit Chain (CVE-2023-29357 & CVE-2023-24955)
  documentation/modules/exploit/windows/http/sharepoint_dynamic_proxy_generator_unauth_rce.md
  modules/exploits/windows/http/sharepoint_dynamic_proxy_generator_auth_bypass_rce.rb
Labels: module, docs

#18891 Add wp_bricks_builder_rce (CVE-2024-25600)
  data/wordlists/wp-exploitable-themes.txt
  documentation/modules/exploit/multi/http/wp_bricks_builder_rce.md
  modules/exploits/multi/http/wp_bricks_builder_rce.rb
Labels: module, docs

#19021 Updates `admin/mysql/mysql_enum` to work with newer versions of MySQL
  modules/auxiliary/admin/mysql/mysql_enum.rb
Labels: rn-fix

#19014 Add MySQL session type acceptance tests
  .github/workflows/mysql_acceptance.yml
  spec/acceptance/README.md
  spec/acceptance/mysql_spec.rb
  test/modules/post/test/mysql.rb
Labels: rn-enhancement

#18915 Watchguard firebox unauthenticated RCE [CVE-2022-26318]
  documentation/modules/exploit/linux/http/watchguard_firebox_unauth_rce_cve_2022_26318.md
  modules/exploits/linux/http/watchguard_firebox_unauth_rce_cve_2022_26318.rb
Labels: module, docs

#18935 Fix ldap auto authentication
  lib/metasploit/framework/ldap/client.rb
Labels: rn-fix

#18764 initial POC for jenkins CVE-2024-23897 (unauth arbitrary file read)
  documentation/modules/auxiliary/gather/jenkins_cli_ampersand_arbitrary_file_read.md
  lib/msf/core/exploit/remote/http/jenkins.rb
  modules/auxiliary/gather/jenkins_cli_ampersand_arbitrary_file_read.rb
Labels: module, docs
