Repository rapid7/metasploit-framework, pull requests merged in 2024-01, with the labels that each got.

#18657 Autoload Metasploit Payloads Gem
  lib/msf_autoload.rb
Labels: rn-fix

#18404 Working Module for CVE-2023-38146
  documentation/modules/exploit/windows/fileformat/theme_dll_hijack_cve_2023_38146.md
  modules/exploits/windows/fileformat/theme_dll_hijack_cve_2023_38146.rb
Labels: docs, rn-modules

#18666 Fix the save command when dns_feature is disabled
  lib/msf/ui/console/command_dispatcher/core.rb
Labels: library, bug, easy

#18376 NTLM support for the LDAP capture capabilities
  lib/msf/core/exploit/remote/ldap/server.rb
  lib/rex/proto/ldap/auth.rb
  lib/rex/proto/ldap/server.rb
  modules/auxiliary/server/capture/ldap.rb
  spec/lib/rex/proto/ldap/auth_spec.rb
  spec/lib/rex/proto/ldap/server_spec.rb
Labels: GSoC

#18604 Add Post Windows Gather to perform Mikrotik Winbox "Keep Password" credentials extraction
  documentation/modules/post/windows/gather/credentials/winbox_settings.md
  modules/post/windows/gather/credentials/winbox_settings.rb
Labels: docs, rn-modules

#18656 Force `reload_all` to load unloaded modules before refreshing modules
  lib/msf/base/simple/framework/module_paths.rb
  lib/msf/core/module_manager/reloading.rb
  lib/msf/core/modules/metadata/cache.rb
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: rn-fix

#18655 Use first module with enabled hierarchical search
  lib/msf/ui/console/command_dispatcher/modules.rb
Labels: rn-fix

#18682 Add tests for Msf::Exploit::Local exploit_type and sysinfo methods
  spec/lib/msf/exploit/local_spec.rb
Labels: enhancement, rn-enhancement

#18633 WordPress Backup Migration Plugin PHP Filter Chain RCE (CVE-2023-6553)
  data/wordlists/wp-exploitable-plugins.txt
  documentation/modules/exploit/multi/http/wp_backup_migration_php_filter.md
  lib/msf/core/exploit/remote/http/php_filter_chain.rb
  modules/exploits/multi/http/wp_backup_migration_php_filter.rb
Labels: module, docs, rn-modules

#18630 Add CVE-2023-50917: MajorDoMo Command Injection Module
  documentation/modules/exploit/linux/http/majordomo_cmd_inject_cve_2023_50917.md
  modules/exploits/linux/http/majordomo_cmd_inject_cve_2023_50917.rb
Labels: module, docs

#18729 Update Metasploit-Guide-SMB.md
  docs/metasploit-framework.wiki/Metasploit-Guide-SMB.md
Labels: easy, rn-documentation

#18712 Fix `undefined method` error in `/api/v1/modules` endpoint
  lib/msf/core/web_services.rb
  spec/lib/msf/core/web_services_spec.rb
Labels: database, rn-fix

#18568 added exploit for CVE-2023-32781 - PRTG authenticated RCE
  documentation/modules/exploit/windows/http/prtg_authenticated_rce_cve_2023_32781.md
  modules/exploits/windows/http/prtg_authenticated_rce_cve_2023_32781.rb
Labels: needs-docs, needs-linting

#18645 Add a way to get the buildid via perf
  modules/exploits/linux/local/glibc_tunables_priv_esc.rb
Labels: enhancement, rn-enhancement

#17634 Add additional reliability and stability notes to modules
  modules/auxiliary/scanner/http/emby_version_ssrf.rb
  modules/exploits/apple_ios/browser/safari_jit.rb
  modules/exploits/linux/http/dlink_dwl_2600_command_injection.rb
  modules/exploits/linux/http/geutebruck_testaction_exec.rb
  modules/exploits/linux/http/microfocus_obr_cmd_injection.rb
  modules/exploits/linux/http/nagios_xi_plugins_check_plugin_authenticated_rce.rb
  modules/exploits/linux/http/pandora_ping_cmd_exec.rb
  modules/exploits/linux/http/rconfig_ajaxarchivefiles_rce.rb
  modules/exploits/linux/http/synology_dsm_smart_exec_auth.rb
  modules/exploits/linux/http/unraid_auth_bypass_exec.rb
  modules/exploits/multi/browser/chrome_cve_2021_21220_v8_insufficient_validation.rb
  modules/exploits/multi/browser/chrome_simplifiedlowering_overflow.rb
  modules/exploits/multi/http/baldr_upload_exec.rb
  modules/exploits/multi/http/gogs_git_hooks_rce.rb
  modules/exploits/multi/http/horde_csv_rce.rb
  modules/exploits/multi/http/horizontcms_upload_exec.rb
  modules/exploits/multi/http/maracms_upload_exec.rb
  modules/exploits/multi/http/microfocus_obm_auth_rce.rb
  modules/exploits/multi/http/microfocus_ucmdb_unauth_deser.rb
  modules/exploits/multi/http/phpstudy_backdoor_rce.rb
  modules/exploits/multi/http/playsms_template_injection.rb
  modules/exploits/multi/http/shiro_rememberme_v124_deserialize.rb
  modules/exploits/multi/http/solr_velocity_rce.rb
  modules/exploits/multi/http/vbulletin_getindexablecontent.rb
  modules/exploits/multi/http/wp_ait_csv_rce.rb
  modules/exploits/multi/http/wp_file_manager_rce.rb
  modules/exploits/multi/sap/cve_2020_6207_solman_rs.rb
  modules/exploits/multi/scada/inductive_ignition_rce.rb
  modules/exploits/unix/fileformat/exiftool_djvu_ant_perl_injection.rb
  modules/exploits/unix/fileformat/metasploit_libnotify_cmd_injection.rb
  modules/exploits/unix/http/zivif_ipcheck_exec.rb
  modules/exploits/unix/webapp/openmediavault_rpc_rce.rb
  modules/exploits/unix/webapp/opensis_chain_exec.rb
  modules/exploits/unix/webapp/trixbox_ce_endpoint_devicemap_rce.rb
  modules/exploits/windows/http/apache_activemq_traversal_upload.rb
  modules/exploits/windows/http/dlink_central_wifimanager_rce.rb
  modules/exploits/windows/http/flexdotnetcms_upload_exec.rb
  modules/exploits/windows/http/fortilogger_arbitrary_fileupload.rb
  modules/exploits/windows/http/kentico_staging_syncserver.rb
  modules/exploits/windows/http/prtg_authenticated_rce.rb
  modules/exploits/windows/http/zentao_pro_rce.rb
  modules/exploits/windows/local/cve_2020_1048_printerdemon.rb
  modules/exploits/windows/local/cve_2021_21551_dbutil_memmove.rb
  modules/exploits/windows/local/druva_insync_insynccphwnet64_rcp_type_5_priv_esc.rb
  modules/exploits/windows/local/microfocus_operations_privesc.rb
  modules/exploits/windows/local/srclient_dll_hijacking.rb
  modules/exploits/windows/scada/rockwell_factorytalk_rce.rb
Labels: enhancement, rn-enhancement

#18626 Saltstack salt minion deployer
  documentation/modules/exploit/linux/local/saltstack_salt_minion_deployer.md
  lib/msf/core/exploit/local/saltstack.rb
  modules/exploits/linux/local/saltstack_salt_minion_deployer.rb
  modules/post/multi/gather/saltstack_salt.rb
Labels: module, docs

#18648 GL.iNet unauthenticated RCE [CVE-2023-50445]
  documentation/modules/exploit/linux/http/glinet_unauth_rce_cve_2023_50445.md
  modules/exploits/linux/http/glinet_unauth_rce_cve_2023_50445.rb
Labels: module, docs

#18634 asan local better check
  modules/exploits/linux/local/asan_suid_executable_priv_esc.rb
Labels: enhancement

#18741 Verify ntpath works as expected
  lib/rex/post/smb/ui/console/command_dispatcher/shares.rb
  spec/lib/rex/post/smb/ui/console/command_dispatcher/shares_spec.rb
Labels: rn-no-release-notes

#18740 Remove invalid modification time test
  spec/support/shared/examples/msf/module_manager/cache.rb
Labels: rn-no-release-notes

#18737 Update metasploit-payloads gem to 2.0.165
  Gemfile.lock
  LICENSE_GEMS
  metasploit-framework.gemspec
  modules/payloads/singles/windows/meterpreter_bind_named_pipe.rb
  modules/payloads/singles/windows/meterpreter_bind_tcp.rb
  modules/payloads/singles/windows/meterpreter_reverse_http.rb
  modules/payloads/singles/windows/meterpreter_reverse_https.rb
  modules/payloads/singles/windows/meterpreter_reverse_ipv6_tcp.rb
  modules/payloads/singles/windows/meterpreter_reverse_tcp.rb
  modules/payloads/singles/windows/x64/meterpreter_bind_named_pipe.rb
  modules/payloads/singles/windows/x64/meterpreter_bind_tcp.rb
  modules/payloads/singles/windows/x64/meterpreter_reverse_http.rb
  modules/payloads/singles/windows/x64/meterpreter_reverse_https.rb
  modules/payloads/singles/windows/x64/meterpreter_reverse_ipv6_tcp.rb
  modules/payloads/singles/windows/x64/meterpreter_reverse_tcp.rb
Labels: rn-enhancement

#18734 Add exploit for CVE-2023-22527
  documentation/modules/exploit/multi/http/atlassian_confluence_rce_cve_2023_22527.md
  modules/exploits/multi/http/atlassian_confluence_namespace_ognl_injection.rb
  modules/exploits/multi/http/atlassian_confluence_rce_cve_2023_22527.rb
Labels: module, docs, rn-modules

#18746 Don't change the main modules datastore options
  lib/msf/ui/console/command_dispatcher/payload.rb
Labels: library, rn-fix

#18680 Shared SMB Service
  Gemfile
  Gemfile.lock
  lib/msf/core/exploit/remote/smb/server.rb
  lib/msf/core/exploit/remote/smb/server/share.rb
  lib/rex/proto/smb/server.rb
  lib/rex/service_manager.rb
Labels: library, enhancement

#18755 Add an exploit for Mirth Connect RCE (CVE-2023-43208 and CVE-2023-37679)
  documentation/modules/exploit/multi/http/mirth_connect_cve_2023_43208.md
  modules/exploits/multi/http/mirth_connect_cve_2023_43208.rb
Labels: module, docs, rn-modules

#18628 Puppet: post module to gather configs and such
  documentation/modules/post/linux/gather/puppet.md
  modules/post/linux/gather/puppet.rb
Labels: module, docs
