Repository rapid7/metasploit-framework, pull requests merged in 2024-02, with the labels that each got.

#18762 RCE exploit module for CVE-2024-0204 in Fortra GoAnywhere MFT
  documentation/modules/exploit/multi/http/fortra_goanywhere_mft_rce_cve_2024_0204.md
  modules/exploits/multi/http/fortra_goanywhere_mft_rce_cve_2024_0204.rb
Labels: module, docs

#18704 Leverage the module metadata cache in the module_sets
  .github/workflows/verify.yml
  lib/msf/core/encoded_payload.rb
  lib/msf/core/exploit/remote/browser_autopwn2.rb
  lib/msf/core/module/platform.rb
  lib/msf/core/module/platform_list.rb
  lib/msf/core/module_set.rb
  lib/msf/core/modules/metadata/cache.rb
  lib/msf/core/modules/metadata/obj.rb
  lib/msf/core/payload_generator.rb
  lib/msf/core/rpc/v10/rpc_module.rb
  lib/msf/core/rpc/v10/rpc_session.rb
  lib/msf/ui/console/command_dispatcher/evasion.rb
  lib/msf/ui/console/command_dispatcher/exploit.rb
  lib/msf/ui/console/command_dispatcher/jobs.rb
  lib/msf/ui/console/command_dispatcher/payload.rb
  lib/msf/ui/console/module_option_tab_completion.rb
  lib/rex/post/hwbridge/ui/console/command_dispatcher/core.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/core.rb
  modules/post/multi/recon/local_exploit_suggester.rb
  modules/post/windows/manage/peinjector.rb
  plugins/nessus.rb
  spec/lib/msf/core/encoded_payload_spec.rb
  spec/lib/msf/core/exploit/browser_autopwn2_spec.rb
  spec/lib/msf/core/module_set_spec.rb
  spec/lib/msf/core/payload_generator_spec.rb
  spec/spec_helper.rb
  test/modules/post/test/all.rb
  tools/modules/missing_payload_tests.rb
  tools/modules/module_ports.rb
Labels: rn-fix

#18718 Add MySQL session type
  lib/metasploit/framework/login_scanner/mysql.rb
  lib/msf/base/config.rb
  lib/msf/base/sessions/mysql.rb
  lib/msf/core/exploit/remote/mysql.rb
  lib/msf/core/feature_manager.rb
  lib/msf/core/optional_session.rb
  lib/msf/core/post/common.rb
  lib/msf_autoload.rb
  lib/rex/post.rb
  lib/rex/post/mysql.rb
  lib/rex/post/mysql/ui.rb
  lib/rex/post/mysql/ui/console.rb
  lib/rex/post/mysql/ui/console/command_dispatcher.rb
  lib/rex/post/mysql/ui/console/command_dispatcher/client.rb
  lib/rex/post/mysql/ui/console/command_dispatcher/core.rb
  lib/rex/post/mysql/ui/console/command_dispatcher/modules.rb
  modules/auxiliary/scanner/mysql/mysql_login.rb
  spec/lib/metasploit/framework/login_scanner/mysql_spec.rb
  spec/lib/msf/base/sessions/mysql_spec.rb
  spec/lib/rex/post/mysql/ui/console/command_dispatcher/core_spec.rb
Labels: enhancement, rn-enhancement

#18769 Cacti RCE via SQLi (CVE-2023-49085) and LFI (CVE-2023-49084)
  documentation/modules/exploit/multi/http/cacti_pollers_sqli_rce.md
  modules/exploits/multi/http/cacti_pollers_sqli_rce.rb
Labels: module, docs

#18780 runc cwd priv esc (docker) (cve-2024-21626)
  documentation/modules/exploit/linux/local/runc_cwd_priv_esc.md
  modules/exploits/linux/local/runc_cwd_priv_esc.rb
Labels: module, docs

#18773 Support CTRL + Z for interactive SQL REPL
  lib/rex/post/postgresql/ui/console.rb
  lib/rex/post/postgresql/ui/console/command_dispatcher/client.rb
  lib/rex/post/postgresql/ui/console/interactive_sql_client.rb
Labels: rn-fix

#18782 Update Windows installation docs to mention requirement to install as Administrator
  docs/metasploit-framework.wiki/Nightly-Installers.md
Labels: rn-documentation

#18803 Remove all references to `Msf::SymbolicModule`
  lib/msf/core/module_manager/cache.rb
  lib/msf/core/module_set.rb
  lib/msf/core/payload_set.rb
  spec/lib/msf/core/module_set_spec.rb
  spec/support/shared/examples/msf/db_manager/update_all_module_details_refresh.rb
  spec/support/shared/examples/msf/module_manager/cache.rb
Labels: rn-fix

#18759 Updates MySQL modules to now support the new MySQL session type
  lib/msf/core/exploit/remote/mysql.rb
  lib/msf/core/optional_session.rb
  modules/auxiliary/admin/mysql/mysql_enum.rb
  modules/auxiliary/admin/mysql/mysql_sql.rb
  modules/auxiliary/scanner/mysql/mysql_authbypass_hashdump.rb
  modules/auxiliary/scanner/mysql/mysql_file_enum.rb
  modules/auxiliary/scanner/mysql/mysql_hashdump.rb
  modules/auxiliary/scanner/mysql/mysql_schemadump.rb
  modules/auxiliary/scanner/mysql/mysql_version.rb
  modules/auxiliary/scanner/mysql/mysql_writable_dirs.rb
  modules/exploits/multi/mysql/mysql_udf_payload.rb
  modules/exploits/windows/mysql/mysql_mof.rb
  modules/exploits/windows/mysql/mysql_start_up.rb
Labels: enhancement

#18812 Revert mssql_login TDSENCRYPTION value to false
  modules/auxiliary/scanner/mssql/mssql_login.rb
Labels: rn-fix

#18774 Add support for newer sqlcmd versions
  lib/msf/core/post/windows/mssql.rb
  modules/post/windows/manage/mssql_local_auth_bypass.rb
Labels: rn-fix

#18806 Improves unknown command handling
  lib/rex/ui/text/dispatcher_shell.rb
Labels: enhancement, rn-enhancement

#18823 Fix module metadata platform list comparison
  lib/msf/core/modules/metadata/obj.rb
Labels: bug

#18825 Improve error message for incompatible sessions
  lib/msf/core/session_compatibility.rb
Labels: enhancement, rn-enhancement

#18799 Fix revision number checks for cve_2020_17136.rb
  modules/exploits/windows/local/cve_2020_17136.rb
Labels: module, bug, rn-fix

#18798 windows/local/cve_2020_0787_bits_arbitrary_file_move (and similar) fails due to incorrect revision_number checks
  modules/exploits/windows/local/cve_2020_0787_bits_arbitrary_file_move.rb
Labels: module, bug, rn-fix

#18809 DNS Changes
  Gemfile.lock
  lib/msf/core/exploit/remote/dns/enumeration.rb
  lib/msf/ui/console/command_dispatcher/dns.rb
  lib/msf/ui/console/driver.rb
  lib/net/dns/resolver.rb
  lib/net/dns/resolver/timeouts.rb
  lib/rex/proto/dns/cache.rb
  lib/rex/proto/dns/cached_resolver.rb
  lib/rex/proto/dns/custom_nameserver_provider.rb
  lib/rex/proto/dns/exceptions.rb
  lib/rex/proto/dns/resolver.rb
  lib/rex/proto/dns/static_hostnames.rb
  lib/rex/proto/dns/upstream_resolver.rb
  lib/rex/proto/dns/upstream_rule.rb
  spec/lib/rex/proto/dns/custom_nameserver_provider_spec.rb
  spec/lib/rex/proto/dns/static_hostnames_spec.rb
  spec/lib/rex/proto/dns/upstream_resolver_spec.rb
  spec/lib/rex/proto/dns/upstream_rule_spec.rb
Labels: library, rn-enhancement, usability

#18770 Extract SMB, PostgreSQL, MySQL and MSSQL optional sessions into their own mixins
  lib/msf/base/sessions/mssql.rb
  lib/msf/base/sessions/mysql.rb
  lib/msf/base/sessions/postgresql.rb
  lib/msf/base/sessions/smb.rb
  lib/msf/core/optional_session.rb
  lib/msf/core/optional_session/mssql.rb
  lib/msf/core/optional_session/mysql.rb
  lib/msf/core/optional_session/postgresql.rb
  lib/msf/core/optional_session/smb.rb
  lib/msf_autoload.rb
  modules/auxiliary/admin/mssql/mssql_enum.rb
  modules/auxiliary/admin/mssql/mssql_escalate_dbowner.rb
  modules/auxiliary/admin/mssql/mssql_escalate_execute_as.rb
  modules/auxiliary/admin/mssql/mssql_exec.rb
  modules/auxiliary/admin/mssql/mssql_findandsampledata.rb
  modules/auxiliary/admin/mssql/mssql_idf.rb
  modules/auxiliary/admin/mssql/mssql_sql.rb
  modules/auxiliary/admin/mssql/mssql_sql_file.rb
  modules/auxiliary/admin/mysql/mysql_enum.rb
  modules/auxiliary/admin/mysql/mysql_sql.rb
  modules/auxiliary/admin/postgres/postgres_readfile.rb
  modules/auxiliary/admin/postgres/postgres_sql.rb
  modules/auxiliary/admin/smb/delete_file.rb
  modules/auxiliary/admin/smb/download_file.rb
  modules/auxiliary/admin/smb/psexec_ntdsgrab.rb
  modules/auxiliary/admin/smb/upload_file.rb
  modules/auxiliary/gather/windows_secrets_dump.rb
  modules/auxiliary/scanner/mssql/mssql_hashdump.rb
  modules/auxiliary/scanner/mssql/mssql_schemadump.rb
  modules/auxiliary/scanner/mysql/mysql_file_enum.rb
  modules/auxiliary/scanner/mysql/mysql_hashdump.rb
  modules/auxiliary/scanner/mysql/mysql_schemadump.rb
  modules/auxiliary/scanner/mysql/mysql_version.rb
  modules/auxiliary/scanner/mysql/mysql_writable_dirs.rb
  modules/auxiliary/scanner/postgres/postgres_hashdump.rb
  modules/auxiliary/scanner/postgres/postgres_schemadump.rb
  modules/auxiliary/scanner/postgres/postgres_version.rb
  modules/auxiliary/scanner/smb/pipe_auditor.rb
  modules/auxiliary/scanner/smb/pipe_dcerpc_auditor.rb
  modules/auxiliary/scanner/smb/smb_enum_gpp.rb
  modules/auxiliary/scanner/smb/smb_enumshares.rb
  modules/auxiliary/scanner/smb/smb_enumusers.rb
  modules/auxiliary/scanner/smb/smb_enumusers_domain.rb
  modules/auxiliary/scanner/smb/smb_lookupsid.rb
  modules/exploits/linux/postgres/postgres_payload.rb
  modules/exploits/multi/mysql/mysql_udf_payload.rb
  modules/exploits/multi/postgres/postgres_copy_from_program_cmd_exec.rb
  modules/exploits/multi/postgres/postgres_createlang.rb
  modules/exploits/windows/mssql/mssql_payload.rb
  modules/exploits/windows/mysql/mysql_mof.rb
  modules/exploits/windows/mysql/mysql_start_up.rb
  modules/exploits/windows/postgres/postgres_payload.rb
  modules/exploits/windows/smb/psexec.rb
  spec/lib/msf/base/sessions/mssql_spec.rb
  spec/lib/msf/base/sessions/mysql_spec.rb
  spec/lib/msf/base/sessions/postgresql_spec.rb
  spec/lib/msf/base/sessions/smb_spec.rb
Labels: rn-fix

#18678 LDAP capture capabilities
  data/capture_config.yaml
  documentation/modules/auxiliary/server/capture/ldap.md
  lib/msf/core/exploit/remote/ldap/server.rb
  lib/rex/proto/ldap/auth.rb
  lib/rex/proto/ldap/server.rb
  modules/auxiliary/server/capture/ldap.rb
  plugins/capture.rb
  spec/lib/rex/proto/ldap/auth_spec.rb
  spec/lib/rex/proto/ldap/server_spec.rb
Labels: module, library, GSoC

#18846 msftidy_docs.rb update: add TARGETURI to universal option list
  tools/dev/msftidy_docs.rb
Labels: enhancement

#18681 Update apache_ofbiz_deserialization to include auth bypass
  documentation/modules/exploit/linux/http/apache_ofbiz_deserialization.md
  modules/exploits/linux/http/apache_ofbiz_deserialization.rb
Labels: module, docs

#18700 Kafka-ui unauthenticated RCE [CVE-2023-52251]
  data/kafka_ui_versions.json
  documentation/modules/exploit/linux/http/kafka_ui_unauth_rce_cve_2023_52251.md
  modules/exploits/linux/http/kafka_ui_unauth_rce_cve_2023_52251.rb
Labels: module, docs

#18861 Removes SessionType values from modules with OptionalSession mixin
  modules/auxiliary/admin/mssql/mssql_enum.rb
  modules/auxiliary/admin/mssql/mssql_escalate_dbowner.rb
  modules/auxiliary/admin/mssql/mssql_findandsampledata.rb
  modules/auxiliary/admin/mssql/mssql_idf.rb
  modules/auxiliary/admin/mssql/mssql_sql.rb
  modules/auxiliary/admin/mssql/mssql_sql_file.rb
  modules/auxiliary/admin/mysql/mysql_enum.rb
  modules/auxiliary/scanner/mssql/mssql_hashdump.rb
  modules/auxiliary/scanner/mssql/mssql_schemadump.rb
  modules/auxiliary/scanner/mysql/mysql_file_enum.rb
  modules/auxiliary/scanner/mysql/mysql_hashdump.rb
  modules/auxiliary/scanner/mysql/mysql_schemadump.rb
  modules/auxiliary/scanner/mysql/mysql_writable_dirs.rb
  modules/auxiliary/scanner/postgres/postgres_hashdump.rb
  modules/exploits/multi/mysql/mysql_udf_payload.rb
  modules/exploits/windows/mssql/mssql_payload.rb
  modules/exploits/windows/mysql/mysql_mof.rb
  modules/exploits/windows/mysql/mysql_start_up.rb
Labels: rn-fix

#18855 Use database_name for SQL sessions
  lib/rex/post/mssql/ui/console.rb
  lib/rex/post/mysql/ui/console.rb
  lib/rex/post/postgresql/ui/console.rb
  modules/auxiliary/scanner/mssql/mssql_login.rb
  spec/lib/msf/base/sessions/mssql_spec.rb
  spec/lib/rex/post/mssql/ui/console/command_dispatcher/core_spec.rb
Labels: rn-enhancement

#18854 Add Proxies support to creating a session with mysql_login
  lib/metasploit/framework/login_scanner/mysql.rb
  lib/rex/post/mysql/ui/console.rb
  modules/auxiliary/scanner/mysql/mysql_login.rb
Labels: enhancement, rn-enhancement

#18847 Add Proxies support to creating a session with postgres_login
  lib/metasploit/framework/login_scanner/postgres.rb
  lib/msf/core/exploit/remote/postgres.rb
  lib/postgres/postgres-pr/connection.rb
  modules/auxiliary/scanner/postgres/postgres_login.rb
  spec/lib/metasploit/framework/login_scanner/postgres_spec.rb
Labels: enhancement, rn-enhancement

#18863 Expose MSSQL initial connection info in client
  lib/rex/post/mssql/ui/console.rb
  lib/rex/proto/mssql/client.rb
  lib/rex/proto/mssql/client_mixin.rb
  spec/lib/msf/base/sessions/mssql_spec.rb
  spec/lib/rex/post/mssql/ui/console/command_dispatcher/core_spec.rb
Labels: enhancement, rn-enhancement

#18864 Alias `ls` and `dir` commands inside new SMB session type prompt
  lib/rex/post/smb/ui/console/command_dispatcher/shares.rb
Labels: enhancement, rn-enhancement

#18817 Improve options display optional session types
  lib/msf/base/serializer/readable_text.rb
  lib/msf/core/module/options.rb
  lib/msf/core/opt_condition.rb
  lib/msf/core/option_container.rb
  lib/msf/core/option_group.rb
  lib/msf/core/optional_session/mssql.rb
  lib/msf/core/optional_session/mysql.rb
  lib/msf/core/optional_session/postgresql.rb
  lib/msf/core/optional_session/smb.rb
  spec/lib/msf/base/serializer/readable_text_spec.rb
  spec/lib/msf/core/module/options_spec.rb
  spec/lib/msf/core/option_container_spec.rb
  spec/lib/msf/core/option_group_spec.rb
Labels: enhancement, rn-enhancement

#18832 Exploit module for CVE-2023-47218 in QNAP QTS and QuTH Hero
  documentation/modules/exploit/linux/http/qnap_qts_rce_cve_2023_47218.md
  modules/exploits/linux/http/qnap_qts_rce_cve_2023_47218.rb
Labels: module, docs

#18866 Update Windows 11 Mimikatz support - update metasploit-payloads gem to 2.0.166
  Gemfile.lock
  LICENSE_GEMS
  metasploit-framework.gemspec
Labels: library, payload, rn-payload-enhancement

#18830 SQL sessions consolidation
  lib/msf/base/sessions/mssql.rb
  lib/msf/base/sessions/mysql.rb
  lib/msf/base/sessions/postgresql.rb
  lib/msf/base/sessions/sql.rb
  lib/msf/core/exploit/remote/mssql.rb
  lib/msf/ui/console/command_dispatcher/core.rb
  lib/rex/post/mssql/ui/console.rb
  lib/rex/post/mssql/ui/console/command_dispatcher.rb
  lib/rex/post/mssql/ui/console/command_dispatcher/client.rb
  lib/rex/post/mssql/ui/console/command_dispatcher/core.rb
  lib/rex/post/mssql/ui/console/command_dispatcher/modules.rb
  lib/rex/post/mysql/ui/console.rb
  lib/rex/post/mysql/ui/console/command_dispatcher.rb
  lib/rex/post/mysql/ui/console/command_dispatcher/client.rb
  lib/rex/post/mysql/ui/console/command_dispatcher/core.rb
  lib/rex/post/mysql/ui/console/command_dispatcher/modules.rb
  lib/rex/post/postgresql.rb
  lib/rex/post/postgresql/ui/console.rb
  lib/rex/post/postgresql/ui/console/command_dispatcher.rb
  lib/rex/post/postgresql/ui/console/command_dispatcher/client.rb
  lib/rex/post/postgresql/ui/console/command_dispatcher/core.rb
  lib/rex/post/postgresql/ui/console/command_dispatcher/modules.rb
  lib/rex/post/sql.rb
  lib/rex/post/sql/ui.rb
  lib/rex/post/sql/ui/console.rb
  lib/rex/post/sql/ui/console/command_dispatcher.rb
  lib/rex/post/sql/ui/console/command_dispatcher/client.rb
  lib/rex/post/sql/ui/console/command_dispatcher/core.rb
  lib/rex/post/sql/ui/console/command_dispatcher/modules.rb
  lib/rex/post/sql/ui/console/interactive_sql_client.rb
  lib/rex/proto/mssql/client.rb
  lib/rex/proto/mssql/client_mixin.rb
  spec/lib/msf/base/sessions/mssql_spec.rb
  spec/lib/rex/post/mssql/ui/console/command_dispatcher/core_spec.rb
Labels: enhancement, rn-enhancement

#18849 Improve visual indentation logic for tables
  Gemfile.lock
  lib/msf/ui/console/command_dispatcher/dns.rb
  lib/msf/ui/console/command_dispatcher/modules.rb
  spec/lib/msf/ui/console/command_dispatcher/creds_spec.rb
Labels: library, enhancement, rn-enhancement

#18873 Fixes the create session datastore option from appearing for payloads
  documentation/modules/auxiliary/cloud/aws/enum_ssm.md
  lib/msf/base/sessions/command_shell_options.rb
  lib/msf/base/sessions/create_session_options.rb
  modules/auxiliary/cloud/aws/enum_ssm.rb
  modules/auxiliary/scanner/mssql/mssql_login.rb
  modules/auxiliary/scanner/mysql/mysql_login.rb
  modules/auxiliary/scanner/postgres/postgres_login.rb
  modules/auxiliary/scanner/rservices/rexec_login.rb
  modules/auxiliary/scanner/rservices/rlogin_login.rb
  modules/auxiliary/scanner/rservices/rsh_login.rb
  modules/auxiliary/scanner/smb/smb_login.rb
  modules/auxiliary/scanner/ssh/eaton_xpert_backdoor.rb
  modules/auxiliary/scanner/ssh/fortinet_backdoor.rb
  modules/auxiliary/scanner/ssh/libssh_auth_bypass.rb
  modules/auxiliary/scanner/ssh/ssh_login.rb
  modules/auxiliary/scanner/ssh/ssh_login_pubkey.rb
  modules/auxiliary/scanner/telnet/brocade_enable_login.rb
  modules/auxiliary/scanner/telnet/telnet_login.rb
  modules/auxiliary/scanner/winrm/winrm_login.rb
  modules/exploits/windows/smb/smb_relay.rb
Labels: rn-fix

#18874 Fix undefined mssql_query method call on mssql client
  lib/rex/post/mssql/ui/console.rb
Labels: rn-no-release-notes

#18870 Unauthenticated RCE exploit module for ConnectWise ScreenConnect (CVE-2024-1709)
  documentation/modules/exploit/multi/http/connectwise_screenconnect_rce_cve_2024_1709.md
  modules/exploits/multi/http/connectwise_screenconnect_rce_cve_2024_1709.rb
Labels: module, docs

#18892 AD CS Updates for ESC13
  data/auxiliary/gather/ldap_query/ldap_queries_default.yaml
  docs/_config.yml
  docs/metasploit-framework.wiki/ad-certificates/Attacking-AD-CS-ESC-Vulnerabilities.md
  lib/msf/core/exploit/remote/ldap/queries.rb
  lib/rex/proto/crypto_asn1/o_i_ds.rb
  modules/auxiliary/admin/ldap/ad_cs_cert_template.rb
  modules/auxiliary/gather/ldap_esc_vulnerable_cert_finder.rb
Labels: module, docs, enhancement, rn-enhancement

#18901 Fix Rex MySQL wrapper test to have correct method symbol
  spec/lib/rex/proto/mysql/client_spec.rb
Labels: rn-no-release-notes

#18887 Adds support for searching by session types
  lib/msf/core/modules/metadata/search.rb
  lib/msf/ui/console/command_dispatcher/modules.rb
  lib/rex/post/session_compatible_modules.rb
  lib/rex/post/smb/ui/console.rb
  lib/rex/post/sql/ui/console.rb
  spec/lib/msf/core/modules/metadata/search_spec.rb
Labels: rn-enhancement
