Repository rapid7/metasploit-framework, pull requests merged in 2024-10, with the labels that each got.

#19510 Add cups-browsed Information Disclosure module
  documentation/modules/auxiliary/scanner/misc/cups_browsed_info_disclosure.md
  modules/auxiliary/scanner/misc/cups_browsed_info_disclosure.rb
Labels: module, docs

#19463 Acronis Cyber Infrastructure Default Password RCE [CVE-2023-45249]
  documentation/modules/exploit/linux/http/acronis_cyber_infra_cve_2023_45249.md
  modules/exploits/linux/http/acronis_cyber_infra_cve_2023_45249.rb
Labels: module, docs

#19480 Add openrc to exploits/linux/local/service_persistence.rb
  modules/exploits/linux/local/service_persistence.rb
Labels: enhancement, rn-enhancement

#19542 docs: adding motd_persistence docs
  documentation/modules/exploit/linux/local/motd_persistence.md
Labels: docs, easy, rn-no-release-notes

#19548 Update php actions plugin version
  .github/workflows/meterpreter_acceptance.yml
Labels: rn-no-release-notes

#19473 CVE-2023-6063: Unauthenticated SQL Injection Vulnerability in WP Fastest Cache <= 1.2.2
  data/wordlists/wp-exploitable-plugins.txt
  documentation/modules/auxiliary/scanner/http/wp_fastest_cache_sqli.md
  modules/auxiliary/scanner/http/wp_fastest_cache_sqli.rb
Labels: module, docs, rn-modules

#19485 Add BYOB Unauthenticated RCE module (CVE-2024-45256, CVE-2024-45257)
  documentation/modules/exploit/unix/webapp/byob_unauth_rce.md
  modules/exploits/unix/webapp/byob_unauth_rce.rb
Labels: module, docs, rn-modules

#19561 Add vulnerability report capability to the `ldap_esc_vulnerable_cert_finder` module
  modules/auxiliary/gather/ldap_esc_vulnerable_cert_finder.rb
Labels: enhancement

#19495 Fix crash in `Kerberos::Client::Pkinit#extract_user_and_realm` with specific SAN extension
  lib/msf/core/exploit/remote/kerberos/client/pkinit.rb
Labels: bug

#19108 New process launch API
  Gemfile.lock
  LICENSE_GEMS
  lib/msf/base/sessions/command_shell.rb
  lib/msf/base/sessions/command_shell_unix.rb
  lib/msf/base/sessions/command_shell_windows.rb
  lib/msf/base/sessions/powershell.rb
  lib/msf/core/post/common.rb
  lib/msf/core/post/file.rb
  lib/msf/core/session/provider/single_command_shell.rb
  lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb
  lib/rex/post/meterpreter/extensions/stdapi/tlv.rb
  metasploit-framework.gemspec
  modules/payloads/singles/cmd/unix/reverse_bash.rb
  modules/payloads/singles/linux/armbe/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/armbe/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/armbe/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/armle/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/armle/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/armle/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/mipsbe/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/mipsbe/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/mipsbe/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/mipsle/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/mipsle/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/mipsle/meterpreter_reverse_tcp.rb
  modules/payloads/singles/osx/aarch64/meterpreter_reverse_http.rb
  modules/payloads/singles/osx/aarch64/meterpreter_reverse_https.rb
  modules/payloads/singles/osx/aarch64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/php/meterpreter_reverse_tcp.rb
  modules/post/multi/general/execute.rb
  spec/lib/msf/base/sessions/command_shell_unix_spec.rb
  spec/lib/msf/base/sessions/command_shell_windows_spec.rb
  spec/lib/msf/base/sessions/powershell_spec.rb
  spec/support/acceptance/child_process.rb
  test/modules/post/test/cmd_exec.rb
Labels: rn-enhancement, payload-testing-branch, payload-testing-mettle-branch

#19482 Add LearnPress SQLi module (CVE-2024-8522, CVE-2024-8529)
  documentation/modules/auxiliary/scanner/http/wp_learnpress_c_fields_sqli.md
  modules/auxiliary/scanner/http/wp_learnpress_c_fields_sqli.rb
Labels: module, docs, rn-modules

#19563 Update metabase setuptoken rce to support older versions
  documentation/modules/exploit/linux/http/metabase_setup_token_rce.md
  modules/exploits/linux/http/metabase_setup_token_rce.rb
Labels: rn-fix

#19544 Magento Arbitrary File Read (CVE-2024-34102) + PHP Buffer Overflow iconv() of GLIBC (CVE-2024-2961)
  Gemfile.lock
  documentation/modules/exploit/linux/http/magento_xxe_to_glibc_buf_overflow.md
  metasploit-framework.gemspec
  modules/exploits/linux/http/magento_xxe_to_glibc_buf_overflow.rb
Labels: module, docs, rn-modules

#19564 Adds a resuable pipeline for acceptance testing
  .github/workflows/meterpreter_acceptance.yml
  .github/workflows/shared_meterpreter_acceptance.yml
Labels: payload-testing-branch, payload-testing-mettle-branch

#19568 Adds SMB reusable pipeline for acceptance testing
  .github/workflows/command_shell_acceptance.yml
  .github/workflows/meterpreter_acceptance.yml
  .github/workflows/shared_smb_acceptance.yml
  .github/workflows/smb_acceptance.yml
Labels: rn-no-release-notes

#19567 data/wordlists: Add default passwords for common single-board computers
  data/wordlists/common_roots.txt
  data/wordlists/password.lst
  data/wordlists/unix_passwords.txt
  data/wordlists/unix_users.txt
Labels: enhancement

#19572 Fix UPDATE certificate templates with `admin/ldap/ad_cs_cert_template`
  data/auxiliary/admin/ldap/ad_cs_cert_template/esc15_template.yaml
  documentation/modules/auxiliary/admin/dcerpc/icpr_cert.md
  documentation/modules/auxiliary/admin/ldap/ad_cs_cert_template.md
  modules/auxiliary/admin/dcerpc/icpr_cert.rb
  modules/auxiliary/admin/ldap/ad_cs_cert_template.rb
Labels: rn-fix

#19580 Add gitleaksignore file
  .gitleaksignore
Labels: rn-no-release-notes

#19581 Add additional paths for triggering meterpreter acceptance
  .github/workflows/meterpreter_acceptance.yml
Labels: rn-no-release-notes

#19577 Fix crash when running meterpreter shell command
  lib/rex/post/meterpreter/extensions/stdapi/sys/process.rb
Labels: rn-fix

#19536 Update enum_unattend.rb
  modules/post/windows/gather/enum_unattend.rb
Labels: rn-enhancement

#19575 Builds metasploit-payload gem as part of acceptance tests
  .github/workflows/shared_meterpreter_acceptance.yml
Labels: payload-testing-branch, payload-testing-mettle-branch

#19551 Don't require Username and Password for every RHost auth: allows Scha…
  lib/msf/core/optional_session/ldap.rb
Labels: library, bug, rn-fix

#19360 Add LaunchDaemon Persistence to exploits/osx/local/persistence.rb
  modules/exploits/osx/local/persistence.rb
Labels: needs-linting

#19553 Only retrieve cached credentials that match the requested KrbOfferedEncryptionTypes
  lib/msf/core/exploit/remote/kerberos/service_authenticator/base.rb
  lib/msf/core/exploit/remote/kerberos/ticket/storage/read_mixin.rb
  lib/msf/core/exploit/remote/kerberos/ticket/storage/stored_ticket.rb
  lib/msf/ui/console/command_dispatcher/db/klist.rb
  spec/lib/msf/ui/console/command_dispatcher/db/klist_spec.rb
Labels: bug, rn-fix

#19488 Add auxiliary module for unauth SQLi in Ultimate Member plugin (CVE-2024-1071)
  data/wordlists/wp-exploitable-plugins.txt
  documentation/modules/auxiliary/scanner/http/wp_ultimate_member_sorting_sqli.md
  modules/auxiliary/scanner/http/wp_ultimate_member_sorting_sqli.rb
Labels: module, docs, rn-modules

#19527 Add bypass for GiveWP RCE (CVE-2024-8353)
  documentation/modules/exploit/multi/http/wp_givewp_rce.md
  modules/exploits/multi/http/wp_givewp_rce.rb
Labels: module, docs, rn-modules

#19607 Fix table width bug when running from docker
  Gemfile.lock
Labels: rn-no-release-notes

#19517 Add module for TI WooCommerce Wishlist SQL Injection (CVE-2024-43917)
  documentation/modules/auxiliary/scanner/http/wp_ti_woocommerce_wishlist_sqli.md
  modules/auxiliary/scanner/http/wp_ti_woocommerce_wishlist_sqli.rb
Labels: module, docs, rn-modules

#19499 SolarWinds Web Help Desk Backdoor (CVE-2024-28987) Module
  documentation/modules/auxiliary/gather/solarwinds_webhelpdesk_backdoor.md
  modules/auxiliary/gather/solarwinds_webhelpdesk_backdoor.rb
Labels: module, docs, rn-modules

#19528 Add a python/exec payload to execute OS commands
  modules/payloads/singles/python/exec.rb
  spec/modules/payloads_spec.rb
Labels: module, rn-modules
