Repository rapid7/metasploit-framework, pull requests merged in 2024-07, with the labels that each got.

#19285 Fix sysinfo fails when cwd in the implant is deleted
  lib/msf/base/sessions/meterpreter.rb
Labels: bug, rn-fix

#10113 Add post module to steal azure cli tokens/configuration
  documentation/modules/post/multi/gather/azure_cli_creds.md
  lib/msf/core/post/azure.rb
  modules/post/multi/gather/azure_cli_creds.rb
  spec/lib/msf/core/post/azure_spec.rb
Labels: module, docs

#19204 Zyxel VPN Series Pre-auth Command Injection
  documentation/modules/exploit/linux/http/zyxel_parse_config_rce.md
  modules/exploits/linux/http/zyxel_parse_config_rce.rb
Labels: module, docs

#19312 Fix loading Mettle extensions
  Gemfile.lock
  metasploit-framework.gemspec
Labels: rn-fix

#19274 Ivanti Endpoint Manager (EPM) SQLi and RCE (CVE-2024-29824)
  documentation/modules/exploit/windows/http/ivanti_epm_recordgoodapp_sqli_rce.md
  modules/exploits/windows/http/ivanti_epm_recordgoodapp_sqli_rce.rb
Labels: module, docs

#19315 remove duplicate word in wiki docs
  docs/metasploit-framework.wiki/dev/Setting-Up-a-Metasploit-Development-Environment.md
Labels: docs, rn-documentation

#19314 Exploit module for CVE-2024-21683 - Atlassian Confluence administrator-level RCE
  documentation/modules/exploit/multi/http/atlassian_confluence_rce_cve_2024_21683.md
  modules/exploits/multi/http/atlassian_confluence_rce_cve_2024_21683.rb
Labels: module, docs

#19311 GeoServer unauthenticated RCE [CVE-2024-36401]
  documentation/modules/exploit/multi/http/geoserver_unauth_rce_cve_2024_36401.md
  modules/exploits/multi/http/geoserver_unauth_rce_cve_2024_36401.rb
Labels: module, docs

#19327 Bump metasploit_payloads-mettle to 1.0.31
  Gemfile.lock
  LICENSE_GEMS
  metasploit-framework.gemspec
  modules/payloads/singles/apple_ios/aarch64/meterpreter_reverse_http.rb
  modules/payloads/singles/apple_ios/aarch64/meterpreter_reverse_https.rb
  modules/payloads/singles/apple_ios/aarch64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/apple_ios/armle/meterpreter_reverse_http.rb
  modules/payloads/singles/apple_ios/armle/meterpreter_reverse_https.rb
  modules/payloads/singles/apple_ios/armle/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/aarch64/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/aarch64/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/aarch64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/armbe/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/armbe/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/armbe/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/armle/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/armle/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/armle/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/mips64/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/mips64/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/mips64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/mipsbe/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/mipsbe/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/mipsbe/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/mipsle/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/mipsle/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/mipsle/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/ppc/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/ppc/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/ppc/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/ppc64le/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/ppc64le/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/ppc64le/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/ppce500v2/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/ppce500v2/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/ppce500v2/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/x64/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/x64/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/x64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/x86/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/x86/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/x86/meterpreter_reverse_tcp.rb
  modules/payloads/singles/linux/zarch/meterpreter_reverse_http.rb
  modules/payloads/singles/linux/zarch/meterpreter_reverse_https.rb
  modules/payloads/singles/linux/zarch/meterpreter_reverse_tcp.rb
  modules/payloads/singles/osx/aarch64/meterpreter_reverse_http.rb
  modules/payloads/singles/osx/aarch64/meterpreter_reverse_https.rb
  modules/payloads/singles/osx/aarch64/meterpreter_reverse_tcp.rb
  modules/payloads/singles/osx/x64/meterpreter_reverse_http.rb
  modules/payloads/singles/osx/x64/meterpreter_reverse_https.rb
  modules/payloads/singles/osx/x64/meterpreter_reverse_tcp.rb
Labels: easy

#19304 Module for Magento XXE (CVE-2024-34102)
  documentation/modules/auxiliary/gather/magento_xxe_cve_2024_34102.md
  modules/auxiliary/gather/magento_xxe_cve_2024_34102.rb
Labels: module, docs

#19313 Ghostscript Command Execution via Format String (CVE-2024-29510)
  data/exploits/CVE-2024-29510/ghostscript_format_string.eps
  documentation/modules/exploit/multi/fileformat/ghostscript_format_string_cve_2024_29510.md
  modules/exploits/multi/fileformat/ghostscript_format_string_cve_2024_29510.rb
Labels: module, docs

#19336 Fix SSH scanner tests when report summary enabled
  lib/msf/core/auxiliary/report_summary.rb
Labels: rn-no-release-notes

#19337 mySCADA MyPRO Command Injection (CVE-2023-28384)
  documentation/modules/exploit/windows/scada/mypro_cmdexe.md
  modules/exploits/windows/scada/mypro_cmdexe.rb
Labels: module, docs

#19298 OpenMediaVault authenticated RCE [CVE-2013-3632]
  documentation/modules/exploit/unix/webapp/openmediavault_auth_cron_rce.md
  modules/exploits/multi/http/openmediavault_cmd_exec.rb
  modules/exploits/unix/webapp/openmediavault_auth_cron_rce.rb
Labels: module, docs, rn-modules

#19331 Update empire_skywalker module
  documentation/modules/exploit/linux/http/empire_skywalker.md
  modules/exploits/linux/http/empire_skywalker.rb
Labels: module, docs, rn-modules

#19344 FortiClient EMS FCTID SQLi to RCE fix for 7.2.x version range
  documentation/modules/exploit/windows/http/forticlient_ems_fctid_sqli.md
  modules/exploits/windows/http/forticlient_ems_fctid_sqli.rb
Labels: module, docs
