Repository rapid7/metasploit-framework, pull requests merged in 2025-10, with the labels that each got.

#20566 Update esc_update_ldap module so shadow creds not required
  documentation/modules/auxiliary/admin/dcerpc/esc_update_ldap_object.md
  modules/auxiliary/admin/dcerpc/esc_update_ldap_object.rb
Labels: enhancement, rn-enhancement

#20563 Update reg checks when DC and CA are separate
  documentation/modules/auxiliary/gather/ldap_esc_vulnerable_cert_finder.md
  lib/msf/core/exploit/remote/ldap/active_directory.rb
  modules/auxiliary/admin/dcerpc/esc_update_ldap_object.rb
  modules/auxiliary/gather/ldap_esc_vulnerable_cert_finder.rb
Labels: bug, rn-fix

#20527 update plist persistence to mixin
  modules/exploits/osx/persistence/launch_plist.rb
Labels: enhancement, rn-enhancement

#20586 Add Malicious Windows Script Host Script File (.wsf) module
  documentation/modules/exploit/windows/fileformat/windows_script_host_wsf.md
  modules/exploits/windows/fileformat/windows_script_host_wsf.rb
Labels: module, docs, rn-modules

#20591 Fix typos in documentation / hacktoberfest
  CONTRIBUTING.md
  docker/README.md
  docs/metasploit-framework.wiki/Evading-Anti-Virus.md
  docs/metasploit-framework.wiki/Get-Started-Writing-an-Exploit.md
  docs/metasploit-framework.wiki/How-to-get-started-with-writing-an-auxiliary-module.md
  documentation/modules/auxiliary/admin/aws/aws_launch_instances.md
  documentation/modules/auxiliary/admin/smb/ms17_010_command.md
Labels: rn-no-release-notes, hacktoberfest-accepted

#20600 Unpin octokit
  Gemfile.lock
  metasploit-framework.gemspec
Labels: rn-no-release-notes

#20602 Remove a CVE that was mistakenly added
  modules/exploits/unix/webapp/fusionpbx_exec_cmd_exec.rb
Labels: easy, rn-no-release-notes
