Repository rapid7/metasploit-framework, pull requests merged in 2025-04, with the labels that each got.

#19993 BUGFIX: cmd encoder base64
  modules/encoders/cmd/base64.rb
Labels: bug, rn-fix

#19995 Module for CVE-2025-24813
  documentation/modules/exploit/multi/http/tomcat_partial_put_deserialization.md
  modules/exploits/multi/http/tomcat_partial_put_deserialization.rb
Labels: module, docs, rn-modules

#20007 Add Appsmith RCE module (CVE-2024-55964)
  documentation/modules/exploit/linux/http/appsmith_rce_cve_2024_55964.md
  modules/exploits/linux/http/appsmith_rce_cve_2024_55964.rb
Labels: module, docs

#20008 Pandora FMS authenticated RCE [CVE-2024-12971]
  documentation/modules/exploit/linux/http/pandora_fms_auth_rce_cve_2024_12971.md
  modules/exploits/linux/http/pandora_fms_auth_rce_cve_2024_12971.rb
Labels: module, docs

#20001 Adds a shared pipeline for gems verify workflow
  .github/workflows/shared_gem_verify.yml
  .github/workflows/shared_gem_verify_rails.yml
Labels: rn-no-release-notes

#20006 Fixes modules that were causing Rubocop to fail
  modules/exploits/unix/webapp/phpbb_highlight.rb
  modules/exploits/windows/smb/ms10_061_spoolss.rb
Labels: rn-fix

#20018 pgAdmin Query Tool Authenticated RCE (CVE-2025-2945)
  documentation/modules/exploit/multi/http/pgadmin_query_tool_authenticated.md
  lib/msf/core/exploit/pgadmin.rb
  lib/msf_autoload.rb
  modules/exploits/multi/http/pgadmin_query_tool_authenticated.rb
Labels: module, docs

#20024 Add support for network capture decryption
  Gemfile.lock
  lib/msf/core/exploit/remote/http_client.rb
  lib/msf/core/exploit/remote/tcp.rb
  lib/rex/proto/http/client.rb
Labels: enhancement, rn-enhancement

#19997 Add PIPE_FETCH option to fetch payloads to make payloads shorter
  docs/metasploit-framework.wiki/How-to-use-fetch-payloads.md
  lib/msf/core/payload/adapter/fetch.rb
  lib/msf/core/payload/adapter/fetch/http.rb
  lib/msf/core/payload/adapter/fetch/https.rb
  lib/msf/core/payload/adapter/fetch/linux_options.rb
  lib/msf/core/payload/adapter/fetch/server/http.rb
  lib/msf/core/payload/adapter/fetch/server/https.rb
  lib/msf/core/payload/adapter/fetch/windows_options.rb
  modules/payloads/adapters/cmd/windows/smb/x64.rb
Labels: payload, enhancement

#19982 Improve a bit modules/post/linux/gather/enum_protections.rb
  modules/post/linux/gather/enum_protections.rb
Labels: rn-enhancement

#20031 modules/exploits/freebsd: Add Notes and resolve RuboCop violations
  modules/exploits/freebsd/ftp/proftp_telnet_iac.rb
  modules/exploits/freebsd/http/citrix_dir_traversal_rce.rb
  modules/exploits/freebsd/http/watchguard_cmd_exec.rb
  modules/exploits/freebsd/local/intel_sysret_priv_esc.rb
  modules/exploits/freebsd/local/mmap.rb
  modules/exploits/freebsd/local/rtld_execl_priv_esc.rb
  modules/exploits/freebsd/local/watchguard_fix_corrupt_mail.rb
  modules/exploits/freebsd/misc/citrix_netscaler_soap_bof.rb
  modules/exploits/freebsd/samba/trans2open.rb
  modules/exploits/freebsd/tacacs/xtacacsd_report.rb
  modules/exploits/freebsd/telnet/telnet_encrypt_keyid.rb
Labels: code quality

#20032 modules/nops: Resolve RuboCop violations
  modules/nops/aarch64/simple.rb
  modules/nops/armle/simple.rb
  modules/nops/mipsbe/better.rb
  modules/nops/php/generic.rb
  modules/nops/ppc/simple.rb
  modules/nops/sparc/random.rb
  modules/nops/tty/generic.rb
  modules/nops/x64/simple.rb
  modules/nops/x86/opty2.rb
  modules/nops/x86/single_byte.rb
Labels: code quality

#20034 modules/evasion: Resolve RuboCop violations
  modules/evasion/windows/applocker_evasion_install_util.rb
  modules/evasion/windows/applocker_evasion_msbuild.rb
  modules/evasion/windows/applocker_evasion_presentationhost.rb
  modules/evasion/windows/applocker_evasion_regasm_regsvcs.rb
  modules/evasion/windows/applocker_evasion_workflow_compiler.rb
  modules/evasion/windows/windows_defender_exe.rb
  modules/evasion/windows/windows_defender_js_hta.rb
Labels: code quality

#20035 modules/encoders: Resolve RuboCop violations
  modules/encoders/cmd/base64.rb
  modules/encoders/cmd/brace.rb
  modules/encoders/cmd/echo.rb
  modules/encoders/cmd/generic_sh.rb
  modules/encoders/cmd/ifs.rb
  modules/encoders/cmd/perl.rb
  modules/encoders/cmd/powershell_base64.rb
  modules/encoders/cmd/printf_php_mq.rb
  modules/encoders/generic/eicar.rb
  modules/encoders/generic/none.rb
  modules/encoders/mipsbe/byte_xori.rb
  modules/encoders/mipsbe/longxor.rb
  modules/encoders/mipsle/byte_xori.rb
  modules/encoders/mipsle/longxor.rb
  modules/encoders/php/base64.rb
  modules/encoders/php/hex.rb
  modules/encoders/ppc/longxor.rb
  modules/encoders/ppc/longxor_tag.rb
  modules/encoders/ruby/base64.rb
  modules/encoders/sparc/longxor_tag.rb
  modules/encoders/x64/xor.rb
  modules/encoders/x64/xor_context.rb
  modules/encoders/x64/xor_dynamic.rb
  modules/encoders/x64/zutto_dekiru.rb
  modules/encoders/x86/add_sub.rb
  modules/encoders/x86/alpha_mixed.rb
  modules/encoders/x86/alpha_upper.rb
  modules/encoders/x86/avoid_underscore_tolower.rb
  modules/encoders/x86/avoid_utf8_tolower.rb
  modules/encoders/x86/bloxor.rb
  modules/encoders/x86/bmp_polyglot.rb
  modules/encoders/x86/call4_dword_xor.rb
  modules/encoders/x86/context_cpuid.rb
  modules/encoders/x86/context_stat.rb
  modules/encoders/x86/context_time.rb
  modules/encoders/x86/countdown.rb
  modules/encoders/x86/fnstenv_mov.rb
  modules/encoders/x86/jmp_call_additive.rb
  modules/encoders/x86/nonalpha.rb
  modules/encoders/x86/nonupper.rb
  modules/encoders/x86/opt_sub.rb
  modules/encoders/x86/service.rb
  modules/encoders/x86/shikata_ga_nai.rb
  modules/encoders/x86/single_static_bit.rb
  modules/encoders/x86/unicode_mixed.rb
  modules/encoders/x86/unicode_upper.rb
  modules/encoders/x86/xor_dynamic.rb
Labels: code quality

#20036 exploit/windows/local/unquoted_service_path: Check if write_file fails
  modules/exploits/windows/local/unquoted_service_path.rb
Labels: module, bug

#20022 Add Langflow unauth RCE module (CVE-2025-3248)
  documentation/modules/exploit/multi/http/langflow_unauth_rce_cve_2025_3248.md
  modules/exploits/multi/http/langflow_unauth_rce_cve_2025_3248.rb
Labels: module, docs

#20043 Update att open proxy error handling
  modules/auxiliary/scanner/wproxy/att_open_proxy.py
Labels: rn-fix

#20044 Updated service_permissions with action to exploit CVE-2025-21293
  documentation/modules/exploit/windows/local/service_permissions.md
  modules/exploits/windows/local/service_permissions.rb
Labels: module, rn-modules

#20047 modules/exploits/aix: Resolve RuboCop violations
  modules/exploits/aix/local/xorg_x11_server.rb
  modules/exploits/aix/rpc_cmsd_opcode21.rb
  modules/exploits/aix/rpc_ttdbserverd_realpath.rb
Labels: code quality

#20048 modules/exploits/bsdi: Resolve RuboCop violations
  modules/exploits/bsdi/softcart/mercantec_softcart.rb
Labels: code quality

#20051 modules/exploits/dialup: Resolve RuboCop violations
  modules/exploits/dialup/multi/login/manyargs.rb
Labels: rn-no-release-notes, code quality

#20052 Move exploit/dialup/multi/login/manyargs to exploit/solaris/dialup/
  modules/exploits/solaris/dialup/manyargs.rb
Labels: rn-enhancement, code quality

#20053 modules/exploits/bsd: Resolve RuboCop violations
  modules/exploits/bsd/finger/morris_fingerd_bof.rb
Labels: rn-no-release-notes, code quality

#20054 modules/exploits/firefox: Resolve RuboCop violations
  modules/exploits/firefox/local/exec_shellcode.rb
Labels: rn-no-release-notes, code quality

#20056 modules/exploits/irix: Resolve RuboCop violations
  modules/exploits/irix/lpd/tagprinter_exec.rb
Labels: code quality

#20057 modules: examples: Resolve RuboCop violations
  modules/auxiliary/scanner/udp/example.rb
  modules/exploits/example_webapp.rb
  modules/exploits/windows/browser/example.rb
Labels: rn-enhancement, code quality

#20058 modules/exploits/apple_ios: Resolve RuboCop violations
  modules/exploits/apple_ios/browser/safari_libtiff.rb
  modules/exploits/apple_ios/browser/webkit_createthis.rb
  modules/exploits/apple_ios/browser/webkit_trident.rb
  modules/exploits/apple_ios/email/mobilemail_libtiff.rb
Labels: code quality

#20055 modules/exploits/netware: Resolve RuboCop violations
  modules/exploits/netware/smb/lsass_cifs.rb
  modules/exploits/netware/sunrpc/pkernel_callit.rb
Labels: code quality

#20065 modules/exploits/hpux: Resolve RuboCop violations
  modules/exploits/hpux/lpd/cleanup_exec.rb
Labels: code quality

#20063 payloads: Ruby pingback: Resolve RuboCop violations
  modules/payloads/singles/ruby/pingback_bind_tcp.rb
  modules/payloads/singles/ruby/pingback_reverse_tcp.rb
Labels: bug, payload, rn-fix, code quality

#20064 payloads: cmd/unix/reverse_php_ssl: Resolve RuboCop violations
  modules/payloads/singles/cmd/unix/reverse_php_ssl.rb
Labels: bug, payload, rn-fix, code quality

#20028 Refactor pgAdmin modules to use new lib
  lib/msf/core/exploit/pgadmin.rb
  modules/exploits/multi/http/pgadmin_session_deserialization.rb
  modules/exploits/windows/http/pgadmin_binary_path_api.rb
Labels: enhancement, rn-enhancement

#20068 exploit/solaris/sunrpc/sadmind_*: Cleanup and add documentation
  documentation/modules/exploit/solaris/sunrpc/sadmind_adm_build_path.md
  documentation/modules/exploit/solaris/sunrpc/sadmind_exec.md
  modules/exploits/solaris/sunrpc/sadmind_adm_build_path.rb
  modules/exploits/solaris/sunrpc/sadmind_exec.rb
Labels: docs, rn-enhancement, code quality

#19760 Add certs command & use pkinit if kerberos tickets are not available in cache
  lib/metasploit/framework/ldap/client.rb
  lib/metasploit/framework/login_scanner/ldap.rb
  lib/msf/core/db_manager/cred.rb
  lib/msf/core/exploit/remote/kerberos/service_authenticator/base.rb
  lib/msf/core/exploit/remote/ms_icpr.rb
  lib/msf/core/exploit/remote/pkcs12/storage.rb
  lib/msf/core/exploit/remote/pkcs12/stored_pkcs12.rb
  lib/msf/ui/console/command_dispatcher/db.rb
  lib/msf/ui/console/command_dispatcher/db/certs.rb
  modules/auxiliary/scanner/ldap/ldap_login.rb
  spec/lib/msf/core/exploit/remote/pkcs12/storage_spec.rb
  spec/lib/msf/core/exploit/remote/pkcs12/stored_pkcs12_spec.rb
  spec/lib/msf/ui/console/command_dispatcher/db/certs_spec.rb
Labels: enhancement, rn-enhancement, usability

#20046 Add BentoML's runner server unauth RCE module (CVE-2025-32375)
  documentation/modules/exploit/linux/http/bentoml_runner_server_rce_cve_2025_32375.md
  modules/exploits/linux/http/bentoml_runner_server_rce_cve_2025_32375.rb
Labels: module, docs, rn-modules

#20077 Update haraka module to work with newer python versions
  lib/msf/core/modules/external/python/metasploit/version.py
  modules/exploits/linux/smtp/haraka.py
Labels: rn-enhancement

#20076 Fix typo in bypassuac_fodhelper.rb
  modules/exploits/windows/local/bypassuac_fodhelper.rb
Labels: rn-no-release-notes

#20067 Fix defer module payload regression
  lib/msf/core/payload_set.rb
Labels: rn-no-release-notes

#20086 modules/post/aix: Resolve RuboCop violations
  modules/post/aix/hashdump.rb
Labels: rn-no-release-notes, code quality

#20083 modules/exploits/android: Resolve RuboCop violations
  modules/exploits/android/adb/adb_server_exec.rb
  modules/exploits/android/browser/samsung_knox_smdm_url.rb
  modules/exploits/android/browser/stagefright_mp4_tx3g_64bit.rb
  modules/exploits/android/browser/webview_addjavascriptinterface.rb
  modules/exploits/android/fileformat/adobe_reader_pdf_js_interface.rb
  modules/exploits/android/local/binder_uaf.rb
  modules/exploits/android/local/futex_requeue.rb
  modules/exploits/android/local/janus.rb
  modules/exploits/android/local/put_user_vroot.rb
  modules/exploits/android/local/su_exec.rb
Labels: rn-enhancement, code quality

#20087 modules/post/android: Resolve RuboCop violations
  modules/post/android/capture/screen.rb
  modules/post/android/gather/hashdump.rb
  modules/post/android/gather/sub_info.rb
  modules/post/android/gather/wireless_ap.rb
  modules/post/android/manage/remove_lock.rb
  modules/post/android/manage/remove_lock_root.rb
Labels: code quality

#20088 modules/post/bsd: Resolve RuboCop violations
  modules/post/bsd/gather/hashdump.rb
Labels: rn-no-release-notes, code quality

#20089 modules/post/networking: Resolve RuboCop violations
  modules/post/networking/gather/enum_brocade.rb
  modules/post/networking/gather/enum_juniper.rb
Labels: code quality

#20090 modules/post/apple_ios: Resolve RuboCop violations
  modules/post/apple_ios/gather/ios_image_gather.rb
  modules/post/apple_ios/gather/ios_text_gather.rb
Labels: rn-no-release-notes, code quality

#20073 modules/exploits/solaris: Resolve RuboCop violations
  modules/exploits/solaris/dtspcd/heap_noir.rb
  modules/exploits/solaris/local/extremeparr_dtappgather_priv_esc.rb
  modules/exploits/solaris/local/libnspr_nspr_log_file_priv_esc.rb
  modules/exploits/solaris/local/rsh_stack_clash_priv_esc.rb
  modules/exploits/solaris/local/xscreensaver_log_priv_esc.rb
  modules/exploits/solaris/lpd/sendmail_exec.rb
  modules/exploits/solaris/samba/lsa_transnames_heap.rb
  modules/exploits/solaris/samba/trans2open.rb
  modules/exploits/solaris/sunrpc/ypupdated_exec.rb
  modules/exploits/solaris/telnet/fuser.rb
  modules/exploits/solaris/telnet/ttyprompt.rb
Labels: rn-enhancement, code quality

#20091 modules/post/linux/gather: Resolve RuboCop violations
  modules/post/linux/gather/checkvm.rb
  modules/post/linux/gather/ecryptfs_creds.rb
  modules/post/linux/gather/enum_configs.rb
  modules/post/linux/gather/enum_nagios_xi.rb
  modules/post/linux/gather/enum_network.rb
  modules/post/linux/gather/enum_protections.rb
  modules/post/linux/gather/enum_system.rb
  modules/post/linux/gather/enum_users_history.rb
  modules/post/linux/gather/gnome_commander_creds.rb
  modules/post/linux/gather/gnome_keyring_dump.rb
  modules/post/linux/gather/hashdump.rb
  modules/post/linux/gather/mount_cifs_creds.rb
  modules/post/linux/gather/openvpn_credentials.rb
  modules/post/linux/gather/phpmyadmin_credsteal.rb
  modules/post/linux/gather/pptpd_chap_secrets.rb
  modules/post/linux/gather/tor_hiddenservices.rb
Labels: code quality

#20093 Fix an unfortunate typo
  modules/post/linux/gather/enum_protections.rb
Labels: rn-no-release-notes

#20094 modules/post/hardware: Resolve RuboCop violations
  modules/post/hardware/automotive/can_flood.rb
  modules/post/hardware/automotive/canprobe.rb
  modules/post/hardware/automotive/diagnostic_state.rb
  modules/post/hardware/automotive/ecu_hard_reset.rb
  modules/post/hardware/automotive/getvinfo.rb
  modules/post/hardware/automotive/identifymodules.rb
  modules/post/hardware/automotive/malibu_overheat.rb
  modules/post/hardware/automotive/mazda_ic_mover.rb
  modules/post/hardware/automotive/pdt.rb
  modules/post/hardware/rftransceiver/rfpwnon.rb
  modules/post/hardware/rftransceiver/transmitter.rb
  modules/post/hardware/zigbee/zstumbler.rb
Labels: code quality

#20104 modules/post/solaris: Resolve RuboCop violations
  modules/post/solaris/escalate/pfexec.rb
  modules/post/solaris/escalate/srsexec_readline.rb
  modules/post/solaris/gather/checkvm.rb
  modules/post/solaris/gather/enum_packages.rb
  modules/post/solaris/gather/enum_services.rb
  modules/post/solaris/gather/hashdump.rb
Labels: rn-enhancement, code quality

#20107 modules/post/multi/gather: Resolve RuboCop violations
  modules/post/multi/gather/apple_ios_backup.rb
  modules/post/multi/gather/aws_ec2_instance_metadata.rb
  modules/post/multi/gather/aws_keys.rb
  modules/post/multi/gather/check_malware.rb
  modules/post/multi/gather/chrome_cookies.rb
  modules/post/multi/gather/dbvis_enum.rb
  modules/post/multi/gather/dns_bruteforce.rb
  modules/post/multi/gather/dns_reverse_lookup.rb
  modules/post/multi/gather/dns_srv_lookup.rb
  modules/post/multi/gather/docker_creds.rb
  modules/post/multi/gather/enum_vbox.rb
  modules/post/multi/gather/fetchmailrc_creds.rb
  modules/post/multi/gather/filezilla_client_cred.rb
  modules/post/multi/gather/find_vmx.rb
  modules/post/multi/gather/firefox_creds.rb
  modules/post/multi/gather/gpg_creds.rb
  modules/post/multi/gather/grub_creds.rb
  modules/post/multi/gather/irssi_creds.rb
  modules/post/multi/gather/jboss_gather.rb
  modules/post/multi/gather/jenkins_gather.rb
  modules/post/multi/gather/lastpass_creds.rb
  modules/post/multi/gather/maven_creds.rb
  modules/post/multi/gather/minio_client.rb
  modules/post/multi/gather/multi_command.rb
  modules/post/multi/gather/netrc_creds.rb
  modules/post/multi/gather/pgpass_creds.rb
  modules/post/multi/gather/pidgin_cred.rb
  modules/post/multi/gather/ping_sweep.rb
  modules/post/multi/gather/remmina_creds.rb
  modules/post/multi/gather/resolve_hosts.rb
  modules/post/multi/gather/rsyncd_creds.rb
  modules/post/multi/gather/rubygems_api_key.rb
  modules/post/multi/gather/run_console_rc_file.rb
  modules/post/multi/gather/skype_enum.rb
  modules/post/multi/gather/ssh_creds.rb
  modules/post/multi/gather/thunderbird_creds.rb
  modules/post/multi/gather/tomcat_gather.rb
  modules/post/multi/gather/ubiquiti_unifi_backup.rb
  modules/post/multi/gather/wlan_geolocate.rb
Labels: rn-enhancement, code quality

#20085 Add new exploit for CVE-2025-32432: Craft CMS Preauth RCE
  documentation/modules/exploit/linux/http/craftcms_preauth_rce_cve_2025_32432.md
  modules/exploits/linux/http/craftcms_preauth_rce_cve_2025_32432.rb
Labels: module, docs

#20108 modules/post/multi: Resolve RuboCop violations
  modules/post/multi/escalate/aws_create_iam_user.rb
  modules/post/multi/escalate/cups_root_file_read.rb
  modules/post/multi/escalate/metasploit_pcaplog.rb
  modules/post/multi/general/close.rb
  modules/post/multi/general/execute.rb
  modules/post/multi/general/wall.rb
  modules/post/multi/manage/autoroute.rb
  modules/post/multi/manage/dbvis_add_db_admin.rb
  modules/post/multi/manage/dbvis_query.rb
  modules/post/multi/manage/hsts_eraser.rb
  modules/post/multi/manage/multi_post.rb
  modules/post/multi/manage/open.rb
  modules/post/multi/manage/play_youtube.rb
  modules/post/multi/manage/record_mic.rb
  modules/post/multi/manage/set_wallpaper.rb
  modules/post/multi/manage/shell_to_meterpreter.rb
  modules/post/multi/manage/sudo.rb
  modules/post/multi/manage/system_session.rb
  modules/post/multi/manage/upload_exec.rb
  modules/post/multi/manage/zip.rb
  modules/post/multi/recon/local_exploit_suggester.rb
  modules/post/multi/recon/multiport_egress_traffic.rb
  modules/post/multi/recon/sudo_commands.rb
Labels: code quality

#19938 Extapi clipboard update
  lib/rex/post/meterpreter/extensions/stdapi/fs/file.rb
  lib/rex/post/meterpreter/ui/console/command_dispatcher/extapi/clipboard.rb
Labels: bug

#20081 Adds module for CVE-2023-41425 WonderCMS RCE
  documentation/modules/exploit/multi/http/wondercms_rce.md
  modules/exploits/multi/http/wondercms_rce.rb
Labels: module, docs

#20017 Add LAPSv1 and LAPSv2 LDAP Module
  Gemfile.lock
  data/auxiliary/gather/ldap_query/ldap_queries_default.yaml
  documentation/modules/auxiliary/gather/ldap_hashdump.md
  documentation/modules/auxiliary/gather/ldap_passwords.md
  lib/msf/core/exploit/remote/ldap/queries.rb
  lib/msf/core/exploit/remote/ms_gkdi.rb
  lib/rex/proto/crypto_asn1/cms.rb
  lib/rex/proto/crypto_asn1/o_i_ds.rb
  lib/rex/proto/ldap/auth_adapter/rex_ntlm/encryptor.rb
  metasploit-framework.gemspec
  modules/auxiliary/gather/ldap_hashdump.rb
  modules/auxiliary/gather/ldap_passwords.rb
  spec/acceptance/ldap_spec.rb
  test/ldap/Dockerfile
  test/ldap/laps-accounts.ldif
  test/ldap/laps-schema-add.ldif
  test/ldap/laps-schema-modify.ldif
  test/ldap/samba-ad-setup.sh
Labels: docs, rn-modules
