Repository rapid7/metasploit-framework, pull requests merged in 2025-07, with the labels that each got.

#20334 Add payload/linux/x64/set_hostname module.
  modules/payloads/singles/linux/x64/set_hostname.rb
  spec/modules/payloads_spec.rb
Labels: payload

#19709 Bump IRB
  Gemfile.lock
  metasploit-framework.gemspec
Labels: blocked

#20391 Add a missing keyword for option validation
  lib/msf/core/opt_int_range.rb
Labels: library, bug, easy, rn-fix

#20392 Remove the version from the default prompt
  lib/msf/ui/console/driver.rb
Labels: easy, rn-no-release-notes, usability

#20375 WP Photo Gallery by 10Web Unauthenticated SQLi (CVE-2022-0169)
  documentation/modules/auxiliary/gather/wp_photo_gallery_sqli.md
  modules/auxiliary/gather/wp_photo_gallery_sqli.rb
Labels: module, docs, rn-modules

#20403 Dependency update
  .github/workflows/shared_meterpreter_acceptance.yml
  Gemfile.lock
  metasploit-framework.gemspec
Labels: rn-no-release-notes

#20415 Unpin json dependency
  Gemfile.lock
  metasploit-framework.gemspec
Labels: rn-no-release-notes

#20401 Add gMSA Secret Extraction From LDAP
  lib/metasploit/framework/password_crackers/jtr/formatter.rb
  lib/msf/util/windows_crypto_helpers.rb
  modules/auxiliary/gather/ldap_passwords.rb
  spec/acceptance/ldap_spec.rb
Labels: module, feature, rn-modules

#20417 fix: Fix typo in reflective_pe_loader.rb
  lib/msf/core/payload/windows/reflective_pe_loader.rb
Labels: bug, easy, rn-no-release-notes

#20420 Bump rails to 7.2
  Gemfile.lock
  config/application.rb
  db/schema.rb
  lib/metasploit/framework/rails_version_constraint.rb
  lib/msf/core/db_manager/cred.rb
  lib/msf/core/exploit/remote/mysql.rb
  metasploit-framework.gemspec
  modules/post/windows/gather/win_privs.rb
  modules/post/windows/manage/make_token.rb
  spec/file_fixtures/migrate/20250612131915_test_db_migration.rb
  spec/lib/msf/debug_spec.rb
  spec/modules/auxiliary/admin/kerberos/forge_ticket_spec.rb
  spec/support/shared/contexts/msf/db_manager.rb
Labels: rn-no-release-notes

#20422 Update jsonrpc dependencies
  Gemfile.lock
  metasploit-framework.gemspec
Labels: rn-no-release-notes

#20428 Fix achat_bof by increasing the available payload space
  modules/exploits/windows/misc/achat_bof.rb
Labels: module, easy, rn-fix
