Repository rapid7/metasploit-framework, pull requests merged in 2025-06, with the labels that each got.

#20270 Add documentation for auxiliary/scanner/discovery/udp_probe
  documentation/modules/auxiliary/scanner/discovery/udp_probe.md
Labels: docs, easy, rn-no-release-notes

#20271 modules/auxiliary/server/dns: Resolve RuboCop violations
  modules/auxiliary/server/dns/native_server.rb
  modules/auxiliary/server/dns/spoofhelper.rb
Labels: rn-no-release-notes, code quality

#20237 modules/auxiliary/scanner/couchdb: Resolve RuboCop violations
  modules/auxiliary/scanner/couchdb/couchdb_enum.rb
  modules/auxiliary/scanner/couchdb/couchdb_login.rb
Labels: rn-no-release-notes, code quality

#20272 Add missing references for AD CS modules
  modules/auxiliary/admin/dcerpc/icpr_cert.rb
  modules/auxiliary/admin/ldap/ad_cs_cert_template.rb
Labels: module, easy, rn-no-release-notes

#19900 Add Notes->AKA for EquationGroup codenames
  modules/auxiliary/admin/kerberos/ms14_068_kerberos_checksum.rb
  modules/auxiliary/dos/smtp/sendmail_prescan.rb
  modules/auxiliary/dos/windows/smb/ms09_050_smb2_negotiate_pidhigh.rb
  modules/auxiliary/dos/windows/smb/ms09_050_smb2_session_logoff.rb
  modules/auxiliary/scanner/ike/cisco_ike_benigncertain.rb
  modules/exploits/freebsd/samba/trans2open.rb
  modules/exploits/linux/local/sock_sendpage.rb
  modules/exploits/linux/samba/trans2open.rb
  modules/exploits/osx/samba/trans2open.rb
  modules/exploits/solaris/samba/trans2open.rb
  modules/exploits/unix/webapp/phpbb_highlight.rb
  modules/exploits/windows/smb/ms08_067_netapi.rb
  modules/exploits/windows/smb/ms09_050_smb2_negotiate_func_index.rb
  modules/exploits/windows/smb/ms10_061_spoolss.rb
Labels: rn-enhancement

#20273 fix(post/windows/manage/remove_host): handle whitespace parsing robustly
  modules/post/windows/manage/remove_host.rb
Labels: bug

#20281 post/windows/manage/remove_host: resolve hosts-file path dynamically instead of hard-coded C:\Windows
  modules/post/windows/manage/remove_host.rb
Labels: module, bug, rn-fix

#20263 Register VulnAttempts for both Exploit and Auxiliary modules
  lib/msf/base/simple/auxiliary.rb
  lib/msf/core/auxiliary.rb
  lib/msf/core/db_manager/exploit_attempt.rb
  lib/msf/core/db_manager/vuln.rb
  lib/msf/core/exploit.rb
  lib/msf/core/module.rb
  lib/msf/core/module/failure.rb
  spec/support/shared/examples/msf/db_manager/exploit_attempt.rb
Labels: enhancement

#20282 Jenkins Enum Documentation Added
  documentation/modules/auxiliary/scanner/http/jenkins_enum.md
Labels: module, docs, easy, rn-documentation

#20264 Process and propagate KERB-SUPERSEDED-BY-USER error details
  lib/metasploit/framework/login_scanner/kerberos.rb
  lib/rex/proto/kerberos/model.rb
  lib/rex/proto/kerberos/model/error.rb
  lib/rex/proto/kerberos/model/kerb_superseded_by_user.rb
  lib/rex/proto/kerberos/model/krb_error.rb
  lib/rex/proto/kerberos/model/pre_auth_data_entry.rb
Labels: enhancement, rn-enhancement

#20170 Msf::Module::UUID: Generate UUID using UUID_CHARS.sample(8).join
  lib/msf/core/module.rb
  lib/msf/core/module/uuid.rb
Labels: library, enhancement, code quality

#20160 Add PHP adapters and refactor PHP payloads
  Gemfile.lock
  lib/msf/core/exploit/php_exe.rb
  lib/msf/core/exploit/remote/http/wordpress/admin.rb
  lib/msf/core/payload/php.rb
  lib/msf/core/payload/python.rb
  modules/exploits/linux/http/craftcms_preauth_rce_cve_2025_32432.rb
  modules/exploits/multi/http/cacti_package_import_rce.rb
  modules/exploits/multi/http/invision_customcss_rce.rb
  modules/exploits/multi/http/spip_bigup_unauth_rce.rb
  modules/exploits/multi/http/spip_connect_exec.rb
  modules/exploits/multi/http/spip_porte_plume_previsu_rce.rb
  modules/exploits/multi/http/spip_rce_form.rb
  modules/exploits/multi/http/wp_backup_migration_php_filter.rb
  modules/exploits/multi/http/wp_hash_form_rce.rb
  modules/exploits/multi/http/wp_time_capsule_file_upload_rce.rb
  modules/payloads/adapters/cmd/unix/php.rb
  modules/payloads/adapters/cmd/unix/python.rb
  modules/payloads/adapters/php/unix/cmd.rb
  modules/payloads/singles/php/bind_perl.rb
  modules/payloads/singles/php/bind_perl_ipv6.rb
  modules/payloads/singles/php/exec.rb
  modules/payloads/singles/php/reverse_perl.rb
  modules/payloads/singles/php/shell_findsock.rb
  spec/modules/payloads_spec.rb
Labels: rn-enhancement, rn-payload-enhancement

#20293 Add Mr. Robot Easter egg
  modules/exploits/android/browser/samsung_knox_smdm_url.rb
Labels: module, easy, rn-no-release-notes

#20295 Fix some spacing issues
  modules/auxiliary/admin/networking/thinmanager_traversal_delete.rb
  modules/auxiliary/admin/networking/thinmanager_traversal_upload.rb
  modules/auxiliary/admin/networking/thinmanager_traversal_upload2.rb
  modules/auxiliary/gather/thinmanager_traversal_download.rb
Labels: easy, rn-no-release-notes

#20299 Modules: Convert DisableNops property to Boolean in several modules
  modules/exploits/freebsd/tacacs/xtacacsd_report.rb
  modules/exploits/mainframe/ftp/ftp_jcl_creds.rb
  modules/exploits/multi/browser/msfd_rce_browser.rb
  modules/exploits/multi/ftp/wuftpd_site_exec_format.rb
  modules/exploits/windows/browser/orbit_connecting.rb
  modules/exploits/windows/fileformat/acdsee_xpm.rb
  modules/exploits/windows/fileformat/apple_quicktime_pnsize.rb
  modules/exploits/windows/fileformat/audio_wkstn_pls.rb
  modules/exploits/windows/fileformat/ccmplayer_m3u_bof.rb
  modules/exploits/windows/fileformat/csound_getnum_bof.rb
  modules/exploits/windows/fileformat/digital_music_pad_pls.rb
  modules/exploits/windows/fileformat/fdm_torrent.rb
  modules/exploits/windows/fileformat/free_mp3_ripper_wav.rb
  modules/exploits/windows/fileformat/ht_mp3player_ht3_bof.rb
  modules/exploits/windows/fileformat/magix_musikmaker_16_mmm.rb
  modules/exploits/windows/fileformat/mini_stream_pls_bof.rb
  modules/exploits/windows/fileformat/mjm_coreplayer2011_s3m.rb
  modules/exploits/windows/fileformat/mjm_quickplayer_s3m.rb
  modules/exploits/windows/fileformat/ms_visual_basic_vbp.rb
  modules/exploits/windows/fileformat/safenet_softremote_groupname.rb
  modules/exploits/windows/fileformat/videospirit_visprj.rb
  modules/exploits/windows/fileformat/vuplayer_cue.rb
  modules/exploits/windows/fileformat/vuplayer_m3u.rb
  modules/exploits/windows/fileformat/wireshark_mpeg_overflow.rb
  modules/exploits/windows/fileformat/wireshark_packet_dect.rb
  modules/exploits/windows/ftp/comsnd_ftpd_fmtstr.rb
  modules/exploits/windows/ftp/httpdx_tolog_format.rb
  modules/exploits/windows/ftp/seagull_list_reply.rb
  modules/exploits/windows/ftp/vermillion_ftpd_port.rb
  modules/exploits/windows/http/amlibweb_webquerydll_app.rb
  modules/exploits/windows/http/apache_mod_rewrite_ldap.rb
  modules/exploits/windows/http/badblue_passthru.rb
  modules/exploits/windows/http/belkin_bulldog.rb
  modules/exploits/windows/http/hp_nnm_getnnmdata_hostname.rb
  modules/exploits/windows/http/hp_nnm_getnnmdata_icount.rb
  modules/exploits/windows/http/hp_nnm_getnnmdata_maxage.rb
  modules/exploits/windows/http/httpdx_handlepeer.rb
  modules/exploits/windows/http/httpdx_tolog_format.rb
  modules/exploits/windows/http/steamcast_useragent.rb
  modules/exploits/windows/iis/iis_webdav_scstoragepathfromurl.rb
  modules/exploits/windows/local/pxeexploit.rb
  modules/exploits/windows/misc/bigant_server.rb
  modules/exploits/windows/misc/bigant_server_250.rb
  modules/exploits/windows/misc/nettransport.rb
  modules/exploits/windows/misc/poppeeper_date.rb
  modules/exploits/windows/misc/poppeeper_uidl.rb
  modules/exploits/windows/misc/talkative_response.rb
  modules/exploits/windows/misc/wireshark_packet_dect.rb
  modules/exploits/windows/novell/groupwisemessenger_client.rb
  modules/exploits/windows/scada/sunway_force_control_netdbsrv.rb
Labels: rn-no-release-notes, code quality

#20303 modules/exploits/linux/postgres: Resolve RuboCop violations
  modules/exploits/linux/postgres/postgres_payload.rb
Labels: rn-no-release-notes, code quality

#20305 Fixes duplicate notes in a couple of modules
  modules/exploits/linux/local/sock_sendpage.rb
  modules/exploits/unix/webapp/phpbb_highlight.rb
Labels: rn-fix

#20312 Msf::Module::PlatformList: Resolve RuboCop violations
  lib/msf/core/module/platform_list.rb
Labels: code quality

#20309 modules/exploits/linux/samba: Resolve RuboCop violations
  modules/exploits/linux/samba/chain_reply.rb
  modules/exploits/linux/samba/is_known_pipename.rb
  modules/exploits/linux/samba/lsa_transnames_heap.rb
  modules/exploits/linux/samba/setinfopolicy_heap.rb
  modules/exploits/linux/samba/trans2open.rb
Labels: code quality

#20327 Update `vulns` command
  lib/msf/ui/console/command_dispatcher/db.rb
  spec/lib/msf/ui/console/command_dispatcher/db_spec.rb
Labels: rn-enhancement

#20315 Adds Rubocop rule to detect leading/trailing whitespace in module metadata
  .rubocop.yml
  lib/rubocop/cop/lint/detect_metadata_trailing_leading_whitespace.rb
  spec/rubocop/cop/lint/detect_metadata_trailing_leading_whitespace_spec.rb
Labels: rn-no-release-notes

#20336 Update opennms_horizon_authenticated_rce.rb
  modules/exploits/linux/http/opennms_horizon_authenticated_rce.rb
Labels: bug

#20335 Rubocop: Lint/DetectMetadataTrailingLeadingWhitespace: Except BadChars
  lib/rubocop/cop/lint/detect_metadata_trailing_leading_whitespace.rb
Labels: easy, rn-no-release-notes, code quality

#20337 opentsdb_key_cmd_injection: Set Arch to ARCH_CMD
  modules/exploits/linux/http/opentsdb_key_cmd_injection.rb
Labels: bug, rn-fix

#20340 exploit/windows/browser/ms08_070_visual_studio_msmask: Cleanup and add documentation
  documentation/modules/exploit/windows/browser/ms08_070_visual_studio_msmask.md
  modules/exploits/windows/browser/ms08_070_visual_studio_msmask.rb
Labels: docs, rn-no-release-notes, code quality

#20342 Runs Style/TrailingCommaInArguments Rubocop against modules
  modules/auxiliary/admin/oracle/oraenum.rb
  modules/auxiliary/gather/ms14_052_xmldom.rb
  modules/auxiliary/gather/windows_deployment_services_shares.rb
  modules/auxiliary/scanner/http/appletv_login.rb
  modules/auxiliary/scanner/http/es_file_explorer_open_port.rb
  modules/auxiliary/scanner/http/frontpage_credential_dump.rb
  modules/auxiliary/scanner/http/trace.rb
  modules/auxiliary/scanner/misc/cisco_smart_install.rb
  modules/auxiliary/scanner/scada/moxa_discover.rb
  modules/auxiliary/scanner/smb/smb_enumshares.rb
  modules/auxiliary/scanner/smb/smb_lookupsid.rb
  modules/auxiliary/scanner/ssh/karaf_login.rb
  modules/auxiliary/scanner/ssh/ssh_login.rb
  modules/auxiliary/scanner/varnish/varnish_cli_login.rb
  modules/auxiliary/server/ms15_134_mcl_leak.rb
  modules/exploits/linux/http/cve_2019_1663_cisco_rmi_rce.rb
  modules/exploits/linux/http/dlink_dir615_up_exec.rb
  modules/exploits/linux/http/dlink_dir850l_unauth_exec.rb
  modules/exploits/linux/http/linksys_wrt110_cmd_exec.rb
  modules/exploits/linux/http/netgear_dgn1000_setup_unauth_exec.rb
  modules/exploits/linux/http/netgear_dnslookup_cmd_exec.rb
  modules/exploits/linux/http/xplico_exec.rb
  modules/exploits/linux/local/service_persistence.rb
  modules/exploits/linux/snmp/net_snmpd_rw_access.rb
  modules/exploits/multi/ftp/pureftpd_bash_env_exec.rb
  modules/exploits/multi/hams/steamed.rb
  modules/exploits/multi/http/cisco_dcnm_upload_2019.rb
  modules/exploits/multi/http/horde_form_file_upload.rb
  modules/exploits/multi/http/netwin_surgeftp_exec.rb
  modules/exploits/multi/http/phpmailer_arg_injection.rb
  modules/exploits/multi/misc/erlang_cookie_rce.rb
  modules/exploits/unix/http/laravel_token_unserialize_exec.rb
  modules/exploits/unix/http/lifesize_room.rb
  modules/exploits/unix/http/pfsense_graph_injection_exec.rb
  modules/exploits/unix/http/xdebug_unauth_exec.rb
  modules/exploits/unix/webapp/actualanalyzer_ant_cookie_exec.rb
  modules/exploits/unix/webapp/drupal_coder_exec.rb
  modules/exploits/windows/fileformat/blazedvd_plf.rb
  modules/exploits/windows/fileformat/cve_2017_8464_lnk_rce.rb
  modules/exploits/windows/fileformat/ms14_017_rtf.rb
  modules/exploits/windows/local/cve_2017_8464_lnk_lpe.rb
  modules/exploits/windows/local/ps_persist.rb
  modules/exploits/windows/local/razer_zwopenprocess.rb
  modules/exploits/windows/local/service_permissions.rb
  modules/exploits/windows/misc/hta_server.rb
  modules/exploits/windows/misc/lianja_db_net.rb
  modules/exploits/windows/postgres/postgres_payload.rb
Labels: rn-no-release-notes

#20326 Add total number of currently defined aliases
  plugins/alias.rb
Labels: enhancement, easy

#19910 Fixing PPC64 template and payloads
  data/templates/src/elf/exe/elf_ppc64_template.s
  data/templates/template_ppc64_linux.bin
  lib/msf/util/exe.rb
  modules/payloads/singles/linux/ppc64/shell_bind_tcp.rb
  modules/payloads/singles/linux/ppc64/shell_find_port.rb
  modules/payloads/singles/linux/ppc64/shell_reverse_tcp.rb
Labels: bug, enhancement, rn-payload-enhancement

#20351 Fix non-printable non-ascii chars in module description and name
  modules/auxiliary/admin/http/wp_gdpr_compliance_privesc.rb
  modules/auxiliary/scanner/http/apache_normalize_path.rb
  modules/auxiliary/scanner/http/dolibarr_16_contact_dump.rb
  modules/auxiliary/scanner/http/jira_user_enum.rb
  modules/encoders/php/minify.rb
  modules/exploits/linux/http/qnap_qts_rce_cve_2023_47218.rb
  modules/exploits/linux/http/solarview_unauth_rce_cve_2023_23333.rb
  modules/exploits/linux/local/cve_2023_0386_overlayfs_priv_esc.rb
  modules/exploits/multi/http/apache_commons_text4shell.rb
  modules/exploits/multi/http/apache_normalize_path_rce.rb
  modules/exploits/multi/http/cve_2021_35464_forgerock_openam.rb
  modules/exploits/multi/http/invision_customcss_rce.rb
  modules/exploits/multi/http/roundcube_auth_rce_cve_2025_49113.rb
  modules/exploits/multi/http/spip_porte_plume_previsu_rce.rb
  modules/exploits/multi/http/wp_hash_form_rce.rb
  modules/exploits/multi/veritas/beagent_sha_auth_rce.rb
  modules/exploits/unix/http/pfsense_pfblockerng_webshell.rb
  modules/exploits/unix/webapp/wp_wpdiscuz_unauthenticated_file_upload.rb
  modules/exploits/windows/http/git_lfs_rce.rb
  modules/exploits/windows/http/moveit_cve_2023_34362.rb
  spec/module_validation_spec.rb
  spec/support/lib/module_validation.rb
Labels: rn-no-release-notes

#20353 Add validation for arch values
  modules/exploits/linux/http/suitecrm_log_file_rce.rb
  modules/exploits/multi/http/spip_bigup_unauth_rce.rb
  modules/exploits/unix/webapp/byob_unauth_rce.rb
  modules/exploits/unix/webapp/vicidial_agent_authenticated_rce.rb
  spec/module_validation_spec.rb
  spec/support/lib/module_validation.rb
Labels: rn-no-release-notes

#20341 Adds module for Skyvern SSTI (CVE-2025-49619)
  documentation/modules/exploit/linux/http/skyvern_ssti_cve_2025_49619.md
  modules/exploits/linux/http/skyvern_ssti_cve_2025_49619.rb
Labels: module, docs

#20346 Use the smaller base64 encoder
  modules/exploits/multi/http/php_fpm_rce.rb
Labels: bug, easy, rn-fix

#20289 Adds support for MITRE ATT&CK References
  lib/msf/core/mitre/attack/categories.rb
  lib/msf/core/mitre/attack/technique.rb
  lib/msf/core/module/reference.rb
  lib/msf/core/modules/metadata/search.rb
  lib/msf/ui/console/command_dispatcher/modules.rb
  modules/exploits/linux/samba/is_known_pipename.rb
  modules/exploits/windows/ftp/quickshare_traversal_write.rb
  modules/exploits/windows/ldap/pgp_keyserver7.rb
  modules/exploits/windows/lotus/domino_sametime_stmux.rb
  modules/exploits/windows/mysql/mysql_mof.rb
  modules/exploits/windows/rdp/cve_2019_0708_bluekeep_rce.rb
  modules/exploits/windows/scada/sunway_force_control_netdbsrv.rb
  modules/exploits/windows/sip/aim_triton_cseq.rb
  modules/exploits/windows/smb/ms17_010_eternalblue.rb
  modules/exploits/windows/smb/ms17_010_psexec.rb
  modules/exploits/windows/smb/psexec.rb
  modules/exploits/windows/ssl/ms04_011_pct.rb
  spec/module_validation_spec.rb
  spec/support/lib/module_validation.rb
  tools/dev/generate_mitre_attack_technique_constants.rb
Labels: rn-enhancement

#20358 Fix module cache generation
  tools/automation/cache/build_new_cache.sh
  tools/automation/cache/wait_for_cache.rc
Labels: rn-no-release-notes
